### ISSUE TITLE
Configure, check for null values?

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#10]
**Do you want to request a *feature* or report a *bug*?**

feature

**Bug: What is the current behavior?**
If one of these values is null, I get a bad request:

```jsx
<Configure
  aroundLatLng={listing.aroundLatLng}
  insideBoundingBox={listing.insideBoundingBox}
/>
```

So I have to do:

```js
const configure = {};
if (listing.aroundLatLng) configure.aroundLatLng = listing.aroundLatLng;
if (listing.insideBoundingBox)
  configure.insideBoundingBox = listing.aroundLatLng;
```

**Bug: What is the expected behavior?**

To be able to pass null values and the component not pass them through to algolia

**What is the version you are using? Always use the latest one before opening a bug issue.**

react-instantsearch 3.3.1

**info**

reported by @zackify in https://github.com/algolia/instantsearch.js/issues/2099

**Comment by mthuret** [comment]
Hi @zackify,

I'm not sure this is a good idea as `null` could be actually a value. 

If you know that because this prop has a `null` value, then you should removed it from the configure props.

**Comment by zackify** [comment]
I was hoping this would be the use case others run into. Sometimes our api returns a bounding box. Sometimes it returns around last lng. Would just be nice for configure to be smart enough to not apply null values. I guess I can just make my own wrapped configure that removes null values.

**Comment by davidfurlong** [comment]
I'd be surprised if the declarative syntax of Multi-index doesn't support multiple Configure objects - I'd expect in such a case 

```js

<InstantSearch>
  <Configure someThing={3} />
  <Index indexName="a>
     <Configure someThingElse={5} />
  </Index>
  <Index indexName="b">
</InstantSearch>

```

I would expect both index `a` and `b` to have the configuration of `someThing: 3` and only index `a` to have `somethingElse:5`. But nested configurations overwriting the other ones if that prop is omitted seems absurd.
