### ISSUE TITLE
Redux state change toggles searching prop from Hits connected to connectSearchState

### ISSUE THREAD

**Issue by rtman** [algolia/react-instantsearch#1002]
I'm working on a shopping cart system and have passed a redux state and actions to a hits widget that is connected to connectStateResults. On each hit I have a quantity +/- button and whenever I press either it triggers the searching prop causing my spinner to show with a large delay. Maybe I've done something wrong here, but this shouldn't be happening.

Here's my code example:

```
export const HitsSearching = ({cart, decrementItem, incrementItem, onPressHit, hits, hasMore, refine, uid, navigation, fieldOne, fieldTwo, fieldThree, fieldFour, usersRef, chatsRef, searching}) => {
  const onEndReached = function() {
    if (hasMore) {
      refine();
    }
  };

  if(searching){
    return (
      <Spinner/>
    )
  } else {
    return(
        <FlatList
          data={hits}
          onEndReached={onEndReached}
          keyExtractor={(item, index) => item.objectID}
          ItemSeparatorComponent={Separator}
          renderItem={({ item }) => {
            return (
              <TouchableOpacity onPress={() => onPressHit(item)}>
                <View style={styles.itemRowsContainer}>
                  <View style={{flex:1, flexDirection: 'column'}}>
                    <View style={styles.imageAndTextContainer}>
                      <View style={{flexDirection: 'row'}}>
                        <Image 
                          source={{ uri: item.image.thumb.url}} 
                          style={styles.image}
                          resizeMode={'cover'}/>
                        <View style={{justifyContent: 'flex-start', paddingLeft: 8, flexDirection: 'column'}}>
                          <Text style={styles.itemHeader1}>
                            <Highlight attributeName={fieldOne} hit={item} />
                          </Text>
                          <Text style={styles.itemHeader2}>
                            <Highlight attributeName={fieldTwo} hit={item} />
                          </Text>
                          <Text style={styles.itemHeader2}>
                            <Highlight attributeName={fieldThree} hit={item} />
                          </Text>
                        </View>
                      </View>
                      <Text style={styles.itemHeader2}>
                        Distance
                      </Text>
                    </View>
                    <View style={{flexDirection: 'row', paddingTop: 8, justifyContent: 'space-between'}}>
                      <View style={{paddingRight: 10}}>
                        <Text style={styles.itemDescription}>
                          {/*<Highlight attributeName={description} hit={item} />*/}
                          Desrcription
                        </Text>
                      </View>
                            <View style={styles.cartQuantityButton}>
                              <TouchableOpacity onPress={() => decrementItem(item.docId)}>
                                <Icon2 name= 'minus' size={Styles.primaryIconSize} color={Colors.primaryGrayColor}/>
                              </TouchableOpacity>
                              <Text style={[styles.itemHeader1, {color: Colors.primaryGrayColor}]}>
                                {cart.items[item.docId].quantity}
                              </Text>
                              <TouchableOpacity onPress={() => incrementItem(item.docId)}>
                                <Icon2 name='plus' size={Styles.primaryIconSize} color={Colors.primaryGrayColor}/>
                              </TouchableOpacity>
                            </View>
                    </View>
                  </View>
                </View>
              </TouchableOpacity>
            );
          }}
        />
    );
  }
};

export const HitsConnected =  connectInfiniteHits(connectStateResults(HitsSearching));
```

The widget is called like this from a parent component:

```
	return (
            <View style={styles.container}>
                <InstantSearch
                    appId={algoliaAppId}
                    apiKey={algoliaApiKey}
                    indexName={currentIndex}
                    root={{
                      Root: View,
                      props: {
                        style: {
                          flex: 1
                        }
                      }
                    }}>
                                <HitsConnected
                                    fieldOne="itemName"
                                    fieldTwo="price"
                                    fieldThree="companyName"
                                    fieldFour="description"
                                    uid={this.user.uid}
                                    navigation={this.props.navigation}
                                    usersRef={this.usersRef}
                                    chatsRef={this.chatsRef}
                                    onPressHit={this.onPressItem}
                                    incrementItem={this.props.incrementItem}
                                    decrementItem={this.props.decrementItem}
                                    cart={this.props.cart}/>
                </InstantSearch>
            </View>
)
```

**Comment by rtman** [comment]
@samouss @Haroenv can someone have a look at this when you guys get a minute please?

**Comment by samouss** [comment]
Hi @rtman, without an example it's pretty hard to investigate the issue. Could you provide us a small example with the issue? 

Did you try to use a component simpler than a `< FlatList>` for debugging? Maybe the delay come from the fact that you mount / unmount the list every time the `searching` value change.

**Comment by rtman** [comment]
Unfortunately my time is pretty limited at the moment as I'm close to a deadline, but I will try and provide an example.

Do you guys have an expo snack or other template for react native that I can start with?

> Did you try to use a component simpler than a < FlatList> for debugging? Maybe the delay come from the fact that you mount / unmount the list every time the searching value change.

Searching shouldn't be changing at all though, I'm changing the value of something unrelated to the data coming from algolia. I suppose it could be related to the mounting/unmounting.

**Comment by samouss** [comment]
You can use the [React Native example](https://github.com/algolia/react-instantsearch/tree/master/packages/react-instantsearch/examples/react-native) as a start. Then you can use Expo to share the example with us.

If I correctly understand when you press the buttons inside the `<FlatList>` the Algolia search should not be trigger but it is. Then is cause the `<Spinner>` & `<FlatList>` to be mount / unmount since the `searching` attribute change. Am I right?

**Comment by rtman** [comment]
Yes, that is correct.

The searching prop is toggling when i click those + and - buttons as well as in some other other non search related actions, which is causing the flatlist to unmount and my spinner to mount. As well as causing the SpinnerOverlay component from my refinements drawer to mount on a completely different screen.

```
export const DrawerRefinementsConnected = connectStateResults(({searching}) => {
  return(
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <SpinnerOverlay 
        visible={searching}
        animation={'none'}
        overlayColor={'rgba(0, 0, 0, 0.5)'}>
        <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
          <View style={{backgroundColor: Colors.background}}>
            <View style={{alignItems: 'center', justifyContent: 'center', padding: 25}}>
              <Spinner isVisible={searching} color={Colors.secondaryColor} type='Bounce'/>
              <Text style={{fontSize: 14, color: Colors.primaryTextColor, paddingTop: 10}}>
                Updating ...
              </Text>
            </View>
          </View>
        </View>
      </SpinnerOverlay>
      <DrawerRefinements/>
    </View>
  )
})
```

**Comment by samouss** [comment]
Since you are using Redux every component that is connected to the store will re-render when those actions are dispatched. It's possible that in one of those components there is a widget that trigger a new search because one of his props have changed.

**Comment by rtman** [comment]
Ok, I didn't know that (new to redux). So my searchResults screen component is connected to the store it contains the + and - buttons in question as well as a lot of other algolia related components. If Redux is re rendering the SearchResults page every time I update the store by clicking on the + and - that might explain it. Although I'm not sure how to avoid this at this point.

**Comment by rtman** [comment]
> If I correctly understand when you press the buttons inside the <FlatList> the Algolia search should not be trigger but it is. Then is cause the <Spinner> & <FlatList> to be mount / unmount since the searching attribute change. Am I right?

@samouss 

I'm not seeing any components unMounting and reMounting during the process, just seems that searching is toggling somehow. I've got console logs set up on the componentWillMount and componentWillUnmount and the components never unmount.

This seems odd, because a re render shouldn't trigger this behavious correct?

**Comment by samouss** [comment]
> This seems odd, because a re render caused by props or state update shouldn't trigger this behaviour correct?

It depends, when the props of a widget aren't shallow equal it **does trigger** a new search. Since we don't have informations about your code it's very complicated to investigate the issue. A working example of the issue would help a lot.

**Comment by rtman** [comment]
ok I'm working on it atm, will get back to you soon.

**Comment by rtman** [comment]
@samouss

I've created a github repository which reproduces the issue I'm having, I simplified it as much as I could

[https://github.com/rtman/reduxAlgolia.git](https://github.com/rtman/reduxAlgolia.git)

Let me know if you get it working and can see what I'm seeing.

**Comment by samouss** [comment]
Hi @rtman, the issue comes from the fact that the `cart` prop is always a new object when you increment the counter (it's the intended behaviour with Redux). So when the prop is passed to the `<HitsConnected>` the widget will trigger a request since the the props aren't shallow equal anymore.

In order to avoid to trigger a new request you can connect your component to the Redux store under the `connectInfiniteHits` component. It will avoid you to pass the cart to the `<HitsConnected>` component and only pass props that don't change on every render.

It's a know issue on our side, we should be a bit more aggressive regarding the shallow equal.

**Comment by rtman** [comment]
@samouss 

Ah ok, that makes sense.

I'm having trouble applying the fix you are referring to. Can you show me in code what you mean? Or maybe submit a PR to that repo?

**Comment by rtman** [comment]
@samouss 

I've updated the repo with my attempt at a fix:
[reduxAlgolia](https://github.com/rtman/reduxAlgolia)

I connected the `HitsSearchingClass` component to redux and and removed the parent level connection. That seems to have fixed the unnecessary searches. But now I can't seem to get the component quantity indicators to update with redux store changes, not sure what the deal is there.

**Comment by rtman** [comment]
I just noticed that if I press the hardware back button and background the app, then re open it I can see instantsearch initiating a search (search prop goes true) then when its done the quantities are updated properly. Is this another algolia issue?

**Comment by samouss** [comment]
I looked at your example, the quantity indicator is not updated because the `<FlatList>` doesn't re-render the item when you trigger the action. The component do a shallow equal on the props in order to trigger a re-render. In your example no props have changed, so no re-render. To trigger a new render you can pass the prop cart to the `<FlatList>`.

> This is a `PureComponent` which means that it will not re-render if `props` remain shallow-equal. Make sure that everything your `renderItem` function depends on is passed as a prop (e.g. `extraData`) that is not `===` after updates, otherwise your UI may not update on changes. This includes the `data` prop and parent component state.
>
> https://facebook.github.io/react-native/docs/flatlist.html

**Comment by rtman** [comment]
@samouss ah jeez, thats emabarassing haha. This is not the first time I've missed that `extraData` prop either.

Thanks for all your help, I realize that last question was not something you had to help me with either! I was honestly stumped tho, so ya... thanks. Looks like everything is working now 👍
