### ISSUE TITLE
Changing state in hitComponent does not fire componentWillReceiveProps

### ISSUE THREAD

**Issue by Drakota** [algolia/react-instantsearch#1030]
**Do you want to request a *feature* or report a *bug*?**
*feature?*

**Feature: What is your use case for such a feature?**
I want to change a state and be able to change hits.

**What is the version you are using? Always use the latest one before opening a bug issue.**
4.5.1

I'm trying to set the state of a variable, but if the component is passed inside Hit's hitComponent it seems like componentWillReceiveProps does not fire
```javascript

renderRow({hit})
{
    return(<Crypto name={hit.symbol} currency="CAD" priceupdate={this.state.newUpdate} socket={this.props.socket}/>);
}
  
render() {
  return (
    <div className="card-columns">
      <Crypto name="BTC" currency="CAD" priceupdate={this.state.newUpdate} socket={this.props.socket}/> // Fires componentWillReceiveProps
      <Hits hitComponent={this.renderRow}/> // Does not
    </div>
  );
}
```

**Comment by samouss** [comment]
In your example the `Hits` component will never trigger a re-render of the `hitComponent`. Internally the `Hits` component does a shallow equal in `shouldComponentUpdate`. The reference of `renderRow` never change so the lifecycle will always return `false` when you perform a 
`setState` in your component. 

For achieve this kind of behaviour you can use the [`connectHits`](https://community.algolia.com/react-instantsearch/connectors/connectHits.html) connector. The connector API lets you have the full control on the rendering. You can find more details about that in [our documentation](https://community.algolia.com/react-instantsearch/guide/Connectors.html). Here is [an example](https://codesandbox.io/s/q4z4ly6pm6) that does something similar to your code.
