### ISSUE TITLE
Duplicate requests are sent when use transformItems

### ISSUE THREAD

**Issue by phidang0810** [algolia/react-instantsearch#1037]
Hi guy, I want report a bug. I'm using react-router v4, when I add widget **RefinementList** with **transformItems** property to sort items, duplicate request are send to algolia. More detail, you can see https://codesandbox.io/s/43k243yqlx

**Comment by samouss** [comment]
Hi @phidang0810, thanks for reporting the issue. 

It's a known problem on our side, we trigger a new request when the props aren't shallow equal. In your example there is a new function create on every render. It means that the props of the `RefinementList` aren't shallow equal on every new render. You can avoid this issue by passing the same reference to the `transformItems` function.

**Comment by phidang0810** [comment]
Could you give me a example for this?

**Comment by samouss** [comment]
Yes sure, I wasn't able to give you an example since I had some trouble with CodeSandbox. But now it's good, [here](https://codesandbox.io/s/rr553zm3o) you can find you example updated. 

Let me know how it goes 😉

**Comment by phidang0810** [comment]
Great. Thank you :)
