### ISSUE TITLE
How to build autocomplete with connectAutoComplete?

### ISSUE THREAD

**Issue by phidang0810** [algolia/react-instantsearch#1039]
Hi guy, I want to build autocomplete. It means that when I press a text, suggestion was shown and after I clicked it, the result have been updated. Same with amazon's search page, It only show suggestion key, but not product list. Could you help me?

**Comment by samouss** [comment]
Hi @phidang0810, did you check our example in the documentation? There are some that demonstrate the usage of the `connectAutoComplete` connector with existing autocomplete component. You can find those examples [in our recipes](https://community.algolia.com/react-instantsearch/examples/Recipes.html) (see "Autocomplete integration").

**Comment by samouss** [comment]
@phidang0810 Did you solve your issue?

**Comment by samouss** [comment]
I'm closing this one, feel free to open a new one if you still have a question.
