### ISSUE TITLE
More aggressive shallow equal in willReceiveProps

### ISSUE THREAD

**Issue by samouss** [algolia/react-instantsearch#1042]
## Problem

In the current implementation on every render we check if the given props are shallow equal or not in order to trigger a new request. We check **all** the props and not only the ones used by the connector. It can lead to useless requests when we pass an props that will change on every render (ex: Anonymous function, value from a Redux store, plain object, ...).

See https://github.com/algolia/react-instantsearch/issues/1002 https://github.com/algolia/react-instantsearch/issues/1037.

https://github.com/algolia/react-instantsearch/blob/5ecec858f41ff3964bce0d26431804f8fe67308f/packages/react-instantsearch/src/core/createConnector.js#L166-L175

## Solution

A possible solution will be to let the inner connector do the shallow equal. The connector has more knowledge about his props than `createConnector`. By doing that we can specify which props needs to be check in order to trigger a new request (ex: `attribute`). We should also split the props in two categories UI / search. An update on the UI props must not trigger a new request (ex: `translations`).

**Comment by rtman** [comment]
Just wondering if this has progressed at all? I still see occasions when searching is triggered and it shouldn't be.

**Comment by samouss** [comment]
Nope not yet! We don't have any ETA on it neither.

**Comment by sarahdayan** [comment]
As we're deprecating React InstantSearch v6 to the benefit of React InstantSearch Hooks, we'll most likely not work on this optimization in v6.
