### ISSUE TITLE
StarRating: Calculate based on score attribute

### ISSUE THREAD

**Issue by Kikobeats** [algolia/react-instantsearch#105]
StarRating component doc says:

```
min
type: number
 
Minimum value for the rating. When this isn’t set, the minimum value will be automatically computed by Algolia using the data in the index.
max
type: number
 
Maximum value for the rating. When this isn’t set, the maximum value will be automatically computed by Algolia using the data in the index.
```

Currently my rating score is represented as a number between `0` to `1`.

The widget can't handle it; Does it need a number between `0` to `6`? 

I supossing that because the max number of star I see are `6` at Storybook.

It would be deseable the calculate the number of star based on the attribute `min`/`max` value.

Example:

- If your `max` is `1`, then it equals to `6` stars
- If your `min` is `0`, then it equals to `0` stars
- Be possible calculate all the mid values (`0.5` → `3` stars)

Another expected thing could be possible determinate the max of stars to use. For example, I want to represent my max value as `3` stars.

**Comment by mthuret** [comment]
Hello @Kikobeats,

This widget doesn't handle half stars. 

That being said you can already represent your max value as 3 stars. Just use 3 for max. (It means that your highest rating attribute must be 3 then).

**Comment by Kikobeats** [comment]
could be sense expose a function in the component API for calculate the number of stars?

**Comment by mthuret** [comment]
I'm not sure to understand.

Let say you have records with a `rating` attribute that goes from 1 to 3. Then, by default, the StarRating widget will display three rows going from 1 stars to 3 stars.

**Comment by Kikobeats** [comment]
Ok let me try, thanks!
