### ISSUE TITLE
Order documentation section for widgets / connectors

### ISSUE THREAD

**Issue by samouss** [algolia/react-instantsearch#1059]
In the current documentation the section are presented like this: 

- description
- props
- requirements
- usage
- CSS classes
- translations keys

One problem that I saw with the current layout is that the requirements are not visible when you arrive on the page. You need to scroll in order to see them. When the user comes on the page he should be able to see those requirements immediately. Inside the library we don't handle properly the errors regarding the requirements, most of the time we don't throw any errors but nothing happening. Until we do something for that we should re-order a bit the sections like:

- description
- **requirements**
- **props**
- usage
- CSS classes
- translations keys

WDYT? cc @mthuret @vvo @Haroenv

**Comment by Haroenv** [comment]
I'm all in for this change, requirements is the first thing you should see after the description. Nice find 👍

**Comment by vvo** [comment]
Seems like a good quick win, ultimately in Q2 we will work on that too but you can definitely go for a quick change so that we get less support emails about those requirements!
