### ISSUE TITLE
"Back" navigation scroll position resets

### ISSUE THREAD

**Issue by catamphetamine** [algolia/react-instantsearch#1061]
Currently if a user navigates "Back" from a search result page to the search page the scroll position is reset because Algolia search widget loads after the page has been shown therefore resetting the scroll position.

The application could either delay "restoring previous scroll position" after performing "Back" navigation until Algolia loads its data (via polling document height - still hacky and error-prone) or it could somehow make Algolia widget cache the results so that it doesn't start from scratch every time a user hits the "Back" button.

**Comment by catamphetamine** [comment]
E.g. the `<InstantSearch/>` widget could take some `initialHits` property which would represent the `hits` to be shown while it loads so that it doesn't collapse in the meantime.
The `initialHits` property could be stored in Redux state somehow (perhaps via some `onHitsReceived(hits)` event listener) so that it's available when a user hits "Back".

**Comment by catamphetamine** [comment]
In the source code I can see this:

> @propType {SearchResults|SearchResults[]} [resultsState] - Use this to inject the results that will be used at first rendering

So, I could inject `resultsState` so that the search widget doesn't collapse while it's loading the first time.
But how can one obtain that `resultsState` data?
Is there some callback?

**Comment by catamphetamine** [comment]
(the following is for v4, i didn't check whether v5 has the bug)

So an idea I've come up with is implement a custom `connectHits` connector which returns `hits, hitsPerPage and preloading: true/false`.

The code should be placed in `cc-frontend/src/react-instantsearch` folder.

* `indexUtils.js` should be copy-pasted from https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/src/core/indexUtils.js

* `connectHits.js` should be combined from with https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/src/connectors/connectHits.js and https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/src/connectors/connectHitsPerPage.js

```js

  getProvidedProps(props, searchState, searchResults) {
    // console.log('searchResults', searchResults)
    // console.log(this.context)

    const hitsPerPage = getCurrentRefinement(
      'hitsPerPage',
      props,
      searchState,
      this.context
    )....;

    const results = getResults(searchResults, this.context);
    const hits = results ? results.hits : [];
    const preloading = !results;

    return { hits, hitsPerPage, preloading };
  }
```

* `InstantSearchResults` (paginated) should check the `preloading: true/false` property. If it's `true` then construct an array of "stub" `hits` with length of `hitsPerPage` and show them as usually but with `visibility: hidden` so that the search results widget doesn't collapse to zero height.

**Comment by samouss** [comment]
Hi, first of all sorry fo the delayed answer I messed up with my notifications and thanks for all those feedbacks. But I have some struggle to properly understand all the issue and the potential solution. Could you provide an example with the issue that you faced on? It will help us a lot to understand and try to found a proper solution. We provide template in order to avoid you the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/React%20InstantSearch).

**Comment by catamphetamine** [comment]
@samouss See if these two gifs clarify the issue:

Desktop, Chrome, wide:

![123](https://user-images.githubusercontent.com/477167/37825378-a9031cd8-2ea0-11e8-81fc-c84587e27064.gif)

Desktop, Chrome, narrow:

![1234](https://user-images.githubusercontent.com/477167/37825387-b32b9b22-2ea0-11e8-82eb-5ab830b26ee5.gif)

**Comment by catamphetamine** [comment]
@samouss You can test it yourself on this website: https://www.collegeconsortium.org/institutions/

**Comment by catamphetamine** [comment]
@samouss So the issue is, once again, to clarify the case: InstantSearch (at version 4 at least) shows results with `@connectHits()` which gets an empty array (see the source code for @connectHits) upon page load and so it's collapsed and that messes the proper restoring of scroll position.

**Comment by catamphetamine** [comment]
@samouss On this particular website you can notice how on "back" navigation the green banner flashes on the screen briefly - that's because the search widget has height equal to `0` cause it hasn't fetched the data from algolia yet.

**Comment by samouss** [comment]
Thanks for the GIF and the explanations, I will need a bit of time in order to dig a bit more the issue. I come back to you as soon as I have more informations.

**Comment by catamphetamine** [comment]
Some more of the ideas on this issue.

So, `<InstantSearch/>` returned from this library accepts `resultsState`.
In the scenario described above the search has already returned some results, so they could be stored somewhere in Redux state (or in a global variable) to later be read from that Redux state (or global variable) when a user hits the "Back" button and passed to `<InstantSearch/>` as the `resultsState` property.
I guess that would work.

But, how does one obtain those `resultsState`?

There are two ways, theoretically.
One is to obtain the reference to the internal `InstantSearch.js` component instance and then do `this.instantSearchRef.aisManager.store.getState().results`.
The other is to forge a proxy `searchClient` and then pass it as the `searchClient` property to `<InstantSearch/>` returned from this library.
The proxy `searchClient` would somehow intercept the default results returned from Algolia search and write those results to Redux state (or a global variable) and then proceed as the default one.
The "default one" is [`algoliasearch/lite`](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/dom.js).
https://github.com/algolia/algoliasearch-client-javascript/blob/develop/src/browser/builds/algoliasearchLite.js

Instead of somehow forging a proxy `searchClient` the first variant would be more convenient.
But `react-instantsearch` doesn't provide a way to hook on "search results obtained" event.
https://github.com/algolia/react-instantsearch/blob/174cc28a6ed8ef09da1b5128c5d2157182303e3a/packages/react-instantsearch/src/core/createInstantSearchManager.js#L30-L33

```js
  const helper = algoliasearchHelper(searchClient, indexName, baseSP);
  helper.on('result', handleSearchSuccess);
  helper.on('error', handleSearchError);
  helper.on('search', handleNewSearch);


  function handleSearchSuccess(content) {
    const state = store.getState();
    let results = state.results ? state.results : {};
    ...
  }

```

E.g. some `onSearchResults()` property (similar to the existing `onSearchStateChange()` property) would solve the issue.

**Comment by catamphetamine** [comment]
Ok, seems that I found another way that works.

```js
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { connectHits } from 'react-instantsearch/connectors';

@connectHits
export default class InstantSearchResultsState extends Component {
  static contextTypes = {
    ais: PropTypes.object.isRequired
  };

  componentDidUpdate() {
    // Store results here somehow.
    // E.g. in Redux state or in a global variable.
    console.log(this.context.ais.store.getState().results);
  }

  render() {
    return null;
  }
}
```

Placing this element inside `<InstantSearch/>` gives access to the results which can later be passed to `<InstantSearch/>` in the form of `resultsState` property when a user hits the "Back" button.

**Comment by samouss** [comment]
Indeed the solution should work, thanks for posting it. You can use [`connectStateResults`](https://community.algolia.com/react-instantsearch/connectors/connectStateResults.html#default-props-entry-connectStateResults-searchResults) instead of relying on `connectHits` to retrieve the `results`. It will avoid you to access the `results` directly from the context. Note that in the connector the prop that contains the results is `searchResults`.
