### ISSUE TITLE
Documentation: connectors code sample

### ISSUE THREAD

**Issue by redox** [algolia/react-instantsearch#107]
While browsing the **Connectors** pages, we don't explain from where to import the connectors nor how to use them. Would be cool to have a small snippet of code:

```js
import { connectMenu } from 'react-instantsearch/connectors';

const MyMenu = connectMenu(...);
```

**Comment by redox** [comment]
So we do have examples for some of them (like the `connectHighlight`; but the `import { connectHighlight }` is missing)

**Comment by mthuret** [comment]
Ideally we should add a connector usage example inside the storybook and link the source code of that story. The storybook is not yet tested but at least the code is executed often when developing.

**Comment by harshmaur** [comment]
Often, I need to find what underlaying connectors does all the components use so that I can take that and modify as per custom needs. It would be great if the snippet could be included in the Connectors docs.

**Comment by Haroenv** [comment]
I think we can learn from the documentationjs work that @bobylito did for IS.js v2, which does have generated code samples

**Comment by Haroenv** [comment]
In the new documentation; every widget has a section "customize the UI", which has an example usage of the connector, here's e.g. `connectMenu` being used: https://www.algolia.com/doc/api-reference/widgets/menu/react/#connector
