### ISSUE TITLE
Add common props to documentation

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#1072]
`className` is missing for most, I think others are missing too, but not sure

**Comment by Haroenv** [comment]
the new docs does not have a page for this yet either.

**Comment by FabienMotte** [comment]
Closing this issue because the documentation has been updated since then, React InstantSearch Hooks lists all the props in the [reference API](https://www.algolia.com/doc/api-reference/widgets/react-hooks/).
