### ISSUE TITLE
Feature Request: SearchBox refine on mount when defaultRefinement is provided.

### ISSUE THREAD

**Issue by Bouncey** [algolia/react-instantsearch#1102]
**Feature: What is your use case for such a feature?**

We have built a component to search a `query_suggestions` index. The purpose of which is to suggest queries to users. If the user picks a suggestion, they are directed to a search page that displays the results. The users query is passed through the url `?q=my%20query`.

The search component is used across multiple subdomains, they all point to the one search page.

It would be nice that, if `defaultRefinement` is defined, the developer has an option to submit a query on mount.

Currently, I am having to do something like this

```jsx
import React, { PureComponent } from 'react';
import { SearchBox } from 'react-instantsearch/dom';
import qs from 'query-string';

import './header.css';

class Header extends PureComponent {
  componentDidMount() {
    const { props: searchBoxProps, refine } = this._SearchBox_;
    const { defaultRefinement } = searchBoxProps;
    return defaultRefinement ? refine(defaultRefinement) : null;
  }

  getQueryFromLocation() {
    if (typeof window === 'undefined') {
      return '';
    }
    const { q: query } = qs.parse(window.location.search);
    return query ? query : '';
  }

  render() {
    return (
      <header>
        <nav>
          <div className="nav-logo">
            <img
              alt="freeCodeCamp logo. Learn to code and help non-profits"
              src="https://s3.amazonaws.com/freecodecamp/freecodecamp_logo.svg"
            />
          </div>
          <SearchBox
            defaultRefinement={this.getQueryFromLocation()}
            ref={ref => {
              this._SearchBox_ = ref;
            }}
            translations={{
              placeholder: 'Search 8,000+ lessons, articles, and videos'
            }}
          />
        </nav>
      </header>
    );
  }
}

export default Header;

```

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

```jsx
<SearchBox 
  defaultRefinement='Some query'
  refineOnMount={ true } // possibly defaults to false to preserve current API contracts
/>
```

**Comment by Haroenv** [comment]
I think this should be the case already without the need of a new option. @samouss, do you have any idea where the bug may lie?

**Comment by samouss** [comment]
No I have no idea from the code. Could you provide us an example it will be much easier to understand. You can find a template on [CodeSandbox](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/React%20InstantSearch). Here is [an example](https://codesandbox.io/s/jp44z0y375) that renders a `SearchBox` with a `defaultRefinement`. Every 2.5 seconds the refinement will change from one value to the other. You can see that the refinement is apply from the first render.

**Comment by Bouncey** [comment]
I cannot reproduce on CodeSandbox. The repository is [here](https://github.com/freeCodeCamp/search-assets) in the `www/` folder.

Could it be due to the fact that we are not refining as such? We display the results as they come. The `defaultRefinement` prop seemed to do what I wanted at the time (populate SearchBox on mount).

**Comment by samouss** [comment]
Thanks for the example it helps a lot! Even without the call to `refine` the default refinement is correctly applied on the SearchBox but the results are not displayed. In React InstantSearch a `defaultRefinement` is not applied on the `searchState`. Only a "'real" refinement (triggred by `refine`) is applied. In the `<Results>` component there is condition to display the freeCodeCamp logo when the query is empty. The value from the query is coming from the `searchState` where the `defaultRefinement` is not applied. So the value is empty and we display the logo instead of the results.

You don't need to use the `defaultRefinement` to achieve the URLSync. You can use the control mode of `<InstantSearch>`. You can find more details about that [in our documentation](https://community.algolia.com/react-instantsearch/guide/Routing.html). I made [a PR](url) that implement the URLSync in your project.

**Comment by Bouncey** [comment]
Awesome! Thanks @samouss! I will pull it down and check it out shortly! :+1:

**Comment by Bouncey** [comment]
Thanks for all your help on this @samouss and @Haroenv

**Comment by Haroenv** [comment]
With pleasure! Nice to see fcc uses Reacr InstantSearch :)
