### ISSUE TITLE
[docs]: Autocomplete does not close correctly

### ISSUE THREAD

**Issue by pixelastic** [algolia/react-instantsearch#112]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When typing a search query on the website, there is no way to close the autocomplete unless we select a result.

![2017-06-03_13h21m29](https://cloud.githubusercontent.com/assets/283419/26753130/99938134-485f-11e7-928d-f05bb2636e48.gif)

**Bug: What is the expected behavior?**
Clicking outside the dropdow, pressing Escape or clicking the "close" icon should hide the dropdown.

**Comment by Haroenv** [comment]
We should move to the community header. There are some other bogs with this search bar too. Cc @jonasba
