### ISSUE TITLE
Hit's properties are undefined within custom hit component

### ISSUE THREAD

**Issue by sakhmedbayev** [algolia/react-instantsearch#1122]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**

I am using custom `hitComponent` to display individual `hits`. Here is how I declare it

```
<Hits
      hitComponent={hit => <HitComponent hit={hit} openLinkItemInModal={openLinkItemInModal} locale={intl.locale} />}
/>
```

If I `console.log(hit)` within `HitComponent` component, all hit's properties values are present, but if `console.log(hit.someproperty)` it is not, none of the properties are accessible. They all get `undefined`.

**What is the version you are using? Always use the latest one before opening a bug issue.**

v4.5.2 (cannot use latest v5 version, this project is in production)

**Comment by sakhmedbayev** [comment]
Sorry, did not realize that after such refactoring:

```
<Hits
      hitComponent={hit => <HitComponent hit={hit} openLinkItemInModal={openLinkItemInModal} locale={intl.locale} />}
/>
```

hit's properties become access not like `hit.someproperty`, but like `hit.hit.someproperty`

**Comment by Haroenv** [comment]
```jsx
<Hits
      hitComponent={({hit}) => <HitComponent hit={hit} openLinkItemInModal={openLinkItemInModal} locale={intl.locale} />}
/>
```

writing the code like this allows the access like you originally expected, 

Another option you can do is:

```jsx
<Hits hitComponent={HitComponent} />
```

In that case you'd need to make sure the other props are somehow given to HitComponent too, which might not make sense in your app
