### ISSUE TITLE
How to order or sort hits alphabetically in React Native

### ISSUE THREAD

**Issue by ragunaru** [algolia/react-instantsearch#1123]
Hi there,

After hours of searching all possible places, I am no closer to understanding how does one sort or order their returned hits in React Native.

I have set up the Configure widget like such:

```
<Configure filters='NOT venue_categories.name:"This"' />
```

The hits are returned by default in alphabetically descending order, I would like them to be in ascending order.

I would appreciate the help because the documentation just does not provide this simple piece of information.

**Comment by Haroenv** [comment]
You can change that in the index settings, since it's related to how the index actually is searched. Your attribute in `searchableAttributes` either has unordered or descending set. 

Did that help your issue?

**Comment by ragunaru** [comment]
It seems I had to also add it to the ranking formula like such:

![image](https://user-images.githubusercontent.com/795389/38084167-b5469e14-3343-11e8-9762-2c59b383fbd8.png)

Solved now! Many thanks, @Haroenv! Closing the issue.

**Comment by ragunaru** [comment]
Just as a follow up: I feel like this should be mentioned in the documentation somewhere, around query parameters and filters for the poor souls who, like me, go there to look for this.

**Comment by Haroenv** [comment]
Ah yeah sorry, it indeed had to be changed in the ranking formula too. Thanks for this feedback. Lots of information is also in the main [algolia.com/doc](https://algolia.com/doc), don't forget to look there too :)
