### ISSUE TITLE
How to show results only when user types in the search box?

### ISSUE THREAD

**Issue by kaloraat** [algolia/react-instantsearch#1126]
I just went through <a href="https://www.algolia.com/doc/tutorials/search-ui/instant-search/build-an-instant-search-results-page/reactinstantsearch/">this article</a> and it is fantastic but I want to show the results only when user starts to type something in the searchbox.

But the tutorial shows a list of results already on display! I don't remember visiting a single site on the internet that has a search box with results already pre-populated? I just can't understand why you would create a tutorial like that... but I agree that it is a great idea for a tutorial :) since users can see the content on the page as they land, and all they do is filter the existing content using serachbox... huh!

Can anyone help me understand how to show the results only when user starts typing and I would also like to add a link on the search results, that will take users to that particular product page.. Thanks!

**Comment by Haroenv** [comment]
You can use [`connectStateResults`](https://community.algolia.com/react-instantsearch/connectors/connectStateResults.html) to get the query the user typed, and not render the results in case the `searchState.query === ''`. 

See also [this guide](https://community.algolia.com/react-instantsearch/guide/Conditional_display.html#displaying-content-when-the-query-is-empty) about the topic

**Comment by kaloraat** [comment]
Hi Haroenv, thanks for your reply. I am new to it and just cant seem to figure it out. I was able to follow the official tutorial but... once i add connectStateResults, I don't know how to go further.. Can you please help... here is my code:

```
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { InstantSearch, Hits, SearchBox, Highlight, HitsPerPage, Configure } from 'react-instantsearch/dom';
import { connectStateResults } from 'react-instantsearch/connectors';

const Search = () => {
    return (
        <div className="container">
            <SearchBox />
            <Hits hitComponent={Product} />
        </div>
    );
};

const Product = ({ hit }) => {
    return (
        <div style={{ marginTop: '10px' }}>
            <span className="hit-name">
                <a href="#">
                    <Highlight attribute="name" hit={hit} />
                </a>
            </span>
        </div>
    );
};

const Content = connectStateResults(
    ({ searchState }) =>
        searchState && searchState.query ? <div>The query {searchState.query} exists</div> : <div>No query</div>
);

const App = () => (
    <InstantSearch appId="latency" apiKey="6be0576ff61c053d5f9a3225e2a90f76" indexName="instant_search">
        <Configure hitsPerPage={20} />
        <Search />
        <Content />
    </InstantSearch>
);

export default App;
```
<a href="https://prnt.sc/iy0mor">Link to the screenshot 1</a>
<a href="https://prnt.sc/iy0n8f">Link to the screeshot 2</a>

**Comment by Haroenv** [comment]
You're able to do the following: 

```js
import React, { Component } from "react";
import ReactDOM from "react-dom";
import {
  InstantSearch,
  Hits,
  SearchBox,
  Highlight,
  Configure
} from "react-instantsearch/dom";
import { connectStateResults } from "react-instantsearch/connectors";

const Search = () => {
  return (
    <div className="container">
      <SearchBox />
      <Results />
    </div>
  );
};

const Product = ({ hit }) => {
  return (
    <div style={{ marginTop: "10px" }}>
      <span className="hit-name">
        <a href="#">
          <Highlight attribute="name" hit={hit} />
        </a>
      </span>
    </div>
  );
};

const Results = connectStateResults(
  ({ searchState }) =>
    searchState && searchState.query ? (
      <Hits hitComponent={Product} />
    ) : //<div>No query</div>
    null
);

const App = () => (
  <InstantSearch
    appId="latency"
    apiKey="6be0576ff61c053d5f9a3225e2a90f76"
    indexName="instant_search"
  >
    <Configure hitsPerPage={20} />
    <Search />
  </InstantSearch>
);

ReactDOM.render(<App />, document.getElementById("root"));
```

see this sandbox: https://codesandbox.io/s/y2k9mv02xv

**Comment by kaloraat** [comment]
@Haroenv 
You are an absolute legend! Seriously, Cant thank you enough! Now I understand how it works...

Cheers!

**Comment by Haroenv** [comment]
With pleasure!

**Comment by jameskennethrobinson** [comment]
@Haroenv Thank you!
