### ISSUE TITLE
Geo Search example for react native?

### ISSUE THREAD

**Issue by ramachandranv** [algolia/react-instantsearch#1138]

**Comment by samouss** [comment]
We don't have a specific example of GeoSearch for React Native. But you can find a GeoSearch example [in our documentation](https://github.com/algolia/react-instantsearch/tree/master/examples/geo-search). The concepts remain the same, only the rendering will change. We also have an example of [a complete application](https://github.com/algolia/react-instantsearch/tree/master/examples/react-native) built with React Native.

**Comment by samouss** [comment]
I'm closing this one, feel free to open a new one if you still have a question.
