### ISSUE TITLE
[docs]: Community icon not showing properly

### ISSUE THREAD

**Issue by pixelastic** [algolia/react-instantsearch#114]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Clicking on the "Algolia Community" link in the head will show a dropdown of our community projects, but some of them are missing icons.
![image](https://cloud.githubusercontent.com/assets/283419/26753209/b30b44ec-4861-11e7-873e-fb2b6d9da20a.png)

**Bug: What is the expected behavior?**
All projects should have their icon.

cc @LukyVj @JonasBa: I don't know where those images should be loaded from.

**Comment by mthuret** [comment]
I think it's the same thing than here => RIS must be updated with the new header from @JonasBa => https://github.com/algolia/react-instantsearch/issues/40
