### ISSUE TITLE
Documentation for conditional display with multiple indices appears to have a bug in it.

### ISSUE THREAD

**Issue by tmaconnelly** [algolia/react-instantsearch#1140]
Hello! 

Thank you so much for this project as it has been an immense help!

I believe that while reading the documentation on how to implement a no search results found page (https://community.algolia.com/react-instantsearch/guide/Conditional_display.html) with multiple indices I have found a bug in the code snippet provided in the documentation.

The reduce function will return true if the last expression evaluates to `true`.  This means if you have a search result hit in the the first index, but not in the last index the function in the documentation will return true, and hide search results event though there are some results. 

Locally I have just changed the `reduce` to `every` and it seems to work fine.

`const array1 = [false, false, false, true];`
`const reducer = (accumulator, currentValue) => currentValue;`
`// Will output true`
`console.log(array1.reduce(reducer, false));`

Here is the screenshot for the code in question.  Please let me know if I'm missing something or any clarification is needed.

https://community.algolia.com/react-instantsearch/guide/Conditional_display.html
<img width="811" alt="screen shot 2018-04-03 at 12 48 28 pm" src="https://user-images.githubusercontent.com/33642109/38263249-9b17239e-373d-11e8-8478-410dac84382a.png">

**Comment by samouss** [comment]
Hi @tmaconnelly, thanks for spotting this it's definitely an bug!
