### ISSUE TITLE
How to apply default filters for boolean and date field

### ISSUE THREAD

**Issue by ramachandranv** [algolia/react-instantsearch#1143]
I have a jobs record which have a **boolean** **attribute** active and a **valid_until**  **date** attribute.

I would like to get the jobs list applying these two attribute filters. How would I implement this in react native?

**Comment by Haroenv** [comment]
You can put both of those in the `filters` key for `Configure`

**Comment by ramachandranv** [comment]
Thank you @Haroenv 

Below thing worked for me
`var filterQuery = "active:true AND valid_until>"+Math.round(+new Date()/1000);`
`<Configure filters={filterQuery} />`
