### ISSUE TITLE
Question: how to detect and handle errors? (especially apiKey)

### ISSUE THREAD

**Issue by ArnaudRinquin** [algolia/react-instantsearch#1144]
We are building an SPA which uses Algolia for search-related features. While we periodically renew users apiKey, cases might happen where the key is expired (user reopens his laptop and starts searching right away before any renewal can be made).

I've searched through the documentation but could not find a way to hook an `onError` callback or even detect when there are similar issues.

Does anyone have pointers?

**Comment by Haroenv** [comment]
A regular error should be thrown when API key is incorrect. In that case you can use an Error boundary around the `<InstantSearch />`

see https://reactjs.org/docs/error-boundaries.html

**Comment by samouss** [comment]
You can also use the connector [`connectStateResults`](https://community.algolia.com/react-instantsearch/connectors/connectStateResults.html#default-props-entry-connectStateResults-error) to access the error.

**Comment by ArnaudRinquin** [comment]
@Haroenv I tried using React error boundaries with success:

```js
class SearchContainer extends React.Component {
  componentDidCatch(error) {
    debugger
    console.log('error', error)
  }
  render() {
    const { searchToken, searchState, searchApplicationId } = this.props
    if (!searchToken) {
      return false
    }

    const query = cleanSearchQuery(searchState.get('query'))
    return (
      <InstantSearch
        appId={searchApplicationId}
        apiKey="obviously-invalid" //{searchToken}
        indexName="notes"
        root={{
          Root: 'div',
          props: {
            className: 'flexbox flexbox-no-grow flexbox-no-shrink',
            style: { width: 300 },
          },
        }}
        searchState={{ query, hitsPerPage: HITS_PER_PAGE }}
      >
        <SearchPanel />
      </InstantSearch>
    )
  }
}
```

I can see the 403s in the debug tools but the debugger isn't stopping and no logs show in my console. This isn't so surprising as I guess these network errors are asynchronous and can't be caught by React (unless InstantSearch specifically rethrows them in a way React can catch).

I coupled it with @samouss solution and it worked:

```js
class SearchContainer extends Component {
  componentDidCatch(error, info) {
    this.props.fetchSearchToken()
  }

  render() {
    const { searchToken, searchState, searchApplicationId } = this.props
    if (!searchToken) {
      return false
    }

    const query = cleanSearchQuery(searchState.get('query'))
    return (
      <InstantSearch
        appId={searchApplicationId}
        apiKey={searchToken}
        indexName="notes"
        root={{
          Root: 'div',
          props: {
            className: 'flexbox flexbox-no-grow flexbox-no-shrink',
            style: { width: 300 },
          },
        }}
        searchState={{ query, hitsPerPage: HITS_PER_PAGE }}
      >
        <SearchErrorCatcher />
        <SearchPanel />
      </InstantSearch>
    )
  }
}

const SearchErrorCatcher = connectStateResults(
  class SearchErrorCatcher extends Component {
    error = null

    componentWillReceiveProps(nextProps) {
      if (this.error && !nextProps.error) {
        this.error = null
      }
      if (!this.error && nextProps.error) {
        // only throw on new errors
        throw nextProps.error
      }
    }
    render() {
      return null
    }
  }
)
```

**Comment by samouss** [comment]
@ArnaudRinquin Thanks for sharing your solution. At the end you don't even need to re-throw the error. You can call a function that will renew the `apiKey` directly from `willReceiveProps`.

**Comment by ArnaudRinquin** [comment]
Oh I know I don't have to, but it feels cleaner.

**Comment by samouss** [comment]
The error boundaries are used to catch error related to the rendering. This one is not related to the rendering, you can recover it independently from React (see [Error Boundaries](https://reactjs.org/docs/error-boundaries.html)).

You are right a prop `onError` could also work, I like the approach with the declarative `SearchErrorCatcher `. It act a bit like an error boundaries at the end, it catch the network error of InstantSearch. We could provide a widget out of the box it will feels a bit more natural.

**Comment by carlreid** [comment]
@Haroenv What would the equivalent hook for `connectStateResults` be then? I can't find anything that matches it on the [upgrade guide](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react-hooks/), or no [widget in the list](https://www.algolia.com/doc/api-reference/widgets/react-hooks/) that seems to have a state that contains `error`.  
  
I also can't find a hook that exposes `searching` either. Would I have to `useConnector` to [`connectStateResults`](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/connectors/connectStateResults.js) from `react-instantsearch-core`? The [example](https://www.algolia.com/doc/api-reference/widgets/connector/react-hooks/#examples) on how to do this, shows connecting to a connector from `instantsearch.js/es/connectors`, but it seems there is no `connectStateResults` connector in the [connectors directory](https://github.com/algolia/instantsearch.js/tree/master/src/connectors) over there?  
  
Maybe you can see, I'm a bit lost!

**Comment by carlreid** [comment]
@dhayab Thanks, I'll check it out. Completely missed this "Conditional Display" section when I CTRL + F for errors 😅

Stalled isn't enough in the case we wish to show a spinner while it's searching, so could be nice if it made a return in the future, though not critical to have for now.

**Comment by FabienMotte** [comment]
Hey!

We're doing a round of clean up before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js).

I'm going to close this issue since a solution was provided by @dhayab.
We now have a [Status API](https://www.algolia.com/doc/api-reference/widgets/use-instantsearch/react-hooks/#widget-param-status) returned by the `useInstantSearch()` hook that could be useful for your use-case.
