### ISSUE TITLE
Clear only Specific Filters

### ISSUE THREAD

**Issue by ramachandranv** [algolia/react-instantsearch#1152]
Is there a way to clear specific facet filters in instant search. I would like to know the implementation of that in react native.

Or else after clear refinements how do I reset to default refinements applied initially. Because the clearRefinement actually clears default refinements applied to a facet field.

For example I have a refinement as below which has defaultRefinement set

<RefinementList attribute="specialities" defaultRefinement={['foo', 'bar']} />

The clearRefinement method as implemented below
const ClearAllRefinements = ({refine, items}) => {
return <TouchableHighlight underlayColor="#eef0f0" onPress={() => refine(items)} style={{height: 50, flex: 1, flexDirection: 'column', justifyContent: 'center', alignItems: 'center'}}>
Clear

};

const ConnectedClearAllRefinements = connectCurrentRefinements(ClearAllRefinements);

clears all filters including the defaultRefinements. I don't want that defaultRefinement to be cleared off.

Is there any option parameter which I can pass to to ignore that was my question.

**Comment by Haroenv** [comment]
Did you try the `transformItems` as I suggested?

**Comment by Haroenv** [comment]
You can also `.filter` out directly in `refine(items)` to exclude `specialities`

**Comment by ramachandranv** [comment]
@Haroenv Can you provide a example code for my above code? I just want to clear all filters including specialities except the specialities that is defined as defaultRefinement.

**Comment by Haroenv** [comment]
you can take a look at https://github.com/algolia/react-instantsearch/issues/69 :)

**Comment by ramachandranv** [comment]
@Haroenv  That works.:) Thank you.:)

**Comment by ramachandranv** [comment]
The example actually skips the entire category filter itself. 

My requirement still is if I select more categories apart from defaultRefinement then clear should only clear the extra categories selected but not the default

I have categories like 
<RefinementList 
    attribute="materials" 
    defaultRefinement={["Polyamide"]} 
  />

In facets I have ["Polyamide", "Polyamide1", "Polyamide3"] where Polyamide will be selected by default.

If I select other two filter options Polyamide1 and Polyamide2 and later want to clear filters basically reset the filters, it should only clear Polyamide1 and Polyamide2 and Polyamide should not be cleared.

Is the possible?

**Comment by Haroenv** [comment]
ah, you should be able to do that, if somewhere you keep the default refinements in the state and force a rerender:

```js
class App extends Component {
  state = {
    defaultRefinements: {
      materials: ['Polyamide'],
    },
  };

  render() {
    return (
      <InstantSearch
        appId="latency"
        apiKey="6be0576ff61c053d5f9a3225e2a90f76"
        indexName="ikea"
      >
        <VirtualRefinementList
          attribute="materials"
          defaultRefinement={this.state.defaultRefinements.materials}
        />
        <ClearAll
          transformItems={items => {
            items.filter(item => item.attribute !== 'materials');
            this.forceUpdate();
          }}
        />
        <Hits />
      </InstantSearch>
    );
  }
}
```

By the way, we are aware that this isn't the best solution, but probably the best possible without doing major breaking changes @ramachandranv :)

**Comment by Haroenv** [comment]
thanks, updated it!

**Comment by callmenoodles** [comment]
`refine(null)` worked for me.
