### ISSUE TITLE
Example for Algolia Places integration with react-instantsearch ?

### ISSUE THREAD

**Issue by arnaudambro** [algolia/react-instantsearch#1158]
Hi there,

Do you have somewhere a simple Component example of Algolia Places used with react-instantsearch ?
I am desperately trying to mix the two of them, but I can't figure out what to use : `<Hit>` ? how ?
It's [written in the doc](https://community.algolia.com/places/documentation.html#instantsearchjs) that we should have [a HTMLInputElement as a required container option](https://community.algolia.com/places/documentation.html#options), so how do you deal with React where you shouldn't be able to touch the DOM ?

Cheers
Arnaud

**Comment by Haroenv** [comment]
There's a few React components wrapping Places.js, none of them officially made by us, but they should work:

* https://yarnpkg.com/en/package/algolia-places-react
* https://yarnpkg.com/en/package/react-places-autocomplete
* https://yarnpkg.com/en/package/react-algolia-places
* https://yarnpkg.com/en/package/react-custom-places-input

Does that help you?

**Comment by arnaudambro** [comment]
Hi @Haroenv 
Thanks for your reply, and for the list ! I wanted to do it myself and not use other API, but you're right, why not ?

So from your list :

- `react-custom-places-input` ended up with a coding error (and doesn't seems to be developed by the owner anymore since two years) => you can strike it through
- `react-places-autocomplete` is the one I have been using before, but for me it us using Google and not Algolia, isn't it ? I wish I could leave Google, that's why I went to Algolia, so I won't use this package.

Regarding the two other ones, they seem very easy to use and great, however I get a 403 Error `Invalid Application-ID or API key` even though I think they are valid, because I made the work with `react-instantsearch`, do you have the same results ?

**Comment by Haroenv** [comment]
hmm, did you create an Algolia places app? <https://www.algolia.com/users/sign_up/places>

My bad for that react-places-autocomplete one, didn't read the description properly. 

Which kind of experience do you want to to have with the places input? Is it the users search query, facet query or aroundRadius?

**Comment by arnaudambro** [comment]
Wow, tried for minutes to find a page like [https://www.algolia.com/users/sign_up/places](https://www.algolia.com/users/sign_up/places), but couldn't find it ! What should've done as a user to reach there ? 

It's working perfectly now. 

> Which kind of experience do you want to to have with the places input? Is it the users search query, facet query or aroundRadius?
I want a map (OpenStreetMap) to focus on the Place put by the user. I think Algolia can give me all I need !

Thanks @Haroenv for your precious help !
Cheers

**Comment by Haroenv** [comment]
Perfect! I think @samouss might also have something for that planned in #1073, but it's not ready yet :)  That link was given on https://community.algolia.com/places, but maybe not discoverable enough in the dashboard.

**Comment by samouss** [comment]
Indeed it will fit the use case for displaying hits on the map. But it will not allow you to use Places out of the box. It's still something that we are looking to provide!

**Comment by arnaudambro** [comment]
Even after you tell me, I still don't find the link on the page...
Anyway, I'll use `algolia-places-react` because it offers more configuration possibilities than `react-algolia-places`. Looking forward to you connecting Places with react-instantsearch, because that would be a serious open-source alternative to Google Places API !
Thanks !
