### ISSUE TITLE
Is it possible to add props to a connector?

### ISSUE THREAD

**Issue by roma98** [algolia/react-instantsearch#1167]
Hi all,

This is not bug, nor a feature request, more like a cookbook recipe.
I have been using [connectors](https://community.algolia.com/react-instantsearch/guide/Connectors.html) with great success, mainly to customise the <Hits/> component.
However I have one question, that is maybe more React oriented, but I couldn't find a solution.
I would like to add optional props to this customised `<Hits/>` component (something like `<Hits prop={'bla'}/>`).
But since this component exports `connectHits(({ hits }) => {...}` I feel a bit stuck.
I've been trying to wrap it inside a class, but I couldn't find a solution to get the `hits` props.

Thanks a lot!

**Comment by Haroenv** [comment]
```js
class RawHits extends Component {
  render() {
    const { 
      hits, // from connector
      prop, // from calling Hits
    } = this.props;
    return null; // do something with it
  }
}

const Hits = connectHits(RawHits);
```

or you can do it inline too:

```js
const Hits = connectHits(({hits, prop}) => {}/* use hits and prop */)
```

Then later you can use it like this: `<Hits prop={'bla'}/>`

**Comment by Haroenv** [comment]
Let me know if that was what you expected!

**Comment by roma98** [comment]
thanks @Haroenv! I like the inline solution, it seemedi so obvious at first that I didn't try it in the first place :)

**Comment by Haroenv** [comment]
Perfect! You can also check out the React documentation on higher order components: https://reactjs.org/docs/higher-order-components.html
