### ISSUE TITLE
Connector items returning wrong values

### ISSUE THREAD

**Issue by gilesbutler** [algolia/react-instantsearch#117]
Not sure if this is a bug or if we're doing some thing wrong. When using the [connectRefinementList](https://community.algolia.com/react-instantsearch/connectors/connectRefinementList.html) widget we're getting strange results from the provided `items` prop. The docs say that each items `value` prop should be a string: `type: array.<{count: number, isRefined: boolean, label: string, value: string}>` - But we are getting an array.

Here is a [jsFiddle](https://jsfiddle.net/ar80rgpc/21/) showing the same results. 

**Bug: What is the current behavior?**
```
{
  "label": "double degree",
  "value": [
    "double degree"
  ],
  "count": 700,
  "isRefined": false
}
```

**Bug: What is the expected behavior?**
```
{
  "label": "double degree",
  "value": "double degree",
  "count": 700,
  "isRefined": false
}
```

Also the `value` prop is changing it's value each time we select an item. It looks like the item we are selecting is being added to the `value` prop of all the other items.

**Bug: What is the current behavior?**
```
[
  {
    "label": "double degree",
    "value": [],
    "count": 700,
    "isRefined": true
  },
  {
    "label": "single degree",
    "value": [
      "double degree",
      "single degree"
    ],
    "count": 250,
    "isRefined": false
  },
  {
    "label": "Master Degree",
    "value": [
      "double degree",
      "Master Degree"
    ],
    "count": 123,
    "isRefined": false
  },
]
```

**Bug: What is the expected behavior?**

```
{
  "label": "double degree",
  "value": "double degree",
  "count": 700,
  "isRefined": true
}
```

**Comment by mthuret** [comment]
Hi @gilesbutler, 

Actually this is the normal behaviour :) There's a typo in the documentation. `value` is an array of string because actually it contains all the already selected value plus the value itself if the value is not selected yet, and all the already selected value minus the value itself if the value is selected. It's a precomputed value for the select/unselect value behaviour of the refinementList. 

Is their something wrong in your implementation with the `refinementList`?

**Comment by gilesbutler** [comment]
Thanks for getting back to me @mthuret - sorry for the late reply, I got hit with food poisoning! 

It seems like a bit of an odd implementation but I'm probably just looking at it from our use case. Which is that we're trying to use it with [react-select](https://jedwatson.github.io/react-select/). I find it strange that `value` needs to change at all, maybe I'm missing something. But for each item in the `items` array there is a `isRefined` prop, so why would the `value` of each item need to be changed at all if `isRefined` is set to `true`? 
Again, I don't know all the other use cases so sorry if I'm missing something :)

Do you have any examples of using a dropdown menu with the `refinementsList` at all?

**Comment by Haroenv** [comment]
Shouldn't that be a connectMenu since a drop down can only have one value?

**Comment by gilesbutler** [comment]
@Haroenv react-select has a `multi` option so you can select more than one option. I've got it working now by using the `label` prop instead of `value`. Feels a bit hacky but seems to be working ok. I'm still pretty sure there is something wrong on Algolia's end though. I've seen the `value` prop come through as null, an empty string and a string with the value in it. As well as an array with the behaviour @mthuret described.

**Comment by mthuret** [comment]
@gilesbutler That's because `react-select` uses its own model and keep track of the selected data. This kinda messed up with the way we are computing the values. But it's ok, it still can work :)

Here's a working example using React InstantSearch. 

```js
class ReactSelect extends React.Component {
  constructor(props) {
    super(props);
    this.state = { value: '' };
    this.handleSelectChange = this.handleSelectChange.bind(this);
  }
  handleSelectChange(item) {
    this.props.refine(item.length > 0 ? item[item.length - 1].value : '');
    this.setState({ value: item });
  }
  render() {
    return (
      <Select
        name="form-field-name"
        multi
        value={this.state.value}
        options={this.props.items}
        onChange={this.handleSelectChange}
      />
    );
  }
}
```

Also here's another example of the usage of the connectRefinementList connector. You can see how those pre-computed values make things easier. 

```js
class RefinementList extends React.Component {
  render() {
    const items = this.props.items.map(item => (
      <li
        onClick={() => {
          this.props.refine(item.value);
        }}
      >
        {item.label}
      </li>
    ));
    return <ul>{items}</ul>;
  }
}
```

**Comment by gilesbutler** [comment]
Awesome, thanks @mthuret. Makes more sense :) Appreciate your help 👍
