### ISSUE TITLE
Range query below or above range

### ISSUE THREAD

**Issue by ramachandranv** [algolia/react-instantsearch#1174]
I have a experience field with array of values like [1,2,3,4]. I have a range slider to get the results between two range values.

Initially we get the range values from the results like say 5-20. When I move the slider between 10-20 I do get filtered results. But I'm not able to move the slider below or above range values. I should be able to move back to previous state and get the appropriate results. Is there a way to implement this?

**Comment by samouss** [comment]
Hi, I didn't understood your issue. Could you make a working example that will help us to better understand the problem? With the example please precise the expected behaviour. For the example we provide template in order to avoid you the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/React%20InstantSearch). Thanks!

**Comment by ramachandranv** [comment]
Hi @samouss Basically in range slider we can select the range below or beyond the field min and max values from the search results right? Is there any workaround for that. Or will this work if I remove experience field from facetAttribute?

Below the example code for react native.

`class Range extends React.Component {
  static propTypes = {
    min: PropTypes.number,
    max: PropTypes.number,
    currentRefinement: PropTypes.object,
    refine: PropTypes.func.isRequired,
    canRefine: PropTypes.bool.isRequired
  };

  state = { currentValues: { min: this.props.min, max: this.props.max } };

  componentWillReceiveProps(sliderState) {
    if (sliderState.canRefine) {
      this.setState({
        currentValues: {
          min: sliderState.currentRefinement.min,
          max: sliderState.currentRefinement.max
        }
      });
    }
  }

  onChange = sliderState => {
    this.props.refine({
      min: sliderState[0],
      max: sliderState[1]
    });
    // this.props.refine({
    //   min: (this.props.currentRefinement.min <= sliderState[0] ? sliderState[0] : this.props.currentRefinement.min),
    //   max: (this.props.currentRefinement.max >= sliderState[1] ? sliderState[1] : this.props.currentRefinement.max)
    // });
    this.setState({
      currentValues: { min: sliderState[0], max: sliderState[1] }
    });
  };

  render() {
    const { min, max, currentRefinement } = this.props;
    const { currentValues } = this.state;
    const label = this.props.attribute.split('_').join(' ');
    const filterTitle = label.charAt(0).toUpperCase() + label.slice(1);
    return min !== max ? (
      <View style={{ padding: 20, borderBottomWidth: 1, borderColor: '#ebeced' }}>
        <Text style={{ fontSize: 18, marginBottom: 20 }}>{this.props.attribute.split('_').join(' ').toUpperCase()}</Text>
        <MultiSlider
          containerStyle={{
            height: 20
          }}
          values={[currentRefinement.min, currentRefinement.max]}
          sliderLength={Dimensions.get('window').width - 40}
          onValuesChange={this.onChange}
          min={currentRefinement.min}
          max={currentRefinement.max}
          step={1}
          allowOverlap
          snapped
        />
        <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
          <Text style={{ fontSize: 16, marginRight: 10 }}>From : {currentValues.min}</Text>
          <Text style={{ fontSize: 16 }}>To : {currentValues.max}</Text>
        </View>
      </View>
    ) : null;
  }
}`

`const ConnectedRange = connectRange(Range);`

`class Filters extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      
    }
  }

  render() {
    return (
        <InstantSearch
          appId={Global.INSTANT_SEARCH.appId}
          apiKey={Global.INSTANT_SEARCH.apiKey}
          indexName={Global.INSTANT_SEARCH.indexName}          
        >
          
          <View style={styles.container}>
            <ScrollView contentContainerStyle={{ flexGrow: 1 }}>
              <ConnectedRange attribute="experience" />
              <RefinementList attribute="city" />
            </ScrollView>
          </View>
        </InstantSearch>
    );
  }
}

export default Filters;`

**Comment by ramachandranv** [comment]
@samouss That solves the problem. Thanks a lot.:)
