### ISSUE TITLE
Linked v5 migration guide is a 404

### ISSUE THREAD

**Issue by econner** [algolia/react-instantsearch#1175]
The guide you've linked in CHANGELOG.md under version 5.0.0 points to https://community.algolia.com/react-instantsearch/guide/migration_guide_v5 which is a 404.

There is also no v5 migration guide listed here:
https://community.algolia.com/react-instantsearch/guide/Migration_guides.html

**Comment by samouss** [comment]
Thanks a lot for the notice @econer! We’ll fix it asap.

**Comment by Haroenv** [comment]
link should have been https://community.algolia.com/react-instantsearch/guide/Migration_guide_v5.html
