### ISSUE TITLE
[docs]: Confusing connectHighlight example

### ISSUE THREAD

**Issue by pixelastic** [algolia/react-instantsearch#118]
I'm quite confused as the way highlighting is working in React InstantSearch. I need my highlight to be enclosed in `<span class="highlight"></span>`, so I defined `highlightPreTag` and `highlightPostTag` in my index settings, but those are locally overriden by the library.

I looked at options on how to define a custom markup in the `Highlight` component, but could only find a way to change the HTML tag, and not the CSS class. As usual when it comes to CSS styling, it feels like the solution is using custom connectors.

![image](https://cloud.githubusercontent.com/assets/283419/26763257/1a294220-4950-11e7-9e2b-9bd2f98b7f1a.png)

I got even more confused by this documentation:

- It mentions `attributeName`, `hit` and `path`, but `path` is never used in the code snippet. I don't understand how I'm supposed to use it.
- The snippet mentions `highlightProperty: 'highlightProperty'` but I have no clue what that means
- It's telling me I can use it in the same way as widgets, but I don't understand how

I'm not sure if it's a lack in the documentation or in the feature set, but I can't find the proper way to do highlight with `<span class="highlight">word</span>`.

**Comment by mthuret** [comment]
@pixelastic I did some modifications that were not pushed yet to production about this example but definitely regarding your feedback they were not enough. The right example is: 

```js
import { connectHighlight } from '../packages/react-instantsearch/connectors';

const CustomHighlight = connectHighlight(
({ highlight, attributeName, hit, highlightProperty }) => {
  const parsedHit = highlight({ attributeName, hit, highlightProperty });
  const highligtedHit = parsedHit.map(part => {
    if (part.isHighlighted) return <span class="highlight">{part.value}</span>;
    return part.value;
  });
  return <div>{highligtedHit}</div>;
}
);
```
To be used like: 

```js
<CustomHighlight attributeName="xxx" hit="hit" highlightProperty="_highlightResults"/>
```

highlightProperty is the former path, you need to indicate the structure that contains the highlighting values: _highlightResults or _snippetResults.

**Comment by pixelastic** [comment]
Thanks, it's much clearer. You still have a few small typos (`s/highligtedHit/highlightedHit` and `hit={hit}').

I think the documentation would be enhanced with this example.

By going the custom connector route, aren't I missing some of the features/edge-cases that are handled in the default Highlight component?

**Comment by mthuret** [comment]
Have you some features/edge-cases in mind?

**Comment by pixelastic** [comment]
Nope, I just have the feeling that by using the connector I'm entirely bypassing the work you did on the official `Highlight` component. And as I don't know what it's doing under the hood I was just wondering if maybe there were edge-cases I was missing.

**Comment by mthuret** [comment]
This work is done inside the `highlight` function :). 
The `Highlight` widget only creates the markup. 

Just by curiosity why couldn't you just reuse our own classnames?

**Comment by pixelastic** [comment]
Ideally, I'd like to take advantage of my already existing CSS classes. I already have classes that do highlight, and I would like to apply those classes to the highlight element.

As a workaround, I have been using `.ais-Highlight__highlighted` and used SCSS to `@extend` it to add the styling from my initial class, but this is far from optimal. The way `@extend` works in SCSS creates cascading priorities issues and won't scale well. It works for now, but I know it will hit me later, so I'd rather use my own existing classes if possible.
