### ISSUE TITLE
[InfiniteHits]: "Load More" button is displayed when there are no more results

### ISSUE THREAD

**Issue by pixelastic** [algolia/react-instantsearch#119]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When using the `InfiniteHits` widget, if I type a query that results in very few results, the `Load More` button is still displayed while there are no more records to load. Clicking on it does not do anything.

You can test it in the [storybook](https://community.algolia.com/react-instantsearch/storybook/?selectedKind=InfiniteHits&selectedStory=default&full=0&down=1&left=1&panelRight=1&downPanel=kadirahq%2Fstorybook-addon-knobs), by typing `grundtal hanging`
![image](https://cloud.githubusercontent.com/assets/283419/26764433/14d2282a-4967-11e7-9826-c507c269ce80.png)
The only two matching hits are displayed, and the button is still visible.

**Bug: What is the expected behavior?**
I would expect the button to not be present, as to not imply a behavior that does not exist.

Note: A `disabled` attribute is added to the element, so it is possible to hide it using CSS.
```css
.ais-InfiniteHits__loadMore[disabled] {
  display: none;
}
```
I'm not sure this is the right way to do it. If it is, I think it should be included in the default stylesheet.

**Comment by mthuret** [comment]
It misses our `disabled` style: 

```css
    opacity: 0.5;
    pointer-events: none
```
