### ISSUE TITLE
Faceting: ConnectedRefinementList + Material UI not working properly

### ISSUE THREAD

**Issue by gennaroanesi** [algolia/react-instantsearch#1196]
**Do you want to request a *feature* or report a *bug*?** Bug

**Bug: What is the current behavior?**

When I call the refine button, my items are not consistently filtered (I get more items that the one i've refined), and the "isRefined" flag doesn't get set.

Sample (full code available on codesandbox below):

```
const MyRefinementList = ({
  attribute,
  refine,
  createURL,
  currentRefinement,
  items,
  searchForItems,
  isFromSearch,
}) => {

  return (
    <div>
      {items.map(item =>
        <Checkbox
          key={item.label}
          label={item.label + ' (' + item.count + ')'}
          checked={item.isRefined}
          onCheck={() => {
            refine(item.value);
          }}
        />
      )}
    </div>
  )
};

const ConnectedRefinementList = connectRefinementList(MyRefinementList);
```
[![Edit mjpvml420x](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mjpvml420x)
https://codesandbox.io/embed/mjpvml420x

**Bug: What is the expected behavior?**

When calling the refine button, I get all items, and the ones currently refined have the "isRefined" key set to true, so I can mark the checkbox "checked".

**Bug: What browsers are impacted? Which versions?**
Tested on Chrome 65.0.3325.181 

**What is the version you are using? Always use the latest one before opening a bug issue.**
5.0.3

**Comment by gennaroanesi** [comment]
It seems to be working fine on the demo index, but I can't get it working on my index... The faceting works fine on the Algolia Index page.

**Comment by gennaroanesi** [comment]
It's working now - guess it was a temporary glitch on the app. Thanks!

**Comment by Haroenv** [comment]
Okay, that’s good!
