### ISSUE TITLE
Add isLoading flag to connectInfiniteHits

### ISSUE THREAD

**Issue by leonardo2204** [algolia/react-instantsearch#1218]
**Feature**

Being able to receive a isLoading flag in the `connectInfiniteHits`.

**Feature: What is your use case for such a feature?**
It would be cool to show the user some UI feedback while data is being fetch from the server.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
Add a isLoading (or similar) flag in the connectInfiniteHits connector;

**Comment by leonardo2204** [comment]
I'm so sorry, actually #87 solved that!

**Comment by Haroenv** [comment]
You should also be able to use `connectStateResults` for this I think.
