### ISSUE TITLE
Feature Request - ReasonML bindings

### ISSUE THREAD

**Issue by kristinn93** [algolia/react-instantsearch#1256]
**Feature Request**

Ship with [ReasonML](https://reasonml.github.io/) bindings

**Feature: What is your use case for such a feature?**
Since the reason community is growing and gaining more adoption it would make InstantSearch a good choice for search related implementation where developers don't need to create their own bindings that could result in multiple partially completed bindings, or unofficial bindings.

Purpose of this issue is mainly to get notified if react-instantsearch ships with Reason bindings.

cc @mthuret

**Comment by Haroenv** [comment]
We are seeing less interest into reasonml / rescript nowadays. While this can be very interesting, the effort related in maintaining a binding isn't something that we can commit to. However if there's an equivalent to definitely-typed for rescript, we definitely welcome that and will try to keep it in mind!
