### ISSUE TITLE
[Theme] Hierarchical menu has no height

### ISSUE THREAD

**Issue by olance** [algolia/react-instantsearch#126]
I'm using `<Panel>` components to wrap my different refinement components.
I have a `margin-top` on the panel root to space my panels:
![image](https://user-images.githubusercontent.com/314079/27080204-307be86a-503b-11e7-96a4-6eaec3712194.png)

However as you can see, `Marcas` is not spaced from the categories menu even though the margin is applied.

The reason for that seems to be that the `.ais-HierarchicalMenu__root` element has no height, due to its children being `float: left`:
![image](https://user-images.githubusercontent.com/314079/27080314-8eed3796-503b-11e7-8aac-506705a27d46.png)

As a result, my second refinement list `Marcas` starts too high in the flow:
![image](https://user-images.githubusercontent.com/314079/27080373-d55d5fc6-503b-11e7-9022-6d0debf5e0a5.png)

cc @LukyVj

**Comment by Haroenv** [comment]
I guess since they’re floating, we need a clearfix there.

**Comment by olance** [comment]
@Haroenv I tried quickly but couldn't have it to work... I might have missed something 😅

**Comment by samouss** [comment]
I'm closing this issue since the React InstantSearch Theme doesn't exist anymore. You can take a look to [InstantSearch.css](https://github.com/algolia/instantsearch.css) instead. Thanks!
