### ISSUE TITLE
[Question] Waiting hits

### ISSUE THREAD

**Issue by Kikobeats** [algolia/react-instantsearch#131]
Hello, folks

I'm trying to setup a content placeholder until `hits` are available.

Live demo: https://tabs--windtoday-app.netlify.com/#/search

For that, I'm using a connector around `connectInfiniteHits` because I need an extra things not available in `connectInfiniteHits`, like the number of results. 

It looks like:

```jsx
export default createConnector({
  displayName: 'SearchResults',
  getProvidedProps (props, searchState, searchResults) {
    const {query} = searchState
    const {results, page} = searchResults
    const noResults = results ? results.nbHits === 0 : false

    return {query, noResults, page}
  }
})(connectInfiniteHits(Results))
```

so I use `noResults` for determinate if `hits` is ready or the query has no results:

```jsx
const products = hits.length > 0 ? hits : Array(hitsPerPage).fill({})

return (
      <main
        ref={node => (this.results = node)}
        data-app='search-results'
        className={className}>
        {isMobile && <Overlay active={hasAsideOpen} />}
        {createElement(noResults
          ? SearchNoHits
          : SearchHits, {
            ...this.props,
            hits: products
          })}
        <Footer />
      </main>
    )
```

As you can see in the code, if `hits` is empty I generate a fake array of objects. This is just for create the content placeholder until `hits` is available.

![](https://d26dzxoao6i3hh.cloudfront.net/items/3L2b2s2w3V2I2t3E2o3L/Screen%20Recording%202017-06-19%20at%2012.26%20am.gif?v=49aac582)

[source code](https://github.com/windtoday/windtoday-marketplace/blob/tabs/src/app/SearchResults/index.js#L57) 

All works fine, except the case when the URL need to load more than one page, like: 

https://tabs--windtoday-app.netlify.com/#/search?page=3

In this case, `hits` take a little of time to have 3 pages of results, so first the view will be renderered with the content placeholder. I expected, as soon as `hits` is available with the results, the view should be refresh, but don't know why this is not happening. 

In a moment of the future `hits` has the results (I saw that debugging with console.log), but the view is not refreshing the content.

I'm not sure if this is happening because I'm using a pure component... If `props` change (and `hits` is inside), render should be refresh the view, right?

Maybe is a silly thing but I didn't find the way.

**Comment by mthuret** [comment]
Hi @Kikobeats 

I'm not sure to see the issue here, on the link you gave (with page=3), I can see an actual content. Maybe it's not the good one? Can you try to isolate the wrong behavior using a [jsfiddle](https://jsfiddle.net/vvoyer/ar80rgpc/2/), it would help me understand better. 

Also, why not getting the `searchResults.searching` variable to know if the content is loading?

**Comment by Kikobeats** [comment]
Hmm lol, working in production but non on development, I suppose that is a bug from my side 🤔 

One thing, what means `es` folder in the `react-instantsearch` bundle? Should I use it if I'm using webpack and babel stack?
