### ISSUE TITLE
Can you pre filter connectInfiniteHits with transformItems ? Or remove hits somehow?

### ISSUE THREAD

**Issue by rtman** [algolia/react-instantsearch#1312]
HI,

I would like to be able to remove a list of hits from the results received by `connectInfiniteHits`, I don't see that `transformItems` is allowed as a prop. Is there a way to do this?

My use case is that I'm giving a user the ability to add items to their order, but I don't want them to be able to add duplicates of items already in their order so I need to remove whatever is in their order from the hits results.

thanks!

**Comment by Haroenv** [comment]
Hey @rtman, for that it'll be best to use `connectInfiniteHits` and use `hits.filter(isDuplicateOfUserProvided)`. Does that make sense?

**Comment by rtman** [comment]
@Haroenv  Yup totally, I was actually thinking of doing something like that but I wondered if there was a built in way with react-instantsearch. This works good tho!
