### ISSUE TITLE
No way to get refinement count? 

### ISSUE THREAD

**Issue by wallawe** [algolia/react-instantsearch#1329]
I have searched far and wide to no avail. I do not want to get the `CurrentRefinements`; Rather I just want to get a number of refinements currently applied. Is this possible?

(asked on stackoverflow as well here: https://stackoverflow.com/questions/50821523/how-can-i-get-the-current-refinement-count-using-algolia)

**Comment by Haroenv** [comment]
You can use `items.length` when doing `connectCurrentRefinements`. This will give you the number of refinements.

**Comment by wallawe** [comment]
@Haroenv thanks for your response. Does this work if I'm trying to get the count of multiple different components, e.g. `Menu`, `RangeInput`, `RefinementList`, etc?
