### ISSUE TITLE
Autocomplete Example

### ISSUE THREAD

**Issue by marcobiedermann** [algolia/react-instantsearch#1361]
I've noticed that in you autocomplete example (https://codesandbox.io/embed/github/algolia/react-instantsearch/tree/master/examples/autocomplete) the value inside the search box does not get updated after you select a value from the autosuggestion suggest box.

Do you have any hints how to fix this?
I wanted to implement this on my own project and have the same issue.

**Comment by samouss** [comment]
Thanks a lot for the notice. I've added a [PR](https://github.com/algolia/react-instantsearch/pull/1366) to fix the issue.

**Comment by marcobiedermann** [comment]
@samouss Thank you very much for the quick fix!
