### ISSUE TITLE
Ability to persist a widget

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#14]
# Use case

You have a mobile app using React Native and you want to use a modal to display some filters. When this modal is closed, the widgets that sets the refinements are unmounted, therefore, they're not in the state anymore. see: https://github.com/algolia/instantsearch.js/issues/2069

# Need

Being able to say that a widget is persistent. That way its state will remain and can still be applied if a virtual widget is present. 

# Proposal 

Add a prop `isPersistent`, that if present will indicate that nothing should happen inside the `clean` function.

**Comment by mthuret** [comment]
Another possibility here is to actually use another `<InstantSearch>` instance inside the modal, and forward the state to the main one. That way, virtual widgets does apply.

**Comment by ylac** [comment]
Yes this would be very helpful.

**Comment by mclapa** [comment]
I also see this as a problem as I have it set up in the header of my page, and every navigation between pages causes another POST

In turn I have about 2200 requests while dev (out of 100k) which will quickly fill up when it goes live.

I'm thinking about creating a component with it at the top-most parent and passing it down, perhaps it won't re-render when the component itself gets re-rendered, but we'll see how it goes

**Comment by catamphetamine** [comment]
@mclapa Thread hijacker, no thread hijacking!
We're also having this issue when using filters inside `react-modal` which unmounts contents on close.
The virtual widgets workaround would most likely work but since we're not constrained by mobile SDK here we decided to try the quick old-school pure CSS modal approach instead.

**Comment by mthuret** [comment]
I'm closing this as for now I don't have a really good API proposal that would fix everything. Our getting started explains how to get along this, feel free to re-open it if necessary or if you have a proposal :)
