### ISSUE TITLE
_geoloc object is allowed to be nested?

### ISSUE THREAD

**Issue by rtman** [algolia/react-instantsearch#1407]
Hi,

Just wondering if the _geoloc object is allowed to be nested?

Such as:

```
location: {
    _geoloc:{
        lat: 1,
        lng: 2
    },
    city: 'city',
    state: 'state,
    country: 'country'
}
```

I'm not sure if algolia is picking up the geo data in my records if they are entered as such (above).

**Comment by samouss** [comment]
The `_geoloc` must be at the root of the records otherwise it won't be picked as a location by the engine. You can find more information about that in this [Discourse](https://discourse.algolia.com/t/how-to-get-geolocation-under-nested-attribute/3577/3) thread.

**Comment by rtman** [comment]
@samouss thanks!
