### ISSUE TITLE
[ Bug ] Use of VirtualMenu with ReactNative returns 0 results in all cases

### ISSUE THREAD

**Issue by Braidio** [algolia/react-instantsearch#1411]
Using React-InstantSearch Version 5.0.3

My code is simple ->

```jsx
import { InstantSearch, Configure } from 'react-instantsearch/native';
import { connectMenu } from 'react-instantsearch/connectors';

const VirtualMenu = connectMenu(() => null);
const ByDomainName = () => <VirtualMenu attribute="type" defaultRefinement="Solution" />;

  render() {
    return (
      <View style={[styles.container]}>
        <InstantSearch
          appId={ALGOLIASEARCH_APPLICATION_ID}
          apiKey={ALGOLIASEARCH_API_KEY_SEARCH}
          indexName={ALGOLIA_INDEX_NAME}
        >
          <View
            style={{
              flexDirection: 'row',
            }}
          >
            <SearchBox />
          </View>
          <SearchContent
            shouldScrollTop={this.state.shouldScrollTop}
            onResultClick={this.onResultClick}
          />
          <ByDomainName />
        </InstantSearch>
      </View>
    );
  }
```

This is a super generic, super general filter and should return at least 5K records. However, if I convert it to use any of the attributes for our objects with the defaultRefinement to any value I can see within our Algolia Dashboard, it will always return 0 results.

This appears in all devices for mobile.

**Comment by samouss** [comment]
It it possible to provide a live example? It will help to better understand the issue. We provide template to avoid you the boilerplate part. You can find it [on CodeSandbox](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/React%20InstantSearch). The template is for React DOM but you should be able to reproduce the issue in this environment. Otherwise you can also create a small repo that we can clone & run. Thanks!

**Comment by Braidio** [comment]
@samouss Yes even more simply put. 

If I index my objects like so

```ruby
  def algolia_object
    {
      objectID:    "#{self.class.to_s.downcase}-#{id}",
      title:       self.title,
      description: self.body,
      type:        self.class.to_s,
      url:         self.url,
      tags:        self.tags.map(&:skill).map(&:name),
      _tags:       self.registration_ids,
      created_by:  self.member.full_name,
      created_on:  self.updated_at.strftime('%b %-d, %Y'),
    }
  end
```

And then I go to the Algolia Dashboard console ( algolia.com/apps )

And I search for `_tags:1` or `created_by:A Name I know exists`, no results return affected by any sort of filter/refinement. This is likely, we believe, why our search results do not work in react-instantsearch as well.
