### ISSUE TITLE
"Edit this page" button URL is broken

### ISSUE THREAD

**Issue by samouss** [algolia/react-instantsearch#1419]

**Comment by JureSotosek** [comment]
I see this still hasn't been resolved. Is anyone working on it? Can i give it a try?

**Comment by Haroenv** [comment]
Yes, if you feel like contributing, this definitely would be welcome. It's likely something that changed when we changed the folder structure. Source for the documentation is https://github.com/algolia/react-instantsearch/tree/master/docgen

**Comment by JureSotosek** [comment]
@Haroenv One quick question. If I'm not mistaken, docs are partly generated from comments from inside some of the files right?

So for example [connectHits page](https://community.algolia.com/react-instantsearch/connectors/connectHits.html) is generated from the comments from [this](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/connectors/connectHits.js) file and if somebody clicked "Edit this page" on the connectHits page they should be redirected to [this](https://github.com/algolia/react-instantsearch/edit/master/packages/react-instantsearch-core/src/connectors/connectHits.js), an edit page for the file I linked.

Or am i missing something?

**Comment by Haroenv** [comment]
yes, the link should be towards the source code, since that's what is needed to be updated :)
