### ISSUE TITLE
Add Configure widget example for filtering boolean attributes

### ISSUE THREAD

**Issue by agdavid** [algolia/react-instantsearch#1420]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**Feature: What is your use case for such a feature?**
Consider showing users how to implement `<Configure />` widget with `filters` parameters (even better if for `boolean` attributes). Currently, page talks about filtering but no example.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
Possibly adding to the ["Sorting and filtering"](https://community.algolia.com/react-instantsearch/guide/Sorting_and_filtering.html) guide an Example of Configure using filters with boolean attributes, or link to Configure [concept](https://community.algolia.com/react-instantsearch/widgets/Configure.html) and filters [docs](https://www.algolia.com/doc/api-reference/api-parameters/filters/).

**Comment by Haroenv** [comment]
```jsx
<Configure
  filters="featured:true"
/>
```

Just wondering if that is what you meant or something else :)

**Comment by agdavid** [comment]
Yes, something like that :p - I mentioned the boolean attribute example because it even gets a little more confusing with the numeric vs string boolean: 

```
<Configure filters="show:true"/>
// or <Configure filters="show=1"/>  
```

**Comment by Haroenv** [comment]
An example with `filters` should probably be put in https://www.algolia.com/doc/api-reference/widgets/configure/react/

**Comment by samouss** [comment]
Closed with https://github.com/algolia/doc/pull/2390.

**Comment by Renew-codefabric** [comment]
this dont worked, i tried this is my code: 

<Configure  filters="is_public:true" hitsPerPage={20} />

i am getting nothing

**Comment by Haroenv** [comment]
is the is_public attribute set as attributesForFaceting @Renew-codefabric ?

**Comment by Renew-codefabric** [comment]
> attributesForFaceting

so far its working with filters="category:cars" but with is_public dont worked, what is the wrong?

**Comment by Haroenv** [comment]
you set it with the dashboard or via the api client @Renew-codefabric
