### ISSUE TITLE
Reference Error : 

### ISSUE THREAD

**Issue by sabativi** [algolia/react-instantsearch#1425]
**Bug: What is the current behavior?**

After `npm i react-instantsearch-dom-maps`, and importing `import { GoogleMapsLoader, GeoSearch, Control, Marker } from 'react-instantsearch-dom-maps';` I have an error : 

```
ReferenceError: document is not defined
W20180710-18:37:06.608(2)? (STDERR)     at /Users/sabativi/playground/pup/node_modules/scriptjs/dist/script.js:12:13
W20180710-18:37:06.608(2)? (STDERR)     at doc (/Users/sabativi/playground/pup/node_modules/scriptjs/dist/script.js:8:72)
W20180710-18:37:06.608(2)? (STDERR)     at Object.<anonymous> (/Users/sabativi/playground/pup/node_modules/scriptjs/dist/script.js:11:3)
W20180710-18:37:06.609(2)? (STDERR)     at Module._compile (module.js:652:30)
W20180710-18:37:06.609(2)? (STDERR)     at Object.Module._extensions..js (module.js:663:10)
W20180710-18:37:06.609(2)? (STDERR)     at Module.load (module.js:565:32)
W20180710-18:37:06.609(2)? (STDERR)     at tryModuleLoad (module.js:505:12)
W20180710-18:37:06.609(2)? (STDERR)     at Function.Module._load (module.js:497:3)
W20180710-18:37:06.609(2)? (STDERR)     at Module.require (module.js:596:17)
W20180710-18:37:06.610(2)? (STDERR)     at require (internal/module.js:11:18)
W20180710-18:37:06.610(2)? (STDERR)     at Object.<anonymous> (/Users/sabativi/playground/pup/node_modules/react-instantsearch-dom-maps/dist/cjs/GoogleMapsLoader.js:15:17)
```

I am using meteor, but I am pretty certain this is not related.

Maybe this is due to being in an SSR environment ?

**Comment by Haroenv** [comment]
Yes, this seems to be related to Meteor / SSR, could you make a project we can clone and check out where the issue is? See also the dedicated [SSR guide](https://community.algolia.com/react-instantsearch/guide/Server-side_rendering.html). 

Thanks

**Comment by samouss** [comment]
It's related to the Node environment. We use use external library to load external scripts (for Google Maps) but this library only work in a browser environment. We should be able to run the components in a non browser environment. This is definitely an issue, thanks for spotting this!
