### ISSUE TITLE
Failed prop type: Invalid prop `root.Root` warning

### ISSUE THREAD

**Issue by mxmzb** [algolia/react-instantsearch#1446]
**example code causing the issue:**

(taken from https://community.algolia.com/react-instantsearch/Getting_started_React_native.html#add-the-%3Cinstantsearch%3E-component)
``` javascript
<InstantSearch appId="latency" apiKey="6be0576ff61c053d5f9a3225e2a90f76" indexName="ikea">
    <Text>Congrats 🎉! Your application is now connected to Algolia!</Text>
</InstantSearch>
```

**Bug: What is the current behavior?**

Warning is being thrown: 
```
Warning: Failed prop type: Invalid prop `root.Root` supplied to `CreateInstantSearch`.
    in CreateInstantSearch (at Search.js:21)
    ... further stack incoming
```

**Bug: What is the expected behavior?**

No warning I guess? However, the search still works, it's just a warning, not an error.

**Bug: Which versions?**

RN@0.56.0, babel@7.0.0-beta.52, react-instantsearch@5.2.2

**Comment by rossvz** [comment]
I noticed this when upgrading to RN@0.56

**Comment by Haroenv** [comment]
Hmm, that prop type seems to be correct, I wonder where that error is coming from. Thanks for reporting. This is indeed just a warning though, so can safely be ignored by you

**Comment by JonnyBurger** [comment]
`View` now uses `React.forwardRef`. That means it's type is an `object`.

Made a Pull Request which explains it: #1461.

Thanks for merging!

**Comment by Haroenv** [comment]
thanks @JonnyBurger, I missed some context there, your PR looks good ❤️

**Comment by samouss** [comment]
The next version will be released beginning of next week.
