### ISSUE TITLE
What is the url request to reset react instantsearch hits?

### ISSUE THREAD

**Issue by jackmatrix** [algolia/react-instantsearch#1454]
I am using react instantsearch and sometime i need to check if my index has new entries without to be required to remounting my component.

So i know that when my component is called the first time, `react-instantsearch` make an initial request to fetch the most pertinent hits :

```javascript
 export const Hits = connectInfiniteHits(({ hits, hasMore, refine,currentRefinement}) => {




return (


  <View>//put my Hits here//</View>

);
});
```

So in my case i need to re-fetch hits sometimes but when i call a new instance of `<Hits />`  i get the same result even if my index has new entries. I always need to manually reset my component to see the changes.

I may have need a simple url to fetch and update my hits, for ex : `axios.get('/getLastHits'....`

Any idea ?

**Comment by Haroenv** [comment]
Answered in https://github.com/algolia/algoliasearch-client-javascript/issues/715#issuecomment-406903374, basically should be explained in https://community.algolia.com/react-instantsearch/guide/Refreshing_cache.html, please comment here if anything else is unclear so we can reopen if necessary

**Comment by jackmatrix** [comment]
I've already tried the `refresh` attribute but my problem is still unresolved because i need the hits list to be refreshed without typing anything but i just want to programmatically refresh it for exemple triggered by a custo event in my app.

**Comment by samouss** [comment]
@jackmatrix indeed the solution provided by @Haroenv seems to solve your issue. You can take a look at [the story](https://community.algolia.com/react-instantsearch/storybook/?selectedKind=RefreshCache&selectedStory=with%20a%20refresh%20button&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs) that he provide. We use the `refresh` property to trigger a new request (all the previous cached request are pruned). Does it solve solve your use case?

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a month. Feel free to open a new one!
