### ISSUE TITLE
Task orphaned for request nsmutableurlrequest

### ISSUE THREAD

**Issue by wzup** [algolia/react-instantsearch#1531]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**Bug: What is the current behavior?**

No pictures. Warning is thrown

**Bug: What is the expected behavior?**

No warnings. Picture is returned.

**Bug: What browsers are impacted? Which versions?**

React native. ios env

**Feature: What is your use case for such a feature?**

This is all your example https://community.algolia.com/react-instantsearch/Getting_started_React_native.html#highlight-your-results

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

Read all from here https://community.algolia.com/react-instantsearch/Getting_started_React_native.html#highlight-your-results

**What is the version you are using? Always use the latest one before opening a bug issue.**

**Comment by samouss** [comment]
Hi, could you provide us a bit more informations about your environment? How did you create the React Native application? With Expo? From scratch? Which version of React Native is used? The best would be to provide us a working example of the issue. It will help a lot to better understand the issue. Thanks!

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
