### ISSUE TITLE
Move to webpack 3

### ISSUE THREAD

**Issue by vvo** [algolia/react-instantsearch#154]
Now that webpack 3 [is out](medium.com/webpack/webpack-3-official-release-15fd2dd8f07b), we should use it, use the new features of it. Along with maybe the autodll plugin. @iam4x has a good experience on this so maybe he could help.

The goal is not to be left behind in term of build tools.

**Comment by rayrutjes** [comment]
For the read: https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

**Comment by vvo** [comment]
Taking this one
