### ISSUE TITLE
How do I select an item after a do lookup and close modal and pass selected item back to main screen?

### ISSUE THREAD

**Issue by wzup** [algolia/react-instantsearch#1542]
**Do you want to request a *feature* or report a *bug*?**

Gaps in your documentation.

Your docs do not explain the most important thing in all that search thing. 
This is **_how I select a item, close modal and get selected item back in my main screen_**.

**Bug: What is the current behavior?**

* I have main screen with a "Search" button.

* I click "Search" button. It opens modal.

* In modal I have your <[SearchBox](https://community.algolia.com/react-instantsearch/Getting_started_React_native.html#add-a-searchbox)> and <[connectInfiniteHits](https://community.algolia.com/react-instantsearch/Getting_started_React_native.html#display-infinite-results)> components.

* Now I click an item from InfiniteHits. And.... what?

HOW can I select that item?
HOW can I close modal?
HOW do I pass selected item from closed modal to main screen?

Where is your docs about this?

**Bug: What is the expected behavior?**

I can select an item from `connectInfiniteHits` list by pressing it, close modal and send selected item back to main screen.

**Bug: What browsers are impacted? Which versions?**

```
  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1
  npmPackages:
    apollo-boost: ^0.1.4 => 0.1.10 
    apollo-cache-inmemory: ^1.1.0 => 1.2.5 
    apollo-client: ^2.0.3 => 2.3.5 
    apollo-link: ^1.0.3 => 1.2.2 
    apollo-link-http: ^1.2.0 => 1.5.4 
    react-apollo: ^2.1.1 => 2.1.9
```

**Feature: What is your use case for such a feature?**

See above in **Bug: What is the current behavior?**

**Comment by Haroenv** [comment]
That depends on which modal you are using, but generally it will have either a method on the ref to close it programmatically, or a prop that says open or closed. 

Here's an example: https://codesandbox.io/s/yq2lyo46xx
