### ISSUE TITLE
Where is _ref variable in real-life code?

### ISSUE THREAD

**Issue by wzup** [algolia/react-instantsearch#1543]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

There is `_ref` variable in Devtools but it doesn't exists in real-life code. See screenshot below.
This `_ref` has many values. How to access them?

![screen shot 2018-08-30 at 1 30 29 pm](https://user-images.githubusercontent.com/3880497/44846480-1c337000-ac59-11e8-8a8f-a9342a27b794.png)

**Bug: What is the expected behavior?**

To have `_ref` in real life code.

```javascript
const Hits = connectInfiniteHits(({ hits, hasMore, refine }) => {
  
  let props;
  
  try {
    console.log('[_ref]', _ref);
    props = _ref; // ERROR. _ref is not defined!
    console.log('[props.searchState]', props.searchState);
  } catch (e) {
    console.log('[e]', e);
  }
```

Error
```
[e] ReferenceError: _ref is not defined
    at index.js:14
    at mountIndeterminateComponent (ReactNativeRenderer-dev.js:8905)
    at beginWork (ReactNativeRenderer-dev.js:9367)
    at performUnitOfWork (ReactNativeRenderer-dev.js:11771)
    at workLoop (ReactNativeRenderer-dev.js:11839)
    at Object.invokeGuardedCallback (ReactNativeRenderer-dev.js:39)
    at invokeGuardedCallback (ReactNativeRenderer-dev.js:221)
    at renderRoot (ReactNativeRenderer-dev.js:11925)
    at performWorkOnRoot (ReactNativeRenderer-dev.js:12742)
    at performWork (ReactNativeRenderer-dev.js:12660)
```

**Bug: What browsers are impacted? Which versions?**

```
  System:
    OS: macOS High Sierra 10.13.4
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1
  npmPackages:
    apollo-boost: ^0.1.4 => 0.1.10 
    apollo-cache-inmemory: ^1.1.0 => 1.2.5 
    apollo-client: ^2.0.3 => 2.3.5 
    apollo-link: ^1.0.3 => 1.2.2 
    apollo-link-http: ^1.2.0 => 1.5.4 
    react-apollo: ^2.1.1 => 2.1.9
```

**Comment by Haroenv** [comment]
_ref is created by Babel and has the current scope you destructure from IIRC. If you want to see the details, you should look at the source code (your own) being compiled by babel. 

Everything there you should be able to destructure in the props of the component you are enhancing. 

Does that make sense? 

Please feel free to continue commenting here, and we can reopen if an issue is found

**Comment by Haroenv** [comment]
see https://babeljs.io/repl#?babili=false&browsers=last%202%20versions&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBBIFsCmAxMMC8MAUBvCANDACYC-AlJgHwy4BQMMoksAlmGEgE5pZ4BGBADYVqtBjFJ1SQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=true&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015&prettier=true&targets=&version=6.26.0&envVersion=1.6.2 for more info
