### ISSUE TITLE
React Installation, nothing happens and no error

### ISSUE THREAD

**Issue by nickjuntilla** [algolia/react-instantsearch#1563]
Installed with `npm install react-instantsearch --save`

**Bug: What is the current behavior?**

Doing this procedure: https://community.algolia.com/react-instantsearch/guide/%3CInstantSearch%3E.html

Replaced the values with the values for my project.

**Bug: What is the expected behavior?**

Nothing loads on the page and there is no error.

**Bug: What browsers are impacted? Which versions?**

Chrome on local development

React ^16.0.0

**Comment by francoischalifour** [comment]
Did you install `react-instantsearch-dom`?

This is the new way to use React InstantSearch. You can read more about it in the [migration guide on imports](https://community.algolia.com/react-instantsearch/guide/Migration_guide_package_import.html#migration-for-react-dom).

**Comment by samouss** [comment]
Hi @nickjuntilla did you solve your issue?

**Comment by mthuret** [comment]
@samouss this page https://community.algolia.com/react-instantsearch/guide/Install.html might be outdated?

**Comment by samouss** [comment]
Yep I will update it.
