### ISSUE TITLE
Render errors swallowed with React 15

### ISSUE THREAD

**Issue by simpletrontdip** [algolia/react-instantsearch#1581]
# Background
- Recently, I have taken hours to debug a strange React/DOM related bug on our site(which is using Algolia API) and figured out what wrong with my code.
- The problem was from a function(which was not well coded) inside a `connectHits` component. It failed to handle some kind of input data and makes `render` failed.
- But the thing is, I can't get any exception from the console, output or anywhere and it just fails silently and makes the problem hard to detect. (Actually, I have to look at searchResult.error to find it)
- So I think, we may need to know and which exception is from search operation and which is from the client side itself. And I end up with this proposal

# Proposal
- In the `store`, we may handle the exception and throw it directly in `dispatch` function. This avoids exceptions getting swallowed as a search error (which may be a Network error, API error, permission error...). By change

```js
function dispatch() {
    listeners.forEach(listener => listener());
  }
```

To this

```js
function dispatch() {
  listeners.forEach(listener => {
    try {
      return listener()
    } catch (error) {
      setTimeout(() => {
        throw error
      })
    }
  })
}
```
- This may isolate `listener()` exceptions and throw them directly let people handle problem themselves which helps detecting the problem earlier, sooner

- I don't really understand all the impact or consequence of this change, but if it's OK I'm happy to open a PR

**Comment by samouss** [comment]
I tried to reproduce a similar use case but the error is always catch by React, I probably miss something in my reproduction. I willingly access a non existing property on an object to let the application throw. The error always bubble in the console. Here is [the example](https://codesandbox.io/s/911ln101mw). Could you provide us a reproducible use case? It will help to better understand the issue. We provide template to avoid you the boilerplate part. It's available on [CodeSandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch).

**Comment by simpletrontdip** [comment]
Thankyou for your time!
I have updated your example and reproduce it [here](https://codesandbox.io/s/8808v98n99).
Sorry for not mention that we are using React-15 and our code base cannot be updated to React-16 easily.
The main thing is React-15, in this version the component does not have the `ErrorBoundary` so the exception will not be captured. And thing get failed silently.

**Comment by samouss** [comment]
Thanks for the example and the information about the version. The error is catch inside a promise that is created by one of our internal library ([Algolia JS Helper](https://github.com/algolia/algoliasearch-helper-js)). React 16+ does throw the error though. With the solution proposed the error will indeed be thrown on React 15. But React 16+ user will have the error thrown two times. A possible solution for React 15 is to implement an `Error` component with the `connectStateResults` to rethrow the error since we have access to it in the connector. Here is [an example](https://codesandbox.io/s/88p7kyrwwj).

**Comment by simpletrontdip** [comment]
Thank you! I think the `connectStateResults` may help
