### ISSUE TITLE
SSR: Client Side Routing gives error. 

### ISSUE THREAD

**Issue by harshmaur** [algolia/react-instantsearch#159]
Hello,

I was successfully able to remove all <NoSSR /> Tags and integrated it with react-instantsearch ssr feature. 

However in next.js which also supports client side rendering on click of <Link /> tag, I am getting this error. 

Here is the screenshot of the example. https://cl.ly/1j3l002F1V19

All I did was create another file with the same code as index.js and used <Link /> tag to route the pages on client side. https://cl.ly/3o0v3y1E2k1c

@mthuret

**Comment by mthuret** [comment]
Are you using beta0 or beta1?

I published a beta1 this morning containing a fix to remove those kind of warnings. Maybe it's related.

**Comment by harshmaur** [comment]
Hmm right!! The errors are gone now! Thanks!
