### ISSUE TITLE
Upgrade all deps and use singapore/renovate

### ISSUE THREAD

**Issue by vvo** [algolia/react-instantsearch#162]
It seems that https://github.com/singapore/renovate would be a good overall solution to our struggle about being uptodate in term of dependencies on the project as a whole. We tried greenkeeper without luck in the past. Renovate can update dependencies on multiple lock files projects.

Let's upgrade all our deps first then put renovate in our repository, there's an easy to use app and the author seems very keen to help us using it.

**Comment by vvo** [comment]
taking this one

**Comment by vvo** [comment]
Now need to install renovate, @mthuret I'll leave this one for you.

**Comment by mthuret** [comment]
Renovate is up :)
