### ISSUE TITLE
How to use the connectPagination in React-Native ?

### ISSUE THREAD

**Issue by knightkiddo** [algolia/react-instantsearch#1652]
Hello,

I could use the connectCurrentRefinements correctly because I found a working example but I can't figure how to use the connectPagination in React Native. I searched everywhere but I couldn't find something useful...

I can import it like the CurrentRefinements
`import { connectCurrentRefinements, connectPagination } from "react-instantsearch/connectors";`

I can use it like this :
`const ConnectedPagination = connectPagination(Pagination);`

But then I don't know what to do. How are we suppose to create a component to use the props available ? (https://community.algolia.com/react-instantsearch/widgets/Pagination.html)

I'm confused and new to this. Any help, advice ?

Thank you

**Comment by Haroenv** [comment]
```js
// Pagination.js
import { connectPagination } from 'react-instantsearch/connectors';

const range = (start, end) =>
  Array.from({ length: end - start + 1 }, (_, i) => start + i);

const Pagination = ({ padding = 3, refine, currentRefinement, nbPages }) => (
  <div>
    {range(
      Math.max(1, currentRefinement - padding),
      Math.min(nbPages, currentRefinement + padding)
    ).map(page => (
      <button
        key={page}
        onClick={() => refine(page)}
        style={{
          color: currentRefinement === page ? 'red' : 'unset',
        }}
      >
        {page}
      </button>
    ))}
  </div>
);

const ConnectedPagination = connectPagination(Pagination);

export default ConnectedPagination;

// usage:

import Pagination from './Pagination';

const App = () => (
  <InstantSearch>
    {/* other things */}
    <Pagination padding={2} />
  </InstantSearch>
);
```

Does this help you?

**Comment by Haroenv** [comment]
That's an example using react (DOM), but the same idea goes up for React Native. 

[![Edit react-instantsearch-app](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q8loowqn7w?module=%2Fsrc%2FApp.js)
