### ISSUE TITLE
Configure widget documentation is lacking props

### ISSUE THREAD

**Issue by JakeSidSmith** [algolia/react-instantsearch#1653]
**Do you want to request a *feature* or report a *bug*?**

Documentation update / bug

**Bug: What is the current behavior?**

The [documentation](https://community.algolia.com/react-instantsearch/widgets/Configure.html) states:

> This widget has no props.

And then immediately shows this example

```js
<Configure hitsPerPage={5} />
```

**Bug: What is the expected behavior?**

Should document all available props

**Comment by Haroenv** [comment]
Oops, that's because this documentation is automatically generated. The accepted parameters are:

https://www.algolia.com/doc/api-reference/search-api-parameters/

**Comment by samouss** [comment]
We now have [the full list of accepted props](https://www.algolia.com/doc/api-reference/widgets/configure/react/) inside the new documentation.
