### ISSUE TITLE
How to search multiple indices in one query?

### ISSUE THREAD

**Issue by husbas** [algolia/react-instantsearch#1654]
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**

**Bug: What is the expected behavior?**

**Bug: What browsers are impacted? Which versions?**

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

**What is the version you are using? Always use the latest one before opening a bug issue.**

**Comment by Haroenv** [comment]
```js
import React from 'react';
import algoliasearch from 'algoliasearch/lite';
import { InstantSearch, Hits, SearchBox, Index } from 'react-instantsearch-dom';

const searchClient = algoliasearch('latency', '6be0576ff61c053d5f9a3225e2a90f76');

const App = () => (
  <InstantSearch
    searchClient={searchClient}
    indexName="airbnb"
  >
    <SearchBox />
    <p>Results in first dataset</p>
    <Hits />
    <Index indexName="instant_search">
      <p>Results in second dataset</p>
      <Hits />
    </Index>
  </InstantSearch>
);

export default App;
```
