### ISSUE TITLE
onSearchStateChange is never called after refreshing the cache on react-native app

### ISSUE THREAD

**Issue by tstehle** [algolia/react-instantsearch#1659]
**Bug: What is the current behavior?**
In order to let a user manually refresh a list, I implemented the code provided here
https://community.algolia.com/react-instantsearch/guide/Refreshing_cache.html
on my react-native app, but the onSearchStateChange callback is never called.
This prevents me from showing and hiding a loader while the cache is being refreshed.
I also had to use a timeout to set the state value 'refresh' to false every time there is a refresh in order to 'rearm' it (this normally happens in the onSearchStateChange).

**Bug: What is the expected behavior?**
onSearchStateChange is called after the cache has been refreshed

**What is the version you are using? Always use the latest one before opening a bug issue.**
react-instantsearch 5.3.1
react-native 0.57.2
react 16.5.2

**Comment by samouss** [comment]
Hi, indeed we do a patch on this documentation recently (see https://github.com/algolia/react-instantsearch/pull/1647). But the doc hasn't been published yet. The `onSearchStateChange` is **not** called once we clear the cache. You should use the `setState` callback to turn it back to `false`. Here is [the updated documentation](https://github.com/algolia/react-instantsearch/blob/master/docgen/src/guide/Refreshing_cache.md).

**Comment by tstehle** [comment]
Thanks, it works !
