### ISSUE TITLE
DefinitelyTyped definitions

### ISSUE THREAD

**Issue by gburgett** [algolia/react-instantsearch#1676]
Hello,

We've been using react-instantsearch in our project and developed a few Typescript type definitions for the stuff that we're using.  I could use some assistance in finishing them out to the satisfaction of the DefinitelyTyped maintainers.  If y'all are not interested, we'll just keep using these typedefs internally.

Check out the PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29793

Thanks!

**Comment by Haroenv** [comment]
We are very grateful and following that PR you made. We'll take a look to fix the things mentioned by the DTS maintainers likely during next week. 🙌

**Comment by gburgett** [comment]
Great!  Thank you :)

**Comment by samouss** [comment]
I'm closing this issue since we have an other one on the subject #577.
