### ISSUE TITLE
Errors persist forever

### ISSUE THREAD

**Issue by alexandremeunier** [algolia/react-instantsearch#169]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

When performing two requests, if the API responds to the first one with an error, but the second one does not error, the error state is persisted in the connector. 

[![Edit r0EryLBWB](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r0EryLBWB)

**Bug: What is the expected behavior?**

The second request clears the error state

**What is the version you are using? Always use the latest one before opening a bug issue.**

3 / 4

Thanks ❤️

**Comment by mthuret** [comment]
The `error` is not reset to `null` when a new request is performed (`createInstantSearchManager`)

**Comment by mthuret** [comment]
@alexandremeunier  Should be fix with 4.0.9 (and soon on 4.1.0-beta)

<a href="https://codesandbox.io/s/PNmY1MxR6">
  <img alt="Edit PNmY1MxR6" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

**Comment by alexandremeunier** [comment]
Super awesome @mthuret thanks! 🙌 💯
