### ISSUE TITLE
React Router example is no longer working

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#171]
see: https://codesandbox.io/embed/github/algolia/react-instantsearch/tree/master/packages/react-instantsearch/examples/react-router

This example demonstrate react-router v3. Deps was upgraded to 4.1.2. 

cc @vvo

**Comment by vvo** [comment]
Do you think we could now ditch the v3 example? V4 has been out for quite some time now

**Comment by mthuret** [comment]
Considering react-router is known to completely change their API each time and that I don't know if indeed everyone is willing to migrate I'd rather keep it here. Can be renamed though, to make it explicit that it's v3.

**Comment by Haroenv** [comment]
I would also do that, have the current `latest` be `react-router` and others that are still there `react-router-vX`
