### ISSUE TITLE
Docs: Header behaviour not consistent with other websites

### ISSUE THREAD

**Issue by pixelastic** [algolia/react-instantsearch#172]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**

The current documentation website indicates that I should "Click to go to community, hover to access latest community projects" on the "Community part". But hovering does nothing, and clicking will open the latest community projects.

cc @JonasBa

**Bug: What is the expected behavior?**
Hovering should bring the projects, clicking should bring to the main website

**Comment by Haroenv** [comment]
Yep, I think this has been covered in #112 #40

We should definitely move soon

**Comment by mthuret** [comment]
I asked @JonasBa, He will handle all issues regarding the header.
