### ISSUE TITLE
href links in NextJS not coming

### ISSUE THREAD

**Issue by harshmaur** [algolia/react-instantsearch#177]
Hello, 

I wanted to know why href links as just `#` in the next js example in pagination widget, while it works in the eCommerce demo. 

In order for google to crawl the next pages, its necessary to have the href links inside the <a> tags

**Comment by mthuret** [comment]
Hi @harshmaur,

Can you confirm that this occurs only when entering the page without any refinements made? 

I suspect a wrong usage of the Router. I'll check it out, thanks!

**Comment by harshmaur** [comment]
I am not sure If I understand you correctly. It happens to me on every case. with or without refinements.

**Comment by mthuret** [comment]
Fix with 4.1.0.beta3
