### ISSUE TITLE
Docs: connectStateResults not from 'react-instantsearch-dom'

### ISSUE THREAD

**Issue by nickbae91** [algolia/react-instantsearch#1770]
Hi,

I wanted to report an error(?) in your docs, where it describes the **connectStateResults** to be from 'react-instantsearch/dom':

`import { InstantSearch, SearchBox, Hits, connectStateResults } from 'react-instantsearch-dom';`

I tried importing the connector using the above and it didn't work (was getting an "Object(...) is not a function" error), so I tried importing from 'react-instantsearch/connectors' and it worked just fine:

`import { connectStateResults } from 'react-instantsearch/connectors';`

**Documentation of interest:**
https://community.algolia.com/react-instantsearch/connectors/connectStateResults.html

**Comment by samouss** [comment]
The above should work, which version of the library are you using? We recently update the shape of the package. You have more information about that inside [the documentation](https://community.algolia.com/react-instantsearch/guide/Migration_guide_package_import.html). Here is [an example](https://codesandbox.io/s/8zpz3nzm28) that import the connector from the `react-instantsearch-dom` package.

**Comment by samouss** [comment]
Like I said the import should work from `react-instantsearch-dom`. In case the issue persist please open a new issue with a live example, it will help us to better understand where the problem come from. Thanks!
