### ISSUE TITLE
Bug SSR findResultsState searchState is not accounted for 

### ISSUE THREAD

**Issue by andrewl913** [algolia/react-instantsearch#1786]
**Bug: What is the current behavior?**

When using ssr a call to  `  await findResultsState(Component, {searchState} )`
searchState is not evaluated

**Bug: What is the expected behavior?**

searchState should be evaluated

**Bug: What browsers are impacted? Which versions?**

all

**Feature: What is your use case for such a feature?**
     SSR in a nextjs application using a menu facet 

**What is the version you are using? Always use the latest one before opening a bug issue.**
5.3.2

digging into the source code, there looks to be like an array for` searchParams `that will always be empty
see below

https://github.com/algolia/react-instantsearch/commit/e765886c1481eb39c0e284510fc505a46c251b15#diff-4dba8db67e9bc4d143017557874ea685L42

in here on line 41 on `packages/react-instantsearch/src/core/createInstantSearchServer.js, `

the `searchParameters` array has been moved  to the top of the function
on `line 43 `of the same file it is filtered against but it looks like it will always be empty

**Comment by samouss** [comment]
I didn't manage to reproduce the issue with [the Next example](https://github.com/algolia/react-instantsearch/tree/master/examples/next) that we have on the project. You can play with the UI once the URL is sync your can reload the page. The page should be in the exact same state, it means that the `searchState` is correctly provided to the function. Could you provide us an example of the issue? It will help to better understand the problem. Thanks!

**Comment by andrewl913** [comment]
Thank you for the quick response! 

I took a deeper look into the issue, it seems to be a problem with using the Reacts 16.3 context api. 

If the algolia search component wraps around the context provider and the context consumer uses the instant search components this then causes server render searchState to be evaluated before the context consumer renders.

 I noticed the example demo is still using next 6 and react 16.2, I can make a pr to update this to the latest :).

**Comment by andrewl913** [comment]
Awesome!, I found some time to fork and cut a feature branch here. https://github.com/andrewl913/react-instantsearch/tree/feature/reproduce-context-issue. The RefinementList component inside the consumer seems to be the cause.

**Comment by samouss** [comment]
Thanks a lot for the reproduction it helps a lot! I find out that the issue was not related to the Context API or even React InstantSearch. It's the usage of the SSR that is not correct. I've create a PR on your fork that should fix the issues. I added some explanations on the PR, don't hesitate to ask any questions on the PR thread.

**Comment by samouss** [comment]
The PR opened on the project should have fix the issue. If it's not the case feel free to open a new on on the project.
