### ISSUE TITLE
Cannot Add a child that doesn't have a YogaNode to a parent with out a measure function

### ISSUE THREAD

**Issue by champcmr** [algolia/react-instantsearch#1792]
> I having following **issue on only android** when I used filters( i.e from connectRefinementList) on modal and applied those filter results in search result page (i.e in connectInfiniteHits)

> I followed the steps (especially step#7) from given here [https://community.algolia.com/react-instantsearch/Getting_started_React_native.html](url)

![1544243998847](https://user-images.githubusercontent.com/27066281/49682163-33de8800-fad5-11e8-9273-3e2e8622545c.jpg)

> I also followed this issue's variety of solution provided here [https://github.com/facebook/react-native/issues/13243](url), but it not works for me. Please let me know if any one have idea about this type of error.

**Comment by Haroenv** [comment]
Would it be possible to make a minimal reproduction for this issue?

**Comment by champcmr** [comment]
@Haroenv there was an issue in my code which I fixed it. Thanks :)
