### ISSUE TITLE
Invalid value for "maxFacetHits" parameter, expected integer between 1 and 100

### ISSUE THREAD

**Issue by catamphetamine** [algolia/react-instantsearch#1910]
Today our search widget stopped working when filtering inside "multi-select lists" by "facet values": when typing something in the "Filter facet values" text input.

The error is:

> {"message":"Invalid value for "maxFacetHits" parameter, expected integer between 1 and 100","status":400}

We're using version 4.x of the widget.

I can see you added `maxFacetHits` in version 5.x.
Version 4.x doesn't seem to have any `maxFacetHits` parameter setting.
In DevTool's Network tab I can see it sends `maxFacetHits: 1000`.

Also, seems that you don't keep a dedicated brach for version 4.x which means that you've officially dropped support for verison 4.x once you released 5.x.
Is that so?
Will there be a fix released for version 4.x for the `maxFacetHits` error?

**Comment by samouss** [comment]
Yes indeed it’s fixed in the version 5. We don’t support the older versions anymore. The change won’t be backported to the version 4. The solution for older versions would be to use the connector and patch the values sent to `searchForFacetValues`.
