### ISSUE TITLE
Searchbox placeholder text doesn't change

### ISSUE THREAD

**Issue by biletron** [algolia/react-instantsearch#2017]
https://codesandbox.io/s/jzz66xrok9

**Comment by Haroenv** [comment]
Placeholder text is configured via translations:

```jsx
<SearchBox
  className="searchbox"
  translations={{ placeholder: 'Sample text' }}
/>
```

https://codesandbox.io/s/4xqxx3mp1x

**Comment by biletron** [comment]
Thanks for the reply. Would be nice if you also could update the sample sandbox code in the description.

**Comment by Haroenv** [comment]
Which sample code are you talking about? Would definitely change that!

**Comment by biletron** [comment]
https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch

Playground code in Readme section.

**Comment by Haroenv** [comment]
Yes, I updated it here: https://github.com/algolia/create-instantsearch-app/pull/361
