### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined

### ISSUE THREAD

**Issue by liumin1128** [algolia/react-instantsearch#2031]
![image](https://user-images.githubusercontent.com/12379461/52837843-6f2bb180-312b-11e9-882a-b1b882dc9362.png)

**Comment by liumin1128** [comment]
![image](https://user-images.githubusercontent.com/12379461/52838214-dc8c1200-312c-11e9-8db9-c37dcc02c288.png)

**Comment by liumin1128** [comment]
![image](https://user-images.githubusercontent.com/12379461/52838259-f9c0e080-312c-11e9-9ff5-8d04404aa1b5.png)

**Comment by samouss** [comment]
I didn't manage to reproduce the issue. Could you provide a working example of your issue? It will help a lot to better understand the problem. You can create one from the [React template](https://codesandbox.io/s/new) on CodeSandbox.

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
