### ISSUE TITLE
currentRefinements connector does not provide query

### ISSUE THREAD

**Issue by gzzo** [algolia/react-instantsearch#2033]
The [documentation](https://community.algolia.com/react-instantsearch/connectors/connectCurrentRefinements.html) stats that currentRefinements provides 
 a `query` prop. 

currentRefinements [does not](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/connectors/connectCurrentRefinements.js#L52) provide that prop.

`query` is not listed in the `items` prop either.

**Comment by Haroenv** [comment]
You need to add `clearsQuery={true}` to the props for it to show up.

**Comment by gzzo** [comment]
@Haroenv that added two copies of the query refinement to the `items` prop.  It still doesn't pass a `query` prop.

**Comment by samouss** [comment]
This documentation website is not up to date anymore. The new documentation website is available on [algolia.com/doc](https://www.algolia.com/doc/api-reference/widgets/current-refinements/react/?language=react#connector). Indeed there is no `query` prop provided by the connector. The `query` is part of the provided `items`.
