### ISSUE TITLE
Recipe: building an autocomplete manually

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#21]
We released in beta the new `<Index>` widget that allows people to simply do multi index requests. We want to advertise this feature in order to build fully featured autocomplete.

We already have a recipe to show how to use an external autocomplete but we miss an example showing how you can achieve the same thing using only React InstantSearch. 

# Goal 

Building an autocomplete menu that allows navigation with keyboard.

**Comment by khrome83** [comment]
@mthuret i am looking for this functionality. Reading the API and the examples, it is very unclear to me how to make this work. 

We are trying to implement this right now. Can you offer and advice short of building out the example? The one using the "react-autocomplete" seems to throw errors when I change the data set and does not allow keyboard. The mention example has keyboard support, but is targeting a text area. 

I am about to start hacking on this. Thanks.

**Comment by mthuret** [comment]
Hi @khrome83,

You currently you have two options for this:

1. You can use an external autocomplete React component and use our `connectAutoComplete` connector to achieve what you want. 

You'll get access to the `hits`, the `query` and the `refine` function that will allow you to update the query. Check this documentation: https://community.algolia.com/react-instantsearch/connectors/connectAutoComplete.html

You can find an example using `react-autosuggest` library here: https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/examples/autocomplete/src/App-Multi-Index.js

The advantage of this is that you have all the feature coming with the react autocomplete component you'll choose like keyboard support.  

2. Directly use the Multi Index API 

It means that you will need to handle yourself the display of the content depending if something is typed on the search box. To build that you can use widgets such as `<SearchBox/>`, `<Hits/>` and `<Index/>`. You'll need to handle yourself the keyboard navigation. 

Also can you be more specific about this "The one using the "react-autocomplete" seems to throw errors when I change the data set and does not allow keyboard"? What is not working and where can I see it?

**Comment by khrome83** [comment]
@mthuret - ok that makes sense. 

I found out that when I removed out index's, I had things blow up. But it was because the "multiSelection={true}". This attribute was referring to multiple indexes instead of selecting multiple items in the list apparently. Just made it confusing to work with.

Trying to determine how to add keyboard support now. Thank you!

**Comment by mthuret** [comment]
It you're using [`react-autosuggest`](https://github.com/moroshko/react-autosuggest) the keyboard should be already working. 

See here: https://community.algolia.com/react-instantsearch/storybook/?selectedKind=<Index>

**Comment by khrome83** [comment]
The example you shared does not appear to use the `react-autosuggest`. In the example I downloaded from the AutoComplete option for multiple Index, the keyboard does not show it working at all. Maybe it was but there was no feedback?

**Comment by mthuret** [comment]
I'm not sure of what example you're talking about, maybe you can send me the link :)

This one that I linked earlier does support keyboard: https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/examples/autocomplete/src/App-Multi-Index.js (base on react-autosuggest)

**Comment by khrome83** [comment]
yeah, when I installed the locally, it did not show any keyboard support. I don't know why. I set up the same example in a codepen and I have it working. I am honestly not sure what is going on. Like I said, it may just be that I am missing the feedback (highlight on down arrow of selected item).

I switched my example to use the CSS from the react-autocomplete code pen. I am trying to add highlighting but am running into issues. 

https://codepen.io/WebGrindIO/pen/5fdd5c6ffdf5d9f54cc3fb047739972f

Here is a example of that. Do you know if the connectHits and hightlight will work with the `react-autocomplete`. Including `<CustomHits />` and shown in the `<Hightlight>` page from the API docs breaks the `Autosuggest` and hits is always zero.

**Comment by mthuret** [comment]
You're mixing concept here. You don't need the connectHits if you use the connectAutoComplete because you already get the `hits` from the `connectAutoComplete` connector. 

Then you can totally use the `<Highlight>` widget inside the hit template. 

Here's an example for a single hit autocomplete:

https://codepen.io/mthuret/pen/VWbgxZ?editors=1111

**Comment by khrome83** [comment]
Ok that makes sense. Thank you for that!

**Comment by samouss** [comment]
We now have [a dedicated section](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/autocomplete/react/) about that in the new documentation.
