### ISSUE TITLE
[bug] syntax errors in react-instantsearch-theme-algolia css

### ISSUE THREAD

**Issue by roma98** [algolia/react-instantsearch#213]
Hello,
I have realised that the instantsearch css contains a few errors, if you search for `"" 2` in the file (both version `3.0.0` and `4.0.0`), you'll find 3 references for `content: "" 2; }`
I found out after having a character "2" displaying randomly in my page.
For performance reasons, I also have inlined the code in `index.html`, also revealing another error on line `@supports (src:local("")) and (not (background-blend-mode:luminosity)) {` giving
`Function 'local()' is allowed only in following rules: @font-face`

those errors are seen on:
https://unpkg.com/react-instantsearch-theme-algolia@4.0.0/style.css
https://unpkg.com/react-instantsearch-theme-algolia@3.0.0/style.css
https://unpkg.com/react-instantsearch-theme-algolia@3.0.0/style.min.css
https://unpkg.com/react-instantsearch-theme-algolia@4.0.0/style.min.css

**Comment by mthuret** [comment]
Thanks for reporting this @roma98. We'll have a look shortly :)

**Comment by vvo** [comment]
> @supports (src:local("")) and (not (background-blend-mode:luminosity)) { giving
> Function 'local()' is allowed only in following rules: @font-face

@LukyVj Can you help here? See code: https://github.com/algolia/react-instantsearch/blob/c1e751a973f5c54684efa2da96418ae52de93cdc/packages/react-instantsearch-theme-algolia/styles/_Toggle.scss#L33-L35

**Comment by vvo** [comment]
Solved the first issue, as for the second one I would go for removing the rule since it seems only valuable within font-face but @LukyVj might know more.

**Comment by roma98** [comment]
Awesome guys thanks!

**Comment by vvo** [comment]
Wait it's not completely solved, we will need to fix the second one and do a release :)

**Comment by samouss** [comment]
I'll close this issue, since in the next version we drop the support for the theme. We are now rely on a new library called [InstantSearch.css](https://yarnpkg.com/en/package/instantsearch.css).

**Comment by Haroenv** [comment]
That second part was to detect an older version of Safari, not necessary now
