### ISSUE TITLE
Start testing React 16

### ISSUE THREAD

**Issue by vvo** [algolia/react-instantsearch#215]
It's out! https://github.com/facebook/react/issues/10294

There will be soon a way to activate async rendering too (No idea what that means).

The sooner we try it the better usually for this kind of dependency.

Last time for React 15 we did not do it while we discovered breaking changes in React 15 (once released). See https://github.com/algolia/react-element-to-jsx-string/issues/56#issuecomment-261113118

**Comment by Haroenv** [comment]
see #212 and #211

**Comment by mthuret** [comment]
I'm currently in the process to write tests for all our recipes. We'll merge those PR afterwards (only concerns react-native example). 

And yes, we should tried the beta on all the rest of the code.

**Comment by mthuret** [comment]
https://github.com/storybooks/storybook/issues/1868

**Comment by mthuret** [comment]
Step to get there: 

- [ ] Ensure that storybook is working with 16

- [ ] Fix our Enzyme test using the new adapter strategy

**Comment by boaticus** [comment]
As mentioned, defaultProps not being static on List is still throwing this warning:

`Setting defaultProps as an instance property on List is not supported and will be ignored. Instead, define defaultProps as a static property on List.`

**Comment by mthuret** [comment]
@boaticus I'm in the middle of cleaning and upgrading everything :)
