### ISSUE TITLE
Pass custom className to InstantSearch to allow customizing it

### ISSUE THREAD

**Issue by StanleySathler** [algolia/react-instantsearch#2165]
First of all, thank you for all this awesome effort, guys. We're loving to deal with Algolia and all its features.

**Is your feature request related to a problem? Please describe 🙏**

It is a bit frustrating that we can not wrap an `InstantSearch` into a Styled Component instance or even pass a custom class name to it.

**Describe the solution you'd like 🤔**

I'd like to be able to pass a custom class name to the `InstantSearch` component. So that, I can customize its style or even wrap it into a Styled Component using `styled-components` package.

**Describe alternatives you've considered ✨**

None, actually.

**Additional context**

In our case, we use Styled Components to deal with our project styling. Here, we have the following structure:

```js
const InstantSearchWrapper = styled(InstantSearch)`
  height: 100%;
`

/* ... more code here ... */

<SearchWrapper>
  <InstantSearchWrapper>
    <MySearchComponent />
  </InstantSearchWrapper>
</SearchWrapper>
```

But since `InstantSearch` component doesn't allow a custom `className` property, any style applied to the wrapper are not effectively applied to the component.

In case of Styled Components, the style is not affected because the `styled-components` package adds a class to the `InstantSearch` automatically.

More info about this problem can be found here:
https://www.styled-components.com/docs/advanced#styling-normal-react-components

**Comment by StanleySathler** [comment]
Guys, it seems that I can accomplish my goal by using `InstantSearch`'s `root` property.

```js
const InstantSearchWrapper = styled.div`
  height: 100%;
`

/* ... omitted code ... */

<InstantSearch root={{ Root: InstantSearchWrapper }} />
```

For future reference (for someone else facing the same issue), you can find [more info here.](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/?language=react#widget-param-root)

**Comment by samouss** [comment]
Yes it's definitely the way to go! Glad to see that you've solve your issue!
