### ISSUE TITLE
Multi-index with empty first search

### ISSUE THREAD

**Issue by 4l3nc** [algolia/react-instantsearch#2211]
We are trying to perfom a multi-index search from an empty scenario because we can't prevent search on init. To acomplish this we are not adding the two `<Index />` components until we have a valid query on the search box, you can take a look in this repo:

https://github.com/4l3nc/react-native-instant-search/blob/master/src/Home.js#L93

The problem is that when we add a query, the component is re-rendered with the two Indexes and the first thing that we receive is results for both indexes based on the index that initializes the `<InstantSearch />` component as you can see in the gif below (the red line separate each index). So for a second we see results coming from the index of the `<InstantSearch />` in both `<Index />` components and after that the real results for each Index. For the first index we have only 2 results, basketball and football that are repeated for a moment.

![Algolia-search](https://user-images.githubusercontent.com/31773239/54769970-9d0c8600-4c02-11e9-9f09-9de2946da37b.gif)

We would like to know if there is some way to accomplish the initial empty search with multiple indexes or if you know some workaround to avoid this behaviour.

if you need more details you can reproduce the behavior with my repository and expo.

1. Install and execute on Expo.
2. Go to search bar and write a 'm'.

**Environment:**

 - OS: [iOS]
 - react-instantsearch Version [5.4.0]

**Comment by tkrugg** [comment]
HI there, thanks for reaching out!
One workaround for this issue would be to add an extra check comparing your query to the currentRefinement. 
This would effectively wait for the results to be in sync.
This workaround has is been demonstrated here: https://github.com/algolia/react-instantsearch/issues/465#issuecomment-363403278
Let us know if this helps.

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
