### ISSUE TITLE
Make the connector docs more usable

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#222]
The terms "provided props" and "exposed props" are confusing, even after you've already used connectors. I propose that there's an example on every connector page that explains clearly in what spot each type is used. Here listed for clarity in case this issue gets indexed in Google before we get around it: 

--- 

## Exposed props

Once a component is connected, these props become available on the connected component, you can use them in the JSX you use when using this component

## Provided props

These are the props that you can use in your component that you will connect. These are typically things like `items`, to build your UI and `refine`, to be called when you click on a certain `item`.

---

An alternative to the example is adding this text (or similar) to those documentations

**Comment by samouss** [comment]
We now have code samples for every widget inside the documentation. Here is an example for the [`SearchBox`](https://www.algolia.com/doc/api-reference/widgets/searchbox/react/#connector).
