### ISSUE TITLE
How to configure the <NumericMenu /> ?

### ISSUE THREAD

**Issue by MaximeConan** [algolia/react-instantsearch#2231]
**Describe the bug 🐛**

Good morning, everyone,
I am currently trying to configure the <NumericMenu /> in my application, but without success.

This is my code:

```
<NumericMenu
        attribute="calorie"
        translations={{
          all: 'Tout',
        }}
        items={[
          { label: 'Tout' },
          { label: '- de 300 calories', end: 300 },
          { label: '0 à 600 calories', start: 301, end: 600 },
          { label: '+ 600 calories', start: 601 },
        ]}
      />
```
I have a "calorie" attribute in my record (number, not a string)). But when I look into my components with React devtools I have the following attributes in my props :+1: 

```
canRefine: false
isRefined: true
```
**Environment:**

 - OS:  windows / linux
 - Browser Chrome

**Comment by Haroenv** [comment]
Is the attribute set up as "attributesForFaceting" in your index? If that didn't solve the issue, can you please make a sandbox that shows the issue? We have a template: http://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
