### ISSUE TITLE
Calendar Widget

### ISSUE THREAD

**Issue by ArionHardison** [algolia/react-instantsearch#2242]
To build a calendar widget using react, should I use the rangeConnector and extend a widget or should I create my own.

**Comment by Haroenv** [comment]
You should use the range connector if your events only have a single time stamp date, which is the simplest case. 

We have an experimental two-attribute (start & end) version here: https://codesandbox.io/s/kwklo3rz63

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
