### ISSUE TITLE
Reset page selection on query change

### ISSUE THREAD

**Issue by eyn** [algolia/react-instantsearch#2315]
USING REACT-INSTANTSEARCH.JS

**Do you want to request a *feature* or report a *bug*?**
Feature [maybe bug :)]

**What is the current behavior?**
When searching if I go to page 2/3 then change the query in the searchbox it doesn't reset to page 1 so when you then have less than page x * number_of_items_per_page results you get a blank search result. I've had a few users confused by this. 

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**
&p query parameter gets changed to 0 when SearchBox changes

**Comment by chlec** [comment]
I'm having the same bug. @SavageWilliam did you manage to fix it?

**Comment by Haroenv** [comment]
Can you create a reproduction @chlec ? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by semanticart** [comment]
@Haroenv and @mthuret I'm bumping into the problem where changing filters doesn't reset the page number as well.

I've created a reproduction here: https://codesandbox.io/s/xenodochial-flower-geljq1?file=/src/App.js

You can get into this state in a number of ways, but here's one form:

1. Visit page 2 for the default results. You see page 2 of results as expected.
2. Note that the `searchState` now shows page two.
3. Pick a brand. You see page 2 of results even though the filter has changed.

Changing the search query _does_ reset the page.

Let me know if I can provide any additional helpful information!

**Comment by Haroenv** [comment]
@semanticart, that is because you are using Configure, and not Menu which would fit your use case better, and automatically resets the page. Configure is meant for arbitrary search parameters, and thus does not reset the page, as the behaviour would be unexpected

**Comment by semanticart** [comment]
@Haroenv ah. Thank you for explaining how `Configure` is a poor fit here.

I don't think `Menu` actually helps us in our case since we already have a custom UI built. Is there an easy `Configure`-like way to pass in filters to `InstantSearch` that would reset the page when things change?

Or is my best bet to use `searchState` directly?

**Comment by Haroenv** [comment]
You can use the `connectMenu` HOC to get access to the items, counts and `refine` function. If you don't have much code yet, you can also consider react-instantsearch-hooks which is experimental
