### ISSUE TITLE
Documentation of upgrade guides from v4 to v5 missing changed classname of `InfiniteHits`

### ISSUE THREAD

**Issue by paschalidi** [algolia/react-instantsearch#2382]
Hello you al! Thanks for the nice project you offer to the community and for the oportunity you give us all to help you make it better!! 👋 ☮️ 

**Describe the bug**

When updating from v4 to v5 I realised that a piece of documentation is missing.
In the section regarding the component `InfiniteHits`, the fact that the old class `.ais-InfiniteHits__loadMore` is being changed to `.ais-InfiniteHits-loadMore` is missing. Please for more look [here](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/?language=javascript#infinitehits).

**To Reproduce 🔍**

1. Go to https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/?language=javascript#infinitehits you can see that the class `.ais-InfiniteHits__loadMore` is not being mentioned as one that needs to be updated.

**Comment by francoischalifour** [comment]
Hey, thank you for reporting this. A fix is on its way!

**Comment by paschalidi** [comment]
welcome @francoischalifour can I contribute on this ?

**Comment by francoischalifour** [comment]
The new documentation website is unfortunately closed source for now. There's no way for external contributors to edit guides.
