### ISSUE TITLE
Where are the "docgen" docs?

### ISSUE THREAD

**Issue by catamphetamine** [algolia/react-instantsearch#2385]
There used to be the docs:
https://github.com/algolia/react-instantsearch/tree/c2dbfe6cdfa89268342fa95ab532063e84f49a57/docgen/src/guide
Where is it now?

**Comment by catamphetamine** [comment]
Seems that the docs have been rewritten and moved to the website.
https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/react/

**Comment by tkrugg** [comment]
Yes! That's a generic guide explaining how to [create your own widgets](https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/react/).

I don't know what you want to achieve but I should add that in most cases customising the UI of an existing widget is good enough. The API reference of each widget has a `Customize the UI` section with lots of examples. See for example SearchBox: https://www.algolia.com/doc/api-reference/widgets/search-box/react/?language=component#connector

As of why we've made all theses changes in ours docs, it's all explained in this blog post: https://blog.algolia.com/redesigning-our-docs-part-1-why/

I hope this helps.

**Comment by catamphetamine** [comment]
@tkrugg Thanks.

As for why did I read the custom connectors readme: this library doesn't have a conventional "Reset" button. It only has "Clear Filters" one which doesn't reset "Hits Per Page" or "Sort By" widgets.
But we decided to not implement the "Reset" button because "Clear Filters" will be sufficient.
