### ISSUE TITLE
URL sync unchecked toggles still present

### ISSUE THREAD

**Issue by catamphetamine** [algolia/react-instantsearch#2393]
As per the guide: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/#overview

We added URL syncing but when toggles are toggled off again they don't disappear from the URL because previously they weren't in the `state` and now they're `false` in the `state`.
Is there an officially recommended way to clear such `false` togglers from the state URL?
A toggle can also have a default refinement of `true`. For example, search for "Local: true" apparments by default.

**Comment by catamphetamine** [comment]
This is not a critical issue or something like that.
It's just an idea of making URLs look cleaner.
Not that any users would actually care though.

**Comment by samouss** [comment]
Hi, we don't advocate for a particular solution in those cases. With React InstantSearch we don't have a built-in API for the URLSync. You have the full control on what is pushed inside the URL. You can definitely omit some of the values before pushing them inside the URL. It's up to you.
