### ISSUE TITLE
connectMenu()/ MenuSelect does not show any facets

### ISSUE THREAD

**Issue by ishitagoel** [algolia/react-instantsearch#2412]
I am trying to create a custom menu to filter by a facet but it does not list any facet values.

The facet is on a nested attribute (user.email). It has been configured as "filter only". It works on Algolia dashboard -> Browse -> Add query param -> Advanced search -> Facet filters

But when I try to use this facet as attribute to MenuSelect widget in my ReactJS app, no facets get listed. I have tried connectMenu(), connectRefinementList() and Menu widget but in each the problem remains the same. 

I am on Community edition.

Here's my code:

````
import algoliasearch from 'algoliasearch/lite';
import { InstantSearch, connectMenu, SearchBox, Hits} from 'react-instantsearch-dom';

const UserSelect = ({items}) => {
    console.log('In UserSelect', items); //Problem: items is an empty array []
    return....
}

export const Search = (props) => {

    const algolia = algoliasearch(
        process.env.REACT_APP_ALGOLIA_ID, 
        process.env.REACT_APP_ALGOLIA_SEARCH_KEY);

    const CustomUserSelect = connectMenu(UserSelect);

    return (
         <InstantSearch searchClient={algolia} indexName={process.env.REACT_APP_ALGOLIA_INDEX}> 
              <CustomUserSelect attribute='user.email' />  
              <SearchBox />
               <Hits />
         </InstantSearch>  
    );  
}

```

**Comment by Haroenv** [comment]
The attribute needs to be set up for regular filter, not `filterOnly` to work as a menu. The reason is that we retrieve the list of the facet counts & possible facets (`items` provided to the component). This isn't possible and will not be returned by the engine if set up as `filterOnly`.

I'm going to close this issue, since there's no workaround except changing your settings. Hope that helps!

**Comment by ishitagoel** [comment]
Thank you! Yes that worked

**Comment by colepeters** [comment]
@Haroenv Sorry to bring up an old issue, but I'm having a similar problem with a custom Menu Select component. The attributes being targeted by this menu are all set up as 'not searchable' — 'filter only' is not selected. However, these attributes are still getting stripped from the MenuSelect's options when they would return 0 results. Any advice?
