### ISSUE TITLE
[Custom Infinite Hits] Unexpected behaviour after refine (show more being clicked)

### ISSUE THREAD

**Issue by gjergjk71** [algolia/react-instantsearch#2418]
**Describe the bug 🐛**
The facetFilter's work correctly when "Show more" is not clicked (http://prntscr.com/nmkwk9)
After show more is clicked, ex. after reaching end aka. all objects http://prntscr.com/nmkwua
Now when I query for a another category (facetFilter) the hits don't get replaced with the new ones.

I tried refresh'ing with setting 'refresh' true then false. ( and a lot of other stuff, but honestly I can't even remember much to explain )

**Expected behavior 💭**

When changing facetFitler hits should be replaced with the new ones.

**Environment:**
React

**Additional context**
Code:
```js
const _AppsInfinite = ({ hits, hasMore, refine, pass_filterBy}) => {
  console.log(hits,pass_filterBy);
  return (
    <div>
      <div className="apps__content">
        {hits.map(hit => <App hit={hit} pass_filterBy={pass_filterBy} />)}
      </div>
      <center>
        <button disabled={!hasMore} onClick={refine}>
          {hits.length ? (hasMore ? 'Show more' : null) : 'Nothing to show.'}
        </button>
      </center>
    </div>
  )
};
```
```js
const AppsInfinite = connectInfiniteHits(_AppsInfinite);
```
```js
                  <Configure
                    hitsPerPage={4}
                    facetFilters={this.state.filterBy.appCategory === "all" ? [] : [
                      `appCategory.name:${this.state.filterBy.appCategory}`
                    ]}
                  />
                  <AppsInfinite
                      hitComponent={(data) => <App hit={data.hit} pass_filterBy={this.state.filterBy} />}
                      pass_filterBy={this.state.filterBy}
                    />
```

**Comment by Haroenv** [comment]
You are using facetFilters in a configure, doing it that way it might:

- get overridden by any other widget using that same attribute
- not reset the page to 0

A more robust way of doing that same should be by using a virtual widget with default refinement:

https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/#virtual-widgets

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
