### ISSUE TITLE
[Feature Request] Pass extra info to refine.

### ISSUE THREAD

**Issue by gjergjk71** [algolia/react-instantsearch#2445]
**Is your feature request related to a problem? Please describe 🙏**

Knowing why refine was called is useful for conditional rendering for choosing between loading spinner or skeleton.

**Describe the solution you'd like 🤔**

Being able to pass extra info to refine, which then can be accessed through connectStateResults.

**Comment by Haroenv** [comment]
Could you describe how you want to use this? 

You can alias the refine function in your custom widget and e.g. send an event up to the parent which then can do the custom rendering without you needing to read it from the search state

**Comment by samouss** [comment]
I'm closing this issue because it's inactive since a while. Feel free to open a new one!
