### ISSUE TITLE
Consider using Danger for non-test tests

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#246]
[Danger](http://danger.systems/js/) is really awesome, it allows to enforce rules like which branch to do a PR on, or enforcing ESLint, but in a way that's easy to write, and more maintainable than bash scripts. The dashboard team uses the ruby version already. Some rules that could be added: 

* eslint enforcing
* commit convention
* enforcing yarn.lock to be updated if package.json is updated
* [enforcing shorter PRs](https://github.com/ReactiveX/rxjs/blob/d2a32f9a18ebbf65bea798f558364571c91a9d79/dangerfile.js#L18-L22)
* [size difference](https://github.com/ReactiveX/rxjs/blob/master/dangerfile.js#L88-L96)
* [enfocing a pr description](https://github.com/artsy/emission/blob/master/dangerfile.ts#L47-L49)
* [make sure every component has a story](https://github.com/artsy/emission/blob/master/dangerfile.ts#L95-L117)
* [checking spelling](https://github.com/orta/danger-plugin-spellcheck)

I'm sure there are more possibilities too. 

What are you thinking?

**Comment by mthuret** [comment]
What rules would you add right now?

**Comment by Haroenv** [comment]
Would start small, but the ones I suggested in that list seemed applicable to react-instantsearch

**Comment by mthuret** [comment]
Yes ok.

However I'm not sure we should add those ones. 

enforcing shorter PRs
size difference
enfocing a pr description

**Comment by vvo** [comment]
Are there any issues we face today in term of productivity as for the way we collaborate over GitHub? If yes and obvious one yes we should fix them. Otherwise I don't think it's worth it (but for the sake of learning danger)

**Comment by mthuret** [comment]
Let's reopen this if we have issues coming in the future.
