### ISSUE TITLE
jsonp-request Error (too long?)

### ISSUE THREAD

**Issue by davist11** [algolia/react-instantsearch#2494]
**Describe the bug 🐛**

We are running into a weird issue where filtering stops working once you have a number of facets set. It appears like the JSONP request URL being generated is too long (6100 characters)

**To Reproduce 🔍**

1. <a href="https://www.hamiltoncompany.com/laboratory-products/hplc-columns/products?menu%5Bfilter_facet_10552%5D=PRP%26dash%3BX100&menu%5Bfilter_facet_10537%5D=HPLC%20Column&menu%5Bfilter_facet_10547%5D=4.1%20mm&page=1&configure%5BhitsPerPage%5D=1000">Visit this site</a>
2. Select `50 mm` from the **Hardware Length** dropdown
4. See error in console

**Expected behavior 💭**

The filtering continues to work

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/199985/58666270-d814ef00-8300-11e9-83b0-b0d6c16fb44e.png)

**Environment:**

 - OS: Mac
 - Browser: Chrome
 - Version: 74.0.3729.169 (Official Build) (64-bit)

**Comment by yannickcr** [comment]
JSONP is used as a fallback when a regular XMLHttpRequest cannot be done or if CORS is not supported (on very old browsers for example) and has some limitations compared to regular XMLHttpRequests (like URL size limit).

But in your case even modern browsers are using JSONP, which is not normal.

Seems that [`algoliasearch-client-javascript` is unable to find XMLHttpRequest on the global object](https://github.com/algolia/algoliasearch-client-javascript/blob/c27e89ff92b2a854ae6f40dc524bffe0f0cbc169/src/browser/createAlgoliasearch.js#L45-L48) (that should be `window` here, we're using [`global`](https://github.com/Raynos/global) to find it).

It can come from the way you are bundling your application, see if there is something in your webpack configuration that could explain this issue.

**Comment by davist11** [comment]
Thanks for that! That led us to tracking down the issue. We actually had some code in `global/index.js` and the module wasn't being resolved correctly.
