### ISSUE TITLE
Meteor usage: Same error as instantsearch.js

### ISSUE THREAD

**Issue by Discordius** [algolia/react-instantsearch#251]
I am running react-instantsearch on Meteor, and I seem to be getting the same bug as is documented here: https://github.com/algolia/instantsearch.js/issues/1024

But the suggested bugfix appears to be instanstsearch specific, so I can't fix it. Here is a screenshot: 
<img width="1666" alt="screen shot 2017-08-09 at 10 53 10 pm" src="https://user-images.githubusercontent.com/9090789/29156226-94113ffa-7d55-11e7-8094-8976b479f478.png">

Here is my complete component code: 

```
  <InstantSearch
    appId="Z0GR6EXQHD"
    apiKey="0b1d20b957917dbb5e1c2f3ad1d04ee2"
    indexName="dev_posts"
    >
    <Search />
  </InstantSearch>

const Search = () =>
  <div>
    <Hits />
  </div>
```

**Comment by Haroenv** [comment]
Seems like you have the same issue indeed. Can you give a replication repo so I see exactly how you're requiring what?

**Comment by Discordius** [comment]
Ah, just solved it! I didn't find anything under Meteor in this repo, but this was addressed in the instantsearch.js repo here: 

https://github.com/algolia/instantsearch.js/issues/1807

**Comment by Haroenv** [comment]
Glad you found the solution, these kinds of issues are super hairy to debug. Enjoy your day!
