### ISSUE TITLE
Make it possible to refresh a InstantSearch instance

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#252]
**Do you want to request a *feature* or report a *bug*?**

Feature

**Feature: What is your use case for such a feature?**

When you add an object to your index, you want the frontend to be updated. Right now this can be done _slightly_, by having a custom client, calling `.clearCache` and then somehow triggering a new search (mounting/unmounting or simulating an event in the input), but that's quite hacky.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

A widget and connector for `refresh`. It should call `client.clearCache()`, and search again with the current parameters. 

This can also be useful if you want a "definitely search" button. 

related to https://github.com/algolia/react-instantsearch/issues/100, https://github.com/algolia/react-instantsearch/issues/131, https://github.com/algolia/vue-instantsearch/issues/241 and [this discourse post](https://discourse.algolia.com/t/force-refresh-of-react-instantsearch-resulst/1780/3)

**Comment by mthuret** [comment]
I agree we should do something about this use case.

What would be the API of such a widget? How do you expect to use it? Same for the connector? 

What that would bring compare to a simple function? 

Can you clarify the concept of a  "definitely search" button?

**Comment by Haroenv** [comment]
for "definitely search", I had a use case in mind, where none of your filters are actually applied until you press a button to search (not exactly our ideal usecase), but now that I think about it again, that would need another concept. 

The widget would be rendering a button, on click, the results would refine. You could add that component yourself dynamically whenever you get a notice from your backend somehow that the data is stale. 

```jsx
const App = () =>
  <InstantSearch>
    <SearchBox />
    <Refresh />
    <Hits />
    <Pagination />
  </InstantSearch>;
```

This pattern is described in https://github.com/algolia/vue-instantsearch/issues/241#issuecomment-320210145

The connector would look like this:

```jsx
const Refresh = connectRefresh(({ refine }) =>
  <button onClick={() => refine()}> refresh </button>
);
```

The refine function here will clear the cache, do a new query and update the results with that new query

**Comment by mthuret** [comment]
This would mean adding a side effect to call the clearCache inside the refine function (which the purpose is to return a new searchState based on the current one). I'm not a fan of the idea. 

Why not just having a regular `refresh` function. I'm also wondering if could have something directly on the `<InstantSearch/>` component.

**Comment by Haroenv** [comment]
How can you call that function then?

**Comment by mthuret** [comment]
Either with another HOC or indirectly by having 

```
<InstantSearch refresh> // to use in conjonction with `onSearchStateChange` to toggle to false? 
   ...  
</InstantSearch>
```

I thing it's good to explore options and compare each trade-off of them :)

**Comment by Haroenv** [comment]
As possible UI inspiration, here's what this message looks like in Safari DevTools search

<img width="225" alt="screen shot 2017-08-10 at 18 35 03" src="https://user-images.githubusercontent.com/6270048/29181256-c4cf019a-7dfa-11e7-82e8-d1fa68b835d0.png">

**Comment by vinhlh** [comment]
Could we provide an option to clear specified records?

**Comment by Haroenv** [comment]
What exactly do you mean by that, @vinhlh; I have the feeling it might be an unrelated issue, feel free to open another issue for that.

**Comment by vinhlh** [comment]
I mean, this issue is about adding an object to the index. What I did concern is similar: removing an object from the index.
I don't want to clear the whole client cache but only deleted objects. Should we?

**Comment by Haroenv** [comment]
It will be more efficient to clear the cache than to store which objects are deleted; it will also not be simple to actually know which objects are deleted, so clearing the cache on a certain moment seems better to me.

**Comment by mthuret** [comment]
I did some research about this API request and here is what I propose: 

1. adding a prop `refresh` on InstantSearch 
2. when set to true, we clear the cache and we make a new search
3. `refresh` should be then to false using a React lifecycle hook or `onSearchStateChange`. 

@VincentCtr @georgejor @pyankoff @LaurentLousky @vinhlh @vvo @Haroenv: what do you think?

**Comment by Haroenv** [comment]
I'm not 100% convinced, but with the `onSearchStateChange` it's pretty simple to implement. Would love to see this pattern possible, and that's a reasonable solution 😄

**Comment by vvo** [comment]
LGTM 👍

**Comment by LaurentLousky** [comment]
Yeah that looks good to me as well!

**Comment by sokki** [comment]
I'm also craving for this feature. 

In the meanwhile, I helped me with this hack:
```js
  clearCache() {
    this.setState({
      clearedCache: -(new Date()),
    });
  }
```
...
```js
<Configure filters={`createdAt > ${this.state.clearedCache}`} />
```

**Comment by marielaures** [comment]
Thank you for sharing it @sokki, this feature is currently being worked on. Stay tuned!
