### ISSUE TITLE
index name serialization at URL

### ISSUE THREAD

**Issue by Kikobeats** [algolia/react-instantsearch#254]
I noted that `indexName` at `<InstantSearch/>` is not serialized into the URL:

![](https://d26dzxoao6i3hh.cloudfront.net/items/3Y0e0u3f1Y0g382c3D0J/Screen%20Recording%202017-08-11%20at%2012.13%20am.gif?v=27692e71)

I can understand why, but could be possible do it? I have different indexes and I retrieve the properly index from the user selection, so how to do it persistent into the URL.

Also I saw that is not available at `<Configure/>`, and actually `<Index/>` is not useful here because the user case is not support different replica results in the same view; just serialize the current index name to be possible share the link and get all the user configuration.

**Comment by Haroenv** [comment]
Serializing the URL is a user concern in React InstantSearch, it should be possible. What you should do in this case I think, is indeed `Index`, and enable the result that has been serialized.

Can you provide a bit more detail into what you need that's not offered right now?

**Comment by Kikobeats** [comment]
I suppose this functionality have to live into `<Index />` component, but it needs to be updated for support it.

Currently, I have this:

```jsx
<InstantSearch  indexName={this.state.indexName} {...props} />
```

where the value of the `indexName` is determinated using the UI (also the application provide a default value). It works fine.

If I do something like:

```jsx
<InstantSearch  indexName={this.state.indexName} {...props}>
<Index indexName={this.state.indexName}></Index>
</InstantSearch>
```

It throws an error:

```
warning.js?3e5f6e9:35 Warning: Failed prop type: Invalid prop `resultsState` of type `array` supplied to `_class`, expected `object`.
    in _class (created by Container)
    in Container (created by App)
    in div (created by App)
    in App
```

I suppose because `<Index />` wasn't designed to be used with the same index than `<InstantSearch/>` at the same time.

**Comment by mthuret** [comment]
Hi @Kikobeats, 

Having an Index component using the same index name that the default one (on InstantSearch) is a supported syntax. 

It seems that the warning refers to the newly SSR feature (mentioning 'resultsState'). I'll try to reproduce it or better you could provide us a live example (codesandebox is great for that).

Does this warning prevent you to serialize the index name in the url? They should be present in the search state.

**Comment by mthuret** [comment]
@Kikobeats: can we close this?

**Comment by Kikobeats** [comment]
yes!

Using `</sortBy>` all works fine 😄
