### ISSUE TITLE
[ New design ] Sidebar issue 

### ISSUE THREAD

**Issue by LukyVj** [algolia/react-instantsearch#256]
On some pages of the new documentation, the sidebar is really buggy. 

Branch:  `feat/new-design`
Example: https://puu.sh/x9FjQ/e9fab971b7.png

**Comment by Haroenv** [comment]
Shouldn't it overflow like it did before?

**Comment by LukyVj** [comment]
Not related to overflowing

**Comment by rayrutjes** [comment]
We've got the same issue on Vue, it is related to the script doing the positioning.
Probably an edge case.

**Comment by LukyVj** [comment]
Yep, that's why I notified @bobylito :)
