### ISSUE TITLE
searchState.hasOwnProperty is not a function due to Object.create(null)

### ISSUE THREAD

**Issue by avaragado** [algolia/react-instantsearch#2568]
**Describe the bug 🐛**

I'm using the npm module [`query-string`](https://www.npmjs.com/package/query-string) to parse search terms previously encoded into URLs. The `parse` method this module exposes creates objects using `Object.create(null)`, which means they don't have a prototype.

If I use the `query-string` module to parse an Algolia searchState from the URL, and then pass that searchState to the `InstantSearch` component, I get an error:

`Uncaught TypeError: searchState.hasOwnProperty is not a function`

This is coming from react-instantsearch-core, `src/core/indexUtils.js`, `hasRefinements` function. The error occurs because the `searchState` I'm passing has no prototype, and so it has no `hasOwnProperty` function.

**To Reproduce 🔍**

Pass any `searchState` object created with `Object.create(null)` to `InstantSearch`.

**Expected behavior 💭**

No error.

**Environment:**

 - macOS 10.14.5
 - Chrome 74

**Additional context**

Consider replacing the current calls to `searchState.hasOwnProperty(x)` with `{}.hasOwnProperty.call(searchState, x)`

**Comment by samouss** [comment]
Thanks a lot for the issue! Until we fix the issue inside the codebase, a quick fix it to force the return value of the [`query-string`](https://www.npmjs.com/package/query-string) package to be an object with prototype. Here is an example of a possible solution:

```js
const searchState = {
  ...queryString.parse('?query=Apple'),
};
```

**Comment by Haroenv** [comment]
seems like the behaviour by query-string was on purpose: https://github.com/sindresorhus/query-string/issues/50

**Comment by Haroenv** [comment]
6.0.0-beta.0 has the new behaviour of working with non-Object objects for searchState
