### ISSUE TITLE
withSearchbox shows "no results" until three characters are typed when there's another refinement

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#257]
**Do you want to request a *feature* or report a *bug*?**

bug

**Bug: What is the current behavior?**

https://codesandbox.io/s/oY1klpZYB

1. refine in one of the refinementLists
2. search in another refinementList
3. see `No results` until three characters are typed

**Bug: What is the expected behavior?**

See the result immediately

**Bug: What browsers are impacted? Which versions?**

All AFAIK

I'm not sure if this is a limitation of SFFV or the combination with what is already refined, but it's still an odd situation

**Comment by mthuret** [comment]
Can you precise your workflow because I couldn't see it using your example? 

1. I click on "react" on the first refinement list
2. I search for "g" on the second one
3. I can see four results

**Comment by Haroenv** [comment]
Whoa you’re right, I can no longer reproduce it. It must have been some kind of fluke 🤔 I’ll reopen if I can reproduce it again.
