### ISSUE TITLE
Using 2 HierarchicalMenu on same page with same attributes creates an issue

### ISSUE THREAD

**Issue by discussion4all** [algolia/react-instantsearch#2620]
so I've been wanting to use 2 hierarchicalMenu on the same page and also they have the same attributes but the styling is different.
The thing is I want to display the 2nd menu in place of default hits when the query is empty or when the page is open first time 

**when I try to do it this is the error shown in console**
index.js:973 Uncaught (in promise) Error: Cannot declare two hierarchical facets with the same name: `categories.lvl0`
    at SearchParameters.addHierarchicalFacet (index.js:973)
    at Connector.getSearchParameters (connectHierarchicalMenu.js:217)
    at Connector.getSearchParameters (createConnector.js:278)
    at eval (createInstantSearchManager.js:104)
    at Array.reduce (<anonymous>)
    at getSearchParameters (createInstantSearchManager.js:103)
    at search (createInstantSearchManager.js:142)
    at onWidgetsUpdate (createInstantSearchManager.js:258)
    at eval (createWidgetsManager.js:19)

Link where i've pointed the issue
https://codesandbox.io/s/react-instantsearch-app-3c1oq

**Comment by eunjae-lee** [comment]
Hi @discussion4all , thank you for reaching out to us.
If I understand your issue correctly, when there is no search result,
instead of displaying hits, you want to display the hierarchical menu again.

For now, you cannot have more than one HierarchicalMenu with same attribute.
What you can do is, use `connectStateResults` and render whatever you want to with the data.

Here is an example for you.
https://codesandbox.io/s/react-instantsearch-app-74r4u

Please let me know if it helps or if you have further question.

**Comment by Haroenv** [comment]
IIRC it might also be useful to use the [CurrentRefinements](https://www.algolia.com/doc/api-reference/widgets/current-refinements/react/) component there if that fits what you want to do with `transformItems`

**Comment by discussion4all** [comment]
> Hi @discussion4all , thank you for reaching out to us.
> If I understand your issue correctly, when there is no search result,
> instead of displaying hits, you want to display the hierarchical menu again.
> 
> For now, you cannot have more than one HierarchicalMenu with same attribute.
> What you can do is, use `connectStateResults` and render whatever you want to with the data.
> 
> Here is an example for you.
> https://codesandbox.io/s/react-instantsearch-app-74r4u
> 
> Please let me know if it helps or if you have further question.

Worked thx!
@Haroenv I will definitely try that too. thx

**Comment by francoischalifour** [comment]
Let us know if you encounter any other issue.
