### ISSUE TITLE
Need a way to pass extra headers to findResultsState

### ISSUE THREAD

**Issue by callmephilip** [algolia/react-instantsearch#2648]
When using `findResultsState` returned from `createInstantSearch` (`react-instantsearch-dom/server`), i need to pass extra headers (specifically `X-Forwarded-For`) to make sure the search works correctly for `aroundLatLngViaIP` when rendering server side. 

It works great client side but once i use `findResultsState`  from the server, it messes up the results. While trying to debug `findResultsState`, I have noticed that it seems to be using its own instance of the algolia search client. So my question/request is to be able to pass an extra header to it.

**Comment by Haroenv** [comment]
This is something we have fixed in v6, where the client is the same one you pass, and thus can pass extra headers with `.setExtraHeader`, however we didn't release this yet.

**Comment by Haroenv** [comment]
I was confused, you can already do this in v5: https://codesandbox.io/s/example-server-side-rendering-ekc4e

**Comment by Haroenv** [comment]
https://codesandbox.io/s/example-server-side-rendering-ekc4e, you can pass props as the second argument to `findResultsState`

**Comment by callmephilip** [comment]
@Haroenv this seems to work. thank you very much for your help  🙌
