### ISSUE TITLE
Highlight Widget does not work for attribute 'objectID'

### ISSUE THREAD

**Issue by JStonevalley** [algolia/react-instantsearch#265]
**Do you want to request a *feature* or report a *bug*?**
bug

Cannot reproduce with the bestbuy index since objectID appears to be unsearchable on a global level.

**Bug: What is the current behavior?**
'<'Highlight attributeName='objectID' hit={user} '/>' does not work. Nothing is shown.
objectID is added to the searchable attributes in the global index settings.
**Bug: What is the expected behavior?**
'<'Highlight attributeName='objectID' hit={user} '/>' should work as any other attribute such as email: 
'<'Highlight attributeName='email' hit={user} '/>'
**What is the version you are using? Always use the latest one before opening a bug issue.**
4.0.10

**Comment by Haroenv** [comment]
Did you add `objectID` to `attributesToHighlight` in your index settings, I think it might not be possible altogether though, I just tested around a bit. 

From what I can tell now, `objectID` can’t be highlighted. You’ll have to have a second attribute with the same value for highlighting

**Comment by mthuret** [comment]
This is a limitation of the API, it does not highlight the objectID field as it's not really an attribute of the record.
