### ISSUE TITLE
`Highlighter` errors when attribute is a nested array

### ISSUE THREAD

**Issue by timswalling** [algolia/react-instantsearch#2688]
**Describe the bug 🐛**

Highlighting a nested array (ie using a dot-separated `attribute` prop when that attribute is an array) causes `Highlighter` to fail.

**To Reproduce 🔍**

1. Go to https://codesandbox.io/s/react-instantsearch-app-99k45 (which includes `<Highlight attribute="dog.lifestage" hit={props.hit} />` and `<Highlight attribute="dog.size" hit={props.hit} />` in its `Hit` component)
1. Wait for the results to load
1. See error:
```
The above error occurred in the <Highlighter> component:
    in Highlighter (created by Highlight)
    in Highlight (created by AlgoliaHighlighter(Highlight))
    in AlgoliaHighlighter(Highlight) (created by Hit)
    in p (created by Hit)
    in article (created by Hit)
    in Hit (created by Hits)
    in li (created by Hits)
    in ul (created by Hits)
    in div (created by Hits)
    in Hits (created by AlgoliaHits(Hits))
    in AlgoliaHits(Hits) (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by InstantSearch)
    in InstantSearch (created by CreateInstantSearch)
    in CreateInstantSearch (created by App)
    in div (created by App)
    in div (created by App)
    in App
```

**Expected behavior 💭**

The `dog.lifestage` and `dog.size` array values will be rendered with highlights.

**Additional context**

This appears to be due to [line 52 in `Highlighter.js`](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-dom/src/components/Highlighter.js#L52) which uses bracket notation to access the attribute - `hit[attribute]`. Replacing this with Lodash's `get` function (as per [`highlight.js`](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/core/highlight.js#L75)) - eg `get(hit, attribute)` - should resolve this issue.

If time permits I'll open a PR to fix this later today.

**Comment by Haroenv** [comment]
Thanks for the report! the component indeed does not deal correctly with nested arrays. However, it should be replaced with `hit && hit[attribute]`, because we have already removed lodash in the upcoming next version of this code base.

Thanks!

**Comment by Haroenv** [comment]
Thought about it more, if a hotfix for this is needed, you can use `get` from lodash, I'll use another util on v6

**Comment by Haroenv** [comment]
Thought about it even more, let's just use the index as the key, there's no need to generate the key

**Comment by Celtian** [comment]
@Haroenv this happens also in angular library v3.

**Comment by Haroenv** [comment]
thanks for the report @Celtian, for the moment only React InstantSearch has support for nested arrays, so you should read the highlight property manually for Angular InstantSearch for the time being :)
