### ISSUE TITLE
ToggleRefinement not working with Routing URLs example

### ISSUE THREAD

**Issue by yannickcr** [algolia/react-instantsearch#2689]
**Describe the bug 🐛**

When using the [ToggleRefinement](https://www.algolia.com/doc/api-reference/widgets/toggle-refinement/react/) widget with the routing enabled (following the [Routing URLs
 guide](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/) in the documentation) then the toggle parameter is passed as a `string` to the widget instead of a `boolean`.

We got this warning from React:

```js
Warning: Failed prop type: Invalid prop `currentRefinement` of type `string` supplied to `ToggleRefinement`, expected `boolean`.
```

And when refreshing the page the checkbox is always checked (since we receive the `"false"` string which is truthy).

This is because the [qs module](https://github.com/ljharb/qs) parses the url parameters as string by default (https://github.com/ljharb/qs/issues/91). You can fix this by using `qs.decoder` (https://github.com/ljharb/qs/issues/91#issuecomment-437926409) but this is not very convenient (and not precised in the documentation).

**To Reproduce 🔍**

1. Go to https://codesandbox.io/s/example-react-router-b3u4m
2. Click on 'Free shipping'
3. See warning in console.

**Expected behavior 💭**

The `toggle` parameter should be correctly passed to the widget as a `boolean`.

**Environment:**

 - OS: Linux
 - Browser: Chrome
 - Version: 75

**Comment by samouss** [comment]
This is something that we are already doing for a couple of widgets e.g. [`RefinementList`](https://github.com/algolia/react-instantsearch/blob/f8b80dea98432b43a510c78eec8805c22f3f4f48/packages/react-instantsearch-core/src/connectors/connectRefinementList.js#L17-L35). We can implement the logic inside the [`getCurrentRefinement`](https://github.com/algolia/react-instantsearch/blob/f8b80dea98432b43a510c78eec8805c22f3f4f48/packages/react-instantsearch-core/src/connectors/connectToggleRefinement.js#L27-L29) function of the `ToggleRefinement` connector.
