### ISSUE TITLE
Verify App Build size big due to export strategy and add TreeShaking

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#27]
The goal here is to create a new application using React InstantSearch and very if the build contains only imported functions.

For example by importing `<InstantSearch>`, `<SearchBox>` and `<connectHits>`.

If not, actions should be taken to fix it.

**Comment by Haroenv** [comment]
This is mostly because we export only commonjs at this point. Exporting as es-modules, so only transpiling "es2015, modules: false" will work perfectly with modern build tools like webpack 2

**Comment by rayrutjes** [comment]
Basically we need:
- statically analyzable exports (ES6 exports)
- add `module` key to package.json

Then use webpack 2 or rollup will treeshake.
