### ISSUE TITLE
How can I prevent item re-ordering in a connected RefinementList component?

### ISSUE THREAD

**Issue by JoaoCnh** [algolia/react-instantsearch#2728]
I'm creating a custom UI for a RefinementList. 

Whenever I refine, the items array is re-ordered breaking my custom component intented UI.

Is there a way I can turn this off? I don't want to add ordering functions for these arrays whenever it renders.

Or even set a sortBy method by yourself for each facet that you're using in the refinement list.

**Comment by yannickcr** [comment]
There is no option to turn this off, but you can use the [`transformItems`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/react/#widget-param-transformitems) prop to re-order the items:

```jsx
<RefinementList
  attribute="brand"
  transformItems={items => {
    // Sort all items alphabetically
    return items.sort((a, b) => {
      const labelA = a.label.toUpperCase();
      const labelB = b.label.toUpperCase();
      if (labelA < labelB) {
        return -1;
      }
      if (labelA > labelB) {
        return 1;
      }
      return 0;
    });
  }}
/>;
```
