### ISSUE TITLE
<Highlight> Not handling integers/floats

### ISSUE THREAD

**Issue by mclapa** [algolia/react-instantsearch#273]
**Bug: What is the current behavior?**
When using the Highlight component

```
<Hits hitComponent={HomeItem} />
...
<Highlight
  attributeName="unit_number"
  hit={this.props.hit}
/>

<Highlight
  attributeName="location_name"
  hit={this.props.hit}
/>
```
If unit_number is not a string then that component will not return anything. 

**Bug: What is the expected behavior?**
Should convert it to a string and then do the string operations on it

**What is the version you are using? Always use the latest one before opening a bug issue.**
"react-instantsearch": "^4.0.10",

The temporary workaround is convert all the integers to strings before sending it to Algolia. In my case for Laravel 5.4 it was a toSearchableArray()

**Comment by Haroenv** [comment]
Yes, it's not possible to highlight numbers as numbers in Algolia. Best option is to have a string for displaying as text (highlighting), and a number if you want to use it for Range or similar. 

This can't be solved in React InstantSearch, so I'll close it, but I put it on our internal feedback board. 

Have a nice day!
