### ISSUE TITLE
SortBy doesn't work when passing indexId prop

### ISSUE THREAD

**Issue by colis** [algolia/react-instantsearch#2775]
**Describe the bug 🐛**

When using the `Index` component - along with the `indexId` prop to implement a multi-index configuration - the `SortBy` component stops working after the first id switch.

**Expected behavior 💭**

The `SortBy` component should sort the results under the current `indexId`.

**Screenshots 🖥**

This is the `searchState` object: the `sortBy` parameters point to the correct indices, but the results don't get updated.

<img width="388" alt="Screenshot 2019-08-20 at 23 00 48" src="https://user-images.githubusercontent.com/9059716/63387997-dce8bc80-c39e-11e9-8ed4-d3c2c10c0c0e.png">

**Environment:**

 - OS: macOS
 - Browser: Chrome
 - Version: 5.7.0

**Comment by Haroenv** [comment]
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

You can use the indices `instant_search`, `instant_search_rating_asc` and `instant_search_price_asc` (to see a difference)

This is to make sure the situation is correctly solved, since from your text I'm not sure how many Index components you are having for this issue to show up.

**Comment by colis** [comment]
hi @Haroenv, thanks for getting back to me.

I'll try to create a sandbox asap. Meanwhile, this is pretty much the structure of the app

```
<InstantSearch
    indexName={institutionIndexName}
    searchClient={client}
>
    <DataFilters /> ----> This extends the Menu component

    <Index
	indexId="based on the DataFilters selection above, i.e.: LP, GP, etc.
	indexName="same as indexName above"
    >
        <FiltersSection /> ----> Facets

        <CustomStats /> ----> Number of results

        <DataResults /> ----> Custom Hits				
    </Index>
</InstantSearch>
```

Essentially, all the institutions are in the same index, but we assign an `indexId` to filter down institutions of a specific type (LP, GP), selected via the `DataFilters (menu)` component.

**Comment by colis** [comment]
@Haroenv after a bit of debugging, I noticed that when I click the sortBy button, no queries are being sent to Algolia after the first `menu` refinement. Can that be related to a wrong `searchState` format?

**Comment by Haroenv** [comment]
could be related. Are you using searchState / onSearchStateChange? Do you have a live website to debug?

**Comment by sarahdayan** [comment]
Hey!

We're doing a round of clean up before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately. Is it still relevant @colis?

**Comment by colis** [comment]
@sarahdayan no longer relevant, cheers!
