### ISSUE TITLE
Rendering a refinement list on demand triggers a refine

### ISSUE THREAD

**Issue by JoaoCnh** [algolia/react-instantsearch#2782]
I have a modal in which the content is only rendered if a certain boolean value in state is `true`.

In the content of this Modal I have some custom RefinementList components that I developed and work great.

However, when the content is rendered, they trigger their defaultRefinements (in my case I have none), thus, triggering a refine on my Index. I understand the behaviour but it would be great that, if the defaultRefinement is not set, that the simple act of rendering wouldn't trigger a full refinement.

If there is a way to turn it off, how?

Thanks in advance and I would love to discuss this further.

**NOTE**
I'm not rendering the content of the modal before hand to save on rendering. It's a complex page and I could use any bit of performance gains.

**Comment by francoischalifour** [comment]
You can be fully in control of when to refine with the [`onSearchStateChange`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-onsearchstatechange) and [`searchState`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-searchstate) options combination.

More resources:

- [The search state format explained](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/#the-search-state-format-explained)
- [Basic routing](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/#basic-urls)

**Comment by JoaoCnh** [comment]
Sorry but I'm not sure I understand how I can prevent the query if the search state has changed already. At least not from the examples provided.

**Comment by francoischalifour** [comment]
I didn't get that you wanted to avoid the request on first render.

That's not really possible with the current API. However, you might be able to catch this context and avoid triggering another request by mocking the search client.

See [Mocking a request](https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/react/#mocking-a-search-request).

**Comment by websocket98765** [comment]
**Related:** When components are **_removed_** from the DOM as well, they invoke `onSearchStateChange` (so I assume they're hitting the API), even if they were untouched and never interacted with. 

Example: I change a boolean value which renders a few Algolia Menu Select elements. (AFAICT, I'm not getting default refined when they appear in the DOM as mentioned in this issue because it doesn't appear onSearchStateChange is being called any more than expected, in my case.) _But_ when I switch that boolean off and the Menu Selects are _removed_ from the DOM, `onSearchStateChange` is called once for each instance of Menu Select that was on the page. Meaning if I remove 6 Menu Selects from the DOM, `onSearchStateChange` is invoked 6 times!

**Comment by Haroenv** [comment]
Yes, when an element is removed, its refinement is also removed, and thus a new request needs to be done. If you don't want that, you can "soft-remove" it (via e.g. css)

**Comment by websocket98765** [comment]
> Yes, when an element is removed, its refinement is also removed, and thus a new request needs to be done. If you don't want that, you can "soft-remove" it (via e.g. css)

It'd be more ideal if Menu Select (& other elements) checked if it was in its default, unrefined state when removed from the DOM to avoid sending an unnecessary refinement in that case.

(I can't merely hide via CSS b/c _if_ the Menu Select was interacted with and is restricting the results, then in that case I do need it to send a request to clear its refinement when removed from view. But my point is, it only makes sense to send that refinement if the item is restricting results when removed from the DOM.)

**Comment by dhayab** [comment]
Hi! We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, so we're going to close it. Feel free to reopen if needed.
