### ISSUE TITLE
connectPagination does not add CSS classnames

### ISSUE THREAD

**Issue by EdwardBarton** [algolia/react-instantsearch#2784]
**Describe the bug 🐛**

When attempting to customize the `Pagination` widget using `connectPagination`, the outputting HTML does not contain any of the css classes that the Algolia theme utilizes.

Per the docs:
[CustomPagination Component](https://www.algolia.com/doc/api-reference/widgets/pagination/react/?language=component#full-example)

```js
import { connectPagination } from 'react-instantsearch-dom';

const Pagination = ({ currentRefinement, nbPages, refine, createURL }) => (
  <ul>
    {new Array(nbPages).fill(null).map((_, index) => {
      const page = index + 1;
      const style = {
        fontWeight: currentRefinement === page ? 'bold' : '',
      };

      return (
        <li key={index}>
          <a
            href={createURL(page)}
            style={style}
            onClick={event => {
              event.preventDefault();
              refine(page);
            }}
          >
            {page}
          </a>
        </li>
      );
    })}
  </ul>
);

const CustomPagination = connectPagination(Pagination);

// usage
<CustomPagination />
```
_should_ result in the following [HTML Output](https://www.algolia.com/doc/api-reference/widgets/pagination/react/?language=usage#html-output)
```html
<div class="ais-Pagination">
  <ul class="ais-Pagination-list">
    <li class="ais-Pagination-item ais-Pagination-item--firstPage ais-Pagination-item--disabled">
      <span class="ais-Pagination-link" aria-label="First">‹‹</span>
    </li>
    <li class="ais-Pagination-item ais-Pagination-item--previousPage ais-Pagination-item--disabled">
      <span class="ais-Pagination-link" aria-label="Previous">‹</span>
    </li>
    <li class="ais-Pagination-item ais-Pagination-item--selected">
      <a class="ais-Pagination-link" href="#">1</a>
    </li>
    <li class="ais-Pagination-item ais-Pagination-item--page">
      <a class="ais-Pagination-link" href="#">2</a>
    </li>
    <li class="ais-Pagination-item ais-Pagination-item--page">
      <a class="ais-Pagination-link" href="#">3</a>
    </li>
    <li class="ais-Pagination-item">
      <a class="ais-Pagination-link" href="#">4</a>
    </li>
    <li class="ais-Pagination-item ais-Pagination-item--nextPage">
      <a class="ais-Pagination-link" aria-label="Next" href="#">›</a>
    </li>
    <li class="ais-Pagination-item ais-Pagination-item--lastPage">
      <a class="ais-Pagination-link" aria-label="Last" href="#">››</a>
    </li>
  </ul>
</div>
```
However, the _actual_ HTML output is:
```html
<ul>
  <li>
    <a href="#" style="font-weight: bold;">1</a>
  <li>
  <li>
    <a href="#" style="font-weight: bold;">2</a>
  <li>
  ...
</ul>
```

**To Reproduce 🔍**

1. import `Pagination` and `connectPagination`
2. Create `CustomPagination` component per docs (linked above)
3. Render `Pagination` component
4. Render `CustomPagination` component
5. Compare differences

A live example helps a lot! We have a simple online template for you to use for your explanations:

> https://ncy5r.csb.app

**Expected behavior 💭**

`CustomPagination` should still retain styles from `Pagination` widget using `connectPagination`

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/12461490/63552915-03296c00-c507-11e9-8a9c-a0a606e3d811.png)

**Environment:**

 - OS: macOS Mojave 10.14.6
 - Browser: Chrome
 - Version: 76

**Additional context**

N/A

**Comment by francoischalifour** [comment]
Connectors only provide the logic of the widget and do not specify/override the rendering. Thus, the JSX that you return remains as is.

As soon as you use a connector, you bail out of the HTML output specification and are on your own for the rendering.

You can read more on [Customize the complete UI of the widgets](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/#customize-the-complete-ui-of-the-widgets).

**Comment by EdwardBarton** [comment]
> Connectors only provide the logic of the widget and do not specify/override the rendering. Thus, the JSX that you return remains as is.
> 
> As soon as you use a connector, you bail out of the HTML output specification and are on your own for the rendering.
> 
> You can read more on [Customize the complete UI of the widgets](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/#customize-the-complete-ui-of-the-widgets).

Thank you for that explanation as well as the helpful link! If I may, a suggestion might be to update the Widget docs a bit. I looped in a fellow dev and we both read the docs as:

1. Create custom widget with `connectWidget` using the code from the `Full Example` section
2. The _expected_ render HTML should look like that of the `HTML Output` section

Thank you again for all your help!

**Comment by francoischalifour** [comment]
I see what you mean – you're right, it's confusing.

Thank you for the feedback, I'll see if we can reorder this section before the connector.
