### ISSUE TITLE
Support multiple Configure widget

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#28]
We should be able to use multiple `<Configure>` under one `<InstantSearch/>` like:

```js
<InstantSearch>
    <Configure hitsPerPage={10}/>
    <Configure distinct={true}/>
</InstantSearch>
```

See: https://github.com/algolia/instantsearch.js/issues/2006

**Comment by rayrutjes** [comment]
@mthuret why did we go for "virtual"  elements here?
Why not go with the props exposed directly on `InstantSearch`?

I feel like going with `Configure` is overkill and introduces more complexity. For example one could have 2 times a `Configure` element acting on the same property.

**Comment by mthuret** [comment]
@rayrutjes  

Having `<Configure>` as a component is useful. It allows you to write something like:

```js
<InstantSearch>
     <Configure globalSearchParam={}/>
     <Index>
         <Configure hitsPerPage={1}/>
     </Index>
     <Index>
         <Configure hitsPerPage={10}/>
     </Index>
</InstantSearch>
```

You can also mount/unmount them easily.

Also `Configure` can take a list of props, so you don't actually need several one. But we need to support it as it's possible to write it this way.

**Comment by rayrutjes** [comment]
Ok, I'm not convinced of the necessity of those 2 concepts 'Index/Configure'.

```
<InstantSearch hitsPerPage={1} distinct={true}>

<InstantSearch>
<InstantSearch hitsPerPage={10}>

<InstantSearch>
```

I think this is all related to the fact we use derived helper which requires us to be able to handle multiple indices under the same `InstantSearch`.

> Also Configure can take a list of props, so you don't actually need several one. But we need to support it as it's possible to write it this way.

Ok!

The only pro I see here is the "shared config" logic, but I don't think the implementation overhead is worth it.

**Comment by mthuret** [comment]
How do you share the query with the syntax you indicate? And what exactly is the implementation overhead you are talking about?

**Comment by rayrutjes** [comment]
> How do you share the query with the syntax you indicate
Not sure with the current implementation, but basically injecting the same query in both InstantSearch instances would do the trick. Not sure if this is do-able, but it would simplify the nesting I feel like.

> And what exactly is the implementation overhead
2 virtual widgets `Configure` & `Index`, that are more just configuration of the `InstantSearch` element.

**Comment by mthuret** [comment]
It's what we had. To synchronise both instances you needed to listen to the `onSearchStateChange` hook, get the `searchState` and inject it into the other instance. 

Basically with the new `<Index>` api, our multi index example went down to 20 LOC instead of 65. I think it worth it. 

But I think we digress a bit from the purpose of this issue. Maybe we can discuss about that elsewhere?

**Comment by vvo** [comment]
We should be careful about hijacking conversations, here the issue is about fixing a bug on a current implementation (Configure).

We can discuss the way you are able to set search parameters (or how to do multiple indexes) but not in the same issue. Aside from technical implementations any API discussion we should focus it on:
- what are we trying to solve
- what is the current solution
- why another solution would be better (for users, for implementers)

For reference, on react-instantsearch, we moved from:
- function to provide search parameters
- static object to provide search parameters
- Configure widget (latest iteration)

To know more about how we went there, have a look at previous discussions: https://github.com/algolia/instantsearch.js/issues/1342

**Comment by mthuret** [comment]
@zackify I wasn't able to reproduce this bug anymore using our 4.0.0-beta.2 version.

Here's an example of what I'm doing to reproduce this issue, and this is working.

class ConfigureExample extends React.Component {
  constructor() {
    super();
    this.state = { hitsPerPage: 3 };
  }

  onClick() {
    const hitsPerPage = this.state.hitsPerPage === 3 ? 1 : 3;
    this.setState({ hitsPerPage });
  }

  render() {
    const hitsPerPage = <Configure hitsPerPage={this.state.hitsPerPage} />;
    const facets = this.state.hitsPerPage === 3
      ? <Configure filters="category:Bathroom" />
      : <Configure filters="category:Lighting" />;

    return (
      <WrapWithHits linkedStoryGroup="Configure">
        {hitsPerPage}
        {facets}
        <button onClick={this.onClick.bind(this)}>Toggle HitsPerPage</button>
      </WrapWithHits>
    );
  }
I will close this issue, please reopen it if you still have an issue while using multiple configure.
