### ISSUE TITLE
Algolia instantsearch is 70% of my website bundle

### ISSUE THREAD

**Issue by bartol** [algolia/react-instantsearch#2810]
My site is build with Gatsby is using these instantsearch packages:

<img width="784" alt="Screen Shot 2019-08-31 at 11 41 10" src="https://user-images.githubusercontent.com/32748145/64062242-8708e580-cbe4-11e9-9b37-f13be3356cf0.png">

But majority of its size is `InstantSearch` module.

<img width="784" alt="Screen Shot 2019-08-31 at 11 41 31" src="https://user-images.githubusercontent.com/32748145/64062274-bb7ca180-cbe4-11e9-8675-8bf15a491fd6.png">

And here is bundle size produced by webpack bundle analyzer:

![Screen Shot 2019-08-31 at 11 33 47](https://user-images.githubusercontent.com/32748145/64062279-ce8f7180-cbe4-11e9-94ca-e31487805f0d.png)

As you can see, my whole parsed bundle is 506KB and algolia instantsearch is 340KB (70% of bundle) and that is without including lodash that comes with instantsearch.

I hope I'm doing something wrong here. Algolia has awesome search and I love it but this is just too much.

**Comment by Haroenv** [comment]
Can you use the beta version of React InstantSearch? It’s a lot better for bundle size :) see the migration guide: https://github.com/algolia/react-instantsearch/blob/next/MIGRATION.md

**Comment by bartol** [comment]
Thanks, it's not perfect but is noticeably better.
Glad to see improvement!

**Comment by Haroenv** [comment]
@bartol, can you tell the output after using the beta version. For us this version should have removed _a lot_ (50%+) of the size, and all of the clear lowhanging fruit.

**Comment by bartol** [comment]
@Haroenv My bundle size is now ~60 KB lighter.

**Comment by Haroenv** [comment]
If you don't mind, I'll close this issue then, unless you see more ways this bundle can be made significantly lighter, which doesn't require rewriting everything. Hope you understand!
