### ISSUE TITLE
Initial client render with SSR is querying Algolia for the same search state

### ISSUE THREAD

**Issue by andreyvital** [algolia/react-instantsearch#2829]
**Describe the bug 🐛**

Client initial render is sending a request to Algolia even though it's server rendered with the same search state.

**To Reproduce 🔍**

1. Go to https://z3n8x.sse.codesandbox.io/
2. Inspect the network
3. You'll see that there's a request made to Algolia

**Expected behavior 💭**

Shouldn't have any requests made in the initial render on the client, since all the data came back from the server and the search state is the same.

**Comment by Haroenv** [comment]
This has been fixed in v6, which is now in beta!

**Comment by andreyvital** [comment]
Oh—cool. Thanks! However, I can't seem to move to v6 because of #2828. 😞

**Comment by andreyvital** [comment]
Hey @Haroenv do you know when v6 will be ready? I am having some issues with this issue here...and its costing me a lot on Algolia—each day it's more or less extra 100k queries...

**Comment by Haroenv** [comment]
Very soon, you can use the beta for now

**Comment by andreyvital** [comment]
@Haroenv the beta is broken for me :(

https://github.com/algolia/react-instantsearch/issues/2828

**Comment by tkrugg** [comment]
fixed in https://github.com/algolia/react-instantsearch/pull/2862
