### ISSUE TITLE
React 16.9 Deprecation Warnings - componentWillMount rename

### ISSUE THREAD

**Issue by hatched-danny** [algolia/react-instantsearch#2836]
I'm currently getting console warnings from to prepare for React 17's componentWillMount rename:

```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AlgoliaAutoComplete(withWindowWidth(SearchBarInput)), 
```
Also getting it for these:
```
AlgoliaConfigure(UnknownComponent), CreateInstantSearch, InstantSearch
```
```
AlgoliaHighlighter(Highlight)
```

Are there any plans to handle this so the warnings go away?

**Comment by francoischalifour** [comment]
We released a new beta version `6.0.0-beta.0` with support for the upcoming React 17. You can read more about it on [Discourse](https://discourse.algolia.com/t/react-instantsearch-v6-beta-0-released/8308/).

Try installing it and let us know how it goes!

**Comment by husseinbob** [comment]
Which branch in the repo should I be looking at for this? thanks

**Comment by Haroenv** [comment]
the branch is called `next`: https://github.com/algolia/react-instantsearch/tree/next
