### ISSUE TITLE
Refining hits with facet filters react native instasearch?

### ISSUE THREAD

**Issue by developerk786** [algolia/react-instantsearch#2848]
I am using react native instasearch and in my case, I need to refine results but with facet filters
for eg: 
```JavaScript
{
  query: "Shoe",
  facets: "category:jordan",
}
```

how can I achieve this using react native instasearch
also, i need to pass initial category
for eg: **i want to search only Jordan shoes** in spite of all shoes when i go to the search screen

**Code**

```JavaScript
...
import { connectInfiniteHits, connectSearchBox } from "react-instantsearch/connectors"
...

class Products extends Component<Props, {}> {
  render() {
    let algolia = {}
    if (this.props.navigation) {
      algolia = this.props.navigation.getParam("algolia")
    } else {
      algolia = this.props.algolia
    }

    /* algolia object looks like this
       {
          filters: "category:jordan"
       }
    */

    return (
      <Block flex={1} color="gray3">
        <InstantSearch
          appId="[APP_ID]"
          apiKey="[API_KEY]"
          indexName="[INDEX_NAME]"
          // so that when user visits this screen he/she will search only jordan shoes
          initialParams={{ filters: "category:jordan" }}
        >
          <SearchBox
            // i am passing this variable so that i can use it for refining in search box
            algolia={algolia}
          />
          <Results />
        </InstantSearch>
      </Block>
    )
  }
}

const SearchBox = connectSearchBox(
  ({ refine, algolia }) => {
    console.log(algolia) // i am receiving this
    const onChangeText: (query: string) => {
      // currently working but searching in all documents
      refine(query)
      // what i want
      refine(query, {
        // this object will come from parent as algolia prop
        filters: "category:jordan"
      })
    }

    return (
      <Block>
         <TextInput onChangeText={onChangeText} />
      </Block>
    )
  },
)

// Infinite component
const Results = connectInfiniteHits(({ hits, hasMore, refineNext }) => {
  const onEndReached = () => {
    if (hasMore) {
      refineNext()
    }
  }

  const renderRow = ({ item }: { item: IProduct }) => <Product product={item} />

  return (
    <FlatList
      showsVerticalScrollIndicator={false}
      data={hits}
      numColumns={2}
      keyExtractor={keyExtractor}
      onEndReached={onEndReached}
      onEndReachedThreshold={0.3}
      renderItem={renderRow}
      columnWrapperStyle={{
        justifyContent: "space-between",
        paddingHorizontal: SCREEN_WIDTH * 0.025,
      }}
      contentContainerStyle={{
        paddingBottom: 100,
      }}
    />
  )
})

```

**Comment by Haroenv** [comment]
Hi @developerk786,

The guide: https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/#apply-default-value-to-widgets should apply to your use case well:

```js
import algoliasearch from 'algoliasearch/lite';
import {
  InstantSearch,
  connectSearchBox,
  connectRefinementList,
  connectHits,
} from 'react-instantsearch-native';

const searchClient = algoliasearch(
  'xxx',
  'xxx'
);

const RefinementList = connectRefinementList(() => null);
const SearchBox = connectSearchBox(() => {
  // ...
});
const Hits = connectHits(() => {
  // ...
});

const App = () => (
  <InstantSearch indexName="instant_search" searchClient={searchClient}>
    <SearchBox defaultRefinement="Shoe" />
    <RefinementList attribute="category" defaultRefinement="jordan" />
    <Hits />
  </InstantSearch>
);
```

**Comment by developerk786** [comment]
Thanks, @Haroenv dude that's what i am exactly looking for. But what about more **complex logics** how to handle that,
let say:
I use some logic to calculate favourite products of any customer
let say 
```JavaScript
[productID1, prouctID2.....productID10....productID(Nth)]
```
i want to apply filters, limit, sort by, infinite hits and other cool algolia features only in those products how am i supposed to do it is there any way around?

**Comment by Haroenv** [comment]
@developerk786, this is the most straightforward way of doing it. If you are also displaying the filters, then you should render the values inside the connector (instead of null, what i replied to you). 

There's also the Configure widget for filtering by plain search parameters.

I'm not too sure what you want to calculate based on product IDs, can you clarify?

**Comment by developerk786** [comment]
This question should be in new thread/issue, but i am asking here,
let say i have 10,000 products in my MongoDB database and all are synced up with algolia.
let say i want only Jordan shoes =>
in algolia, i can do, 
```JavaScript
{ filters: "category:Jordan" }
```
but let say these filters are not suitable for the type of data i want to get for example if i want to fetch top products of any customer based on his activity of viewing products, then i cannot apply that logic via algolia query/filters so i need to apply that logic in my own server.
now let's say my server returns 500 products that are top picks for a particular customer.

now i have 500 products and i want to apply same algolia filters to those products like sort them by price, filtering by category, etc. etc.

how can i do that?

**Comment by Haroenv** [comment]
You will need to transform that to an Algolia query. You can do something like a RefinementList on `attribute="objectID"` (with default refinement being all the selected items), but that eventually will get to the limit of filters (IIRC it's 1000), so you'll need to be more clever with it and change your index every time someone favorites to add their id to a list in the record itself and filter on that. 

If that is still too long for the record, you'll need to do some more advanced logic to mix the two options & group users in advance.

I'll close this issue now since your original question is solved.
