### ISSUE TITLE
Error trying compile react-instantsearch with webpack and babel 7 

### ISSUE THREAD

**Issue by lleonesouza** [algolia/react-instantsearch#2855]
Error trying compile react-instantsearch with webpack and babel 7 

(function (exports, require, module, __filename, __dirname) { export default function _classCallCheck(instance, Constructor) {
                                                              ^^^^^^
SyntaxError: Unexpected token export

**To Reproduce 🔍**

1- SetUp WebPack for React with @Babel 7

webpack: 
```
 options: {
                    presets: [
                        ["@babel/env",
                            {
                              "useBuiltIns": "entry",
                              targets: {browsers: [
                                  '>1%',
                                  'not ie 11',
                                  'not op_mini all'
                                ]}
                            }
                          ], "@babel/react"
                    ],
                    "plugins": [
                        [
                          "@babel/plugin-proposal-class-properties",
                        ]
                    ]
                }
```

2. Try import anything from 'react-instantsearch-dom' inside a component;
such as : 
import {InstantSearch } from 'react-instantsearch-dom'

3. try to compile to Bundle.js and see the error: 

```
(function (exports, require, module, __filename, __dirname) { export default function _classCallCheck(instance, Constructor) {
                                                              ^^^^^^
SyntaxError: Unexpected token export
```

**Screenshots 🖥**

![Sem título](https://user-images.githubusercontent.com/55259670/66580108-3c1fad80-eb54-11e9-8d1e-a9292df824f4.png)

**Environment:**

 - OS: windows 10
 - Browser chrome
 - Version latest

**Comment by Haroenv** [comment]
Can you provide the project on GitHub please? These screenshots aren’t enough information to debug. React InstantSearch works with Babel 7 & webpack, since that’s what we use in our examples.

**Comment by lleonesouza** [comment]
@Haroenv thanks for the answer dude, i dont know whats was happening but its just working now. make sure to close this issue

**Comment by Haroenv** [comment]
All right, glad you found the issue, sorry I couldn’t help
