### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded in connectStateResults

### ISSUE THREAD

**Issue by janosh** [algolia/react-instantsearch#2867]
**Describe the bug 🐛**

The following error is thrown when React updates [my `Search` component](https://github.com/janosh/janosh.io/blob/master/src/components/Search/index.js) in development. No problems [in production](https://janosh.io/blog) as far as I can tell.

```js
index.js:37 Uncaught RangeError: Maximum call stack size exceeded
    at keys (<anonymous>)

The above error occurred in the <AlgoliaStateResults(UnknownComponent)> component:
    in AlgoliaStateResults(UnknownComponent) (created by Context.Consumer)
```

<details>
<summary>Full stack trace</summary>

```
in AlgoliaStateResults(UnknownComponent) (created by Context.Consumer)
in ConnectorWrapper (at Search/index.js:52)
in Index (created by Context.Consumer)
in IndexWrapper (at Search/index.js:47)
in div (created by Context.Consumer)
in StyledComponent (created by styles__HitsWrapper)
in styles__HitsWrapper (at Search/index.js:45)
in InstantSearch (at Search/index.js:39)
in div (created by Context.Consumer)
in StyledComponent (created by styles__Root)
in styles__Root (at Search/index.js:38)
in Search (at Header/index.js:21)
in header (created by Context.Consumer)
in StyledComponent (created by styles__HeaderContainer)
in styles__HeaderContainer (at Header/index.js:14)
in Header (at Global/index.js:40)
in MDXProvider (at Global/index.js:36)
in ThemeProvider (at Global/index.js:35)
in Global (at page.js:13)
in PageTemplate (created by HotExportedPageTemplate)
in AppContainer (created by HotExportedPageTemplate)
in HotExportedPageTemplate (created by PageRenderer)
in PageRenderer (at json-store.js:93)
in JSONStore (at root.js:51)
in RouteHandler (at root.js:73)
in div (created by FocusHandlerImpl)
in FocusHandlerImpl (created by Context.Consumer)
in FocusHandler (created by RouterImpl)
in RouterImpl (created by Context.Consumer)
in Location (created by Context.Consumer)
in Router (created by EnsureResources)
in ScrollContext (at root.js:64)
in RouteUpdates (at root.js:63)
in EnsureResources (at root.js:61)
in LocationHandler (at root.js:119)
in LocationProvider (created by Context.Consumer)
in Location (at root.js:118)
in Root (at root.js:126)
in MDXProvider (at wrap-root-element.js:65)
in MDXScopeProvider (at wrap-root-element.js:64)
in Unknown
in Unknown (at wrap-root-element.js:72)
in _default (at app.js:67)

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```
</details>

I was able to narrow the cause down to this state connector:

```js
const Results = connectStateResults(
  ({ searchState: state, searchResults: res, children }) =>
    res && res.nbHits > 0 ? children : `No results for '${state.query}'`
)
```

which wraps the hits component

```js
<Results>
 <Hits hitComponent={hitComps[hitComp](() => setFocus(false))} />
</Results>
```

I don't understand what exactly the problem is. This component used to work fine for a long time. It may be related to a recent upgrade to `react-instantsearch-dom@.0.0-beta.2`

**Environment:**

 - OS: macOS
 - Browser: Chrome
 - Version: 78

**Comment by Haroenv** [comment]
I think this might be a duplicate of https://github.com/algolia/react-instantsearch/issues/137, could you try the suggested solutions there? Ideally could you also make a reproduction on a sandbox? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by janosh** [comment]
@Haroenv Thanks for the pointer. I tried [this](https://github.com/algolia/react-instantsearch/issues/137#issuecomment-349385276) and [this](https://github.com/algolia/react-instantsearch/issues/137#issuecomment-354343777) suggestion but in both cases the issue persisted.

I also tried setting up a [code sandbox](https://codesandbox.io/s/react-instantsearch-app-l0nor) but keep running into an odd CORS error. Maybe you know how to resolve that?

**Comment by janosh** [comment]
@Haroenv Never mind, managed to resolve the issue by [refactoring `Results` and `Hits` to be siblings rather than parent and child](https://github.com/janosh/janosh.io/commit/54987289dc02fd3fb996ed646b53be011ff98ac6#diff-385902f1d7347e40bd6f8b8ced7eea25R48).

**Comment by Haroenv** [comment]
Sorry I missed your response, but the nesting indeed can cause issues, which can be fixed by avoiding nesting. The issue I linked tracks that behaviour, but for now we can not see a workaround or solution for it unfortunately.
