### ISSUE TITLE
Add react hooks

### ISSUE THREAD

**Issue by GriffinSauce** [algolia/react-instantsearch#2870]
**Problem:**

Connector HOCs add boilerplate and can be unwieldy. When you have an existing component already the modification to make it connected is a hassle. It also interferes with Flow type-checks because it adds "invisible" props and is hard to compose when you need multiple things.

For example:

```.jsx
// Base component
const Title = () => {
  return <h1>Search results</h1>;
};

// With results
import { connectStateResults } from "react-instantsearch/connectors";
const Title = ({ searchResults }) => {
  return <h1>{searchResults.hits.length} search results</h1>;
};
export default connectStateResults(Title);
```

Redacted from these examples is Flow type checking and our styles HOC that makes it even more messy.

**Solution:**

React hooks offer a more encapsulated and concise way to do this:

```.jsx
// With results from hook
import { useStateResults } from "react-instantsearch/hooks";
const Title = () => {
  const searchResults = useStateResults();
  return <h1>{searchResults.hits.length} search results</h1>;
};
export default Title;
```

It is also much easier to deal with composing multiple things like results _and_ searchState:
```.jsx
// With results and searchState from hook
import { useStateResults, useSearchState } from "react-instantsearch/hooks";
const Title = () => {
  const searchResults = useStateResults();
  const searchState = useSearchState();
  return <h1>{searchResults.hits.length} search results for {searchState.query}</h1>;
};
export default Title;

// Or alternatively in one:
import { useSearch } from "react-instantsearch/hooks";
const Title = () => {
  const { searchState, searchResults } = useSearch();
  return <h1>{searchResults.hits.length} search results for {searchState.query}</h1>;
};
export default Title;
```

This seems like a small change but having the Algolia parts decoupled from the props and export makes a big difference in aggregate.

**Comment by tkrugg** [comment]
Hi @GriffinSauce, thank you, I appreciate you taking the time to give us feedback. 
This is likely something we'll work on in the future but I can't give an ETA, but  it's nice to hear from the community about it.
I'll close this as it's already tracked by our internal project tracking tools.

**Comment by coreyward** [comment]
I'm rather disappointed that Algolia has completely abandoned keeping progress with React. Hooks came out a year ago and are resolve significant pain points. As a senior freelance engineer that has a lot of weight in the technology decisions of startups, I'm unlikely to recommend Algolia any further as a result of this.

**Comment by Haroenv** [comment]
We take this kind of feedback seriously Corey, so thanks for bringing it up again! 

We have it in our plans to make a refresh with hooks included, but it’s not straightforward to decide which api is nice to use with hooks compared to what we have now. 

StateResults is indeed a good one to start with exposing, but do you have an idea what you’d like to use? 

We are all ears

**Comment by GriffinSauce** [comment]
@coreyward this is the hook I ended up building for us:
https://gist.github.com/GriffinSauce/0451d328511b4e82469f4e9f688e5118

You can dump the return into the context provider and use the extra hook to grab those again down the tree. That's a super easy way to connect stuff up, you could probably make one hook to both (initialise / grab whatever is already there) but I like the explicit nature of these.

This works for us, it might not fit your context but maybe it helps. Let me know if you end up using it and see any possible improvements. :)

@Haroenv it could help to start small, as you can see from ours we really just need results, loading state and changing the search.

**Comment by coreyward** [comment]
@Haroenv  My use case is relatively simple, effectively a straightforward instant search page with a search input and some little search result tiles. Single index, no facets, no pagination, etc. I ultimately did the same as @GriffinSauce and simply integrated directly using `algoliasearch/lite`.

Here's what my integration looks like (slightly simplified, but this is the bulk of the logic):

```jsx
import React from "react"
import algoliaClient from "algoliasearch/lite"
import debounce from "lodash-es/debounce"

const algolia = algoliaClient(
  process.env.ALGOLIA_APP_ID,
  process.env.ALGOLIA_SEARCH_KEY
).initIndex("pages")

const search = (query, params = {}) =>
  algolia.search(query, {
    attributesToHighlight: null,
    hitsPerPage: 60,
    ...params,
  })

const Search = () => {
  const [loading, setLoading] = useState(false)
  const [results, setResults] = useState([])
  const [query, setQuery] = useState("")

  const updateResults = useCallback(
    debounce(currentQuery => {
      search(currentQuery).then(({ hits }) => {
        setResults(hits)
        setLoading(false)
      })
    }, 250),
    []
  )

  const handleChange = useCallback(
    e => {
      setQuery(e.target.value)

      if (e.target.value.length > 0) {
        setLoading(true)
        updateResults(e.target.value)
      } else {
        setLoading(false)
      }
    },
    [updateResults]
  )

  return (
    <div>
      <input type="search" onChange={handleChange} />
      {results.length > 0 ? (
        <Results results={results} />
      ) : (
        query.length > 0 && !loading && (
          <div>No results</div>
        )
      )}
    </div>
  )
}
```

As you can see, there's not much needed, but it would be much preferred if this type of approach worked instead, though:

```jsx
import React from "react"
import { useSearch } from "react-algolia-search"

const Search = () => {
  const { query, results, loading, setQuery } = useSearch(
    process.env.ALGOLIA_APP_ID,
    process.env.ALGOLIA_SEARCH_KEY
  )

  return (
    <div>
      <input type="search" onChange={e => { setQuery(e.target.value) }} />
      {results.length > 0 ? (
        <Results query={query} results={results} />
      ) : (
        loading
          ? "Loading…"
          : query.length > 0 && `No results for “${query}”.`
      )}
    </div>
  )
}
```

Obviously you could add additional fields and params to this to accept additional params, tune the debouncing (the lack of any debouncing in the existing React InstantSearch is super wasteful), and so on.

**Comment by ItsWendell** [comment]
I'd love to see this too, I've written a handful of components for React Native that use the connectors, but the job would be so much easier done with Hooks, also type safety would be easier to manage.

**Comment by vvo** [comment]
Just chiming in too, I am one of the developers to blame here: I did not see hooks coming when I was working at Algolia mostly because I was not building enough real world React apps to see that hooks were everywhere in the ecosystem.

Now that I am heavy in building a real world React app and using many other libraries, I can see it clearly: hooks are everywhere and yes it would be awesome to be able to use hooks to build an Algolia experience.

Even if it starts very lightly at first like the proposal from @coreyward, it would be awesome!

**Comment by nandorojo** [comment]
I wrote my own hook using Vercel's `swr` as the fetching mechanism under the hood.

```ts
import { SearchResponse } from '@algolia/client-search'
import { useState, useEffect } from 'react'
import useSWR, { ConfigInterface, responseInterface } from 'swr'
import { algolia } from '../server/algolia/algolia-client'

export const useSearchState = () => {
  const [query, setQuery] = useState('')

  return {
    query,
    setQuery,
  }
}

type Options = {
  facets?: string[]
  index?: string
}

type Returns<T> = responseInterface<
  SearchResponse<AlgoliaHit<T>> | undefined,
  unknown
>

type AlgoliaHit<T> = T & { _highlightResult?: HighlightResult<T> }

type HighlightResult<T> = {
  [key in keyof T]?: {
    value?: string
    matchLevel?: 'none' | 'full'
    matchedWords?: string[]
    fullyHighligted?: boolean
  }
}

export function useAlgoliaSearch<T>(
  query: string,
  options: Options = {},
  swr: ConfigInterface<SearchResponse<AlgoliaHit<T>>> = {}
): Returns<T> {
  const { index, facets } = options

  const makeSWRKey = ({
    query,
    facets,
    index,
  }: {
    query: string
    facets?: string[]
    index?: string
  }) => {
    return ['algolia-search', query, index, JSON.stringify(facets)]
  }
  const response = useSWR(
    () => makeSWRKey({ query, facets, index }),
    async (
      ...[
        _,
        query = '',
        index = 'artists', // Defaulted to my typical index
        facetString,
      ]: ReturnType<typeof makeSWRKey>
    ) => {
      const facets = facetString ? JSON.parse(facetString) ?? [] : undefined
      const results = await algolia
        .initIndex(index)
        .search<AlgoliaHit<T>>(query, {
          facets,
        })
      return results
    },
    {
      refreshInterval: 0,
      refreshWhenHidden: false,
      ...swr,
    }
  )

  return response
}
```

And then in my screen:

```tsx
type Artist = {
  name: string
}

const { query, setQuery } = useSearchState()
const { data, error } = useAlgoliaSearch<Artist>(query)

if (error) return <Text>Error...</Text>

if (!data) return <Text>Loading...</Text>

return data.hits.map(({ name, objectID }) => <Text key={objectID}>{name}</Text>)
```

**Comment by Haroenv** [comment]
this is really interesting for non-faceting use cases, thanks @nandorojo

**Comment by nandorojo** [comment]
@Haroenv I did include facets too.

```js
const { data, error } = useAlgoliaSearch<Artist>(query, {
  facets: ['genre', 'popularity']
})
```

**Comment by Haroenv** [comment]
Yes, what I meant is not that your implementation is lacking, but that it doesn't have individual pagination, refinement list etc. widgets / imports. That's totally expected of course from a just new project.

**Comment by nandorojo** [comment]
@Haroenv Makes sense. I'll probably use `useSWRInfinite` to handle infinite scrolling as my project expands. It wouldn't be too hard to add pagination to my current hook above, too.

**Comment by nandorojo** [comment]
@Haroenv any idea how I could implement a refinement list with hooks? I'm not sure how to even fetch the list of possible refinements via the JS SDK directly. Does it require that I use the context from the Algolia react provider?

**Comment by Haroenv** [comment]
We rely on the [helper](https://github.com/algolia/algoliasearch-helper-js) for doing requests which need multiple queries, e.g. for disjunctive facet count. You can look at the code for `connectRefinementList` on how we use it.

**Comment by otusweb** [comment]
For those searching for a solution, I found: https://www.npmjs.com/package/use-algolia

**Comment by mikefisher84** [comment]
I must say it's a little disappointing that this ticket was opened in 2019 and here we are in 2021 with no solution from Algolia yet. I can't think of any popular React based library in 2021 that doesn't have a hooks implementation, let alone a commercial product.

**Comment by tiagosatur** [comment]
Would be nice to have a roadmap from the algolia team. Because from where I see, hooks should be in the higher priority position. Right now I'm in a situation where I need to connect the same component twice (connectStateResults, connectPagination) and I'm giving up implementing this, the only way out is repeating the code.

**Comment by kobeaerts** [comment]
@tkrugg @vvo Can we get any update on this issue? I'm really liking Algolia, I'm also paying quite some money for it so it would be really nice if you guys give us an update!

**Comment by Kerim-Willem** [comment]
I agree. It would be nice if you can give an update on the matter @Algolia!

**Comment by francoischalifour** [comment]
Hey folks! Happy to say that we've started planning and scoping the work for introducing Hooks to React InstantSearch. This will be one of our main projects starting in a few weeks. We'll need to restructure our core codebase so we'll likely introduce them with an incremental feature set, tagged as alpha/beta at first (to be determined!).

We'll communicate more once this is available for use.

**Comment by francoischalifour** [comment]
@ivasilov For now you should be able to use Next's [Dynamic Import](https://nextjs.org/docs/advanced-features/dynamic-import). We're making this issue a priority and we'll let you know once this is fixed.

**Comment by cmaycumber** [comment]
> @ivasilov For now you should be able to use Next's [Dynamic Import](https://nextjs.org/docs/advanced-features/dynamic-import). We're making this issue a priority and we'll let you know once this is fixed.

Do you have any examples of this by any chance? I'm having trouble getting the workaround working.

**Comment by Haroenv** [comment]
We have fixed this in pull requests on React InstantSearch & InstantSearch.js, but not yet released due to less people being available for the holidays. Will be done in early january

**Comment by francoischalifour** [comment]
React InstantSearch Hooks [**v6.19.0**](https://github.com/algolia/react-instantsearch/releases/tag/v6.19.0) is now compatible with Next.js out of the box. Give it a try and [let us know how it goes](https://github.com/algolia/react-instantsearch/discussions)!

(cc @schoenwaldnils @ivasilov @cmaycumber)

**Comment by francoischalifour** [comment]
We're super excited to announce that **[React InstantSearch Hooks](https://algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react-hooks/) is now available for wider use**.

React InstantSearch Hooks provides the power of [InstantSearch.js](https://algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/) with a thin React compatibility layer. You get to use [React Hooks](https://reactjs.org/docs/hooks-intro.html) to power your search experience.

You can find more on the Algolia documentation:

- [What is React InstantSearch Hooks?](https://algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react-hooks/)
- [Installation](https://algolia.com/doc/guides/building-search-ui/installation/react-hooks/)
- [Server-side rendering](https://algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/)
- [API reference](https://algolia.com/doc/api-reference/widgets/react-hooks/)

Check out the [live example](https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/hooks) to play with the library.

Consider using React InstantSearch Hooks **if your app isn’t meant to be production-ready** yet, and:

- you have an existing React InstantSearch application that mainly relies on InstantSearch connectors,
- or you’re creating a new InstantSearch application with React.

Eventually, React InstantSearch Hooks is planned to become the main React implementation of InstantSearch.js.

[Keep us updated](https://github.com/algolia/react-instantsearch/discussions) with the awesome search experiences you build!

**Comment by cohandy** [comment]
@francoischalifour do you have an ETA on when the hooks library will be stable enough for production?

**Comment by Haroenv** [comment]
We are currently in the process of implementing the individual components, during that time some restructuring may still be needed, but overall we are confident of the mechanisms on top of which React InstantSearch Hooks works. Once the components are done, and we have a solid set of feedback from users, we can mark it as stable.
