### ISSUE TITLE
What's the official way of customizing labels in a <RefinementList/>?

### ISSUE THREAD

**Issue by catamphetamine** [algolia/react-instantsearch#2873]
Suppose there's a list of ingredients and each of them is used in some recipe.
So there's an `<InstantSearch index="ingredients"/>` widget for ingredients, and a user can filter by recipes the ingredients are used in.
So there's a `<RefinimentList attribute="recipes"/>` filter widget.
In order for that to work, an ingredient has to have a shape: `{ recipes: ['Coffee', 'Apple pie', ...] }`.
But suppose an application goes multi-lingual.
What's the official way of customizing those labels in a `<RefinimentList/>` widget?
For example, maybe it's better for an ingredient to have a shape `{ recipes: [123, 789, ...] }`, and then somehow print labels for those `id`s in the UI.

The official docs have some `transformItems` property with a very unparticular example of uppercasing all labels.
https://www.algolia.com/doc/api-reference/widgets/refinement-list/react/#widget-param-translations
What about something like this:

```js
<RefinementList
  // ...
  transformItems={items =>
    items.map(item => ({
      ...item,
      label: somehowGetRecipeNameById(item.value),
    }))
  }
/>
```

Would it be the official way to do it?

Having a `somehowGetRecipeNameById(id)` is another thing: obviously it can't query the servers and has to use the data already present in Algolia response.
So it has to reuse the Algolia object of an `item` somehow.
Something like having an ingredient of shape: `{ recipes: [123, 789, ...], recipeLabelsEn: ['Coffee', 'Apple pie', ...], recipeLabelsRu: ['Кофе', 'Яблочный пирог', ...] }` and then somehow getting `recipeLabelsEn`/`recipeLabelsRu` from `item` in that `transformItems` function (I suppose the `index` would be the actual index of the value in the array so that it could be used to get the label).

**Comment by tkrugg** [comment]
Hi @catamphetamine  `transformItems` does not support returning promises. 
What I would do is load all the labels upfront if their number is reasonably low. Usually people would use include their labels in a their i18n bundle, and so they don't need to make an async call after.

**Comment by catamphetamine** [comment]
@tkrugg So do you confirm that using `transformItems` is the officially recommended way of storing `id`s instead of labels in an Algolia object and then printing labels instead of `id`s in a `<RefinementList/>` widget? That could be included on the docs page, because it's a fairly common use case for any multi-lingual project, or a complex enough one.

> `transformItems` does not support returning promises.

I wasn't talking about promises.
If you re-read my comment, there I'm saying that loading labels in `transformItems` could not be an acceptable solution.
What I was talking about is that `transformItems` has to get access to the Algolia object of an `item` somehow.
Suppose there's an ingredient of shape: 

```js
{ 
  recipes: [123, 789, ...], 
  recipeLabelsEn: ['Coffee', 'Apple pie', ...], 
  recipeLabelsRu: ['Кофе', 'Яблочный пирог', ...] 
}
```

Then `transformItems` must somehow get access to `recipeLabelsEn`/`recipeLabelsRu` from the `item` argument of `transformItems` function.
Then, by using `(item, index)` arguments it could get the label:

```js
transformItems((item, i) => {
  return {
    ...item,
    label: somehowGetAlgoliaObjectForItem(item).recipeLabelsEn[i]
  }
})
```

Can it do that?

**Comment by tkrugg** [comment]
@catamphetamine putting it simply, no.
What you can do however is this:
```
const labelsEn = {
   123: 'Coffee',
   789: 'Apple pie'
} 

const labelsRu = {
   123: 'Кофе',
   789: 'Яблочный пирог'
}

transformItems((item, i) => {
  return {
    ...item,
    label: labelsEn[item.value]
  }
})

```

**Comment by catamphetamine** [comment]
@tkrugg I see.
So the official solution would be doing a separate [`browseIndex()`](https://www.algolia.com/doc/api-reference/api-methods/browse/) call on the search page before it loads.
That would introduce an additional latency and the user experience would suffer as a result.
I've measured `browseIndex()` for an index of 200 items and the latency is about 200 milliseconds.
That's a lot.
The only possible solution would be the server pre-computing such an index without Algolia's involvement and then storing it as a JSON file somewhere on disk so that an API call would return that JSON file contents.
That would still be extra latency and a penalty for user experience.

**Comment by Haroenv** [comment]
That's possible, but the ideal way without extra latency is the following:

1. denormalize your facet value `café~Кофе`
2. split within transformItems
3. display only the relevant item

This will have two downsides

1. you need to also have this full value in the URL
2. Search for Facet values might not work as expected

The reason is that a facet is a _value_, not a whole object. That thus also means that a facet is a single item and won't have access to other attributes

**Comment by adenta** [comment]
Is the above still the recommended strategy for tackling this? Seems like this must be a pretty common problem
