### ISSUE TITLE
Geosearch with Configure's aroundLatLng

### ISSUE THREAD

**Issue by youjinp** [algolia/react-instantsearch#2876]
I'm having an issue implementing a simple feature with Geosearch.

This is a simplified version of it:
![Screen Shot 2019-11-28 at 7 28 40 PM](https://user-images.githubusercontent.com/15708500/69782410-d37cb500-1215-11ea-93e9-12c5a1736633.png)

This is the issue I'm having:
- when entering latitude and longitude and pressing submit, everything works and results are shown
- **after moving the map around with search enabled as the map is moved**, entering latitude and longitude and pressing submit no longer works

Here is the code: https://codesandbox.io/s/places-je5xw

**Comment by francoischalifour** [comment]
For the map to be reactive, you'll need to use the options [`searchState`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-searchstate) and [`onSearchStateChange`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-onsearchstatechange).

You can read [our routing guide](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/#before-we-start) that leverages this API and get inspiration in the [tourism demo](https://github.com/algolia/react-instantsearch/blob/master/examples/tourism/URLSync.js).

**Comment by youjinp** [comment]
got it, thanks!
