### ISSUE TITLE
How to clear search and hits when selecting a hit

### ISSUE THREAD

**Issue by deanc** [algolia/react-instantsearch#2885]
I have a simple-use case which I presumed would be the most common, and documented.

I have a custom `hitComponent`:
```
const SearchResult = ({ hit }) => {
  return (
    <div>
      <Link to={`/q/where-to-buy-${hit.slug}-in-finland`}>
        <Highlight attribute="name" hit={hit} />
      </Link>
    </div>
  )
}
```
I render like so:
```
      <InstantSearch
        indexName="items"
        searchClient={searchClient}
      >
        <SearchBox />
        <Hits hitComponent={SearchResult} />
      </InstantSearch>
```

The problem is because the `InstantSearch` component is rendered outside of route changes in my react app, it's not re-rendered, and the search and the results are left in tact. I read a little about searchState but I don't want to add redux as a dependency for now to try and share that state, so how can I ensure when clicking on a search result (a hit) i will reset the search query to empty and therefore clear the results.

I have spent at least two hours reading through the docs and API reference to find a simple solution to this. Might be worth putting whatever the solution is in the current documentation.

**Comment by francoischalifour** [comment]
If I understand correctly, you want to update the search state within your `Hit` component but you do not have access to the setter.

You can pass several props to the `Hit` component via multiple React features. Here's one solution using `React.useRef`:

```js
function SearchResult(props) {
  return (
    <article
      onClick={() => {
        props.setSearchState({
          ...props.searchState,
          query: '',
        });
      }}
    >
      <h1>
        <Highlight attribute="name" hit={props.hit} />
      </h1>
    </article>
  );
}

function App() {
  const [searchState, setSearchState] = React.useState({});
  const Hit = React.useRef(props => (
    <SearchResult
      {...props}
      searchState={searchState}
      setSearchState={setSearchState}
    />
  ));

  return (
    <InstantSearch
      searchClient={searchClient}
      indexName="instant_search"
      searchState={searchState}
      onSearchStateChange={setSearchState}
    >
      <RefinementList attribute="brand" />
      <SearchBox />
      <Hits hitComponent={Hit.current} />
    </InstantSearch>
  );
}
```

Closing this issue – feel free to reopen if you need more help.

**Comment by deanc** [comment]
@francoischalifour Thank you. This met my requirements. I have another requirement which will allow my users to select a hit to populate a field before submit. Autocomplete functionality. Your code above also allowed me to do this by setting the `searchState.query` to the `hit.name` but unfortunately the hits are then still open - not the desired effect. Is it possible to set some property of `searchState` to forcibly hide the hits until another keystroke arrives?
