### ISSUE TITLE
"refresh" on <InstantSearch> doesn't get new results

### ISSUE THREAD

**Issue by rossfishkind** [algolia/react-instantsearch#2886]
**Describe the bug 🐛**
Utilizing the `<InstantSearch>` component, I am toggling the `refresh` prop whenever I add new objects to Algolia. I noticed that nothing seemed to be happening, so I checked the network tab to see the request.

It would seem that when returning the results, the new object(s) are missing entirely. I have double and triple-checked that the objects are added and then the refresh is executed, but nonetheless, no new results.

When I fully reload my page, the results pop in - so I'm imagining there is possibly a problem with my local algolia cache... (I should mention I have my cache disabled on the network tab)

**To Reproduce 🔍**

1. Add objects to your Algolia instance on the server-side
2. Trigger a refresh on the `<InstantSearch>` component

**Expected behavior 💭**

The results returned from Algolia should contain the new objects.

**Environment:**

 - OS: Mac
 - Browser: Chrome
 - Version: 79.0.3945.88

**Comment by Haroenv** [comment]
could this be related to #2742? Are you using infinite hits? If not, could you please make a sandbox, you can start from this: [template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!
