### ISSUE TITLE
React Instant Search range slider using outdated Rheostat package and doesn't support automatically calculated min, max values 

### ISSUE THREAD

**Issue by NethanjanInt** [algolia/react-instantsearch#2889]
**Describe the bug 🐛**
In your [range slider documentation](https://www.algolia.com/doc/api-reference/widgets/range-slider/react/) you are still giving a Rheostat (version 2.x.x)  example. 
And in the documentation you have mentioned that 

> The minimum value for the input. When not provided, the minimum value is automatically computed by Algolia from the data in the index

Yet with Rheostat automatically calculated min, max values are incompatible. It always require initial min max values. I have used the same example you have documented. 

I'm currently using this [example](https://www.algolia.com/doc/api-reference/widgets/range-slider/react/#full-example). 

**Expected behavior 💭**
Currently Rheostat has a version 4.x, so if you can update the documentation it would be helpful. Otherwise if you can point out what I can do to customize existing example for automatic min, max calculation, that would be helpful too.

**Comment by Haroenv** [comment]
We have used v2.x in the documentation because the class names were stable. Is this something which is fixed in v4? 

Can you make a sandbox of what you have so far with v4, so we can take a look?  We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by NethanjanInt** [comment]
Hi,

I have added the price range [here](https://codesandbox.io/s/stupefied-stonebraker-w6exq) as requested. Under refine list there's a price panel and you can click on the slider pop (sorry about the styles) and you will see slider min max values. 

This seems to be working however for me same code is not working in my local environment. For me slider is not displaying until I use min max props. Is there any configuration should I do in algolia index? 

Thanks!

**Comment by Haroenv** [comment]
In your index, did you make sure the attribute is numeric (i.e. no strings, but numbers)?

**Comment by NethanjanInt** [comment]
Yes price attribute is numeric. I'm trying this with Algolia community plan. Could that be a problem? 
 
>We have used v2.x in the documentation because the class names were stable. Is this something which is fixed in v4?

What's the exact problem with class names? I may be able to help.

**Comment by NethanjanInt** [comment]
Found the issue it's with community plan of ALgolia. Tried the same with trail plan it's working fine.
