### ISSUE TITLE
Update array of nested objects!!

### ISSUE THREAD

**Issue by developerk786** [algolia/react-instantsearch#2896]
let say i have an object with this shape:
```javascript
{
  name: "Men Black ZOOM WINFLO 6 Running Shoes",
  variations: [{
    id: 1,
    color: 'red',
    sizes: [{
      id: 1,
      name: "S",
      quantity: 5
    }, {
      id: 2,
      name: "M",
      quantity: 5
    }]
  }, {
    id: 1,
    color: 'blue',
    sizes: [{
      id: 1,
      name: "S",
      quantity: 5
    }, {
      id: 2,
      name: "M",
      quantity: 5
    }]
}]

```

Now let say customer made an order for ```blue``` ```S``` size shoe, now what is the best way to decrease  the quantity of **blue** colored **S** sized product by 1

**Comment by Haroenv** [comment]
For this you need to reindex, thus calling `saveObject` with the mutated version of the object in question. 

This issue doesn't seem too relevant to React InstantSearch, which API client or integration are you using to index the products to Algolia?

**Comment by developerk786** [comment]
I am using react-native-instasearch so basically what you are saying is:

update the whole object then send to aloglia server. 

```javascript
const product = { variations: [...]}
product.variations = ... // apply some logic to update quantity
algoila.partialSaveObject(product)
```
like this insead going deep right..

**Comment by Haroenv** [comment]
Yes, that's correct, You can either give the whole updated object, or only the objectID, and the changed (root) attribute.

More information here: https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/?language=javascript
