### ISSUE TITLE
[react-native] Not able to wrap extended InfiniteHits in another View and InstantSearch

### ISSUE THREAD

**Issue by frankyjuang** [algolia/react-instantsearch#2898]
**Describe the bug 🐛**

Is it possible to wrap InfiniteHits in another View and InstantSearch? That is, the InifiniteHits is not a direct child of root InstantSearch. I know it's possible for refinements according to the guide https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react/. However, when I tried to apply the same way to InfiniteHits, the hits never changed. I can tell the search state is in sync by logging inside the extended InfiniteHits component.

**To Reproduce 🔍**

```jsx
  <InstantSearch
    indexName={indexName}
    onSearchStateChange={onSearchStateChange}
    searchClient={searchClient}
    searchState={searchState}
  >
    <View>
      <InstantSearch
        indexName={indexName}
        onSearchStateChange={onSearchStateChange}
        searchClient={searchClient}
        searchState={searchState}
      >
        <ExtendedInfiniteHits />
      </InstantSearch>
    </View>
  </InstantSearch>
```

**Expected behavior 💭**

InfiniteHits yields correct hits.

**Environment:**

react-native 0.61.5
react-instantsearch-core 6.3.0
react-instantsearch-native 6.3.0

**Comment by Haroenv** [comment]
I don't understand why you wrap InstantSearch inside InstantSearch. Can you explain how you expect this to work? 

A full code sample could help!

**Comment by frankyjuang** [comment]
Turns out that I totally misunderstood the doc. All fixed now!
