### ISSUE TITLE
Want to create separate search page with dynamic routing. Please, help with that

### ISSUE THREAD

**Issue by elmaraliyevdev** [algolia/react-instantsearch#2909]
I’ve used e-commerce demo. All widgets works fine, but there is one problem. For example i have a category “Category Name”. It works fine and displaying related hits. But when i copy the url localhost:3000/page-name/category-name/ and paste in other tab or just refresh the page it doesn’t show. I created separate search page not included in the App.js file like in the demo. Would appreciate any help.

Here is the link for the repo:

https://github.com/webzool/cosmicdomain

**Comment by eunjae-lee** [comment]
Hi there,
Thanks for reaching out to us.
Could you specify what kind of error message you got? (Maybe a screenshot of the error?)
And I tried to reproduce the error by myself, but didn't know what to do with your project.
Please tell me all the steps to reproduce the bug.
And if possible, it'd be greater if you can put into a small code sandbox with minimum code to isolate the issue from your business logic. ([Template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch))

**Comment by Haroenv** [comment]
I've made a PR which fixes your issues: https://github.com/webzool/cosmicdomain/pull/2
