### ISSUE TITLE
Get React ref to input element in SearchBox

### ISSUE THREAD

**Issue by ojeytonwilliams** [algolia/react-instantsearch#2910]
**Is your feature request related to a problem? Please describe 🙏**

I would like to be able to pass a React ref to a `SearchBox` in order to manage focus on its `form` element.

**Describe the solution you'd like 🤔**

`SearchBox` currently has 
https://github.com/algolia/react-instantsearch/blob/478346916ec176ba978576759eb5d5c37b0dc4ee/packages/react-instantsearch-dom/src/components/SearchBox.js#L85-L86

 which can be used to get at the ref attached to the input element:
https://github.com/algolia/react-instantsearch/blob/478346916ec176ba978576759eb5d5c37b0dc4ee/packages/react-instantsearch-dom/src/components/SearchBox.js#L253-L254

However, given that it doesn't appear in the documentation, I don't want to rely on it.

It would be great if this was made part of the api.

**Describe alternatives you've considered ✨**

I tried using `focusShortcuts`, but I want to use `/` to focus search and `?` as a separate shortcut.  Unfortunately the search box gets focused in both cases as `?` is `shift+/`.

I can create a custom component or use `connectSearchBox`, but the widget works perfectly out of the box - except for this one issue.

**Comment by Haroenv** [comment]
Hi @ojeytonwilliams, this indeed is a good use case. As a team we haven't yet decided which the best "official" replacement for this is (likely `inputRef`), or maybe ForwardRef.

In the mean time you can use this undocumented ref, knowing that we will remove it once we have made the replacement.

If you're up for the challenge, we'd also accept a PR to add `inputRef` (without the underscores) to the codebase.

Thanks!

**Comment by ojeytonwilliams** [comment]
Hey @Haroenv, sure thing!  The code change itself seems pretty easy, I'd just rename `__inputRef` -> `setInputRef`.  I'll see about adding tests, too.

I'm not sure how to update the docs, though.  Could you point me in the right direction?

**Comment by Haroenv** [comment]
I'd go with just `inputRef`, the setter seems not needed. The docs are unfortunately not open source, but I'll make sure it gets added once this is added
