### ISSUE TITLE
How do I use local state for RefinementList

### ISSUE THREAD

**Issue by abhirocks550** [algolia/react-instantsearch#2914]
I have created dropdown with list of Countries. Initially CustomRefinementList will be hidden.
  Once user Select the Country from the dropdown then selectedCountries will be updated.
  CustomRefinementList will have   defaultRefinement={this.state.selectedCountries}.

  When I select Unites States from Dropdown then CustomRefinementList with United States selected
  gets applied, when I uncheck it Australia is appearing.

 Can someone please help , what is wrong with below code?

  I have created codesandbox here ```https://codesandbox.io/s/proud-dream-v06y1?file=/src/App.js```

**Comment by yannickcr** [comment]
Seems like when you are unchecking the item in the `CustomRefinementList` you do not reset `this.state.selectedCountries` , so the `CustomRefinementList` is still displayed without any refinement.

What is the expected behavior when you uncheck a country from the `CustomRefinementList` ?

**Comment by abhirocks550** [comment]
> Seems like when you are unchecking the item in the `CustomRefinementList` you do not reset `this.state.selectedCountries` , so the `CustomRefinementList` is still displayed without any refinement.
> 
> What is the expected behavior when you uncheck a country from the `CustomRefinementList` ?

The Refinement should be cleared is the expectation.

**Comment by abhirocks550** [comment]
@yannickcr  that fixed the issue.

Now having another problem.

Let's say I selected United States from drop down and then selected India from drop down.

Now it is working for one refinement but again having same issue for other.

Will see what is going wrong here.

**Comment by abhirocks550** [comment]
When I am selecting India from drop-down the value for item that is coming is
```
{ count: 2
isRefined: false
label: "Australia"
value: (3) ["United States", "India", "Australia"] }
```

**Comment by Haroenv** [comment]
That's expected. The `value` of a refinementlist is _what things will apply once you click this item_. If India & US are currently checked, the next value for that button should be just US, since India gets toggled.

If you want to get access to just the value, it's the `label` (unless you change that during `transformItems`

**Comment by abhirocks550** [comment]
I am sorry maybe I could not get what you are saying.

Could you please let me know what changes I need to make so that it will work?

For example if I select the country from drop-down it should be added to filters and if I uncheck the checkbox then it should be removed.

I am trying to do so but looks like something is going wrong.

**Comment by Haroenv** [comment]
It's hard to know what you are talking about, but if you want something with only one refinement value possible, that's a Menu, not a refinementList. I've changed your example to use only widgets, and not own state, so you don't need to worry about keeping them in sync:

https://codesandbox.io/s/vibrant-pike-qs4el?file=/src/App.js

**Comment by abhirocks550** [comment]
Thanks for sharing the link.

What I want to achieve is I have a dropdown with list of Countries 
let's say I Select US then refinementList will be there with US as checked.

Again I select India then now the refinementList contains India and US selected.

I can select as many countries as I want and when I unchecked the country 
it will be removed from refinementList.

**Comment by abhirocks550** [comment]
The example that you have created looks good only thing is that , is it possible to display multiple items in `<CustomMenu>` i.e list of selected countries?

**Comment by Haroenv** [comment]
I think I misunderstood what you initially wanted, is this what you expected? https://codesandbox.io/s/summer-currying-vb960?file=/src/App.js

If not, please give example of a site where there's search that behaves like this, It's not clear to see what you want to achieve

**Comment by abhirocks550** [comment]
@Haroenv this is exactly what I was looking for. Thank you so much for helping me out.
I appreciate it.

Thanks for the awesome library.

**Comment by Haroenv** [comment]
No problem!
