### ISSUE TITLE
mobile friendly select refinements 

### ISSUE THREAD

**Issue by pdimo** [algolia/react-instantsearch#2916]
I'm admittedly new to algolia; 

finding a lot of the widgets are not very mobile optimised. Have been looking into creating my own widget that utilises https://react-select.com/  (or alike) to allow users to easily select filters on mobile. 

following the guide: 
https://www.algolia.com/doc/guides/building-search-ui/widgets/create-your-own-widgets/react/?language=jsx#usage

But can't seem to sync search state with my custom component widget.

**Comment by Haroenv** [comment]
Hey @pdimo, you usually want to pass props only to your custom widget and let the connector deal with the sate. Can you show what you have made so far in a sandbox? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by pdimo** [comment]
thanks @Haroenv !

I've moved my logic to https://codesandbox.io/s/react-instantsearch-select-ds69h?file=/src/customWidget.js 

 it's quite basic at present but all I'm trying to figure out is how I can get access to the search/filter state so that I can link it up with my own select box.

**Comment by Haroenv** [comment]
Thanks for making a sandbox, but I'm confused as to what you want to achieve. 

- What should the options of the select be? 
- What should happen when you select something?

If you're trying to make an autocomplete / dropdown, I'd advise `connectAutocomplete` so you have access to both refining the query & getting the hits: https://codesandbox.io/s/react-instantsearch-select-rzs1d?file=/src/customWidget.js

**Comment by Haroenv** [comment]
I'll close this issue now, since I hope my suggestion helped, but if there's still issues, don't hesitate to give a clear example of how what you currently have should work.
