### ISSUE TITLE
Calling refineNext from connectInfiniteHits moves autocomplete hits to the next page.

### ISSUE THREAD

**Issue by jacob-qurika** [algolia/react-instantsearch#2917]
**Describe the bug 🐛**

I'm implementing infinite scroll using connectInfiniteHits along with a search box with autocomplete. Infinite scroll is working great, but when the scroll triggers a refineNext() the hits for auto-complete move forward by a page, which is really problematic. 

**Expected behavior 💭**

Auto-complete hits should be stable across multiple calls to refineNext()

**Environment:**

 - OS: macos
 - Browser: chrome
 - Version: 6.4.0

**Comment by Haroenv** [comment]
This happens because there's only one 'search state' per index. A solution here is the following using two Index widgets:

```js
const AutoComplete = connectAutoComplete(
  ({
    refine,
    hits: allHits,
    currentRefinement,
    indexContextValue,
    onSelect,
  }) => {
    const { targetedIndex } = indexContextValue;
    const { hits } =
      allHits.find(hitsList => {
        return hitsList.index === targetedIndex;
      }) || {};

    return (
      <form
        action=""
        onSubmit={e => {
          e.preventDefault();
          onSelect(currentRefinement);
        }}
      >
        <input
          type="search"
          value={currentRefinement}
          onChange={e => refine(e.target.value)}
        />
        {Boolean(currentRefinement.length) && Array.isArray(hits) && (
          <ol>
            {hits.map(hit => (
              <li key={hit.objectID}>
                <Highlight hit={hit} attribute="name" />
                <button
                  type="button"
                  onClick={() => {
                    refine(hit.name);
                    onSelect(hit.name);
                  }}
                >
                  set query
                </button>
              </li>
            ))}
          </ol>
        )}
      </form>
    );
  }
);

function App() {
  const [query, setQuery] = React.useState('');

  return (
    <div>
      <header className="header">
        <h1 className="header-title">
          <a href="/">react-instantsearch-app</a>
        </h1>
        <p className="header-subtitle">
          using{' '}
          <a href="https://github.com/algolia/react-instantsearch">
            React InstantSearch
          </a>
        </p>
      </header>

      <div className="container">
        <InstantSearch searchClient={searchClient} indexName="instant_search">
          <div className="search-panel">
            <div className="search-panel__filters">
              <RefinementList attribute="brand" />
            </div>

            <div className="search-panel__results">
              <Index indexName="instant_search" indexId="autocomplete">
                <AutoComplete onSelect={q => setQuery(q)} />
                {/* page={0} is key here */}
                <Configure hitsPerPage={5} page={0} />
              </Index>

              <InfiniteHits hitComponent={Hit} />
              <Configure hitsPerPage={1} query={query} />
            </div>
          </div>
        </InstantSearch>
      </div>
    </div>
  );
}
```

https://codesandbox.io/s/agitated-breeze-lh9wg?file=/src/App.js

Of course this exact implementation depends on your design, and when you want to refine the main hits vs. when you want to show the autocomplete hits, but key is that the autocomplete needs to be in its own index to set its own parameters, which in this case is a set page of 0

**Comment by jacob-qurika** [comment]
I see. That seems like a decent enough workaround. 

I think this should be considered a bug in connectAutoComplete though. This is the kind of implementation detail I would expect to not have to think about when using a client like InstantSerach. I'm sure some internal record keeping can prevent this from happening in the first place. If InfiniteHits can remember the earlier pages, why can AutoComplete?

FWIW I have just decided to use the js client directly instead of InstantSearch. I'm finding InstantSearch somewhat complicated to reason about. I've hit a few other issues as well (there was an infinite loop when connecting StateResults and Infinite hits to the same component I think). I'm not very fond of HOC's to start with. Do you have any plans to roll out a hooks alternative?

**Comment by Haroenv** [comment]
Suggesting Autocomplete to also keep an internal cache of the first list of hits is a very interesting idea, which could indeed resolve this problem.

Hooks is on our list, but we haven't yet found the best API, which works for all use cases we have envisioned.

Sorry to hear you're not satisfied with InstantSearch for now, and we hope to catch up on this in the future.

If you have other feedback, don't hesitate to let this know, we definitely want this library to fit all use cases

**Comment by jacob-qurika** [comment]
Perhaps there is a good reason for it that I am not yet seeing, but can I suggest that in separating the business logic and rendering code, the business logic has been overfitted to each specific widget? 

In the design I implemented, I provide a single context that exposes all the search parameters, results, and callbacks. I use that context to build all the UI components. We have a pretty simple use case (for now), but it works very well. This way, for example, my autocomplete search bar has access to all the results used by (my equivalent of) InfiniteHits, and so does not suffer from the paging issue.

**Comment by dennism501** [comment]
@Haroenv is there a way of styling this https://codesandbox.io/s/agitated-breeze-lh9wg?file=/src/App.js (Your example) to look like and behave like the `AutoComplete` that come with Algolia by default? Using the Algolia CSS classes like `aa-Autocomplete` for instance?

**Comment by Haroenv** [comment]
There's an example of using autocomplete here: https://codesandbox.io/s/react-instantsearch-with-autocomplete-forked-lriu7?file=/src/App.js, but in the future please open a new discussion for this kind of question @dennism501, it seems unrelated to the parent issue

**Comment by dennism501** [comment]
@Haroenv thank you for the response, and I will do that in the future. I might even do it today if i am not successful

**Comment by sarahdayan** [comment]
Hey!

We're doing a round of clean up before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately and to be mostly solved, so we're going to close it.
