### ISSUE TITLE
Focus shortcuts for Searchbox don't work properly inside shadow dom

### ISSUE THREAD

**Issue by Myrga** [algolia/react-instantsearch#2918]
**Describe the bug 🐛**

Hello :)

I have an issue when I type `s` in the SearchBox component when my React application is placed inside a ShadowDom element.

**To Reproduce 🔍**

1. Create an open ShadowDom element,
2. Render a React application inside it,
3. Use a SearchBox inside it,
4. Type `s`,
5. Notice that nothing is typed.

Here's a live example :
> https://codesandbox.io/embed/infallible-perlman-inmxo?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior 💭**

The focus shortcuts should work in an open ShadowDom element.

**Environment:**

 - OS: Windows 10
 - Browser: Chrome 80

**Additional context**

I noticed that the issue is happening here : https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-dom/src/components/SearchBox.js#L156. `e.target` is not equals to the input but to the shadowDom parent because the shadowDom element is supposed to be a separate html container.
We could test that `e.target` or `e.srcElement` contains a shadowRoot property and if yes, get the composedPath from the event with `e.composedPath()` and take the first element. This first element will be the element from where the event has been triggered.

Thanks for you help :)

**Comment by Haroenv** [comment]
Wow, I didn't know that shadow elements got access totally to their root, even when mode is "open". A solution I see is the following:

1. don't use focusShortcuts
2. add a keydown event yourself
3. call `input.focus` on `<SearchBox inputRef={input} />` in the correct condition

So far this is the first time I see someone using our library with shadow DOM, so there might be other parts which are assuming InstantSearch elements are accessible. 

Let me know if that's clear for you, or if you need any help implementing it

**Comment by Myrga** [comment]
It's super clear thanks for your super fast answer!
Until now, I didn't encounter any other issue but we're mostly building our own components (except for the SearchBox :D).
Will you plan on implementing a fix like the one I mentionned in the addtional context part ? so it would be available out of the box.
I think, with custom components being supported on all recent browsers now, shadow dom will be used more and more and it may happens to more people in the future.

**Comment by Haroenv** [comment]
For now I don't know for sure if this is something that we want to support out of the box, however if the fix is only in this place we can consider it. However I don't know how you can get access to the root, or know the root has shadow DOM? 

Do you check if the target has a shadow root, and then do the same input / textarea / select logic we do in the other places?

**Comment by Myrga** [comment]
For the focus shortcuts, this is the only place where we want to change something but basically it's something that could be done on all document.addEventListener since they would all stop at the shadow parent element.

We only have to check if the target has the `shadowRoot` property and if it has, we can use the event function `e.composedPath()` that will return the real list of element triggered by the event. The first item is the one we're interested in since it would be the input/select/textarea that has triggered the event `onKeyDown`.

I'm not sure if I'm very clear :D

**Comment by Haroenv** [comment]
```
const elt = e.composed ? e.composedPath()[0] : e.target || e.srcElement;
```

This is likely the code we want there. As a temporary workaround I'd advise you to go with [patch-package](https://github.com/ds300/patch-package) before we can decide if this goes in master :)

**Comment by Myrga** [comment]
Yes, perfect! :)
Thank you so much for your efficiency 👌

**Comment by Haroenv** [comment]
As React InstantSearch Hooks does not have this shortcut behaviour anymore, we decided not to add new features/fixes to this feature in React InstantSearch. You can of course continue to use the patch or a custom searchbox for now.
