### ISSUE TITLE
Every component re-render triggers a new search operation.

### ISSUE THREAD

**Issue by waldothedeveloper** [algolia/react-instantsearch#2931]
**Describe the bug 🐛**
I don't know if this is the desired behavior but, every time a React InstantSearch Component re-renders -or page refresh- it adds a search operation when ```responseCache: createNullCache()``` is enabled.
Here's a video that show's what I see live: 
[see-the-video-here](https://www.dropbox.com/s/mc3pe4vkmpcv929/algolia-search-operations.mov?dl=0)

**To Reproduce 🔍**
I have put the following code sandbox for investigation:
[check-the-code-here](https://codesandbox.io/s/algolia-search-22yip?file=/src/Algolia.js:336-351)

**Expected behavior 💭**
I expected hopefully NOT to add search operations on page refresh or component re-render but I don't know if the cause of this is that the local cache is disabled. At least it should not add search operations on re-renders, right?

**Comment by eunjae-lee** [comment]
Hi @waldothedeveloper ,
Whenever you refresh the page, it needs to fetch the initial hits to display. And that triggers a search API.
However, if only react components are re-rendered, then normally it won't trigger a new API call. React InstantSearch manages the current search state and its search result. So as long as it's not changed and it's not lost (by refresh, etc), re-render itself won't trigger another API call.

**Comment by waldothedeveloper** [comment]
Hi @eunjae-lee, sorry it took me this long to reply. The reason why I'm using ```responseCache: createNullCache()``` is because I have a form to create, delete and update clients information pretty much for hours, so imagine that I create a client, save it on my database (FireStore), that triggers a g-cloud function that updates the client on Algolia, but if I have a cache I'd need to empty it out and bring the new data, for some strange reason the 
```// v4
client.clearCache().then(() => {
  // ...
});```

is not working or not cleaning my cache fast enough. see my previous open ticket: [https://github.com/algolia/react-instantsearch/issues/2923](hits does not update).

So, do you have any thoughts on this?

**Comment by dhayab** [comment]
Hi! We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, so we're going to close it, feel free to reopen if needed.
