### ISSUE TITLE
Passing React refs through connectSearchBox connector

### ISSUE THREAD

**Issue by pruett** [algolia/react-instantsearch#2932]
Does [`connectSearchBox`](https://www.algolia.com/doc/api-reference/widgets/search-box/react/#connector) interoperate with `React.forwardRef()`? I cannot seem to pass along a ref to my custom search box UI with the provided connector to allow for gaining focus on my `<input/>` element.

Is there a code example showing how to do this?

**Comment by eunjae-lee** [comment]
Hi there,
if you upgrade React InstantSearch to 4.5.0,
you can do it like the following:

```jsx
const inputRef = React.createRef();
<SearchBox inputRef={inputRef} />
```

https://github.com/algolia/react-instantsearch/pull/2913/files#diff-aad04aa511137d28819489b9eec88d8aR300-R303

**Comment by pruett** [comment]
Thanks for the reply. My question was pretty generic. I was referring to not using the provided `SearchBox` widget but instead using a custom UI with the `connectSearchBox` connector. But this question is very specific on my unique implementation.

I went a different direction and for that reason I'll close this out.

Thanks again.
