### ISSUE TITLE
Ability to disable `onWidgetsUpdate()` 

### ISSUE THREAD

**Issue by websocket98765** [algolia/react-instantsearch#2933]
I've been struggling to prevent my app from sending 2x or more http requests to Algolia for a given UI change. I've identified two reasons this occurs in my app (after rewriting App.jsx in various ways), below is one cause: 

**Is your feature request related to a problem? Please describe 🙏**

Problem: Conditional rendering of widget elements causes 2x HTTP requests to Algolia.

E.g. If I have a MenuSelect element for a productType and various groups of UI elements which are only shown for a given product type, two HTTP requests will be sent to Algolia whenever the product type is changed in the UI, due to 1.) `onExternalStateUpdate()`, and 2) `onWidgetsUpdate()` both being invoked. (Note that I have URL routing set up, similar to the docs but also supporting browser back/forward buttons.)

**Describe the solution you'd like 🤔**

One idea is to pass `enableOnWidgetsUpdate={false}` (default to true) to the InstantSearch component to disable the onWidgetsUpdate() component if a developer needs this control. 

(I assume onWidgetsUpdate() exists to prevent queries being accidentally or incorrectly restricted by UI elements added or removed from the page...but it also makes this impossible to control. In my case, I already clean up the URL to remove refinements from the query string that don't exist for the current product type, to keep the URL clean, so I'm handling what `onWidgetsUpdate()` was presumably created for anyway.)

**Describe alternatives you've considered ✨**

I've tried various combinations of a custom productType UI element that avoids calling `refine()` and uses either React Router's `history.push` or HTML5 `window.history.pushState()`, with the idea to avoid the `onExternalState()` HTTP request when `refine()` is called, given we know `onWidgetsUpdate()` will be invoked anyway when the product-specific UI elements are hidden/shown.

(`history.push` causes a UI infinite loop between old and new product, with my URL routing otherwise set up well. The second does not work for the first click of the browser's history back button.) Both are workarounds anyway and attempts to work around `onWidgetsUpdate()` existing.

The real problem is actually `onWidgetsUpdate()` in this case.

**Comment by Haroenv** [comment]
Do you have a sandbox which shows this behaviour?

**Comment by websocket98765** [comment]
I'm using:
```
"algoliasearch": "^3.35.1",
"react-instantsearch-dom": "^6.5.0",
```
Sorry, should have mentioned that. I'll try v4 client and report back the result.

**Comment by websocket98765** [comment]
Closing this. Upgrading `algoliasearch` to v4 resolved most 2x HTTP requests.

I'll create a more specific issue related to a "conditional rendering causing 2x HTTP requests", now that I've learned more, to try to fix this last, important aspect.
