### ISSUE TITLE
Why is this package so large?

### ISSUE THREAD

**Issue by stephanoparaskeva** [algolia/react-instantsearch#2938]
For React Native:

react-instantsearch-native bundlesize is massive. Checking the package on bundlephobia shows 100kb minified and taking 0.5 seconds on 3g to load just this package. After carefully picking all of my packages for my app, and now seeing this, I feel like it's absurd. Not to mention you also need algoliasearch package.

[link](https://bundlephobia.com/result?p=react-instantsearch-native@6.5.0)

The package also has 3 dependencies including instantsearch-core which is even bigger

[link](https://bundlephobia.com/result?p=react-instantsearch-core@6.5.0)

Lastly it needs babel runtime which is Massive!

[link](https://www.npmjs.com/package/@babel/runtime)

All of this totals to a lot of memory for any app to download.

**Comment by Haroenv** [comment]
I understand this criticism, and it's something we have been working on improving. These packages were originally made in a time where bundle size wasn't the most important concern (2015). As you can see, we made a big improvement in bundle size with the last major version already.

However, you are likely not bundling all of the code in your app, but only what you are using. In the site you posted, you can see that while the required InstantSearch component is the largest, the individual connectors, of which you only will include the ones you're actually using, are much smaller. 

Also note that all exports from InstantSearch native & InstantSearch core are the same, so the size you see in React InstantSearch native is the one which really counts.

The same counts for @babel/runtime, not all of that is used.

Hope that already gives you a better view on what's going on
