### ISSUE TITLE
Reset of refinement when opening a drawer

### ISSUE THREAD

**Issue by Newtchuck** [algolia/react-instantsearch#2942]
**Describe the bug 🐛**

I'm developing my marketplace with Algolia and I'm using this example as support. https://react-instantsearch.netlify.app/examples/e-commerce/

On mobile mode the filters are visible thanks to a drawer.

On my app I made customs UI for every widget. For example when I do a research with the SearchBox and I open my filter drawer, the search is reset.

But when I do it with the widgets (not customs) it works, the search does not reset. It thought it my be a mistake of mine in my custom component so I tried with the Algolia's documentation examples. And I have the same results

```
const SearchBox = ({ currentRefinement, refine }) => (
  <input
    type="search"
    value={currentRefinement}
    onChange={event => refine(event.currentTarget.value)}
  />
);
```
To follow my design I really need to do a custom widget.

Does anyone have an idea why the refinement reset itself with custom widget ?

I also tried Routing URLs but I have an infinite loop with custom widgets ^^""

**Expected behavior 💭**

Same as https://react-instantsearch.netlify.app/examples/e-commerce/ in mobile mode when you select a filter.

**Comment by Haroenv** [comment]
I think you might be unmounting/remounting components, do you have your code in a sandbox too? the SearchBox there looks fine to me though

**Comment by Newtchuck** [comment]
Yes I'm trying to do it but it does not work with custom UI. 

https://codesandbox.io/s/tender-kepler-lxb7u?file=/src/App.js 
I tried to add the UI library I use but it's not working ^^ So the drawer does not appears correctly

**Comment by Newtchuck** [comment]
I can't seems to make it works on SandBox.. But it looks like this. Hope it helps 

```
const [displayDrawer, setDisplayDrawer] = useState(false)

const SearchBox = ({
    currentRefinement,
    refine,
  }) => (

      <form noValidate action='' role='search'>
        <Input
          placeholder={upperFirst(t('common.placeholder.search'))}
          suffix={<SearchIcon />}
          value={currentRefinement}
          onChange={event => refine(event.currentTarget.value)}
          allowClear
        />
      </form>

  )


const CustomSearchBox = connectSearchBox(SearchBox)

return  (<>
        <InstantSearch
            searchClient={searchClient}
            indexName={process.env.REACT_APP_ALGOLIA_INDEX_NAME}
          >
            <CustomSearchBox />

                <Results>
                  <CustomHits />
                </Results>

            <FiltersDrawer
              placement='bottom'
              onClose={() => setDisplayDrawer(false)}
              visible={displayDrawer}
              key='bottom'
              footer={
                <>
                  <ButtonUI size='large'>Wesh</ButtonUI>
                </>
              }
            >
              <RefinementList attribute='discounts' />
              {/* <LeeshopFilters /> */}
            </FiltersDrawer>
          </InstantSearch>
        )}
            <Button
              onClick={() => setDisplayDrawer(true)}
            >
              Filtres
            </ButtonUI>
</>)
```

**Comment by Newtchuck** [comment]
I manages to reproduce the bug here: https://stackblitz.com/run 
It's a custom UI for the SearchBox. When you open the drawer with the Filters Button the search is reset.

**Comment by Haroenv** [comment]
The error is happening because you define the components inside the render method. That means whenever the App rerenders (eg. when state changes) those components are recreated; and thus lose their state. Here's how to solve it: https://stackblitz.com/edit/react-chvwmv?file=index.js

**Comment by Newtchuck** [comment]
Thank you very much !
