### ISSUE TITLE
Conditional rendering of refinements causes 2x HTTP requests to Algolia

### ISSUE THREAD

**Issue by websocket98765** [algolia/react-instantsearch#2943]
**Overview**

I use a MenuSelect for a productType and then show refinements specific to that product type. E.g.

- **Car**: carDoors(2/4), horsepower...
- **Bicycle**: bikeType (mountain/hybrid/road), bikeFrame (aluminum/carbon/steel)...

**Describe the bug 🐛**

Conditional rendering of refinements causes 2 issues:

1.) 2x HTTP requests are sent to Algolia.

The first HTTP request will be initiated via `onExternalStateUpdate()` and the 2nd via `onWidgetsUpdate()` when the refinements specific to the product type are added **OR** removed to/from the DOM. The 1st HTTP request is uneeded & wastes operations (it fetches the old facets). The 2nd HTTP request is correct because it fetches the new, desired facets, that are now visible.

  (This is important because it effectively halves my Algolia operations, since productType will be the most commonly used.) 

2. (Related, smaller issue): For each refinement removed from the DOM, `onSearchStateChange()` is invoked _once for each_, thereby causing many unnecessary invocations  `setSearchState()` and multiple identical history entries. (A possible hack fix for this may be for me to use `JSON.stringify()` to compare searchState vs nextSearchState, like we do in `useEffect()`. This feels hacky, knowing it runs nearly a dozen times when switching off a product with many product-specific refinements. But may be the only way currently.)

**To Reproduce 🔍**

Run [this repo](https://github.com/websocket98765/algolia-url-routing), which I built from the new, official react-router URL routing [example on Github](https://github.com/algolia/react-instantsearch/tree/master/examples/react-router)
(I updated all NPM deps to the latest).

1. `npm run start`
2.  Select 'Connectivity' or 'Wireless speakers'. (I've only implemented product-specific refinements for those, to show the issue.) 

Pretend the refinements that are displayed are specific to that product type.

For example:
- **Car**: carDoors(2/4), horsepower...
- **Bicycle**: bikeType (mountain/hybrid/road), bikeFrame (aluminum/carbon/steel)...

Even though I just had to use generic ones b/c that's all the sample data had.

3. Open Chrome dev tools' Network tab and watch XHR requests to Algolia. You'll see 2x HTTP requests when switching to or from "Connectivity" or "Wireless speakers". (Hard refresh to clear results cache if needed.) For the 2nd issue, open the console, you can notice `onSearchStateChange()` is invoked once for item removed from DOM because I have a console log within `onSearchStateChange()` to show it.

**Expected behavior 💭**

- **1x HTTP request to Algolia**: Could a solution be to allow `refine()` to accept a `false` value to not initiate `onExternalStateUpdate()`, so `onWidgetsUpdate()` can send the one, desired request?
- Don't call `onSearchStateChange()` for every item removed from DOM: I don't have a suggestion for how to fix this one.

**Environment:**

 - OS: Mac
 - Browser: Chrome, FF, Safari.
 - Version:
```
    "algoliasearch": "4.3.0",
    "react-instantsearch-dom": "6.6.0",
```

**Comment by dhayab** [comment]
Hi! We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js).

InstantSearch search state is closely linked to which widgets are present at one point in time in an app, so mounting and unmounting widgets conditionally will trigger new requests (after which they will be cached). An alternative is to rely on CSS to hide/show those widgets.

As this issue seems not to have generated much activity lately, we're going to close it, feel free to reopen if needed.
