### ISSUE TITLE
Page level search - SharePoint framework webpart in React

### ISSUE THREAD

**Issue by ArathyLakshmi** [algolia/react-instantsearch#2947]
I want to implement a page level search similar to Windows Cntrl + F in a modern sharepoint page. This is a blog page. This page has two sections - blog content and comment chains. We have lazy loading/vistualize load implemented in the page. That means dom does not contain the entire results always. Results loads based on scroll. But the search functionality should be able to implement the complete search results while going through "Enter" key press. Please help me understand how i can use Instantsearch for this use case. I have a limited timeline. Thanks for helping.

**Comment by eunjae-lee** [comment]
Hi there, assuming you already indexed your data at Algolia, `searchBox` + `infiniteHits` could work.
Not 100% sure what you intent to do.

Can you check this example and see if it would work for you?
https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/React%20InstantSearch/infinite-scroll

Let me know if you have further question.

**Comment by dhayab** [comment]
Hi! We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, so we're going to close it, feel free to reopen if needed.
