### ISSUE TITLE
InstantSearch simple geo radius search without map features

### ISSUE THREAD

**Issue by guyjacks** [algolia/react-instantsearch#2948]
Are there any widgets (React Native) for allowing the user to filter results by supplying a zipcode and radius (i.e. 20 miles)?  I could only find widgets that work with Google Maps.  I don't want to show results on a map or have the user interact with a map at all.

**Comment by francoischalifour** [comment]
You can use [`connectGeoSearch`](https://www.algolia.com/doc/api-reference/widgets/geo-search/react/#connector) to refine hits based on coordinates (computed from a zipcode and a radius), without displaying a map.

You can find an [example on this sandbox](https://codesandbox.io/s/react-instantsearch-custom-geosearch-s0ggs).

**Comment by guyjacks** [comment]
connectGeoSearch::refine() - Sets a bounding box to filter the results from the given map bounds. The function accepts an object with:
```
    northEast: { lat: number, lng: number }: the top right corner of the map view.
    southWest: { lat: number, lng: number }: the bottom left corner of the map view.
```

I'm trying to use a radius filter, not a bounded box filter.  How can I pass a coordinate and a radius to refine()?  Ty.

**Comment by tkrugg** [comment]
Hi @guyjacks sorry for the late reply. 

While Algolia does allow filtering by radius, the GeoSearch widget is tailored to square shaped maps, and therefore works only with bounding boxes
Fortunately, it's fairly easy to find one bounding box matching the area described by a center and a radius, if you don't need 100% accuracy which is usually the case.

Here is how: https://gis.stackexchange.com/questions/80809/calculating-bounding-box-coordinates-based-on-center-and-radius

If you need more accuracy, I'd suggest turning to specialized libraries such as http://turfjs.org/, which will give you functions like circle:

```js
const center = turf.point([-90.548630, 14.616599]);
const buffered = turf.buffer(point, 500, {units: 'miles'});

turf.bbox(buffered)
-> [-98.02455208434779, 7.3800198428104835, -83.07270791565222, 21.85317815718951]
```

I'll close this issue for now, but feel free to reopen it if it's still isn't solved.
