### ISSUE TITLE
Update next.js examples to v9.5.* with hooks

### ISSUE THREAD

**Issue by francisrod01** [algolia/react-instantsearch#2949]
**Is your feature request related to a problem? Please describe 🙏**

I'm frustrated that great features don't follow the evolution of our favourite libs. It seems like Next.js hooks aren't compatible with Algolia Next.js' examples. Even if I try to use parts of the code, it's not possible letting my Custom SearchBox working fine without empty queries after I hit the submit button.

### Environments

- `next@9.3.6`
- `react@1.3.1`
- `react-dom@1.3.1`
- `algoliasearch@4.2.0`
- `react-instantsearch-dom@6.6.0`

**What have I tried before**

- [github.com/algolia/react-instantsearch/blob/master/examples/next/pages/index.js](https://github.com/algolia/react-instantsearch/blob/master/examples/next/pages/index.js)

- [algolia.com/doc/guides/building-search-ui/server-side-rendering/react/](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react/)
- [algolia.com/doc/guides/building-search-ui/customize-an-existing-widget/react/](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/#customize-the-complete-ui-of-the-widgets)
- https://discourse.algolia.com/t/customsearchbox-searchasyoutype-false-not-working/9164/4

## Describe the solution you'd like 🤔

Here's a GREAT solution using a Next.js hook and less code than official solutions for that.
It doesn't take away my current refinement value like the official solution for Custom SearchBox does.
With that, I can use my own layout with Material-UI and so on.

![image](https://user-images.githubusercontent.com/4691768/86310755-2c218f80-bbf5-11ea-9dd1-4dd1370d36c5.png)

### Describe alternatives you've considered ✨

An alternative solution I've considered today was to use an external feature that cares about the logic stuff itself.

**[next-instantsearch](https://github.com/stuart-williams/next-instantsearch)** by @stuart-williams

Server-side rendering with Next.js and React InstantSearch

Use the `withInstantSearch` HOC to configure **InstantSearch** and enable **SSR**:

https://github.com/stuart-williams/next-instantsearch#readme

### Edit - A full reproduction code

https://codesandbox.io/s/nextjs-instantsearch-ohphp

**Preview:**

[![image](https://user-images.githubusercontent.com/4691768/86538070-084a9c00-beca-11ea-8685-cd1ba2aa8a56.png)](https://codesandbox.io/s/nextjs-instantsearch-ohphp)

**Comment by dhayab** [comment]
Hi! We have released [React InstantSearch Hooks](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react-hooks/), that will play well with React and Next.js's Hooks. You can check out the [upgrade guides](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react-hooks/) to help you move your codebase from your current version of React InstantSearch.

For now I'll close this issue. Feel free to open a new one if necessary.
