### ISSUE TITLE
Please fix poweredBy SSR compatibility

### ISSUE THREAD

**Issue by francisrod01** [algolia/react-instantsearch#2950]
**Describe the bug 🐛**

I was expecting this should be fixed soon: https://github.com/algolia/react-instantsearch/pull/181
Are these this props available for `PoweredBy` of its connectors?

**To Reproduce 🔍**

Steps to reproduce the behaviour:

1. Implement Algolia InstantSearch instance connected by its components
2. Add the `poweredBy` component into it
3. Implement SSR first load to fetch from the InstantSearch instance
4. I can see on the browser console the warning about the URL in the browser with the "localhost" the `&utm_content` property.

```
Warning: Prop `href` did not match. Server:

in a (created by PoweredBy)
    in div (created by PoweredBy)
    in PoweredBy (created by Translatable(PoweredBy))
    in Translatable(PoweredBy) (created by AlgoliaPoweredBy(Translatable(PoweredBy)))
```

**Expected behavior 💭**

This warning in red should not be happening.

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/4691768/86559694-01a43f00-bf33-11ea-8836-06583bd94bcf.png)

**Environment:**

- Linux debian `4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1`
- npm@6.14.4
- node@10.20.1
- next@9.3.6 
- react@16.13.1 
- react-dom@16.13.1 
- react-instantsearch-dom@6.6.0

**Additional context**

In my opinion, it could expect a `Router` property instead of `canRender. Just something like this:

```js
<PoweredBy
  canRender={(window !== undefined)}
  router={useRouter()} // or just that
/>
```

**Comment by yannickcr** [comment]
#181 is a pretty old change and the `canRender` prop no longer exists in the current implementation.

But the issue you reported is correct as we can not determine the hostname in a reliable way when rendering on the server. 

From here I am more to remove the `utm_content` parameter altogether but I need to see the potential impact of it before making the change.

**Comment by Haroenv** [comment]
I think an option would be changing 

https://github.com/algolia/react-instantsearch/blob/91f21028c7a26edc8ea48177f496534ee7005df5/packages/react-instantsearch-core/src/connectors/connectPoweredBy.js#L13-L15

to 

```
getProvidedProps(props) {
  const hostname =
      typeof props.hostname === 'undefined'
          ? props.hostname
          : typeof window === 'undefined'
          ? ''
          : window.location.hostname;
```

**Comment by dhayab** [comment]
Hi! We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js).

You can upgrade to React InstantSearch Hooks which won't have this issue, or use a custom widget based on PoweredBy that implements the change listed on top.

For now we're going to close this issue. Feel free to open a new one if necessary.
