### ISSUE TITLE
Allow multiple SearchBox widgets on the same page

### ISSUE THREAD

**Issue by zachtaylor21** [algolia/react-instantsearch#2952]
**Is your feature request related to a problem? Please describe 🙏**

I want to have multiple search boxes on a page, but if I put multiple `SearchBox` widgets on a page, they all share the same state.

**Describe the solution you'd like 🤔**

I want the ability to have multiple `SearchBox` widgets on a page without them all updating at the same time as I type. 

**Describe alternatives you've considered ✨**

I've tried creating a custom search box widget with their own state, but I would like to have them look the same as the `SearchBox` widget. As far as I can tell, there is no way to replace the connector of a widget but keep its style.

**Comment by francoischalifour** [comment]
Hey—why do you need multiple search boxes that do not share the same state? Are you targeting multiple indices?

**Comment by dhayab** [comment]
Hi! We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js).

This issue seems not to have generated much activity lately, so we're going to close it, feel free to reopen if needed.
