### ISSUE TITLE
ToggleRefinement off parameter 

### ISSUE THREAD

**Issue by RichardJohnn** [algolia/react-instantsearch#2963]
### Feature request to set the unchecked, `off` value with the React instant search component.

> Looking at #905 I see a solution for setting the off value to explicitly be false for a ToggleRefinement. However, for the React component https://www.algolia.com/doc/api-reference/widgets/toggle-refinement/react/#widget-param-value it seems you can only set value which is the value used when checked.

related: https://github.com/algolia/instantsearch.js/discussions/4474

**Comment by Haroenv** [comment]
In the mean time, don't hesitate to try out the edit to the connector and get back with your experience

**Comment by Haroenv** [comment]
We no longer plan to add features like this to the current version of React InstantSearch, but the next major is based on InstantSearch.js out of the box and will have this feature. You can already useConnector(useToggleRefinement) today: https://github.com/algolia/react-instantsearch/tree/master/packages/react-instantsearch-hooks#useconnector
