### ISSUE TITLE
Sharing state between unrelated components

### ISSUE THREAD

**Issue by ilievskizoran** [algolia/react-instantsearch#2965]
Hello there 👋

I'm wondering if anyone has had the need to manage state between react instantsearch components that are not in a parent child hierarchy?

The reason is a migration from instantsearch.js to react instantsearch.
With the current setup using instantsearch.js, hits, facets, pagination and other widgets are initiated on different parts of the page, mixed among static content.

The typical approach with react would be to nest all components under one `<InstantSearch>` component however that may not be possible in our case.

Has anyone used a state management tool like redux or something else to synchronise multiple components that may not be under the same parent?
Is this possible with react instantsearch?

**Comment by Haroenv** [comment]
Our general advise is to use React Portals if the regular architecture does not work, or to put InstantSearch at one of the root levels of the application. Do you have an example application that is tough to implement now that you could put in codesandbox? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by ilievskizoran** [comment]
@Haroenv 

Thank you for your suggestion, it's looking like its exactly what we will need in this instance.
Reached out to Algolia support via the clients customer manager and they suggested the same.

Thank you for your help 👍
