### ISSUE TITLE
Storybook: ConfigureRelatedItems 'View Source' link is broken

### ISSUE THREAD

**Issue by lukethacoder** [algolia/react-instantsearch#2968]
**Describe the bug 🐛**

[ConfigureRelatedItems](https://react-instantsearch.netlify.app/storybook/?path=/story/configurerelateditems--default) storybook 'View Source' link is broken as it appears to be a `.tsx` file instead of a `.js` file.

**To Reproduce 🔍**

1. Go to https://react-instantsearch.netlify.app/storybook/?path=/story/configurerelateditems--default
2. Click on 'View source code'
3. See Github 404 page

**Expected behavior 💭**

Should point to https://github.com/algolia/react-instantsearch/blob/master/stories/ConfigureRelatedItems.stories.tsx

**Additional context**

Looks like this needs a rework to allow both `*.tsx` and `*.js` files.

https://github.com/algolia/react-instantsearch/blob/cb56ca09f97c17d874c922225733274d135e2767/stories/util.js#L69

**Comment by Haroenv** [comment]
I have made a pull request to fix that here: https://github.com/algolia/react-instantsearch/pull/2969
