### ISSUE TITLE
Attribute in MenuSelect, RefinementList and Other widget.

### ISSUE THREAD

**Issue by roshani3110** [algolia/react-instantsearch#2970]
**Describe the bug 🐛**

am working on react and laravel project and implement algolia search but some issues there.

How does attribute get manipulated? And what exactly is considered to attribute for menuSelect and other widgets? What kind of data is considered to be an attribute for menuSelect and other widgets? And how to fetch that? Also working well in Hits widget but not working on menuSelect and other.

**Here is my Code:**

          <div className="right-panel">
            <SearchBox />
            <MenuSelect attribute="status" translations={{
              seeAllOption: 'Venue',
            }}/>
            <RefinementList attribute="name"/>
            <Hits hitComponent={Hit} />
          </div>

**API** 
![Screenshot from 2020-08-28 10-43-55](https://user-images.githubusercontent.com/51118255/91524003-b77c8000-e91b-11ea-9032-ac4de63c5a0c.png)

**Environment:**

 - OS: Linux
 - Browser: Chrome 
 - Version: Laravel: 5.8 and react 16.13.1

**Thanks in advance**

**Comment by Haroenv** [comment]
> How does attribute get manipulated

An attribute does not get manipulated, it's the key in your object/record you're refining. You can find all the attributes you have in the dashboard explorer.

Looking at the screenshot you sent, you seem to save ids of filters, make sure to also save the actual value you want to save in the UI.

Make also sure that the attribute you're using is set up for [`attributesForFaceting`](https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/how-to/declaring-attributes-for-faceting/)

**Comment by roshani3110** [comment]
and can you please tell me? can I give dynamic value in min, max, and defaultRefinement in rangeSlider widget? if yes, then how to do it?

**Comment by Haroenv** [comment]
You can change the props to a widget by keeping track of the value you're using in state. 
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by dhayab** [comment]
Hi! We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, so we're going to close it, feel free to reopen if needed.
