### ISSUE TITLE
"Error: [ssr]: no widgets were added " - A breaking change in v6.8.0, not properly documented.

### ISSUE THREAD

**Issue by ItsWendell** [algolia/react-instantsearch#2978]
**Describe the bug 🐛**

After updating to version v6.8.0 my code stopped working for SRR on NextJS. After digging in the PR's of this repository, I noticed that it is highly likely caused by pull request #2973, which was released a few days ago under v6.8.0.

I think this should have been marked as a breaking change. It changes the way SSR works using the WidgetsCollector which isn't properly documented in the documentation.

[See SSR docs here.](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react/#appjs)

The documentation shows that the `<App />` component now receives a prop for `widgetsCollector` but this prop is never actually passed down by the server. Also, the related examples and type definitions were not properly updated, like the [NextJS example](https://github.com/algolia/react-instantsearch/tree/master/examples/next).

**To Reproduce 🔍**

1. Run the NextJS example and open in your browser.
2. It will popup the following error: ```Error: [ssr]: no widgets were added, you likely did not pass the `widgetsCollector` down to the InstantSearch component.```

**Expected behavior 💭**

I expected this to be either backward compatible or released as a breaking change like the industry-standard [semver](https://semver.org/) suggests.

**Environment:**

 - OS: Linux
 - Browser: Chrome
 - Version: 36

**Additional context**

 - Related pull request: https://github.com/algolia/react-instantsearch/pull/2973

** For people running into the same problem **
I needed install and / or revert back and freeze the version of the packages `react-instantsearch`, `react-instantsearch-dom` and `react-instantsearch-core` to `v6.7.0` in order to fix this problem. I specifically had to install `react-instantsearch-core` separately too and freeze at `v6.7.0` because of `react-instantsearch` is set to resolve all "^6.7.0" (all 6.*.* versions), which means it will install the 'broken' version too, `v6.8.0` and above. Installing and freezing the core package worked for me.

**Comment by Haroenv** [comment]
Thanks for opening an issue, when I tried the example locally (and via the tests) it works without issue, as long as you spread the props in App towards InstantSearch. The goal is to replace the prop `onSearchParameters` with the prop `widgetsCollector` forwarded. I will look into this in detail and try to find the issue 

You're right that this probably should have been a breaking change / major version

**Comment by Haroenv** [comment]
If you have a repo where it's not working as expected, that will help to see what's going wrong.

**Comment by ItsWendell** [comment]
@Haroenv thanks for taking the time to debug this. I converted the above code sandbox to how I've set it up in my next.js project (with getServerSideProps instead of getInitialProps).

Here is my sandbox: [](https://codesandbox.io/s/cool-montalcini-lqyrj?file=/pages/index.js)

I just do not understand where widgetsCollector is coming from, if you follow it up the tree, it never gets assigned or passed down. If I comment it out from the `<InstantSearch ...>` component, you get the error mentioned in this issue.

Yet if you console.log the value of `this.props.widgetsCollector`, you get undefined. I simply do not understand where widgetsCollector is coming from, and why it works.

I'm confused, also the types in the @types package are missing so it's harder for me to pass down all the props into InstantSearch.

Does this help and could you explain what is going on?

**Comment by alexvandervegt** [comment]
I have the same problem

**Comment by Haroenv** [comment]
you seemed to have forgotten the actual sandbox, could you send it please? The typings are indeed not yet updated, since those are community maintained. I can review a PR to definitelyTyped though!

**Comment by ItsWendell** [comment]
Here is the code sandbox: https://codesandbox.io/embed/cool-montalcini-lqyrj?file=/pages/index.js:2110-2123&codemirror=1

**Comment by alexvandervegt** [comment]
An update of the next example would help a lot, really have no clue on how to fix this.

**Comment by ItsWendell** [comment]
@alexvandervegt I can seem like a bit of magic, but here's how I think it works.

In NextJS, since you pass down a Page during SSR to `findResultsState`, that will pass down the prop `widgetsCollector` to that page. Your `<InstantSearch>` component needs this prop during SSR to properly find widgets I guess. So here's what it should look like.

It looks empty indeed in the client side since `findResultsState` only passes down this prop, simply adding the property `widgetsCollector` to the page and passing that down to my `<InstantSearch>` component fixed it for me.

**Comment by alexvandervegt** [comment]
Thanks, I have it working now!

**Comment by alexvandervegt** [comment]
However SSR side is working but how can we fetch the widgetsCollector client side?

**Comment by Haroenv** [comment]
widgetsCollector is _only_ used on the initial render server side, just like how onSearchParameters was :)

**Comment by alexvandervegt** [comment]
I also have the bug client side, see attached.

When i refresh the page the SSR renderer kicks in and everything is working.
![Uploading Screenshot 2020-10-28 at 12.50.01.png…]()

**Comment by Haroenv** [comment]
could you show this bug in a sandbox perhaps @alexvandervegt? This doesn't seem to happen with the demo: https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/next?file=/pages/index.js

**Comment by alexvandervegt** [comment]
I got it working already, was a mistake on my side.

**Comment by Haroenv** [comment]
Were you calling `findResultsState` on the client too maybe?

**Comment by alexvandervegt** [comment]
yep...

**Comment by miggu** [comment]
I need help with regards to this issue , recently in the process of upgrading to 6 from 5.  I have a react app whose every route depends on Algolia to render UI (was working fine), I have found that in SSR, when hitting a Redirect ( basically to add a trailing slash to a url route) , and this not containing any widgets , this is actually causing the SSR to error for the redirects routes . I went to Algolia's source code `/node_modules/react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js` where it checks to see if there is any widgets , it seems to crash when the array of widgets is empty (which is the case of a redirect not containing them) . Experimentally removing this warning check in Algolias code seems to fix the issue completely. I can even create routes that don't contain Algolia components which is something it's not possible to do with the current setup.

**Comment by francoischalifour** [comment]
@miggu What's the structure of your app? Do you wrap it entirely in the `InstantSearch` component, even though some pages have no widgets?

**Comment by miggu** [comment]
Thank you for your answer @francoischalifour , yes we have found a workaround for this by adding a search instance that is in the header this way we will always have at  least a widget , this way the is a least a widgets and now the SSR is not crashing, now my question is more ... was that error message necessary as removing it in the `react-instantsearch-dom`  package simply does not verify for an empty widgets array and the app does not crash. Essentially what causes it to crash is simply that error message.

**Comment by dhayab** [comment]
Hi! We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, so we're going to close it, feel free to reopen if needed.
