### ISSUE TITLE
Expose total records in stats widget

### ISSUE THREAD

**Issue by fabn** [algolia/react-instantsearch#2983]
Stats widget only expose number of retrieved hits as described in https://www.algolia.com/doc/api-reference/widgets/stats/react/#props

It would be awesome to have more details in that widget such as details returned by index browse (or search with no query)

```
              "nbHits" => 295,
                "page" => 0,
             "nbPages" => 1,
         "hitsPerPage" => 1000,
```

A customer of mine wants to show a stats banner like "Showing xx filtered results of yy" and currently the only way I found to do that is to make a fake search with no args to retrieve `yy` number.

Correct me if I'm wrong but currently there's no api (especially if you're using lite client) to retrieve this number.

**Comment by francoischalifour** [comment]
Hey @fabn! The [`connectStateResults`](https://www.algolia.com/doc/api-reference/widgets/state-results/react/#connector) API makes this possible.

**Comment by Haroenv** [comment]
Unfortunately that's the number of hits for _this query_, not for the whole index; and I don't know a way to get that without doing an empty query

**Comment by francoischalifour** [comment]
Using an [`Index`](https://www.algolia.com/doc/api-reference/widgets/index-widget/react/) with an empty query and `connectStateResults` would achieve this though?

If you're using SSR, that's an info that you can pass to your frontend more easily.

Wondering the UX part of this feature though—why does the total number of records matter for the current search?

**Comment by fabn** [comment]
> Using an [`Index`](https://www.algolia.com/doc/api-reference/widgets/index-widget/react/) with an empty query and `connectStateResults` would achieve this though?

This is what I'm doing right now

> If you're using SSR, that's an info that you can pass to your frontend more easily.

Yes, I tried also that approach, but since I'm already loading index with no query at frontend startup I'm saving the initial value of `nbHits` in redux state and I do not update it anymore. Something like 

```js
// Load total number of results
    useEffect(() => {
        searchClient.initIndex(indexName).search('').then(results => dispatch(setTotal(results.nbHits)))
    }, [])
```

> Wondering the UX part of this feature though—why does the total number of records matter for the current search?

It's a customer request, he cares about showing how many records he has in its collection.

It can also be useful as general info, not necessarily bound to current search

**Comment by Haroenv** [comment]
For the time being, this information isn't available when doing a search, however I have relayed the feature request to the search engine team, to see whether they hear this more
