### ISSUE TITLE
Pass props to HitComponent of Hits/InfiniteHits

### ISSUE THREAD

**Issue by springuper** [algolia/react-instantsearch#2985]
**Do you want to request a *feature* or report a *bug*?**

feature request.

**Feature: What is your use case for such a feature?**

Our use case is to support customized columns, for example:

```js
// Search Component
class App extends React.Component {
  render() {
    const { columns } = this.state;
    return (
      <InstantSearch
        appId="latency"
        apiKey="3d9875e51fbd20c7754e65422f7ce5e1"
        indexName="bestbuy"
      >
       <Search/>
       <Hits hitComponent={HitComponent} hitComponentProps={{ columns }}
      </InstantSearch>
    );
  }
}

// HitComponent
class HitComponent extends React.PureComponent {
  render() {
    const { hit, columns } = this.props;
    return (
      <div>
        {columns.map(column => (<div key={column}>{hit[column]}</div>))
      </div>
    };
  }
}
```

**What project are you opening an issue for?**
- react-instantsearch

**Comment by ketan-hauper** [comment]
> @korroktheslavemaster Seeing the same thing. My Guess is that has to do with passing an anonymous function is creating a new instance of the component every render.

Yes, that is exactly what is happening with me, when I pass a function as a props to connectHits it causes a one extra request to the typesense server, can anyone suggest the solution?
