### ISSUE TITLE
React InstantSearch Dom Maps no external TypeScript support

### ISSUE THREAD

**Issue by Will-Mann-16** [algolia/react-instantsearch#2988]
**Describe the bug 🐛**

React InstantSearch Dom Maps doesn't have any clear typescript support/installation. When installed it requires you to add '@types/react-instantsearch-dom-maps' but that package doesn't exist. I can declare the module, but according to the source code there is typescript support in some capacity.

**To Reproduce 🔍**

1. npm install react-instantsearch-dom-maps
2. Import this to a typescript file
3. try install @types/react-instantsearch-dom-maps

**Expected behavior 💭**

I expect to be able to use types without having to use declare and setting all the types to 'any' because I'm not sure what type it should be returning.

**Environment:**

 - OS:  mac
 - Browser chrome
 - Version 6.8.2

**Comment by Haroenv** [comment]
That's right, the package doesn't support typescript for now, you can create your own definition file and upstream it to DefinitelyTyped just like using another non-typed package though

**Comment by Will-Mann-16** [comment]
Ok then if it's in the works I'll look forward to seeing it
