### ISSUE TITLE
Next.js example using getStaticProps

### ISSUE THREAD

**Issue by jeremylynch** [algolia/react-instantsearch#2991]
The [current next.js](https://github.com/algolia/react-instantsearch/tree/master/examples/next) example is very useful however is using `getInitialProps` for SSR which doesn't allow for the pages to be built at runtime. I was wondering if we could see an example of a project using `getStaticProps` instead?

**Comment by realw5** [comment]
Yes, you can. I don't have anything public but I can confirm it really is just as simple as mapping the API from `getInitialProps`to `getStaticProps`. Just need to be mindful that query params can only be read on client-side. But this works quite well with the native instant-search client-side hydration;
