### ISSUE TITLE
No way to reset SearchBox query from within connectStateResults

### ISSUE THREAD

**Issue by rtucker-scs** [algolia/react-instantsearch#2994]
**Describe the bug 🐛**

There isn't an attribute or way to reset the searchBox or InstantSearch query from within an object instantiated by connectStateResults

**To Reproduce 🔍**

const Results = connectStateResults(({ searchState, searchResults, children, props }) =>
//no way to reset state here
)

A live example helps a lot! We have a simple online template for you to use for your explanations:

> https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch

**Expected behavior 💭**

A way to reset the searchState.query and remove searchResults

**Screenshots 🖥**

**Environment:**

 - OS: windows
 - Browser chrome
 - Version 86

**Additional context**

**Comment by Haroenv** [comment]
you can reset the state by using ClearRefinements or connectCurrentRefinements, the documentation for that his here: https://www.algolia.com/doc/api-reference/widgets/clear-refinements/react/

**Comment by rtucker-scs** [comment]
How can you do it programmatically though?

**Comment by rtucker-scs** [comment]
Essentially I want to allow the user to click a link in the <Results /> and reset the search interface.

**Comment by Haroenv** [comment]
you can do it programmatically by using the `refine` function of `connectCurrentRefinements @rtucker-scs

**Comment by rtucker-scs** [comment]
Is there an example?

**Comment by Haroenv** [comment]
https://codesandbox.io/s/fast-pond-gsivd?file=/src/App.js

Here it shows how to make a widget that you can use in results (used in hit component here, but the usage is the same)

**Comment by rtucker-scs** [comment]
This doesn't show how to clear the refinements without someone clicking a button to do it.

**Comment by Haroenv** [comment]
you can do the same refine function around the click on the result, no?

**Comment by rtucker-scs** [comment]
@Haroenv How do you get access to the refine function through connectStateResults?

**Comment by rtucker-scs** [comment]
I found a way to do this inside of connectStateResults.

`const Results = connectStateResults(({ searchState, searchResults, children, props }) =>
props.contextValue.store // <= current state with setState method available
`

**Comment by Haroenv** [comment]
What I meant is that you wrap the individual result component in `connectCurrrentRefinements`, and use the wrapped component inside your results you get from `connectStateResults`
