### ISSUE TITLE
How to remove blue X button?

### ISSUE THREAD

**Issue by oslearningbear** [algolia/react-instantsearch#2997]
**Describe the bug 🐛**

Everytime I type something a blue X button shows up. It's not styled like the site and looks kind of janky.

**To Reproduce 🔍**

Go to https://flurly.com/search, type and see the blue x

> https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch

**Expected behavior 💭**

I want either a teal X or not X at all

**Comment by eunjae-lee** [comment]
Hi there.

![image](https://user-images.githubusercontent.com/499898/102761945-e5c51600-4377-11eb-917b-d78ecb2e4f11.png)

I do not see "X" button. Have you removed it?

Anyway, you can customize the reset button like this:
```jsx
<SearchBox   reset={<img src="/reset.png" alt=""/>} />
```

https://www.algolia.com/doc/api-reference/widgets/search-box/react/#widget-param-reset

**Comment by oslearningbear** [comment]
I can still reproduce. I use CustomSearchBox not SearchBox. The reset prop didn't seem to work for CustomSearchBox

**Comment by Haroenv** [comment]
The blue x you are talking about is browser style for input type search, you can style it like this https://css-tricks.com/webkit-html5-search-inputs/#styling-search-graphical-widgets

hope that helps @oslearningbear
