### ISSUE TITLE
Can use use connectHitInsights with connectHits ?

### ISSUE THREAD

**Issue by hideokamoto** [algolia/react-instantsearch#3001]
I want to use the `search-insights` package with `react-instantsearch-dom`.
But there is no document about how to use the `connectHitInsights` or search-insights functions with `connectHits`.

https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-through-and-conversions/how-to/send-click-and-conversion-events-with-instantsearch/react/

I check the connector code, and the function seems to not support the `connectHits` function.
Because the function can not allow to get the `hits` prop from outside.
https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/connectors/connectHitInsights.ts

Do you have any idea or plan to use both?
Thanks.

**Comment by Haroenv** [comment]
connectHitInsights is used at the level of  a single hit, like here: https://github.com/algolia/react-instantsearch/blob/22ecb3c315cbbb2df43c6d2259318dc487414785/stories/Hits.stories.js#L56

Using connectHits, you'd still use connectHitInsights in the component that actually renders an individual hit.

Hope that makes sense!

**Comment by Haroenv** [comment]
I think this has been answered, but feel free to give more information if you have more questions

**Comment by MistaPidaus** [comment]
@Haroenv doing `<Hits hitComponent={ProductWithInsights} />` result of the custom UI component being wrapped with built-in UI which is not my desire results. Can't we just have an independent, isolated `insights` for tracking analytics?

**Comment by Haroenv** [comment]
@MistaPidaus you can use it like this:

```js
const Hits = connectHits({hits, hitComponent: Hit}) => hits.map(hit => <Hit key={hit.objectID} hit={hit} />))

const MyHit = connectHitInsights(insightsClient)(({hit}) => <div>hi <Highlight hit={hit} attribute='name' /></div>);

<Hits hitComponent={MyHit} />
```

**Comment by MistaPidaus** [comment]
@Haroenv that so confusing.. but it works. will let you know if anything come up. 

Thanks!

**Comment by MistaPidaus** [comment]
@Haroenv sorry but can you help me with the TS for it? I get error at `<Hits hitComponent={MyHit} />` for `hitComponent`.

**Comment by Haroenv** [comment]
We don't officially support TS yet for React InstantSearch, but here's how to do it: https://codesandbox.io/s/dreamy-smoke-yxzwu?file=/src/App.tsx

**Comment by MistaPidaus** [comment]
Works. Thanks so much!

**Comment by MistaPidaus** [comment]
@Haroenv I have setup the analytics with following steps:

- install `aa` package and setup
```jsx
aa('init', {
    appId: APP_ID,
    apiKey: SEARCH_ONLY_API_KEY,
  });
```
- set specific user token if user logged in
```jsx
if (session.uid) {
    aa('setUserToken', session.uid);
  }
```
- finally somewhere inside of my `Hit` component, I have `sendEvent` function which calls `insights` whenever user click on the search item (or button)
```jsx
const sendEvent = () => {
    insights('clickedObjectIDsAfterSearch', {
      eventName: 'Search Item Clicked',
    });
  };
```
I can see the events being logged in the browser console. But I can't see anything on `Insights API Logs` in `Monitoring` section on Algolia website. Did I miss / misunderstand something? 

Sorry if its not related to the issue. Can't find a place to ask question.

**Comment by Haroenv** [comment]
> I can see the events being logged in the browser console. But I can't see anything on Insights API Logs in Monitoring section on Algolia website. Did I miss / misunderstand something?

For issues with the API itself, please contact support@algolia.com, but note that the insights api isn't realtime, but only gets aggregated every 5-15 minutes, so you will not see the events instantly. 

What was the network response of the insights calls? You can see that in the "other" tab in the network panel

**Comment by MistaPidaus** [comment]
@Haroenv sorry for the late. I've checked and found nothing in the "other" network panel. Guess I might missing things somewhere but could not figure out. Can help me point it out?

**Comment by francoischalifour** [comment]
@MistaPidaus Can you please reproduce on this [React InstantSearch template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch)? Thanks!
