### ISSUE TITLE
Cannot retain items in one MenuSelect when refined from another

### ISSUE THREAD

**Issue by ror-y** [algolia/react-instantsearch#3002]
**Describe the bug 🐛**

I cannot retain items in one MenuSelect when refined from another.

I have two MenuSelect components in my app which are correctly linked to Algolia returning data I expect.

```
        <div>
            <MenuSelect attribute="manufacturer" />
            <MenuSelect attribute="model" />
        </div>
```

The user must first choose an item from the `manufacturer` MenuSelect which will refine the `model` MenuSelect.

Currently, after choosing an option from the `model` MenuSelect, the `manufacturer` MenuSelect only shows the currently refined manufacturer item.

I want to retain the options in the `manufacturer` MenuSelect even after refining from the `model` MenuSelect.

Is this possible to achieve with the React Instantsearch library?

**Expected behavior 💭**

I do not want the refinement caused by the `model` MenuSelect to affect the `manufacturer` MenuSelect, otherwise the user is stuck with only one option there when they may want to change it, without clicking 'See all'.

**Screenshots 🖥**

Here is a gif which shows the issue:

![refinement](https://user-images.githubusercontent.com/10364894/105326914-32de1700-5bc6-11eb-9f34-52f35050eabe.gif)

**Environment:**

 - OS: mac
 - Browser: Chrome 87
 - Version: "react-instantsearch-dom": "^6.7.0"

**Comment by Haroenv** [comment]
The behaviour you are interested in sounds more like a hierarchical menu than multiple separated menus, because there will indeed be no more values available once you refine. 

You can use a hierarchical menu connector with select boxes like this: https://codesandbox.io/s/damp-wildflower-kn7s7?file=/src/App.js

```js

const HierarchicalMenuList = ({ items, refine }) => {
  const selectedItem = items.find((item) => item.items);

  return (
    <>
      <select
        onChange={(e) => {
          refine(e.currentTarget.value);
        }}
      >
        <option key="all" value={selectedItem?.value ?? ''}>
          see all
        </option>
        {items.map((item) => (
          <option value={item.value} key={item.label}>
            {item.label} ({item.count})
          </option>
        ))}
      </select>
      {selectedItem && (
        <HierarchicalMenuList items={selectedItem.items} refine={refine} />
      )}
    </>
  );
};

const HierarchicalMenu = connectHierarchicalMenu(HierarchicalMenuList);
```
