### ISSUE TITLE
Image for demo section in README are broken

### ISSUE THREAD

**Issue by imox2** [algolia/react-instantsearch#3004]
**Image for demo section in README are broken 🐛**

One of the broken link is https://www.algolia.com/doc/assets/images/build-search-ui/demos/e-commerce-4391909a.png

**To Reproduce 🔍**

See readme section

**Expected behavior 💭**

The image link should show the image.

**Screenshots 🖥**

![Screenshot 2021-01-24 at 1 59 06 PM](https://user-images.githubusercontent.com/6959913/105625133-0ab41980-5e4d-11eb-9c13-430d149a298e.png)

**Comment by Haroenv** [comment]
Thanks, I've put the images back in the repo!
