### ISSUE TITLE
Strange/Broken behavior with <Configure facets="*">

### ISSUE THREAD

**Issue by jgahn-xom** [algolia/react-instantsearch#3008]
**Describe the bug 🐛**

Using `facets="*"` (or ```facets={`["*"]`}```) , in the Configure component, creates some silent problem that causes InstantSearch to consider results as empty even though the request is returning good data.

**To Reproduce 🔍**

1. https://codesandbox.io/s/great-carson-flmg0?file=/src/App.js:859-905
2. See that I added ```<Configure facets={`["*"]`}>``` on Line 37, resulting no console errors but _no_ _results_!
3. Remove facets prop from Configure to watch the app work again.
4. ctrl+z the facets prop back in, results stay!
5. Watch the network request results are accurate even on the first facets pass.

**Expected behavior 💭**

I expect facets="*" (or facets={`["*"]`}) to fetch all relevant facets for the full result set

**Screenshots 🖥**

https://pasteboard.co/JNIYwzZ.png

**Environment:**

React InstantSearch

**Additional context**

**Comment by Haroenv** [comment]
the correct way of writing that query is `facets={['*']}`, why were you adding it into a string? Note that the "facets" search parameter is a "controlled" search parameter, which is why it might conflict with widgets on the page

https://codesandbox.io/s/great-darkness-e75bv

**Comment by jgahn-xom** [comment]
Thanks, that does solve the issue reported. But I _had_ tried passing the array as well and I must have conflated the problem because I am perhaps running into what you mentioned in the second part of your comment. Although the network request returns facets correctly, the searchResults object given from `connectStateResults` has empty facets, so that is disappointing. This is at least a lead.

I feel like it shouldn't be so hard to build a dynamic list of refinements from the facets in the result set, rather than hardcoding refinementlists.

Thank you for the assist!

**Comment by Haroenv** [comment]
> I feel like it shouldn't be so hard to build a dynamic list of refinements from the facets in the result set, rather than hardcoding refinementlists.

This is something we're currently working on, but just * isn't sufficient in most cases, especially with many possible facets, which is why we haven't focused on * yet previously.
