### ISSUE TITLE
'SmartSort' is not exported from 'react-instantsearch-dom'.

### ISSUE THREAD

**Issue by AdamBCo** [algolia/react-instantsearch#3013]
**Describe the bug 🐛**

Attempted import error: 'SmartSort' is not exported from 'react-instantsearch-dom'.

**To Reproduce 🔍**

1. npm start

**Expected behavior 💭**

I would not get this error.

**Screenshots 🖥**

<img width="699" alt="Screen Shot 2021-02-25 at 7 33 45 AM" src="https://user-images.githubusercontent.com/4572275/109176562-ccf02c80-773b-11eb-8c21-b4d602270bcb.png">

**Environment:**

 - OS: Mac
 - Version

    "react-instantsearch": {
      "version": "6.10.0",
      "resolved": "https://registry.npmjs.org/react-instantsearch/-/react-instantsearch-6.10.0.tgz",
      "integrity": "sha512-g+lzjy1N1f+RptMq1TxV/Ud91vpHqBNTXt32jAOPQSodB98EhjmvL3+bMWdon8wwFdvsC9/Vdon8r4z1i5dZ+A==",
      "requires": {
        "@babel/runtime": "^7.1.2",
        "react-instantsearch-core": "^6.10.0",
        "react-instantsearch-dom": "^6.10.0",
        "react-instantsearch-native": "^6.10.0"
      }
    },

**Additional context**

**Comment by eunjae-lee** [comment]
Hi @AdamBCo, sorry for inconvenience. There was an issue with the release. We will release the correct version early next week (Monday or Tuesday).
In the meantime, 

```
"dependencies": {
  "react-instantsearch-dom": "https://pkg.csb.dev/algolia/react-instantsearch/commit/f7eae28c/react-instantsearch-dom"
}
```

**Comment by WilliamCadenas21** [comment]
Same here, i'm using type script so the message is the next:
`TypeError: (0 , _reactInstantsearchCore.connectSmartSort) is not a function
    at Object.<anonymous> 
`

**Comment by WilliamCadenas21** [comment]
> Same here, i'm using type script so the message is the next:
> `TypeError: (0 , _reactInstantsearchCore.connectSmartSort) is not a function at Object.<anonymous> `

The problem solve upgrading to v6.10.3 !

**Comment by Haroenv** [comment]
note that it has been renamed to RelevantSort and connectRelevantSort, which we didn't consider a breaking change, as it wasn't documented yet.
