### ISSUE TITLE
RefinementList

### ISSUE THREAD

**Issue by christykusuma** [algolia/react-instantsearch#3016]
Everything works perfectly except for the RefinementList. For example, all the cities show up and I can toggle each filter on an off. However the hits only appear after I toggle one off. Let's say I check "Paris", the results will stay the same and then when I uncheck "Paris" it then shows my Paris results. Has anyone else had this issue?

`<RefinementList
          attribute={"city"}
          operator="and"
          transformItems={(items) => orderBy(items, "label", "asc")}
        />`

**Comment by Haroenv** [comment]
Hey, I saw you closed this issue, did you find what was going wrong?
