### ISSUE TITLE
Components seem to trigger onSearchStateChange when unmounted

### ISSUE THREAD

**Issue by dguo** [algolia/react-instantsearch#302]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Hi, I've run into two issues while integrating React Instantsearch into my website, and they seem to have the same root cause. For context, my website is implemented as a SPA, and I'm using React Router v2. 

1) I put the `SearchBox` in my website's header. I want to use [react-responsive](https://github.com/contra/react-responsive) to make the header more responsive. Specifically, I want the `SearchBox` to come before another element on desktop but after the element on mobile. The positioning change works as expected, but the `SearchBox` is cleared when the change occurs. So I enter a query, resize my window, and the query is cleared.

2) I'm trying to sync the search state with the url. I'm following the [guide](https://community.algolia.com/react-instantsearch/guide/Routing.html). It works for the most part, but I have an edge case where sometimes I can't navigate away from my search results page. When I click a link on that page, `onSearchStateChange` is triggered. As in the example code, my `onSearchStateChange` handler pushes a new route, so I immediately end up back on the search results page. From what I can tell, this is because I have a `Pagination` component on the search results page, so when I click a link, it gets unmounted, and that seems to trigger `onSearchStateChange`.

**Bug: What is the expected behavior?**
I don't expect `onSearchStateChange` to be called when components are unmounted. I saw #26. Could it be the case that the behavior applies to the other components as well?

I'm sorry I didn't provide a code example. I'm a little tight on time right now, but I might be able to make a minimal, reproducible example later. 

**Bug: What browsers are impacted? Which versions?**
I experienced the issues on Chrome 60 and Firefox 56.

**What is the version you are using? Always use the latest one before opening a bug issue.**
4.1.0

**Comment by mthuret** [comment]
Hi @dguo, 

It's expected that every time a component is unmounted `onSearchStateChange` get called because it means that a new request has been made => some filters could have change, etc. 

However I did fix something about this and SPA and it's the issue you're referencing here => if the whole <InstantSearch/> instance unmount (most probably because of a click on a link), then `onSearchStateChange` shouldn't be called. 

Can you confirm that in your use case you don't unmount <InstantSearch/> when observing the `onSearchStateChange` calls? 

If yes, one way to fix this is actually to have several InstantSearch and if needed you can share the `searchState` between them. 

If no, then I would need a reproducible example as it shouldn't be the case :)

**Comment by dguo** [comment]
Thanks for the detailed reply, @mthuret. I understand now why it's called on unmounts. I'm definitely not unmounting the whole instance, so it seems that I'll have to follow your suggestion to use multiple `InstantSearch` instances. 

For your consideration, it would be nice if `onSearchStateChange` could provide some context on what caused the change. If I knew that it was due to an unmount of the `Pagination` component, I could just put an if statement in my handler to avoid pushing a new route.

**Comment by ajsharp** [comment]
This issue still happens with nested `RefinementList` and `Pagination` components, and any other component that sets `hasCleanup` to true, making it difficult to manage url state. This appears to be the problem: https://github.com/algolia/react-instantsearch/blob/eca186a99fde4e53ad130dfdc58bacb682ec2f41/packages/react-instantsearch-core/src/core/createConnector.js#L203.

**Comment by ajsharp** [comment]
@mthuret Do you see this as a bug, or expected behavior? I think there needs to be a way to opt-out of it if it's expected.

**Comment by samouss** [comment]
Hi @ajsharp, it's definitely an expected behaviour. This behaviour is deeply linked to how React InstantSearch is implemented. Basically the widget drive the search which means that once they are mounted or unmounted we have to update the state and trigger a new request.
