### ISSUE TITLE
Page state syncing between multiple InfiniteHits components causes initial hits to be hidden

### ISSUE THREAD

**Issue by colepeters** [algolia/react-instantsearch#3024]
**Describe the bug 🐛**

First off, I don't think this is necessarily a ‘bug’ per se, but rather an unexpected behaviour that I’m having trouble working around. I may just not be using the correct components or API methods here — if so, I’m more than happy to be educated! ;)

I have a project that provides multiple views onto a single search, by using multiple instances of InfiniteHits and Configure components. Each InfiniteHits renders its hits with a different custom `hitComponent`, and I use a Configure component to filter the results in each InfiniteHits to a specific type of result. So, structurally, I have:

- InstantSearch
  - ReactRouter Switch
    - Route 1
      - InfiniteHits w/ custom hits component X
      - Configure w/ `filters='type:X'`
    - Route 2
      - InfiniteHits w/ custom hits component Y
      - Configure w/ `filters='type:Y'`
    - etc

The problem I'm having is that, if I click 'Load More' on the InfiniteHits component in Route 1, the search state updates its `page` state to `2`; if I now click over to Route 2, _that_ InfiniteHits component renders hits starting at page 2, without showing the results from page 1.

Without rendering a Load Previous button for every instance of InfiniteHits (which would be suboptimal UX given our UI in this case), I can't seem to force each InfiniteHits component to start rendering its hits at page 1. I even tried adding `page={1}` to my Configure component in each route, but the search state seems to override this every time.

Is there a way to do this, or is there a better way to implement this behaviour with the available components that I'm just overlooking?

**To Reproduce 🔍**

Steps to reproduce the behaviour:

1. Go to https://codesandbox.io/s/upbeat-cloud-2mpn3?file=/src/App.js
2. 20 hits are displayed in each section (All, Samsung, Dell)
3. Scroll down in the list of all results, click Load More
4. There are now 40 results displayed under All
5. Click to Samsung
6. The hits under Samsung start at hit 21

**Expected behaviour 💭**

There should be a way to render each InfiniteHits component starting from page 1.

Thanks in advance for any assitance!

**Comment by yannickcr** [comment]
In your case you want to manually reset the page when filters are updated. For this to work you'll have to switch InstantSearch to controlled mode and use the [`searchState`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-searchstate) and [`onSearchStateChange`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-onsearchstatechange) parameters. That way you can alter `searchState`  the way you want.

I updated your example so you can see how it would work: https://codesandbox.io/s/adoring-ishizaka-6dnj4?file=/src/App.js

**Comment by colepeters** [comment]
@yannickcr Fantastic! Thanks so much, this is a huge help. Much appreciated!
