### ISSUE TITLE
Cant build on react native with latest version

### ISSUE THREAD

**Issue by pdugan20** [algolia/react-instantsearch#3029]
None of these files exist:
  * node_modules/react-instantsearch-core/dist/cjs/connectors/connectSmartSort(
.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.exp
o.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.jsx|.na
tive.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.ts
x|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.nativ
e.json|.json)
  * node_modules/react-instantsearch-core/dist/cjs/connectors/connectSmartSort/
index(.native|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.nati
ve.expo.tsx|.expo.tsx|.android.expo.js|.native.expo.js|.expo.js|.android.expo.j
sx|.native.expo.jsx|.expo.jsx|.android.ts|.native.ts|.ts|.android.tsx|.native.t
sx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|
.native.json|.json)
> 1 | "use strict";
  2 |
  3 | var _interopRequireDefault = require("@babel/runtime/helpers/interopRequi
reDefault");
  4 |
Error: Unable to resolve module ./connectors/connectSmartSort from /Users/patdu
gan/Github/hikearound-app/node_modules/react-instantsearch-core/dist/cjs/index.
js:

**Comment by sbue** [comment]
Getting this error as well

**Comment by WilliamCadenas21** [comment]
Same here, please what is happening ? :/

**Comment by WilliamCadenas21** [comment]
The problem solve upgrading to v6.10.3 !

**Comment by eunjae-lee** [comment]
Sorry, there was an issue with release. Upgrading 6.10.3 will work.
