### ISSUE TITLE
connectMenu creates duplicate keys when 'all' option injected to `items`

### ISSUE THREAD

**Issue by colepeters** [algolia/react-instantsearch#3034]
**Describe the bug 🐛**

This may (once again 😅) be a case of me doing something wrong in my use case, however it seems worth flagging.

I'm using a custom Select component, which I'm hooking up to MenuSelect by way of `connectMenu`, as per the docs.

The docs use an example where an `<option>` is manually created within the select element for the 'all items' option:

```js
const MenuSelect = ({ items, currentRefinement, refine }) => (
  <select
    value={currentRefinement || ''}
    onChange={event => refine(event.currentTarget.value)}
  >
    <option value="">See all options</option>
    {items.map(item => (
      <option
        key={item.label}
        value={item.isRefined ? currentRefinement : item.value}
      >
        {item.label}
      </option>
    ))}
  </select>
);
```

However, the custom Select component I'm using is one used across our site, so I don't have the option of inserting this option manually in the markup. To get around this, I'm prepending an 'all' option to the items passed to the Select component from `connectMenu` — here's an abbreviated example:

```jsx
const CustomSelect = ({ currentRefinement, items, refine }) =>
  <Select
    items={[ { label: 'All', value: '' }, ...items ]}
    value={currentRefinement || ''}
    onChange={e => refine(e.currentTarget.value)}
  />

export default connectMenu(CustomSelect)
```

However, when doing this, there are multiple items with the key `''` created, which causes a bunch of React duplicate keys warnings to be logged (and seems like a potential for bugs).

**To Reproduce 🔍**

1. Open this CSB: https://codesandbox.io/s/quizzical-nash-io47g?file=/src/Select.js:473-474
2. Ensure the console is open
3. Choose a brand refinement from the select element
4. See duplicate keys warnings in the console

**Expected behaviour 💭**

There should be no duplicate keys.

**Comment by Haroenv** [comment]
The value is not a unique value, it is an array of "what should be refined if this is clicked". In the context of a select that might make sense, but in checkboxes this is clearer. Toggling a selected item should unselect it. Therefore `value` isn't unique, and you should use `label` as the key: 


```js
function Select({ currentRefinement, items, refine }) {
  const itemsWithAll = [{ label: 'All', value: '' }, ...items];

  return (
    <select
      value={currentRefinement || ''}
      onChange={(e) => refine(e.currentTarget.value)}
    >
      {itemsWithAll.map((item) => (
        <option
          key={item.label}
          value={item.isRefined ? currentRefinement : item.value}
        >
          {item.label}
        </option>
      ))}
    </select>
  );
}
```

https://codesandbox.io/s/quizzical-nash-io47g?file=/src/Select.js

**Comment by colepeters** [comment]
@Haroenv Interesting, I would've presumed every value would be unique. The documentation says that this component is to allow the user to choose a single value for a specific attribute, and I'm not sure why there would be duplicate values for a single attribute. Maybe I'm not thinking about this correctly?

At any rate, using the item's `label` as the key does seem to resolve this, so I'll close this issue. Thanks!

**Comment by Haroenv** [comment]
That's true, menu could be implemented as a single value (maybe in a next major version), but for now this was done for consistency with RefinementList IIRC (this decision was made when React InstantSearch was originally created)
