### ISSUE TITLE
`connectSearchBox` doesn't allow to pass a ref

### ISSUE THREAD

**Issue by ematipico** [algolia/react-instantsearch#3038]
**Describe the bug 🐛**

We use `connectSearchBox` and the documentation doesn't show a way to pass a `ref`.

This is a duplicate of https://github.com/algolia/react-instantsearch/issues/2932 which was later closed.

I saw that `<SearchBox />` has a prop `inputRef` (_which is missing from the official documentation_) but the connector doesn't have it.

Not having a possibility to hook a ref is a big penalty in terms of accessibility because we can't focus the input when we need.

**To Reproduce 🔍**

1. use `connectSearchBox`
2. can't forwrad a `ref`

**Expected behavior 💭**

I expect to be able to read a `ref` inside the props of the connected component.

**Screenshots 🖥**

not applicable

**Environment:**

 - OS: [e.g. iOS / windows / mac / android] not applicable
 - Browser [e.g. chrome, safari] not applicable
 - Version [e.g. 22] not applicable

**Additional context**

```json
"react-instantsearch-dom": "^6.8.2"
```

**Comment by Haroenv** [comment]
The connector doesn't have it, since the connector doesn't render anything, it passes all props through to the component you passed. Could you clarify what you've used so far and why it doesn't fit the use case? Thanks!

**Comment by ematipico** [comment]
> The connector doesn't have it, since the connector doesn't render anything, it passes all props through to the component you passed.

Gosh I didn't know that!! Thank you! Is there a place in the official docs that says this? The docs of `connectSearchBox` doesn't mention it.

> Could you clarify what you've used so far and why it doesn't fit the use case? Thanks!

We have some strict UI and styling requirements, and we are using the "renderless" components of the library to build the search in our website. I just tried what you've told me and it works perfectly :)

**Comment by Haroenv** [comment]
Could you tell where in the docs you'd expect this to be explained? I'd be happy to add it where you were looking!

**Comment by ematipico** [comment]
https://www.algolia.com/doc/api-reference/widgets/search-box/react/

Here there's no mention of `inputRef`.

About the connector, I was so focused on having a `ref` that I could have used a normal prop to bypass this issue. My bad!

**Comment by Haroenv** [comment]
I'll talk with the team to find how we can make it clearer all props can be passed there
