### ISSUE TITLE
How to snippet without Highlight

### ISSUE THREAD

**Issue by bidoubiwa** [algolia/react-instantsearch#3046]
**Is your feature request related to a problem? Please describe 🙏**

Possibility to Snippet without highlighting on a attribute.

Sorry if its written somewhere!

**Describe the solution you'd like 🤔**

The possibility to apply only Snippeting
<HighlightAndSnippet attribute="description" hits={hit} />

**Describe alternatives you've considered ✨**

/

Thanks for the amazing work!

**Comment by bidoubiwa** [comment]
Ah I tried on your demo! Apparently when I use `snippet` it also highlights! So is it possible to snippet without using the highlight? 
```js
   <InstantSearch indexName="demo_ecommerce" searchClient={searchClient}>
          <Configure attributesToSnippet={['description']} />
          <SearchBox />
          <Hits hitComponent={Hit} />
          <Pagination />
        </InstantSearch>
```

```js
function Hit(props) {
  return (
    <div>
...
        <Highlight attribute="name" hit={props.hit} />
        <Snippet attribute="description" hit={props.hit} />
...
    </div>
  );
}
```

**Comment by eunjae-lee** [comment]
Hi @bidoubiwa ,
I'm not sure if I understand your question correctly.

https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/highlighting-snippeting/js/#snippeting

In the doc above it says,

> Unlike highlighting, snippeting must be proactively enabled for each attribute you wish to snippet

You can set specific attributes (or `*`) in the dashboard and then if you try to use <Snippet> with the attribute, it will work fine.

If it doesn't, could you update [this CodeSandbox template](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch) for reproduction?

**Comment by bidoubiwa** [comment]
Hello! Yes sorry I have updated my question after reading more the documentation! 

Now I wonder how you can snippet without highlighting

**Comment by eunjae-lee** [comment]
https://codesandbox.io/s/elegant-christian-x0exb?file=/src/App.js

Is this what you intend to do?

**Comment by bidoubiwa** [comment]
That but without the highlight! Only the snippeting

Thanks for taking the time to do a demo!

**Comment by eunjae-lee** [comment]
In the example above, I didn't use any <Highlight>.

**Comment by bidoubiwa** [comment]
It still applies the highlight

<img width="537" alt="Screenshot 2021-04-27 at 17 30 12" src="https://user-images.githubusercontent.com/33010418/116269151-41683b80-a77e-11eb-8e48-41ec769433e3.png">

:s

**Comment by eunjae-lee** [comment]
Sorry I don't understand your question. Do you want the yellow color to be removed?

**Comment by bidoubiwa** [comment]
Yes. I want to use the snippets without the matches being highlighted 😊 

So `<Snippet>` on `description` without yellow matches on `description`.

**Comment by eunjae-lee** [comment]
You can add 

```
.ais-Highlight-highlighted,
.ais-Snippet-highlighted {
  background-color: #fff;
}
```

**Comment by bidoubiwa** [comment]
Ah oke! There is no attribute to enable or disable Highlight on Snippet?

```js
function Hit(props) {
  return (
    <article>
      <h1>{props.hit.name}</h1>
      <p>
        {/* no Highlight */}
        <p>${props.hit.description}</p>

        {/* Highlight  and Snippet */}
        <Snippet attribute="description" hit={props.hit} />

        {/* no Highlight */}
        <p>${props.hit.description}</p>

        {/* Only Highlight */}
        <Highlight attribute="description" hit={props.hit} />
      </p>
    </article>
  );
```

**Comment by Haroenv** [comment]
It's not an option we have, snippeting indeed also is highlighted. If you want to implement that, it would need to be implemented on the backend via a new parameter. So far this hasn't really been requested much

**Comment by bidoubiwa** [comment]
Oke! Thanks a lot for your quick replies. I will use the CSS trick :)
