### ISSUE TITLE
Cannot create two `connectHierarchicalMenu` for refinement 

### ISSUE THREAD

**Issue by MistaPidaus** [algolia/react-instantsearch#3049]
**Describe the bug 🐛**

I have 2 `connectHierarchicalMenu`. One for normal, custom UI purpose. another for Virtual Widget. I need the virtual widget for Modal and keeping the refine state purpose when it close but getting `Error: Cannot declare two hierarchical facets with the same name` error instead. Is there any solution or alternate approach for this? keep searching around but nothing useful found.

**To Reproduce 🔍**

Create one normal, custom `connectHierarchicalMenu` and `connectHierarchicalMenu` for virtual widget purpose.

**Expected behavior 💭**

To be able to support 2 `connectHierarchicalMenu` for virtual widget purpose

**Screenshots 🖥**

-

**Environment:**

 - OS: mac
 - Browser: chrome

**Comment by Haroenv** [comment]
Sorry, that's not possible with the current behaviour of the hierarchical menu. Depending on the use case you can also use defaultRefinement on the widget you're rendering or setting the `searchState` prop on the InstantSearch component.

If you make the following change to connectHierarchicalMenu (with patch-package) it should work:

```diff
diff --git a/packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js b/packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
index 3abc7755..7462546e 100644
--- a/packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
+++ b/packages/react-instantsearch-core/src/connectors/connectHierarchicalMenu.js
@@ -243,20 +243,28 @@ export default createConnector({
     const id = getId(props);
     const itemsLimit = showMore ? showMoreLimit : limit;
-    searchParameters = searchParameters
-      .addHierarchicalFacet({
+    const existingRefinement = searchParameters.getHierarchicalFacetByName(id);
+    if (
+      !existingRefinement ||
+      existingRefinement.attributes.some(
+        (value, index) => value !== attributes[index]
+      )
+    ) {
+      searchParameters = searchParameters.addHierarchicalFacet({
         name: id,
         attributes,
         separator,
         rootPath,
         showParentLevel,
-      })
-      .setQueryParameters({
-        maxValuesPerFacet: Math.max(
-          searchParameters.maxValuesPerFacet || 0,
-          itemsLimit
-        ),
       });
+    }
+
+    searchParameters = searchParameters.setQueryParameters({
+      maxValuesPerFacet: Math.max(
+        searchParameters.maxValuesPerFacet || 0,
+        itemsLimit
+      ),
+    });
     const currentRefinement = getCurrentRefinement(props, searchState, {
       ais: contextValue,
```

If that works, we can look at making a PR with it included so that it will work for everyone in the future

**Comment by MistaPidaus** [comment]
I'm currently setting the `searchState` prop. It works for other Virtual Widgets except for hierarchical menu. 

I can't seems to figure out the way of using `defaultRefinement` with state without `connectHierarchicalMenu` Virtual Widget involve to persist the refinement state when Modal close. Tried with other connectors but it seems incompatible. Seems to me they are correlate with each other. 

I'll try with your suggestion and see.

**Comment by MistaPidaus** [comment]
I've tested it. The `Error: Cannot declare two hierarchical facets with the same name` is now gone but another problem arise. 

I've tried with these two cases:

### 1. Define a "controlled" searchState on Virtual Widget

```jsx
const VirtualAuthorList = connectRefinementList(() => null);
const VirtualTopicList = connectHierarchicalMenu(() => null);
const VirtualDateRange = connectRange(() => null);

const SearchResultsPage = () => {
  const [searchState, setSearchState] = useState({});

    const handleStateSearch = (search: any) => {
    console.log('Handle Search =>', search);
    setSearchState({ ...searchState, ...search });
  };
  
  <InstantSearch
       indexName={INDEX_NAME}
       searchClient={searchClient}
       onSearchStateChange={handleStateSearch}
       searchState={searchState}
     >
          <VirtualAuthorList attribute="authors.name" />
          <VirtualDateRange attribute="dateYear" />
          <VirtualTopicList
              attributes={['topics.lvl0', 'topics.lvl1']}
              // if we're not defined it here, the state doesn't persist when modal close
              defaultRefinement={searchState?.hierarchicalMenu?.['topics.lvl0']}
           />
 </InstantSearch>
}
```

### Observation

When I open the Modal and choose/click one the topic in the lists inside of Hierarchical Menu, it seems like the state doesn't refresh like other refinement - once you click any of the refine items, it'll change immediately or show something like you've selected an item, something like `isRefined` becomes `true`, I guess. Then when I close the modal, I can see it not immediately apply like the other refinement widgets. its like it taking time or start fetching then display the correct results. When open the modal back, the filter/refinements are reset. another thing is it doesn't work with other refinement widgets like can't choose more than one refinement type. 

### 2. Specifically/Individually defined state for each refinement on Virtual Widget

```jsx
const VirtualAuthorList = connectRefinementList(() => null);
const VirtualTopicList = connectHierarchicalMenu(() => null);
const VirtualDateRange = connectRange(() => null);

const SearchResultsPage = () => {
  const [topicsState, setTopicsState] = useState();
  const [authorsState, setAuthorsState] = useState([]);
  const [dateState, setDateState] = useState([]);

    const handleStateSearch = (search: any) => {
    console.log('Handle Search =>', search);
    if (search.refinementList?.['authors.name']) {
      setAuthorsState(search.refinementList?.['authors.name']);
    }
    if (search.range?.dateYear) {
      setDateState(search.range?.dateYear);
    }
    if (search.hierarchicalMenu?.['topics.lvl0']) {
      setTopicsState(search.hierarchicalMenu?.['topics.lvl0']);
    }
  };
  
  <InstantSearch
       indexName={INDEX_NAME}
       searchClient={searchClient}
       onSearchStateChange={handleStateSearch}
     >
          <VirtualAuthorList attribute="authors.name" defaultRefinement={authorsState} />
          <VirtualDateRange attribute="dateYear" defaultRefinement={dateState} />
          <VirtualTopicList
            attributes={['topics.lvl0', 'topics.lvl1']}
            defaultRefinement={topicsState}
          />
 </InstantSearch>
}
```


### Observation
Almost similar like 1st observation but there are differences.

Differences:
- The custom hierarchicalMenu UI refinement works with others. Can select more than one type of refinement (i.e Topics, Authors) but date range doesn't work
- when open the modal back, I can see my UI changes when I first select on custom hierarchicalMenu UI

**Comment by Haroenv** [comment]
Thanks for trying it out!

> can't choose more than one refinement type

This is a different limitation, but indeed a facet can only have one type of refinement, so you can't mix hierarchical with refinementList in a single attribute.

With those caveats, does the new behaviour of hierarchical menu satisfy your use cases, or are the remaining behaviours required for your application? Thanks!

**Comment by MistaPidaus** [comment]
> > can't choose more than one refinement type
> 
> This is a different limitation, but indeed a facet can only have one type of refinement, so you can't mix hierarchical with refinementList in a single attribute.

I was referring to different attributes. Meaning that I can't mix with other attributes. For example, I want to filter the hierarchicalMenu (in this case, Topics) with other widget like Author (refinementList) and Date range. While it works with approach #2, it doesn't immediately update the state like refinementList widget. Meaning it should somehow highlight/bold selected item in hierarchicalMenu (assuming  I've done the highlight/bold logic using isRefined)

> With those caveats, does the new behaviour of hierarchical menu satisfy your use cases, or are the remaining behaviours required for your application? Thanks!

I think it feels incomplete. It should be behave like other widgets. 

For example (hierarchicalMenu) let say we go for the approach #2:
- if I select one of the hierarchicalMenu, it should immediately highlight or bold the selected 
- it should be immediately update the state and expand the hierarchicalMenu if there's child

I'm fine with the delay when close the modal as long as the UX above behave like other custom Virtual Widgets.

**Comment by MistaPidaus** [comment]
Not sure if its related but having `defaultRefinement` with Virtual Widget seems a little buggy. For example for `refinementList` when modal first open, it works well. I can select/unselect filter items and results filtered (almost) immediately but when I close and open for a 2nd time, it seems a little buggy - its like I have to click twice in order to unselect them and also its undo the first thing I selected rather than just unselect filter item based on what I click. 

for `range`, it works when first time open the modal i.e I can drag the slider and the results filtered after that and the slider position will remain as you drag them. but on the 2nd open, the position is reset but the results still remain filtered which is good. just in terms of UI state it reset.

**Comment by Haroenv** [comment]
An alternative approach to modals is to only hide the filters, instead of unmounting them. This will save on layout calculations still, so have those advantages, but since the widgets never unmount, their state stays as it was.

**Comment by MistaPidaus** [comment]
I have to refactor/redefine logic of existing component for that purpose hence why I went for virtual widget. otherwise I don't see the point of the existence of virtual widget.

**Comment by MistaPidaus** [comment]
also I found out that if define two `connectHierarchicalMenu` with same attributes with patch-package above without `searchState`, you can't refine the items.

**Comment by MistaPidaus** [comment]
I've resorted to creating a modal that doesn't unmount as an alternative approach/solution with a little bit tweak. Though I still hope this get resolves in the future. 

Feel free to close the issue.

**Comment by Haroenv** [comment]
Thanks for all this feedback @MistaPidaus, we'll take this in account!

**Comment by sarahdayan** [comment]
Hey!

We're doing a round of clean up before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, and is based off of a limitation of React InstantSearch v6, so we're going to close it.
