### ISSUE TITLE
Algolia searchState doesn't work.

### ISSUE THREAD

**Issue by DarkPonyBee** [algolia/react-instantsearch#3052]
**Describe the bug 🐛**

Algolia InstantSearch component's searchState doesn't work.

**To Reproduce 🔍**

I added the sample project.

> https://codesandbox.io/s/shy-haze-2bqtl?file=/src/App.js

**Expected behavior 💭**

Search result should reflect based on the input query.

**Screenshots 🖥**

**Environment:**

 - OS: Mac OS Big Sur 11.4
 - Browser: Chrome
 - Version: 90

**Comment by MistaPidaus** [comment]
If you want to custom UI, you have to use connectors. In this case, for custom input search, you can use [SearchBox connectors](https://www.algolia.com/doc/api-reference/widgets/search-box/react/#connector)

**Comment by shortcuts** [comment]
Hi @DarkPonyBee,

As stated by @MistaPidaus, if you'd like to create a [Custom Widget](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/react/#with-connectors), you can use our connectors to do so: [updated sandbox](https://codesandbox.io/s/nostalgic-vaughan-eu9jw?file=/src/App.js)

If you'd like to create a controlled mode experience (using `searchState` and `onSearchStateChange`), we have a dedicated guide [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/#searchstate)

**Comment by DarkPonyBee** [comment]
Thanks @MistaPidaus , @shortcuts .

I did it with SearchBox connector.

Thanks again.
