### ISSUE TITLE
Ability to use multiple nonconsecutive numeric ranges as filter

### ISSUE THREAD

**Issue by raymondpang365** [algolia/react-instantsearch#3053]
**Is your feature request related to a problem? Please describe 🙏**

I try to use connectRange for a list of checkboxes (eg 6-18, 18-30, 30-50, 50+).

For example, if 6-18 and 50+ are both selected, I want it to search all the records of that attribute within the range 6-18 or within the range 50+

How should I do that?

**Describe the solution you'd like 🤔**

We could also define an array of ranges in refine function instead of just min and max

**Describe alternatives you've considered ✨**

I consider creating a refinement list with these four categories. But I would like my attribute to be an integer, instead of text. It would be a bad developer experience if I have to convert this integer attribute into text for this use case.

**Additional context**

N/A

**Comment by francoischalifour** [comment]
The [`RefinementList`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/react/) component also supports numbers, so you don't need to change your data type. You can then leverage the [`transformItems`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/react/#widget-param-transformitems) prop to group the values as you wish.

**Comment by sarahdayan** [comment]
Hey!

We're doing a round of clean up before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately and to be mostly solved, so we're going to close it.
