### ISSUE TITLE
Warnings with props: React does not recognize the X prop on a DOM element.

### ISSUE THREAD

**Issue by InTheCloudDan** [algolia/react-instantsearch#3057]
**Describe the bug 🐛**

Seeing a number of errors when running a gatsby site in dev mode that has react-instantsearch:
```Warning: React does not recognize the `indexContextValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `indexcontextvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

```react_devtools_backend.js:2557 Warning: React does not recognize the `currentRefinement` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `currentrefinement` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

```react_devtools_backend.js:2557 Warning: React does not recognize the `isSearchStalled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `issearchstalled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

**To Reproduce 🔍**

using version: `react-instantsearch-dom@^6.11.0
`

> https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch

**Expected behavior 💭**

It loads without errors.

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/10308834/119421729-66909100-bccd-11eb-8c03-71b33065d1a6.png)

**Environment:**

 - Framework: Gatsby 3

**Comment by eunjae-lee** [comment]
Hi @InTheCloudDan Thanks for reaching out to us.
The code sandbox https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch doesn't show those warnings.
Could you provide us a minimal reproduction?

**Comment by InTheCloudDan** [comment]
Thanks @eunjae-lee is there some way I can modify the package dependencies there? I'm not sure what's causing it but I do see some differences with the dependencies:

```
"algoliasearch": "^4.9.1"
"react-instantsearch-dom": "^6.11.0"
"gatsby-plugin-algolia": "^0.20.0",
```

`gatsby-plugin-algolia` has a dependency on `4.9.1`

**Comment by eunjae-lee** [comment]
Hey @InTheCloudDan you can just start editing the package.json, and you'll get a fork of the sandbox.

https://codesandbox.io/s/nostalgic-haibt-ecri3?file=/package.json

↑ I updated the version of `algoliasearch` to `4.9.1` and it still doesn't give me the warnings.

**Comment by InTheCloudDan** [comment]
I was able to reproduce it here: https://codesandbox.io/s/wandering-wood-l3h2i I'm not sure if it's due to our implementation or an issue with the repo at this point.

**Comment by InTheCloudDan** [comment]
@eunjae-lee I linked a example sandbox in the comment above. Just realized I forgot to highlight you in that comment yesterday so might not show up in all the noise.

**Comment by eunjae-lee** [comment]
Hey @InTheCloudDan, I'll look into it today. Thanks for pinging :)

**Comment by eunjae-lee** [comment]
Hello @InTheCloudDan,
You're spreading `...rest` into your `<input>` element.
```jsx
<input
  ref={inputRef}
  type="text"
  placeholder="Search"
  aria-label="Search"
  onChange={event => refine(event.currentTarget.value)}
  sx={{
    border: 0,
    width: '100%',
    outline: 'none',
    fontSize: 4,
    '::placeholder': { fontSize: [4, 3, 4] },
  }}
  {...rest}
/>
```

If you look at the `rest` object, it contains InstantSearch-related values, which aren't native attributes of `input` element. That's why React is giving you the error messages.

Instead of spreading all of the `rest` object, you can pick specific values and apply to the element.

**Comment by InTheCloudDan** [comment]
@eunjae-lee sorry for my lack of React knowledge on that and appreciate the help and pointers!
