### ISSUE TITLE
Rheostat PropType Errors and Context API Legacy Error - RangeSlider Widget (Rheostat) with React

### ISSUE THREAD

**Issue by Ekeu** [algolia/react-instantsearch#3058]
**Describe the bug 🐛**

I'm currently working with React Instantsearch. While using the RangeSlider widget using Rheostat with React, I had several errors of this type `Warning: Failed prop type` and a `Contex API Legacy Warning` that only appeared in `Strict Mode`
 
**To Reproduce 🔍**

All I did was I went on Algolia's [doc](https://www.algolia.com/doc/api-reference/widgets/range-slider/react/?client=usage#about-this-widget) copied the custom range slider already provided, created a custom component within my code and then pasted it.

I customized the component, then exported it and just passed the required attribute.

**A live example helps a lot! We have a simple online template for you to use for your explanations:**

You can have access to the example [here ](https://codesandbox.io/s/vibrant-galois-ogqpm?file=/src/App.js). What was really strange was that when I reproduced the scenario in codesandbox, I didn't get the proptype errors as shown in the screenshot section.

**Expected behavior 💭**

As a junior developer and from reasoning based on what I read on Algolia's doc, since Rheostat is already handled by the RangeSlider widget the props causing the errors i.e background, handle and progressBar should be handled too. The values they need are also supposed to be passed in by the widget.

**Screenshots 🖥**

Here are the screenshots of the errors I'm getting

`PropType Errors`
![image](https://user-images.githubusercontent.com/23312714/121193591-3ff65c80-c86e-11eb-9feb-0eea305617f0.png)

`Legacy Error`
![image](https://user-images.githubusercontent.com/23312714/121192319-1ee13c00-c86d-11eb-9375-a46d4e4b66a1.png)

Here is my custom RangeSlider Component

![code-1](https://user-images.githubusercontent.com/23312714/121192447-41735500-c86d-11eb-9213-b702b64a090b.png)

Here is how I use it after it's exported

![code-1](https://user-images.githubusercontent.com/23312714/121192580-610a7d80-c86d-11eb-9b08-f5a9b153eb04.png)

**Environment:**

 - OS: [ windows]
 - Browser [chrome]
 - Version [87.0.4280.66]
 - React [17.0.2]
 - React Script [4.0.2]

May be I'm missing something out.

Thanks and have a nice day!

**Comment by Haroenv** [comment]
the Rheostat example is an _example_ based on a third-party library (Rheostat), which isn't part of InstantSearch. It's true that we didn't use the latest version, since the class names changed considerably, and we couldn't find a way to force the InstantSearch classes on the latest version of Rheostat. If you want an updated version, you can use the latest version of Rheostat and link that to InstantSearch

**Comment by Ekeu** [comment]
Thanks for your feedback @Haroenv .

I did use the latest version of Rheostat which is `v4.1.1`

**Comment by Haroenv** [comment]
The warnings are within Rheostat itself, https://github.com/airbnb/react-with-direction/issues/22 for example. Unfortunately I don't know which other slider to recommend at the moment, but anything more modern should do the trick, maybe https://github.com/chakra-ui/chakra-ui/tree/main/packages/slider

**Comment by Ekeu** [comment]
Ok thanks for the alternatives @Haroenv . Willing to stay within Algolia's services and widgets I think I'll rather switch to a Numeric menu.

**Comment by Haroenv** [comment]
I was a little unclear, I meant that you can plug any other open source slider implementation to InstantSearch, there's just no demo because there aren't good enough candidates to put in our documentation (while rheostat has flaws, it's probably the only one with all features)

**Comment by Ekeu** [comment]
Ok I get it!

**Comment by joshmu** [comment]
It's not ideal but one solution to this if you don't want to switch libraries is to provide empty data of the correct type to the required props for Rheostat.
<img width="682" alt="rheostat-algolia" src="https://user-images.githubusercontent.com/1970265/128275609-ec74d2a1-0a3a-4d67-8b6b-ee3516758be8.png">

**Comment by sarahdayan** [comment]
Hey @Ekeu, it looks like you found a solution. I'll close this issue, don't hesitate to reopen if needed.
