### ISSUE TITLE
Get index of hit (i.e. position in list - 0, 1, 2, 3...)

### ISSUE THREAD

**Issue by dancherb** [algolia/react-instantsearch#3060]
When mapping or rendering items in an array, you typically get an "index" as a second argument (e.g. 0, 1, 2...). How can we get this for a Hit?

```
<Hits hitComponent={hitProps => {
    console.log(hitProps) // only "hit" data
}}/>
```

**Comment by eunjae-lee** [comment]
Hi @dancherb
You can use `hitProps.hit.__position` which indicates the absolute position of the hits in results (which takes pagination into account.)

We recommend not to use inline component which could cause unexpected behaviors. You could also use `hit.objectID` depending on what you'd like to do with it.

**Comment by dancherb** [comment]
Thanks @eunjae-lee, this does the trick :)
