### ISSUE TITLE
Unexpected zoom behaviour when using Geosearch 

### ISSUE THREAD

**Issue by mema17** [algolia/react-instantsearch#3063]
**Describe the bug 🐛**
On some devices there is an unexpected zoom behaviour when using Geosearch.

- when I zoom in on the map, it automatically zooms out.
- when I try to move the map around it also zooms out.

This does not happen on all devices thought 🤔 

**To Reproduce 🔍**

1. Go to [react instant search demo :  tourism]( https://react-instantsearch.netlify.app/examples/tourism/?query=&page=1&configure%5BaroundLatLngViaIP%5D=true )
2. wait for the map to be fully loaded
3. try to zoom in (using the either the "+" icon on the map or the touchpad)
4. See error : on some devices the map will zoom in and immediately zoom out 
5. try to drag the map
6. See error : on some devices there is a zoom out effect too

**Expected behavior 💭**

no automatic zoom out after zooming in

https://user-images.githubusercontent.com/32900067/121660643-bd56e280-caa3-11eb-82d0-1c82a29dcb89.mov

no automatic zoom out when dragging the map

https://user-images.githubusercontent.com/32900067/121660663-c0ea6980-caa3-11eb-9498-3d37d8784a4c.mov

**Screenshots 🖥**

https://user-images.githubusercontent.com/32900067/121660802-deb7ce80-caa3-11eb-972b-718a2daf2ad7.mov

**Environment:**

 - OS: Windows 10 Professionnel Version : 2004 | 19041.867
 - Browser:  Google Chrome
 - Version: 91.0.4472.77

**Comment by Haroenv** [comment]
could you check if this is fixed by #3050 please? It's normally also possible to fix this by sizing the map with whole pixels (not floats), this is a google maps bug in the end

**Comment by mema17** [comment]
Hi, we have tested the fix on [#3050](https://github.com/algolia/react-instantsearch/pull/3050) and the bug does not occur anymore 😃

**Comment by mema17** [comment]
Would you know when this fix is going to be released  😄  ?

**Comment by Haroenv** [comment]
@mema17, can you try out the changes I did to that PR? Once you verify I'll merge and release

**Comment by mema17** [comment]
Thank you so much for merging this PR, we checked our app and there is no weird zoom behavior anymore 😃
