### ISSUE TITLE
Apply Filters from Refinement list Using Configure

### ISSUE THREAD

**Issue by rajaroni** [algolia/react-instantsearch#3064]
Hello , I'm selecting filters from Refinement list and getting list like this
`"color_family` `":["gray","blue"]`
Now when i pass this list in Configure filters it does not apply
`<Configure
        index={index}
        query={query}
         filters= {newSearchState?.refinementList}
      />
`

What am i doing wrong?

**Comment by Haroenv** [comment]
is what you're looking for the `defaultRefinement` prop on the refinement list itself?

**Comment by rajaroni** [comment]
No. When user selected filters items from RefinementList then i get the result in this format
`"color_family ":["gray","blue"]`
Then i pass this result into my Configure Component like this 
`<Configure index={index} query={query} filters= {newSearchState?.refinementList} />   // refinementList ={"color_family ":["gray","blue"]} `

But filters are not applying. What is the issue?

**Comment by Haroenv** [comment]
Can you make a sandbox with what you currently have, I'm not sure I fully understand the goal :)

**Comment by rajaroni** [comment]
I dont want to use VirtualRefinementList

https://codesandbox.io/s/focused-wood-pldwt?file=/App.js

**Comment by Haroenv** [comment]
Why don't you want to use VirtualRefinementList? It's required for a non-visible widget to have a refinement. You could also have it inside the modal component if you don't want to leak the implementation detail

**Comment by rajaroni** [comment]
How can i apply filters using Configure component?

**Comment by Haroenv** [comment]
You have to translate the filter from search state to one that's actually valid for Algolia, like this approximately: https://codesandbox.io/s/gifted-chaplygin-iqfw7?file=/App.js

**Comment by rajaroni** [comment]
Thanks Alot. I was exactly looking for this. (Y)
