### ISSUE TITLE
[Next.JS] Is it possible to have multiple `findResultsState` ?

### ISSUE THREAD

**Issue by luizeboli** [algolia/react-instantsearch#3075]
**Describe the bug 🐛**

When using `findResultsState` in `getInitialProps` for more than one index, it'll always trigger a request in client-side for the second index declared in Page component.

**To Reproduce 🔍**

1. Go to https://codesandbox.io/s/tender-johnson-ns41t
2. Open developer tools, Network tab
3. Notice there's a request to the second index `instant_search_price_desc` in client-side
4. You can swap the rendering order of the components in `IndexPage`, it'll always trigger a request for the second one.

**Expected behavior 💭**

It retrieves data in SSR successfully and doesn't trigger a request in client-side when using multi index.

**Environment:**

 - OS: MacOS
 - Browser: Chrome
 - Version 91

**Comment by luizeboli** [comment]
I've created a sandbox to reproduce this. Notice that in client-side theres always a request to get `instant_search_price_desc` index

https://codesandbox.io/s/tender-johnson-ns41t

**Comment by luizeboli** [comment]
It may be related to https://github.com/algolia/react-instantsearch/issues/2964

**Comment by Haroenv** [comment]
Could I know why you're rendering two InstantSearch instances? This will also do two queries on the frontend, since they aren't related. If you reorganise the app like this:


```
InstantSearch
  Index(first)
  Index(second)
```

You will only have one request been done, and since there's only one InstantSearch instance, the findResultsState can also not be confused. 

Apart from that, findResultsState isn't designed to run more than once, unfortunately the search client cache only gets filled by one of the two (the first mounted one), and thus you'll miss the second cache.

**Comment by luizeboli** [comment]
Hi @Haroenv 

I was doing this way,  using a single InstantSearch and the Index component, but the second index was still triggering a new request on client side.

I did not know that findResultsState can only run once by design. This info isnt in documentation, at least where I read.

So theres no way of getting SSR to work with more than one index at the same page?

Thank you for clarifying

**Comment by Haroenv** [comment]
Looking at the sandbox, you're doing:

```
  InstantSearch
  InstantSearch
```

instead of:

```
InstantSearch
  Index
  Index
```

The second form is preferred, as it will batch the network requests, and cost less (you pay per network request, not per query on the latest plans) on your side.

With different search clients you could solve it too in theory, you're right

**Comment by luizeboli** [comment]
@Haroenv 

I understand that the best way of doing that is be using a single `InstantSearch`, my question is:

In `getInitialProps` I can only pass one index to `findResultsState`, so I cant get SSR to work with multiple indexes, because `findResultsState` wasn't designed to work this way, right?

**Comment by Haroenv** [comment]
This is what I suggested, sorry if that's unclear, but the root index is the one that's requested, but it will still do multi-index behind the screens: https://codesandbox.io/s/compassionate-burnell-3ne0w?file=/pages/index.js

**Comment by luizeboli** [comment]
@Haroenv 

I didn't understand why there's no additional request in client-side to fetch the second index `instant_search_price_desc`, even you passing only the first one to `findResultsState`, can you please explain?

**Comment by Haroenv** [comment]
The `indexName` prop is used at the root of InstantSearch, in theory we would also not need to pass this, as it should be able to be inferred from the InstantSearch usage. In the context of multi-index, only the first index name is read from the props, the others are read from usage. Hope that makes things clearer @luizeboli :)

**Comment by Haroenv** [comment]
> in theory we would also not need to pass this

Using React InstantSearch hooks this is no longer an issue, as the indexName prop isn't asked for getServerState
