### ISSUE TITLE
optionalWords has no effect

### ISSUE THREAD

**Issue by dancherb** [algolia/react-instantsearch#3077]
I'm passing optionalWords as described here:
https://www.algolia.com/doc/api-reference/api-parameters/optionalWords/

This article describes overriding optionalWords for a search query like so:

```
index.search('query', {
  optionalWords: [
    'word1',
    'word2 word3'
  ]
})
```

I could find no examples of how to use this with react-instantsearch, so am passing optionalWords as a prop to `<Configure/>`, which seems to be the equivalent to passing options to index.search:

```
<Configure 
                filters=''
                optionalWords={['pool']}
/>
```

However, this has no effect on the hits result (whereas changes on other props on `<Configure/>` do change the hits result, indicating things are wired up correctly).

**Environment:**

 - OS: Windows
 - Browser: Chrome
 - react-instantsearch-dom: 6.11.0

**Comment by Haroenv** [comment]
Could you clarify how it has no impact? If you try the same query via the dashboard with the same optional words, do you see something else than on your InstantSearch application?

**Comment by dancherb** [comment]
> Could you clarify how it has no impact? If you try the same query via the dashboard with the same optional words, do you see something else than on your InstantSearch application?

Thanks for getting back. If I go onto the dashboard and toggle 'Add query parameter' -> Search -> 'Set All Query Words Optional' and enter the same term, then yes the results react accordingly, with items containing the optional word at the top.

When passing optionalWords on my React application, I'm deliberately testing with words that precisely match an item currently at a very low position, e.g. "pool", which would be expected to rank higher. However, the prop has no effect - the order of items does not change at all.

**Comment by Haroenv** [comment]
I'm assuming this was solved another way, and related to the query not doing what you expected, not to the parameter not applying.

If that's not the case, feel free to post a reproduction here!
