### ISSUE TITLE
External searchState updates don't pick up changes to `analyticsTags` or `ruleContexts`

### ISSUE THREAD

**Issue by Dane-Mutch** [algolia/react-instantsearch#3079]
**Describe the bug 🐛**

We are using the `<InstantSearch>` widget in a controlled fashion. We have a CTA which will update search state, and this update includes changes to the `analyticsTags` and `ruleContexts`. We do not see the updated configure tags reflected in the search.

**To Reproduce 🔍**

Whilst observing the network tab in devtools

1. Go to https://codesandbox.io/s/agitated-lumiere-pps41
2. Click on the CTA above the hits. The CTA amends the query and the configure to include analytics tags.

**Expected behavior 💭**

One search will be triggered, with both the query and analytics tags changes picked up. 

**Actual behaviour**

Two searches are triggered. One is triggered by the external state update which contains only the amendment to the query. As this is not picked up, a second search is then performed, containing the changes to the state dictated by the `<Configure>` component.

Please let me know if any other information is needed :+1:

**Comment by Haroenv** [comment]
This is indeed a little confusing, but Configure only takes its props in account for search parameters, it is only in the search state in case you want to conditionally keep other props based on a value in configure. 

Here's the workaround by passing the searchState as props to configure: https://codesandbox.io/s/boring-varahamihira-xbgt1?file=/src/App.js


As seen in the code here:

https://github.com/algolia/react-instantsearch/blob/225b12fe746af1eefc2b6e70df59817eb908149e/packages/react-instantsearch-core/src/connectors/connectConfigure.js#L18-L21

It only uses the props, and that has always been the case

**Comment by Dane-Mutch** [comment]
Hi @Haroenv thank you for the quick response and the clarification on the way this is intended to be done. 

I have looked at the sandbox you have provided. On clicking the CTA I still see two distinct search requests being made to the server. Do you have any recommendations on how to batch update query parameters alongside query/refinements in such a way which will only trigger a single request? My concern is the skewing of our analytics.

Many thanks again for your help :+1:

**Comment by Haroenv** [comment]
You're right, it's a little ugly, but you can debounce the search a tick (setTimeout 0) and the in-between query will not happen. 

Same sandbox, but now with the debounce: https://codesandbox.io/s/boring-varahamihira-xbgt1?file=/src/App.js

**Comment by Dane-Mutch** [comment]
Nice trick :+1: that works. Thanks again and kudos on a great library! Happy for the issue to be closed.

**Comment by Haroenv** [comment]
Glad this works as expected for you, I'll see if it can be put in the FAQs
