### ISSUE TITLE
[Typescript] HighlightResult types are incorrect

### ISSUE THREAD

**Issue by valtism** [algolia/react-instantsearch#3080]
**Describe the bug 🐛**

When data is nested, the HighlightResult type expects any object to be the tree node containing the match. This leads to incorrect types on the front end.

Nested Data:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/1286001/126116658-28c9ad27-0844-43f7-86a8-966e00fbc9dd.png">

Types don't work on the client:

<img width="603" alt="Screen Shot 2021-07-19 at 5 00 48 pm" src="https://user-images.githubusercontent.com/1286001/126116958-9ac70a1c-173e-4e71-91fa-76a9fdfefa16.png">

**Expected behavior 💭**

Allow HighlightResult type on leaf of Object / Array tree instead of expecting it on first object

**Screenshots 🖥**

**Environment:**

    "algoliasearch": "^4.10.3",
    "react-instantsearch-dom": "^6.12.0",

**Comment by eunjae-lee** [comment]
Hi @valtism,
Unfortunately there is no official type definitions available for React InstantSearch. What you're using is the community one at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by valtism** [comment]
Oh, you're correct. I saw the `.d.ts` file in a folder in `node_modules` called `react-instantsearch-core` without realising it was under another folder `@types` which is DefinitelyTyped. Thanks for clearing this up.
