### ISSUE TITLE
`distinct` / `facetingAfterDistinct`: either wrong counters or facets missing

### ISSUE THREAD

**Issue by catamphetamine** [algolia/react-instantsearch#3082]
Hi.
We're using your search component in our product and it has worked well so far, but now we're reaching its limits it seems.
Prevously, we had a dataset of "items", but now we've decided to show those items as "item groups" instead, something like a "product category" instead of an individual "product".

So, suppose we have: 

| Type | Category | Materials Available |
|-------|-----------|----------------------|
| T-shirts | Upper-wear | Cotton |
| Shirts | Upper-wear | Cotton, Silk |
| Polos | Upper-wear | Cotton, Polyester |
| Trousers | Lower-wear | Leather |
| Cargo Pants | Lower-wear | Jeans |

That would be 5 results total for "clothes types".

But, the requirements have changed and now the management wants to show search results grouped into "categories", so that it would be just 2 results: "Upper-wear" and "Lower-wear".

We've read in Algolia docs that there's a `distinct` proeprty that we could use to make `react-instantsearch` it output the results grouped by "category": for that, `category` attribute should also be marked as `distinct` in the Algolia admin panel.

So, after we've enabled `distinct` property, it seemingly works: "2 Results found".
Until you look at the sidebar filters: in the "Materials" filter we have:

* Cotton — 3
* ...

You can see how `3` is not `1` results users would see when checking the "Cotton" checkbox: where did it loose the other two? Users would be confused.

Then, we've read that there's this `facetingAfterDistinct` property.
So we've enabled that, and it seemingly fixed the counters:

* Cotton — 1
* ...

Except it didn't.

Previously the "Materials" filter showed:

* Cotton — 3
* Silk — 1
* Polyester — 1
* Leather — 1
* Jeans — 1

Now it only shows:

* Cotton — 1
* Leather — 1

Where did Silk, Polyester and Jeans go?
Apparently, with `facetingAfterDistinct` it first un-duplicates the results by the `distinct` attribute (`category`), leaving just Shirts and Trousers, and only then does it fill in the list of the available Materials.

What if a user wants specifically Silk? They wouldn't see it.

Is there any solution for such case?

**Comment by tkrugg** [comment]
Hi @catamphetamine. When doing a deduplication operation with `facetingAfterDistinct`, it'll compute the facets from the result set obtained after deduplication. Let's run through what this means:

#### Step 1: group result sets by category: we end up with two categories

Category: `Upper-wear`
| Type | Category | Materials Available |
|-------|-----------|----------------------|
| T-shirts | Upper-wear | Cotton |
| Shirts | Upper-wear | Cotton, Silk |
| Polos | Upper-wear | Cotton, Polyester |

Category: `Lower-wear`

| Type | Category | Materials Available |
|-------|-----------|----------------------|
| Trousers | Lower-wear | Leather |
| Cargo Pants | Lower-wear | Jeans |

####  Step 2: keep on result from each (case where `distinct: 1`)

Category: `Upper-wear`
| Type | Category | Materials Available |
|-------|-----------|----------------------|
| T-shirts | Upper-wear | Cotton |

Category: `Lower-wear`


| Type | Category | Materials Available |
|-------|-----------|----------------------|
| Trousers | Lower-wear | Leather |

####  Step 3: compute facets:

| Type | Category | Materials Available |
|-------|-----------|----------------------|
| T-shirts | Upper-wear | **Cotton** |
| Trousers | Lower-wear | **Leather** |

Now we end up with only **Cotton** and **Leather**  in the facets.

The behaviour you're describing seems to follow the spec.

**Comment by catamphetamine** [comment]
@tkrugg Yes, thanks, this is exactly how we imagined it does it under the hood.
But, even though mathematically it seems "in accordance with the spec", from the UX point of view it looks like a bug: there are Silk clothes in our catalog but the user won't even see "Silk" option in the filters.
Is there any fix for that, or will we have to abandon the idea of using `facetingAfterDistinct` and just hide the filter counters via CSS so that they don't confuse the users?

**Comment by tkrugg** [comment]
I think what I would do is index categories in a separate index, and use [`partialUpdateObject`](https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/?client=javascript) to populate a `materialsAvailable` attribute.

```json
{ "category": "Upper-wear", "materialsAvailable": [ "Cotton", "Silk", "Polyester" ] }
``` 

Then of course, not use the `distinct`. That should give you the counts you want to see.

**Comment by catamphetamine** [comment]
@tkrugg Aha, clever solutions both ways, thanks.

* Either generate records like:

```js
{ 
  type: 'Shirts', 
  category: { 
    name: 'Upper-wear',
    types: ['Shirts', 'T-Shirts', 'Polos']
  }
}
```

and then filter by `category.types` instead of `type` attribute. I tested with numerical attributes and range filters and those seem to work too: `prices: [100, 200, 300, 400]` can still be filtered using a range filter slider.

* Or, instead of using `distinct`, populate the indexes not with product type records, but with category records, each category property being an array consisting of all possible values of the corresponding property of the product types in this category:

```js
{
  name: 'Upper-wear',
  types: ['Shirts', 'T-Shirts', 'Polos'],
  // uniq(['Cotton'].concat(['Cotton', 'Silk']).concat(['Cotton', 'Polyester']))
  materials: ['Cotton', 'Silk', 'Polyester'],
  ...
}
```

Both approaches seem possible, the second one being more rational due to the savings in Algolia monthly record hosting costs because this way there're several times less records hosted.
