### ISSUE TITLE
`connectStateResults` doesn't allow to use click analytics

### ISSUE THREAD

**Issue by ksntcrq** [algolia/react-instantsearch#3085]
**Describe the bug 🐛**

When using `connectStateResults` in combination with `<Configure /* ... */ clickAnalytics />` and `connectHitInsights`, Algolia is unable to infer `queryID`.

**To Reproduce 🔍**

https://codesandbox.io/s/thirsty-villani-leyzm?file=/src/App.js

Click on "click" and you'll see the error.

**Expected behavior 💭**

Two options:

* `connectStateResults` should add `__queryID` to each current hit
* the error should be different

When adding a breakpoint, we can see that the results do have a `queryID` attached to them, so it should be fairly straightforward to implement option 1?

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/7127784/128494555-37cd4057-afed-4351-9aa4-491b86307c46.png)

**Environment:**

 - OS: Mac
 - Browser: Chrome
 - Version: 92.0.4515.131

**Additional context**

I need to use `connectStateResults` and not `connectHits` because in the same component I need to know if Algolia is currently `searching` or not. I'd appreciate an alternative for that if you can think of anything.

**Comment by Haroenv** [comment]
in the mean time, you can use https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/connectors/connectHits.js#L59-L68, the `addAbsolutePositions` and `addQueryID` functions with `hits`

**Comment by ksntcrq** [comment]
@Haroenv These functions don't seem to be exported from `react-instantsearch-dom` nor `react-instantsearch-core`?

**Comment by Haroenv** [comment]
the implementation is quite simple actually: 

https://github.com/algolia/react-instantsearch/blob/6f868ee388bb47ba0ef1cea3e15e658f1859fe9d/packages/react-instantsearch-core/src/core/utils.ts#L66-L81

https://github.com/algolia/react-instantsearch/blob/6f868ee388bb47ba0ef1cea3e15e658f1859fe9d/packages/react-instantsearch-core/src/connectors/connectHits.js#L59-L68

this could be implemented in a connectStatResults without much effort normally @ksntcrq

**Comment by ksntcrq** [comment]
All right, I thought it would be more sustainable to use the ones implemented in the package already. But understood then, I will include them in our own codebase, thanks!

**Comment by wjpg** [comment]
Also encountered this issue and have had to duplicate the helpers. 

This workaround is made even more sketchy as the `searchResults` type does not have a `queryID` - so I have to override TS warnings when using that value.

Is there a proper fix planned, and perhaps an update to the `searchResults` type?

**Comment by tkrugg** [comment]
Hi there, unfortunately `connectHitInsights` only works with with `<Hits />` and `<InfiniteHits />`, and their connector equivalent `connectHits` and `connectInfiniteHits`. This is not currently supported. 
If you explain your use-case maybe we can try to find a workaround leveraging `<Hits />` ?
If you insist on using searchState,  the best solution is the one pointed out by @Haroenv: https://github.com/algolia/react-instantsearch/issues/3085#issuecomment-894213349 earlier in this thread.

I'll look into having the `queryID` reflected in [SearchResults](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-instantsearch-core/index.d.ts#L696) and send PR shortly. But this is unreleated so this isue can already be closed.
