### ISSUE TITLE
Type checking of hitComponent props of Hits and InfiniteHits should include elementType

### ISSUE THREAD

**Issue by rupertchen** [algolia/react-instantsearch#3086]
**Describe the bug 🐛**

Passing a `hitComponent` that is not a functional component results in a type check warning.  Should the type be [elementType] (introduced in [15.7.0])?

[elementType]: https://github.com/facebook/prop-types/blob/d62a775b78085e38805d34f27295798bcf54987c/README.md#L88
[15.7.0]: https://github.com/facebook/prop-types/blob/d62a775b78085e38805d34f27295798bcf54987c/CHANGELOG.md#user-content-1570

**To Reproduce 🔍**

1. Create a non-functional component.  For example by using `React.memo(...)` which returns an object:

    ```javascript
   const MyHit = React.memo((props => (<div>{props.hit.name}</div>)));
   ```

2. Use the non-functional component in Hits or InfiniteHits:

   ```javascript
   <InfiniteHits hitComponent={MyHit} />
   ```

3. Perform search
4. Open console in dev toolbar to see warning.  For example:

   ```
   Warning: Failed prop type: Invalid prop `hitComponent` supplied to `InfiniteHits`.
       in InfiniteHits (created by Translatable(InfiniteHits))
       in Translatable(InfiniteHits) (created by AlgoliaInfiniteHits(Translatable(InfiniteHits)))
       in AlgoliaInfiniteHits(Translatable(InfiniteHits)) (created by Context.Consumer)
       in ConnectorWrapper (at Demo.js:62)
       in InstantSearch (at Demo.js:51)
       in section (at Demo.js:41)
       in Demo (at App.js:164)
   ```

A live example helps a lot! We have a simple online template for you to use for your explanations:

> https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch

https://codesandbox.io/s/vigilant-hofstadter-kzsib?file=/src/App.js

```
Warning: Failed prop type: Invalid prop `hitComponent` of type `object` supplied to `Hits`, expected `function`.
    in Hits (created by AlgoliaHits(Hits))
    in AlgoliaHits(Hits) (created by Context.Consumer)
    in ConnectorWrapper (at App.js:48)
    in div (at App.js:41)
    in div (at App.js:36)
    in InstantSearch (at App.js:35)
    in div (at App.js:34)
    in div (at App.js:21)
    in App (at src/index.js:6)
```

**Expected behavior 💭**

I expect there to be no warnings.

**Environment:**

All environments where warnings in console are visible.

**Additional context**

The current implementation in [InfiniteHits] also includes `PropTypes.string` which seems incorrect.

[InfiniteHits]: https://github.com/algolia/react-instantsearch/blob/6f868ee388bb47ba0ef1cea3e15e658f1859fe9d/packages/react-instantsearch-dom/src/components/InfiniteHits.js#L65

**Comment by Haroenv** [comment]
FYI, the typescript types aren't maintained here, but by the community on DefinitelyTyped, so it's possible the types aren't correct

**Comment by Haroenv** [comment]
A string actually isn't a wrong type for the PropTypes, as you could do `<InfiniteHits hitComponent="my-custom-element" />` that would accept the hit prop.
