### ISSUE TITLE
Conditional Requests not working with connectInfiniteHits

### ISSUE THREAD

**Issue by meandillar** [algolia/react-instantsearch#3088]
**Describe the bug 🐛**

When implementing a proxy to perform condition requests as described in the docs [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/react/#mocking-a-search-request) custom formatted responses are not updating the component with the results.

**To Reproduce 🔍**

Here's a sandbox: https://codesandbox.io/s/wonderful-wozniak-gs7ri?file=/src/App.js which is using a customised search client and returning a formatted response as per docs. On load this should show one result, but no hits are being passed through to the component.

**Expected behavior 💭**

An InfiniteHits component connected with connectInfiniteHits should receive mocked hits returned from the search function within a custom search client.

**Additional context**

It seems to work with the connectHits rather than connectInfiniteHits in my project, although I tried it in the sandbox and it didn't work for either. I'm using react-instantsearch-dom 6.8.2

**Comment by Haroenv** [comment]
Not sure where you got that static response from, but `results` is an array: https://codesandbox.io/s/hopeful-heyrovsky-hrufg

**Comment by meandillar** [comment]
Wow, my bad. It is indeed working as expected if I pass the correct data, thanks so much!
