### ISSUE TITLE
Ability to get results count for sub-ranges of a RangeSlider component

### ISSUE THREAD

**Issue by braydensterrett** [algolia/react-instantsearch#3089]
**Is your feature request related to a problem? Please describe 🙏**

I'm attempting to create a histogram styled RangeSlider component similar to the one found on Airbnb's filtering. In order to do so, I need to be able to understand how many results there are between specific breakpoints within the min and max of the RangeSlider component. 

**Describe the solution you'd like 🤔**

It would be great to be able to take the min and the max provided in the RangeSlider component and then fire off a series of queries to the index that would return counts for sub ranges within the min and the max. For instance, if I've got a min of 0 and max of 300, I'd like to be able to know:

How many items are between 0-100,
How many items are between 101-200,
How many items are between 201-300

If I am able to get this count data, I can then use it with [chartjs]([https://www.chartjs.org/) to display a nice histogram above the default slider component.

The main rationale for this functionality is to give the user a better idea of where most of the stock lies for the filter that they have picked so they have a better chance at finding relevant results through their filtering.

**Describe alternatives you've considered ✨**

I've considered implementing a refinement list and range slider combo, but I don't think the refinement list will work super well for my use case. I'm curious if anyone else has ever tried to implement this and whether they had any luck doing so..

**Additional context**

Here's a screenshot of the slider concept I am hoping to achieve:

![Screen Shot 2021-08-17 at 11 57 08 AM](https://user-images.githubusercontent.com/7805772/129768757-c0ba0042-58ad-4756-9c80-4e06071b404b.png)

**Comment by Haroenv** [comment]
Unfortunately we don't have that information available in the index today. A workaround is to actually save the ranges as facets:

```json
{
  "range": "0010-0020"
}
```

Then you can use facet count to create these buckets and the diagram you show, but there's no engine feature for bucketing numeric facets, only the min/max/avg is returned

**Comment by Haroenv** [comment]
As the information isn't available, using a static set of ranges (string) is the only option for now.
