### ISSUE TITLE
InfiniteHits with multi-index: hits don't update

### ISSUE THREAD

**Issue by noclat** [algolia/react-instantsearch#310]
When using `<InfiniteHits />` inside a multi-index setup, hits inside `<Index>` don't reload when `Load more` has been pressed at least once. The first dataset behaves correctly.

The expected behavior is: when I load more results for the second dataset, and then edit the query in the searchbox, hits update and only display page 1.

Here's the same code as the multi-index example from this repo, slightly edited to add `<InfiniteHits />` and make it fit in a single page for tests purposes:

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { InstantSearch, InfiniteHits, SearchBox, Index, Configure } from 'react-instantsearch/dom';
import 'react-instantsearch-theme-algolia/style.css';

const App = () =>
  <InstantSearch
    appId="latency"
    apiKey="6be0576ff61c053d5f9a3225e2a90f76"
    indexName="bestbuy"
  >
    <Configure hitsPerPage={ 5 } />
    <SearchBox />
    <p>Results in first dataset</p>
    <InfiniteHits />
    <Index indexName="ikea">
      <p>Results in second dataset</p>
      <InfiniteHits />
    </Index>
  </InstantSearch>;
  
ReactDOM.render(<App />, document.getElementById('root'));
```

Just in case: Chrome 60.0.3112.113 MacOS 10.12.6.

**Comment by mthuret** [comment]
That's a tricky bug :)

This happen because the page is not reseting to 1 when using the searchbox. 
Currently, every "shared" widgets doesn't reset the page to 1 for all the indices. 

Possible way to fix it: when refining on "single" indice, check if the search state contains indices. If yes, reset also the page for them.
