### ISSUE TITLE
Multi-index reorder: HitsPerPage don't update

### ISSUE THREAD

**Issue by noclat** [algolia/react-instantsearch#311]
I have a multi-index results page, with hits bundles (1 bundle = 1 index) and I'd like to allow users to reorder the bundles dynamically (on my own version, it's drag and drop, but for the demo purpose it's a simple button). 

<img width="752" alt="screen shot 2017-09-05 at 16 57 08" src="https://user-images.githubusercontent.com/1834312/30067541-66a0c304-925b-11e7-82b8-921738c34769.png">

To reproduce the bug, you just have to click on “Reverse indices order” after running the code below. The default state is:
1. BestBuy: 3 hits
2. Ikea: 5 hits

When clicking on “Reverse indices order”, the result is:
1. Ikea: 3 hits
2. BestBuy: 5 hits

but we were expecting:
1. Ikea: 5 hits
2. BestBuy: 3 hits

Here's the demo code:

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { InstantSearch, Hits, SearchBox, Index, Configure } from 'react-instantsearch/dom';
import 'react-instantsearch-theme-algolia/style.css';


const Indices = {
  'bestbuy': {
    'indexName': 'bestbuy',
    'hitsPerPage': 3,
  },
  'ikea': {
    'indexName': 'ikea',
    'hitsPerPage': 5,
  }
}
class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      indices: Object.keys(Indices),
    };
    this.reverseIndices = this.reverseIndices.bind(this);
  }

  reverseIndices() {
    this.setState({
      indices: this.state.indices.reverse(),
    });
  }

  render() {
    return (
      <InstantSearch
        appId="latency"
        apiKey="6be0576ff61c053d5f9a3225e2a90f76"
        indexName={ this.state.indices[0] }
      >
        <SearchBox />
        <button type="button" onClick={ this.reverseIndices }>Reverse indices order</button>
        { this.state.indices.map((indexName, key) => (
          <Index key={ key } indexName={ indexName }>
            <Configure hitsPerPage={ Indices[indexName].hitsPerPage } />
            <p>Results in <b>{ indexName }</b></p>
            <Hits />
          </Index>
        ), this)}
      </InstantSearch>
    );
  }
}

ReactDOM.render(<App />, document.getElementById('root'));
```

Chrome 60.0.3112.113 MacOS 10.12.6.

**Comment by noclat** [comment]
Update: actually even the Hits don't move, only the titles change.

**Comment by mthuret** [comment]
I believe that this is also a consequence of this issue: https://github.com/algolia/react-instantsearch/issues/304

Closing it :)
