### ISSUE TITLE
How to pass component "ref" through connectors

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [algolia/react-instantsearch#3126]
**Is your feature request related to a problem? Please describe 🙏**

We are currently using a custom "Input" in our application for which we are listening the "ref" to do some checks against it later.
Now, we want to connect this component to Algolia using "connectSearchBox".
However, are not successful yet (still trying). We have the same error as this ticket : #2984.

**Describe the solution you'd like 🤔**

Maybe "connectors" should use/allow ForwardRef ?

**Describe alternatives you've considered ✨**

We did not find any alternatives yet. If you have one, we will be happy to read.

Yours faithfully,
LCDP

**Comment by sarahdayan** [comment]
Hi there @LeComptoirDesPharmacies!

Connectors don't forward refs to the connected component, however they forward all props, including those that aren't part of the widget's original interface. Therefore, you can work around the issue by passing a ref via a custom prop.

```jsx
// ...

function SearchBox({ currentRefinement, isSearchStalled, refine, inputRef }) {
  return (
    <form noValidate action="" role="search">
      <input
        ref={inputRef}
        type="search"
        value={currentRefinement}
        onChange={(event) => refine(event.currentTarget.value)}
      />
      {/* ... */}
    </form>
  );
}

const CustomSearchBox = connectSearchBox(SearchBox);

function App() {
  const inputRef = useRef(null);

  return (
    <InstantSearch indexName="your_index" searchClient={searchClient}>
      <CustomSearchBox inputRef={inputRef} />
    </InstantSearch>
  );
}
```

**See demo:** https://codesandbox.io/s/old-butterfly-3xfz4?file=/CustomSearchBox.js

**Comment by LeComptoirDesPharmacies** [comment]
Hi @sarahdayan,

Thanks for the information and this workaround !
For thus who encounter this same issue, here is a second workaround combining "ForwardRef" with "connectSearchBox" :

```
const SearchMenuContainer = React.forwardRef(
  ({ refine, ...rest }, ref) => {
    return (
      <TextInput
        onChange={(event) => {
          refine(event.target.value);
        }}
        ref={ref}
      />
    );
  },
);

const SearchBox = React.forwardRef((props, ref) => {
  const ConnectedSearchMenuContainer = React.useMemo(
    () => {
      return connectSearchBox(innerProps => (
        <SearchMenuContainer {...innerProps} ref={ref} />
      ));
    },
    [ref],
  );

  return <ConnectedSearchMenuContainer {...props} />;
});
```

Yours faithfully,
LCDP

**Comment by DavydVeremchuk** [comment]
@LeComptoirDesPharmacies man, you saved me so hard. 
Thank you for posting your own workaround with `rowardRef`!
