### ISSUE TITLE
Is there a way to get get the rankinfo of the results?

### ISSUE THREAD

**Issue by alexvandervegt** [algolia/react-instantsearch#3131]
How can i get the info of this attributes from react instant search?

https://www.algolia.com/doc/api-reference/api-parameters/getRankingInfo/

especially "nbTypos"

**Comment by sarahdayan** [comment]
Hey @alexvandervegt! The [`getRankingInfo`](https://www.algolia.com/doc/api-reference/api-parameters/getRankingInfo/) parameter is a search parameter, so you can pass it like any other Algolia search parameter using the [`Configure`](https://www.algolia.com/doc/api-reference/widgets/configure/react/) widget.

Here's a sandbox implementing it: https://codesandbox.io/s/elastic-shannon-27pdc

You can see in the Algolia response that every hit now contains a `_rankingInfo` object that includes `nbTypos` and other ranking information.
