### ISSUE TITLE
Pagination Not Working

### ISSUE THREAD

**Issue by bharamalhusen** [algolia/react-instantsearch#3134]
Describe the bug 🐛
- I update the version v5 to v6 latest and after that when
1)  I load InstantSearch first time getting hits successfully then 
2) scroll to bottom and call refine a method data not loading
3) onSearchStateChange return searchState = { "page": NaN }

Versions
"react-instantsearch-native": "6.12.1",
"algoliasearch": "4.10.5",
 "react-native": "0.65.1",
 "react": "17.0.2",
 
 sample code:
```
   const onEndReached = () => {
    if (hasMore) {
      refine();
    }
  };
```
  
 Expected Behavior
 Must Be load pages 1,2,3... as onEndReached accordingly

**Comment by Haroenv** [comment]
Sorry, I’m not sure if this is documented correctly, but the method is called refineNext

**Comment by sonawanemayur23** [comment]
@bharamalhusen  I'm facing same issue. How you mange to fix it?

**Comment by bharamalhusen** [comment]
I used **refineNext** and it will work @sonawanemayur23

**Comment by sonawanemayur23** [comment]
Thanks for response. Already using refineNext but i'm also using Infinite scroll. Where I'm getting data till 11 pages but nbPages are 21. After 11 I can see Loading but data is not queried.

**Comment by Haroenv** [comment]
that's an unrelated issue @sonawanemayur23, what I'm thinking is that page 20 is the maximum showable with pagination limited to: https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/pagination/js/#overriding-the-default-limits
