### ISSUE TITLE
Range refine() values should be able to be any valid two numbers

### ISSUE THREAD

**Issue by braydensterrett** [algolia/react-instantsearch#3139]
**Is your feature request related to a problem? Please describe 🙏**

Currently you cannot have a RangeInput and call `refine()` and pass a `min` value smaller than the current `min` of the Algolia query. Nor can you call `refine()` and pass a `max` value larger than the current `max` of the Algolia query. However, you CAN pass a `min` value larger than the `max` of the Algolia query.  A couple examples:

```javascript
function CustomRange({ refine, min = 10, max = 20 }) {
  ...

  const someFunction = () => {
    refine({ min: 5, max: 15 }) //Uncaught Error: You can't provide a min value less than range.
  }

  const someOtherFunction = () => {
    refine({ min: 15, max: 25 }) //Uncaught Error: You can't provide max value greater than range.
  }

  const someOtherOtherFunction = () => {
    refine({ min: 100, max: 15 }) //Just fine, no errors
  }

  const someOtherOtherOtherFunction = () => {
    refine({ min: 15, max: 5 }) //Just fine, no errors
  }
}
```

**Describe the solution you'd like 🤔**

It would be great to be able to provide whatever values I want to refine, regardless of if they are in the min/max range.. 

I am using this in a price range slider filter and I want to be able to have the slider be able to have low and high values outside of the range of prices that my products have. I've hacked around this in _some ways_, but it all just feels really unnecessary if Algolia can just briefly check if the values are inside the current allowed min and max values provided and then structure the query according to their validity, range-wise. 

Another, actually more important, problem this poses is being able to keep URL state. The filter is constantly reverting back to the min and max values even though the user has moved the thumbs to specific places on the track because in order to not get JS errors you must set the refined values to be `undefined` BUT only when the min is lower than the query min or the max is higher than the query max and therefore your URL state doesn't update with the values even if you hack the slider around it! 

**Describe alternatives you've considered ✨**

I believe I have tried actually every other possible solution at this point to hack around Algolia not allowing this behavior and absolutely nothing has worked perfectly. 

**Additional context**

**Comment by sarahdayan** [comment]
Hey @braydensterrett!

By default, the `RangeSlider` helps you refine based on the available values in your search results for a given attribute. React InstantSearch uses the minimum and maximum values for that attribute, provided by the Algolia search engine.

![Capture d’écran 2021-10-01 à 15 18 44](https://user-images.githubusercontent.com/5370675/135626722-54a7abc8-aab1-41dd-a79b-c02a1b08d8b2.png)

This default behavior ensures that no matter how you refine with the `RangeSlider`, you always have results.

If you want to use a wider or narrower range in your front-end, you can pass `min` and `max` props on your connected widget. This lets you control what range is displayed and what values you can refine on.

Here's an example: https://codesandbox.io/s/serene-platform-68dz6?file=/src/App.js:2208-2283

Here, the specified `min={0}` and `max={2000}` props are broader than the total range of values for the `price` attribute in the targeted index. If you try refining on `1000-2000` with the slider, you will get no results, but you won't receive any errors. This lets you perform custom logic or display whatever makes sense in your app when such a scenario happens.

Does this work for you, or would you expect to be able to refine _outside_ of the range, regardless of whether you've manually specified it? And if yes, can you please explain your use case a bit more?

**Comment by braydensterrett** [comment]
Ohhhhh wow, this makes so much more sense. I think this will absolutely do the trick for me. I see that the docs call this behavior out, in a way, but I didn't fully comprehend what they meant until your explanation here. Thanks a bunch for the speedy response!
