### ISSUE TITLE
Using searchState leads to query duplication in 4.11

### ISSUE THREAD

**Issue by fughur** [algolia/react-instantsearch#3187]
## 🐛 Bug description

We want to use the url-sync recipe described in [the docs](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/#basic-urls).
It works fine with [3.33.0](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/React%20InstantSearch/routing-basic?file=/package.json) but leads to a query dublication in [recent (4.*)](https://codesandbox.io/s/xenodochial-rain-tsi6u?file=/package.json:268-274) versions.
Since currently we're running really large requests (2000+ items per request) I'm wondering that this kind of dublication could lead to a serious performance issues.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Open the [4.11.0 playground](https://codesandbox.io/s/xenodochial-rain-tsi6u?file=/package.json:268-274)
2. Click on any filter checkbox
3. Observe that each query are actually running twice

**Live reproduction:**

### 4.11.0 (broken)
https://codesandbox.io/s/xenodochial-rain-tsi6u?file=/package.json:268-274
![FL8B4HL64V](https://user-images.githubusercontent.com/40459362/139699499-b82cd883-699e-467c-b477-530b455a4fd0.gif)

### 3.33.0 (works well)
(copied from documentation)
https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/React%20InstantSearch/routing-basic?file=/package.json
![0vP4NVjDIQ](https://user-images.githubusercontent.com/40459362/139700728-f3d019a2-a070-47b4-b862-ff2e35572938.gif)

## 💭 Expected behavior
There is no query dublication happen in controlled searchState case

## Environment

- OS: Win10
- Browser: Chrome
- Version: 95.0.4638.54

## Additional context
There is no query dublication happen in recent versions if I remove the controlled searchState prop from the component.
![LKWM1YgkD1](https://user-images.githubusercontent.com/40459362/139704603-3cd502f8-41d6-449d-945b-52b9b1f630e1.gif)

**Comment by sarahdayan** [comment]
Hi @fughur!

The sandbox linked from the documentation is outdated, and doesn't match the code in the page (which also has some issues). I've updated it and it seems to be working: https://codesandbox.io/s/fervent-orla-xqxvw?file=/src/App.js

I'll fix the sandbox and documentation right away.
