### ISSUE TITLE
React Instant Search Native not working on android

### ISSUE THREAD

**Issue by Csierram96** [algolia/react-instantsearch#3196]
## 🐛 Bug description
React Instant Search Native not working on android. It works perfectly on IOS. Is there any installation step required for Android, there isnt any documentation on this

## Environment

- OS: Android
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by francoischalifour** [comment]
What errors do you get? And what React InstantSearch version are you using?

**Comment by Csierram96** [comment]
it doesnt return any hits, but on Ios works perfectly. It doesnt throw any error but doesnt return any hits. 

 "react-instantsearch-native": "^6.15.0",
"react-instantsearch": "^6.15.0",

**Comment by Haroenv** [comment]
@Csierram96, please make a reproducible example. Is this also the case for the React InstantSearch demo in this repository for you?

**Comment by Csierram96** [comment]
The react native demo is made with Expo, i'm not currently using expo. 
How can i make a reproducible example?

**Comment by tkrugg** [comment]
Hi @Csierram96 If you can reproduce your issue without Expo, just use React Native Web with codesandbox. It's easier and faster to compile IMO: https://codesandbox.io/s/n5y4rjjn0m?file=/src/App.js
If you need Expo to reproduce your issue, you can start of this codesandbox: https://codesandbox.io/s/react-native-expo-jj0d0

Please keep you example minimal, and make sure you don't disclose any admin api keys.
I'll close the issue while you prepare your example. Feel free to reopen when you're ready.
