### ISSUE TITLE
React 18 seems to break components using connectHits and Suspense

### ISSUE THREAD

**Issue by mellson** [algolia/react-instantsearch#3201]
## 🐛 Bug description

I have a custom component using connectHits. Inside this component I'm fetching data from another server using Relay.
This works fine in React 17, but it breaks in the React 18 beta.
The component wrapped in connectHits stops receiving hits after it has received data from Relay one time.

**Comment by mellson** [comment]
My issue goes away when using the Hooks package instead of the HOC's. But that would leave me needing to rewrite all the UI components and highlighters myself. Yikes... Do you have a rough idea when you'll ship UI along the Hooks package?

**Comment by Motoxpro** [comment]
Exact same issue for me. 17 works fine, 18 crashes. I am also using the HOCs

**Comment by Haroenv** [comment]
Thanks for mentioning, we haven't yet tried relay with suspense in combination with InstantSearch. Is it possible to make an example of a crashing behaviour? We have an example sandbox [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by mellson** [comment]
> Thanks for mentioning, we haven't yet tried relay with suspense in combination with InstantSearch. Is it possible to make an example of a crashing behaviour? We have an example sandbox [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!
> 
> I've also just tried out React 18 beta with the default setup and that seems to work: https://codesandbox.io/s/suspicious-ishizaka-wkqgc?file=/src/index.js

Thanks, I did try to [recreate this](https://codesandbox.io/s/suspense-react-18-idqvh) with vanilla React.Suspense - however that didn't fail. Will try to see if I can manage to do one with Relay soon

**Comment by tkrugg** [comment]
thanks @mellson, I'll close this in the meantime, but please reopen when you example with relay is ready: we'll happily take a look and help troubleshoot.

**Comment by mellson** [comment]
@tkrugg just tried to recreate this and the error has disappeared. Don't know if this is something on my end or due to updates in Algolia or the React RC. Anyways just glad it's fixed. Thanks for the feedback!

**Comment by Haroenv** [comment]
Thanks for keeping us updated. @Motoxpro, do you confirm, or have any failing examples?

**Comment by mellson** [comment]
> Thanks for keeping us updated. @Motoxpro, do you confirm, or have any failing examples?

Sorry, I spoke too fast. It's still broken for me. Will see if I can find time to recreate this (can't share the codebase I'm working on). Either that or move to an earlier version of React until the hooks package is ready with UI.

**Comment by mellson** [comment]
@Haroenv I was able to get an example going where the error is shown.

You need to change something in the CustomHits component to make it suspend, after the change algolia breaks in the same way as it do in my app.

See [example video here](https://cln.sh/oyO9Y6) and the [codesandbox is here](https://codesandbox.io/s/suspense-react-18-forked-6stuf?file=/src/CustomHits.js).

**Comment by Haroenv** [comment]
In your main application, does it also suspend only when you're changing code, or also in regular usage of the app?

As a workaround, is it possible to put the fallback/suspense boundary *inside* the custom hits instead of wrapping it around hits? If a widget is unmounted and remounted, it will cause a new network request, which isn't needed in this case as far as I can tell

**Comment by mellson** [comment]
@Haroenv In my application it suspends whenever I fetch data with Relay, so with regular use. I've tried that workaround it doesn't change anything. As soon as there has been a suspend Algolia breaks.

**Comment by mellson** [comment]
@Haroenv on second thought I think you're right about the workaround, I think I understood the question wrong on the first read. I could move the fallback boundary into the single hit component, I'll try that now. However that would, in my use case, cause a roundtrip to our relay server for each hit instead of the way it is now where it's one roundtrip for all hits at once.

**Comment by Haroenv** [comment]
If I lay out the data like this, there's only one fetch happening as far as I can tell, https://codesandbox.io/s/suspense-react-18-forked-w4ouj?file=/src/App.js (or do I miss something?)

**Comment by mellson** [comment]
@Haroenv thanks - that did indeed work! So until the issue is fixed or the Hooks package has UI components this is a fair compromise for us. Thanks for your help.

**Comment by Haroenv** [comment]
Hooks indeed doesn't have UI components yet, but our example has all implemented hooks as a component (that fits the same dom as before) as well: https://github.com/algolia/react-instantsearch/tree/master/examples/hooks/components

**Comment by mellson** [comment]
> 

In our real app I need to fetch some more data from our server for each hit. That part is not included in the codesandbox example.
