### ISSUE TITLE
Infinite scrolling not working when 'searchState' has data

### ISSUE THREAD

**Issue by Ajmal0197** [algolia/react-instantsearch#3209]
## 🐛 Bug description

Infinite scrolling is not working in 'connectInfiniteHits' when 'searchState' of 'InstantSearch' has data in it. When searchState is null infinite scrolling works.

Code:

```
      <InstantSearch
        searchState={refinementListFilter}
        searchClient={searchClient}
        indexName={sortValueState}>
        <InfiniteHits />
        <VirtualWidgets />
        <FilterSortComponent />
      </InstantSearch>
      
      
        const InfiniteHits = connectInfiniteHits(({ hits, hasMore, refineNext }) => {
    const onEndReached = () => {
      console.log('onEndReached', hasMore, refineNext);
      if (hasMore) {
          refineNext();
      }
    };

    return (
      <FlatList
        data={hits}
        ref={flatListRef}
        renderItem={VehicleListItem}
        style={{
          paddingHorizontal: wpx(15),
          paddingVertical: hpx(20),
        }}
        onEndReached={() => onEndReached()}
        onEndReachedThreshold={0.1}
        keyExtractor={item => item.id}
      />
    );
  });

```

**Comment by Haroenv** [comment]
could you make this into a full example @Ajmal0197? I'm not sure what you mean with "data in it". We have a starter available here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

**Comment by tkrugg** [comment]
Hi @Ajmal0197 I'll close this for now. Please do reopen when you can provide [an example reproducing the issue](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch).).

**Comment by Ajmal0197** [comment]
Hi @Haroenv @tkrugg 
I am using Algolia in react native. Plz provide example for **connectInfiniteHits** where **searchState** is also used in INSTANTSEARCH. You can check [above](https://github.com/algolia/react-instantsearch/issues/3209#issue-1062265964) what I mean.

**Comment by Ajmal0197** [comment]
> could you make this into a full example @Ajmal0197? I'm not sure what you mean with "data in it". We have a starter available here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch). Thanks!

Data in it means refinementList variable, for below infinte scroll doesn’t work.

@Haroenv @tkrugg 
Thanks in advance... :)


```
const refinementList = {
        sortBy: state.sortValueState,
        refinementList: {
          body_type: state.vehicleTypesState,
          brand: state.vehicleMakesState,
          model: state.vehicleModelState,
          spec: state.vehicleSpecsState,
        },
        range: {
          price: state.priceRangeFilter,
          model_year: state.yearRangeFilter,
          km: state.mileageRangeFilter,
        },
      }
      
            <InstantSearch
        searchState={refinementListFilter}
        searchClient={searchClient}
        indexName={sortValueState}>
        <InfiniteHits />
        <VirtualWidgets />
        <FilterSortComponent />
      </InstantSearch>
```

**Comment by Haroenv** [comment]
Hi @Ajmal0197, unfortunately this isn't enough code to reproduce the issue. Could you please reproduce in the sandbox linked earlier and send that link?

**Comment by Ajmal0197** [comment]
> const refinementList = {
>         sortBy: state.sortValueState,
>         refinementList: {
>           body_type: state.vehicleTypesState,
>           brand: state.vehicleMakesState,
>           model: state.vehicleModelState,
>           spec: state.vehicleSpecsState,
>         },
>         range: {
>           price: state.priceRangeFilter,
>           model_year: state.yearRangeFilter,
>           km: state.mileageRangeFilter,
>         },
>       }

@Haroenv Please check if this helps.

https://snack.expo.dev/@ajmal_hasan0197/algolia-infinitehits

**Comment by Haroenv** [comment]
Thanks but this example still has many unrelated errors. Could you not set it up in a way where the only error is the one you opened this issue for? you can put the example on GitHub if that's easier
