### ISSUE TITLE
InfiniteList has been broken since 6.8.0

### ISSUE THREAD

**Issue by iamclaytonray** [algolia/react-instantsearch#3244]
## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/react-instantsearch-infinitehits-with-hook-forked-t9zy6
2. Just change the version in package.json to 6.7.0. Scroll and it works. Change to 6.8.0. Scroll and it does not. 

**Live reproduction:**

https://codesandbox.io/s/react-instantsearch-infinitehits-with-hook-forked-t9zy6

## 💭 Expected behavior

Should scroll infinitely.

## Environment

- OS: [e.g. Windows / Linux / macOS / iOS / Android]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by Haroenv** [comment]
This probably should have been documented more thoroughly, but in 6.8.0 a bug happened where `refine` no longer did anything, while `refineNext` does work. Here you can see the now correct version https://codesandbox.io/s/react-instantsearch-infinitehits-with-hook-forked-1tjrk?file=/src/InfiniteHits.js.

This wasn't considered a breaking change, as it was initially a bug, but as refine wasn't documented (only refineNext), we didn't add it as a breaking change afterwards either

**Comment by iamclaytonray** [comment]
Gotcha. I'll try to create a repro with latest because a custom InfiniteHits sometimes loads the next page but never anything past that

**Comment by iamclaytonray** [comment]
Actually, if you look at the results, it almost seems like it's not an InfiniteList but rather a fixed list of a certain amount of data. As a hack, changing some irrelevant code to trigger a re-render will update the data if you're at the bottom of the list. But that's not correct behavior. Replacing a list of 30 items with new data is not infinite loading. Infinite loading would add to the list (30, 60, 90, 120, etc).

**Comment by iamclaytonray** [comment]
Just want to bump this. I had to write a couple of hacks to workaround this issue but would love a real bug fix

**Comment by Haroenv** [comment]
Sorry, I missed your response here. What seemed to be happening is that `refineNext` is the "current next", not the "absolute next, any time it is called". Because of this you need to make sure you don't use a stale reference in the closure. It can be fixed via putting it in the dependency array (but that's inefficient as it recreates the observer every pagination), or via a ref like this: https://codesandbox.io/s/react-instantsearch-infinitehits-with-hook-forked-i6kbp6.

Hope that helps @iamclaytonray

**Comment by iamclaytonray** [comment]
This looks like it's working as expected so closing this issue. Thanks for the response! 🙂
