### ISSUE TITLE
useRefinementList's transformItems doesn't work

### ISSUE THREAD

**Issue by mellson** [algolia/react-instantsearch#3254]
## 🐛 Bug description

When changing the label using `transformItems` on the props for `useRefinementList` the label doesn't change.

## 🔍 Bug reproduction

See example here: https://codesandbox.io/s/transformitems-error-dmpx2?file=/src/App.js:1095-1127
If you comment in the `dom` version in the imports you can see how it works in that package.

## 💭 Expected behavior

The label should change after a transform that changes it.

**Comment by francoischalifour** [comment]
In the `<RefinementList>` component, you display `item.highlighted`, not `item.label`. So you need to transform the `highlighted` field.

```tsx
<RefinementList
  attribute="brand"
  transformItems={(items) =>
    items.map((item) => ({
      ...item,
      highlighted: item.highlighted.toUpperCase(),
    }))
  }
/>
```

**Comment by mellson** [comment]
@francoischalifour ah okay, thanks for the quick reply 👍🏻
