### ISSUE TITLE
The 'Hit' type does not reflect the different types of records that can be stored in Algolia

### ISSUE THREAD

**Issue by wjpg** [algolia/react-instantsearch#3279]
## 🐛 Bug description

The `Hit` type is restricted to attributes of type <BasicDoc>: `[k: string]: string;`

This means treating a hit attribute as an array, number or object throws ts errors. 

The example record given in your docs would actually throw a typing error https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/#algolia-records.

`"categories": ["pie", "dessert", "sweet"],` would be invalid according to the current `Hit` type

## 💭 Expected behavior

- The `Hit` type should permit all valid algolia record values, presumably: arrays, numbers, strings. 
- It should also allow objects where the value in the key/value pair is of type array, number or string.

**Comment by Haroenv** [comment]
If I understand it correctly, you are using React InstantSearch with @types/react-instantsearch-dom, which isn't officially supported (it's maintained on DefinitelyTyped by community members).

Which method are you using that causes issues though? if I remember it correctly connectHits etc. take a generic to pass your record shape

**Comment by wjpg** [comment]
Thanks for the quick reply! 

Good point. There's actually two issues, let me explain the first: We're using `connectHitInsights` - which doesn't appear to respect the prop types declared on the component passed in the second argument, the `hitComponent`? It looks like it is returned as a ReactComponent with the interface `ConnectHitInsightsProvided`,

so for example:
```js
interface Props {
  name: string;
  onClick: () => void;
}

const ExampleHit: React.FC<Props> = ({ onClick, name }) => {
  ...
};

export default connectHitInsights(aa)(ExampleHit);
```

Will throw:
![Screenshot 2022-01-26 at 17 05 19](https://user-images.githubusercontent.com/90092447/151211428-34d4accc-c6e0-448b-9d53-6d183a0bb8b0.png).

My workaround for _some_ of that - (but not the onClick) is to pass the `hit` directly into the component.
The issue _then_ comes if you treat any of the values on that hit as an array, object etc. as desribed in my OP. Accessing a nested value, for example = ts error.

**Comment by jazanne** [comment]
@wjpg I just dealt with this issue as well and fixed it by doing something like this after reading [this stackoverflow answer](https://stackoverflow.com/questions/48240449/type-is-not-assignable-to-type-intrinsicattributes-intrinsicclassattribu)

```ts
const props = { name, onClick }

...

<ExampleHit {...props} />

```
