### ISSUE TITLE
TypeError: this.client.search is not a function

### ISSUE THREAD

**Issue by andyalex234** [algolia/react-instantsearch#3355]
## 🐛 Bug description

 I was using Algolia's instantsearch in Next.js project, and I come across this bug ```
Server Error
TypeError: this.client.search is not a function
``` when I try to call `findResultsState (Component, {meilisearchClient, indexName, searchState})` and I looked at the call stack trace and the problem was in algoliasearch-helper at` singleIndexSearch `:point_left: this is a helper function that is causing a problem here. `meilisearch `client object doesn't have a search method in its return object rather it is just an empty string. How do we use react instantsearch in SSR environment? 

## 🖥 Screenshots
![image](https://user-images.githubusercontent.com/59474650/153721917-cb7dac3b-cafb-4962-b4fd-c74ed8daef18.png)

## Environment

- OS: Windows
- Browser: Chrome
- Version: latest

**Comment by Haroenv** [comment]
the prop `meiliSearchClient` does not exist, and is meant to be `searchClient`. If there's more meili related issues, those probably should be opened on their repositories, not the Algolia ones

**Comment by andyalex234** [comment]
Hey @Haroenv, I wrote meiliSearchClient to convey that I'm not using Algolia search, but when I call it in my code indeed I used the prop name searchClient `const result = await findResultsState(component, {
      searchClient,
      indexName,
      searchState,
    });`  I open this issue here because I thought reactInstantsearch lib is just UI library which is unopinionated about which search client we choose to use, but it calls Aloglia specific helper function when I call findResultsState, In doing so It is expecting search function in the `searchClient` object which in `meilisearch` is just a string, not a function. Can't I use `react-instantsearch` lib with other search engines other than Algolia especially in Next.js? or can I avoid calling `findResultsState`?

**Comment by Haroenv** [comment]
It's not that it's specific, but more that the prop which InstantSearch and findResultsState accept is called `searchClient`, not `meiliSearchClient` or `algoliaSearchClient`. If you want to rename, you can do `findResultsState(App, { searchClient: myCustomSearchClient, indexName})` as you would on the InstantSearch component
