### ISSUE TITLE
RefinementList translate for `show more`  not working properly

### ISSUE THREAD

**Issue by JSSaint** [algolia/react-instantsearch#3362]
## 🐛 Bug description
RefinementList translate set for `show more`, but it will display on`show more` and `show less` are same text

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. 
```
<RefinementList
                    attribute="project"
                    searchable={false}
                    showMore={true}
                    limit={10}
                    translations={{
                      placeholder: t("Search for projects…"),
                      showMore: t("Show more")
                    }}
```
2. Click on `Show more` link
3.extend result are showed and again display as `Show more`
4. translate `Show less` is overwrite as `Show more`

**Comment by Haroenv** [comment]
Hi, The show more translation accepts a function, so you can use: `showMore: isShowingMore => isShowingMore ? 'show less' : 'show more'` (or pass that variable to the t function if you want)

https://codesandbox.io/s/lively-tree-liwpmy?file=/src/App.js

**Comment by johanguse** [comment]
I have no translation with `react-instantsearch-hooks-web`.

https://codesandbox.io/s/gallant-ritchie-sz120q?file=/src/App.js:175-204
