### ISSUE TITLE
`allSearchResults` is updated too many times after searching

### ISSUE THREAD

**Issue by ksntcrq** [algolia/react-instantsearch#3407]
## 🐛 Bug description

When doing a multiple index query with several `Index`, `allSearchResults` is updated as many times as there are indices after searching instead of at once.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Open the sandbox
2. Type a letter in the search field
3. See the console:
  1. Searching becomes `true`
  2. Searching becomes `false` and the `nbHits` of the main index are updated
  3. Only then the `nbHits` of the other index is updated

**Live reproduction:**

https://codesandbox.io/s/kind-varahamihira-srcdhn?file=/src/App.js

## 💭 Expected behavior

I would expect all the `nbHits` to be updated at the same time, when `searching` becomes false, because this means that searching is done and that everything was retrieved.

## Environment

- OS: macOS
- Browser: Chrome
- Version: 6.23.0

## Additional context

I need everything to be updated at once because I need to send a segment event when we're done searching, with the number of results for each index. For this, I'm looking for a `searching` changing from `true` to `false` and need the number of hits to be updated at the same time.

**Comment by dhayab** [comment]
Hi @ksntcrq , thanks for filing this. It seems like an issue indeed, as `searching` is set to `false` as soon as the state is updated with the first index's results.

We're going to look at this, and in the meantime, you can work around this by thoroughly checking that the search parameters are identical in all indices. Here is a sandbox that checks for the query parameter for example: https://codesandbox.io/s/focused-nobel-jiket5?file=/src/App.js.

**Comment by ksntcrq** [comment]
@dhayab Thanks! 

I see that your Pull Request was already merged. Any ETA on a release?

**Comment by Haroenv** [comment]
It will be released automatically once this PR merges, so in 10-20 minutes, thanks again for reporting! https://github.com/algolia/react-instantsearch/pull/3421

**Comment by ksntcrq** [comment]
Just tried with the new version, I can confirm it's fixed. Thanks!
