### ISSUE TITLE
algolia-react-native-Error -View config getter callback for component `input` must be a function

### ISSUE THREAD

**Issue by swachchhakh** [algolia/react-instantsearch#3417]
### Discussed in https://github.com/algolia/react-instantsearch/discussions/3416

<div type='discussions-op-text'>

<sup>Originally posted by **swachchhakh** March 31, 2022</sup>

![Screenshot_4](https://user-images.githubusercontent.com/49757436/161113527-af8873c6-1312-434e-889b-fa7a9b96f4f4.png)

![Screenshot_1648741532](https://user-images.githubusercontent.com/49757436/161113124-01bfcf18-176f-4797-967c-444350c46a9e.png)
</div>

**Comment by Haroenv** [comment]
You can not use react-instantsearch-dom in react native, the components available in react native are only the non-rendering ones (Index, InstantSearch, Configure). You need to create your own components with the connectors, as in the example: https://github.com/algolia/react-instantsearch/tree/master/examples/react-native
