### ISSUE TITLE
Hooks with React Native: pragma and pragmaFrag cannot be set when runtime is automatic

### ISSUE THREAD

**Issue by Antonhansel** [algolia/react-instantsearch#3426]
## 🐛 Bug description

Following this example: https://github.com/algolia/doc-code-samples/pull/358 by @sarahdayan 
I'm unable to run my React Native Application using Expo once I import InstantSearch from `react-instantsearch-hooks`

```
iOS Bundling failed 4201ms
node_modules/react-instantsearch-hooks/node_modules/instantsearch.js/cjs/components/CurrentRefinements/CurrentRefinements.js: /app/node_modules/react-instantsearch-hooks/node_modules/instantsearch.js/cjs/components/CurrentRefinements/CurrentRefinements.js: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | "use strict";
    | ^
  2 |
  3 | Object.defineProperty(exports, "__esModule", {
  4 |   value: true
SyntaxError: /app/node_modules/react-instantsearch-hooks/node_modules/instantsearch.js/cjs/components/CurrentRefinements/CurrentRefinements.js: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | "use strict";
    | ^
  2 |
  3 | Object.defineProperty(exports, "__esModule", {
  4 |   value: true
    at File.buildCodeFrameError (/app/node_modules/@babel/core/lib/transformation/file/file.js:249:12)
    at NodePath.buildCodeFrameError (/app/node_modules/@babel/traverse/lib/path/index.js:143:21)
    at PluginPass.enter (/app/node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:153:28)
    at newFn (/app/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/app/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/app/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/app/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/app/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitSingle (/app/node_modules/@babel/traverse/lib/context.js:77:19)
```

## 🔍 Bug reproduction

```
import {
  InstantSearch
} from 'react-instantsearch-hooks';
import algoliasearch from 'algoliasearch';

const searchClient = algoliasearch(
  'appId',
  'apiKey'
);


export default function Search(props: RootTabScreenProps<'Search'>) {

  return (<InstantSearch
    searchClient={searchClient}
    indexName='schools'
  ></InstantSearch>)
}
```

## Environment

```
➜  app git:(master) ✗ node -v
v14.18.2
```

-  "algoliasearch": "^4.13.0",
-  "expo": "~44.0.0",
-  "instantsearch.js": "^4.40.3",
-  "react-instantsearch-hooks": "^6.23.3",

Also tried with (same config as example)

-  "algoliasearch": "4.12.1",
-  "expo": "~44.0.0",
-  "instantsearch.js": "4.38.1",
-  "react-instantsearch-hooks": "6.22.0",

I'm not sure what I'm doing wrong here, any insights @sarahdayan  :) ?

**Comment by Haroenv** [comment]
Very odd, it seems to be importing parts of InstantSearch.js which aren't used at all. I wonder if you import the InstantSearch component via a more direct path if you still have the same issue

**Comment by sarahdayan** [comment]
Hey @Antonhansel, I've encountered this error sporadically during development but couldn't reproduce it consistently.

@Haroenv The error doesn't seem to persist with direct imports. React Native indeed tries to imports CJS files that aren't needed or even required by the imported Hooks. No idea for now if this is related to how React Native imports dependencies, or if this is a React InstantSearch Hooks issue.

@Antonhansel For now you can work around the issue with direct imports as @Haroenv suggested:

```js
import { useRefinementList } from 'react-instantsearch-hooks/dist/es/connectors/useRefinementList';

// instead of

import { useRefinementList } from 'react-instantsearch-hooks';
```

We'll update you here once we understand what's going on.

**Comment by Antonhansel** [comment]
Hey @sarahdayan @Haroenv, thank you for this temporary fix, importing everything from `'react-instantsearch-hooks/dist/es/'` solves the issue 👍 
I'll leave this issue open for now if that's ok :)
