### ISSUE TITLE
react-instantsearch-dom@npm:6.23.3 doesn't provide algoliasearch, requested by algoliasearch-helper

### ISSUE THREAD

**Issue by joker-777** [algolia/react-instantsearch#3428]
## 🐛 Bug description

Running `yarn install` shows me two warnings.
```
➤ YN0002: │ react-instantsearch-dom@npm:6.23.3 [a2c17] doesn't provide algoliasearch (pd384a), requested by algoliasearch-helper
➤ YN0002: │ react-instantsearch-dom@npm:6.23.3 [a2c17] doesn't provide algoliasearch (pe0e9b), requested by react-instantsearch-core
```

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**
1. yarn set version stable
2. yarn add react-instantsearch-dom
3. yarn add algoliasearch
4. yarn install
5. There it should show you the warning

You can also try [my small example app](https://github.com/joker-777/test_app).

## 💭 Expected behavior

That it doesn't show any warnings. Either `react-instantsearch-dom` has to satisfy the `peer-dependency` of `algoliasearch-helper` and `react-instantsearch-core` or there is a way of deferring peer dependencies.

## 🖥 Screenshots

![Screenshot_20220411_133148](https://user-images.githubusercontent.com/378859/162730969-11f05a84-eeb5-4e03-981e-f095f6c72c11.png)

## Environment

- OS: Linux arch 5.16.8-arch1-1
- Version: 6.23.3

**Comment by Haroenv** [comment]
Interesting behaviour, you can temporarily solve this by installing `algoliasearch` first, right?

**Comment by joker-777** [comment]
@Haroenv What do you mean by installing `algoliasearch` first?

**Comment by Haroenv** [comment]
doing either `yarn add algoliasearch; yarn add react-instantsearch-dom` or `yarn add algoliasearch react-instantsearch-dom`. This is definitely a new behaviour of the latest Yarn version, in older ones peer dependencies don't need to be consistent between different transitive packages.

according to https://yarnpkg.com/advanced/error-codes/#yn0002---missing_peer_dependency you can override the peerDependencies section of the React InstantSearch packages like this: https://yarnpkg.com/configuration/yarnrc#packageExtensions (before we fix this in the library directly)

```yml
packageExtensions:
  react-instantsearch-dom@*:
    peerDependencies:
      algoliasearch: ">= 3.1 < 5"
  react-instantsearch-core@*:
    peerDependencies:
      algoliasearch: ">= 3.1 < 5"
```
