### ISSUE TITLE
react instantSearch in filters Configure value having spaces

### ISSUE THREAD

**Issue by Gaurav038** [algolia/react-instantsearch#3449]
i am using this configure method in react Instant Search for getting list of trainingLanguage which having a value with a more than  two words like this Ex - "one space Two" , in single words its working fine but due to space in words its not giving results as per needs

```jsx
<Configure
              filters={`trainingLanguages:${lang}`}
 />
```

{lang} is used to get a value in dynamic way.

or 
```jsx
<Configure
              filters={trainingLanguages:"english language"}
 />
```

**Comment by Haroenv** [comment]
you need to add manual quotes to values that have spaces

```jsx
const value = 'English language';

<Configure filters={`trainingLanguages:"${value}"` />
```

**Comment by Gaurav038** [comment]
@Haroenv i already tried this then also its not filtering .

**Comment by Haroenv** [comment]
Here's an example showing adding quotes works for both values with and without spaces in https://codesandbox.io/s/inspiring-brook-4smzks?file=/src/App.js:1083-1163 @Gaurav038

**Comment by Gaurav038** [comment]
thanks @Haroenv  , sorry for late rply but its worked for Me and I forget to Thankyou for this.

**Comment by Haroenv** [comment]
Thanks for confirming!
