### ISSUE TITLE
`offset` and `length` based pagination broken in controlled mode

### ISSUE THREAD

**Issue by joshuabaker** [algolia/react-instantsearch#3451]
## 🐛 Bug description

When managing the `searchState` in controlled mode it’s currently not possible to manage the `searchState.configure.offset` and `searchState.configure.length` without using the `<Configure />` component. This means it’s impossible to build our own pagination without multiple renders/requests for a single page change, unless I’m mistaken.

Related to this, other widget components also set `searchState.page` to the state when pagination resets to ‘first page’ (e.g. a refinement list).

## 💭 Expected behavior

I’d expect that we could pass any [valid state](https://www.algolia.com/doc/api-reference/widgets/ui-state/react/) into `searchState` and this impact the UI as in the same way as if we’d used a widget component.

In respect to other widgets setting the `searchState.page` prop, these should really reset the `searchState.configure.offset` to `0` if `searchState.configure.length` is set.

**Comment by joshuabaker** [comment]
https://codesandbox.io/s/great-phoebe-dxeseg

**Comment by Haroenv** [comment]
The searchState on its own doesn't do anything, it gets however read by each one of the relevant components, which turns it into the correct search parameters or other derived state. For advanced state like that, I'd recommend using a similar pattern as either connectPagination or connectInfiniteHits, which will allow you to have the relevant ui with different search parameters than the default.

You can also directly use configure without searchState, as it's already dynamic

**Comment by joshuabaker** [comment]
The issue is that we cannot intercept the state and then set the state, because we have to pass the props to the `Configure` component. This means we end up with a redundant search request before the request we actually want to make.

**Comment by joshuabaker** [comment]
> it gets however read by each one of the relevant components, which turns it into the correct search parameters or other derived state

This doesn’t appear to be the case for `Configure`. Passing `offset` and `length` to the `searchState` doesn’t do anything.

**Comment by Haroenv** [comment]
when no Configure widget is mounted you mean? That's the same for all other widgets indeed. I'd love to understand what your complete use case is, and the flow of setting state causing an unwanted request.

**Comment by joshuabaker** [comment]
Simplified examples...

```js
function onSearchStateChange(nextSearchState) {
  setSearchState(nextSearchState); // Placing this after setOffset prevents the refinement state update
  
  if (nextSearchState.page === 1) { // i.e. Passed by refinement list
    setOffset(0); // Passed to <Configure />, which causes a re-render and second search request
  }
  
  updateUrl(createURL(nextSearchState));
}
```

```js
function onSearchStateChange(nextSearchState) {
  if (nextSearchState.page === 1) { // i.e. Passed by refinement list
    nextSearchState.configure.offset = 0; // Gets ignored with or without <Configure />
    nextSearchState.configure.length = hitsPerPage + 1; // Gets ignored with or without <Configure />
  }

  setSearchState(nextSearchState);
  
  updateUrl(createURL(nextSearchState));
}
```

**Comment by joshuabaker** [comment]
I near certain that it’s impossible. Perhaps I can’t see the wood for the trees.

Even if we cache the state, remove the `page` prop, and then try and put everything back on the next pass, it’s not working.

```js
function onSearchStateChange(nextSearchState) {
  if (nextSearchState.page) {
    setPage(nextSearchState.page);
    delete nextSearchState.page;
    setCachedSearchState(nextSearchState);
  } else if (cachedSearchState) {
    setSearchState(cachedSearchState);
    setCachedSearchState(undefined);
  } else {
    setSearchState(nextSearchState);
  }
}
```

In the above, we’re deriving markers from the page (i.e. `<Configure {...pageToOffsetAndLength(page)} />`).

**Comment by Haroenv** [comment]
Could you explain why offset and length is used instead of page, or maybe why the translation happens? You can also map in the searchClient in a similar way to https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/js/

The page is here is the state set by the Pagination widget right?

**Comment by joshuabaker** [comment]
The first unfiltered page has 13 hits. Subsequent and unfiltered pages have 12 hits.

We don’t use the `Pagination` widget because that doesn’t allow different hits per page.

**Comment by joshuabaker** [comment]
In pseudo code, we basically want to do the following when `onSearchStateChange` is triggered (before we set `searchState`).

```
baseLength = 12

if (refinements = empty and page = 1) {
  offset = 0
  length = baseLength + 1
} else {
  offset = ((page - 1) * baseLength) + 1
  length = baseLength
}
```

**Comment by joshuabaker** [comment]
Very much appreciate your time and suggestions.

This is why I feel so strongly about allowing mutations via `searchState`. We’re having to hack the request cycle to get a feature working, instead of just setting two nested values in an object.

Are you not at all open to allowing control over the state?

**Comment by Haroenv** [comment]
It's not that we aren't open, I'd just like to question whether using searchState is a more flexible option than modifying both the request and the response, as you are using pagination, you can see in the modified client I made that the response also needs to be transformed and be aware of the search requests. If you just send offset and length instead of page, the response will look different, and not work with the Pagination widget for example.

**Comment by joshuabaker** [comment]
@Haroenv Your requests workaround is clever, no doubt. Getting pagination to work out of box like this _is_ handy. Based on the docs, I never expected it to work though.

> Note that with [InstantSearch](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/), all pagination use cases are implemented with `page` and `hitsPerPage`.

I did expect to be able to switch `InstantSearch` to a properly controlled state though, which means being able to pass down the state value into a prop (i.e. `searchState` and `onSearchStateChange`). [React’s controlled components docs](https://reactjs.org/docs/forms.html#controlled-components) recommend this approach; The component passes the value to the state and the state is passed back into a prop (i.e. `value` and `onChange`). You can then interact with that state as it’s set (directly or via `useEffect`).

Changing a value in a type-safe object is the ideal, more React-y way of doing this, versus having a component to compose this. The latter means we have to deal with the extra render when reconciling things as per this case, but also any others where you might want to adjust the parameters dynamically based on factors external to the search. It’s not a user choice as things stand. For example, the `Configure` component could just override whatever it passed to the `searchState` (constants versus variables), without an API redesign _or_ blocking approaches that you don’t support off the shelf.

**Comment by joshuabaker** [comment]
@Haroenv I’m back up against this issue again. When trying to sync to the URL, the `Pagination` widget is internally setting the page number incorrectly.

For example, paging from `/search` to `/search?page=2` and then going back via the browser back button causes the `Pagination` internals to pass `page: 2` back via `onSearchStateChange`, which cancels out the browser back navigation.

**Comment by Haroenv** [comment]
you need to set the search state on `popstate` to keep it synchronised, otherwise you will read a state that's not correct

**Comment by joshuabaker** [comment]
We were leaning on Next’s router (i.e. `nextRouter.query`). Moving to the native `window.history` and `window.location` has resolved the state sync issue. 👍🏻 

One thing I am now noticing is that we’re back to duplicate requests; One on the server side and the same again in the browser. Reverting to the default search client resolves this, which suggests it’s where we’re modifying the raw requests.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/160484/166961014-5e43e28a-f1a8-47b5-a991-63ad3f95303e.png">

Is there some undocumented deduplication or caching logic we should be using to avoid this?

**Comment by Haroenv** [comment]
Hmm, the majority of the cache-related code is here: https://github.com/algolia/react-instantsearch/blob/2546626e52c84babfc768f6c2082b6b408e7e004/packages/react-instantsearch-core/src/core/createInstantSearchManager.js#L385-L410, but indeed modifying the response maybe causes the cache to no longer match. I'll try to make a reproduction with the code I shared earlier, but if you have a sandbox ready it would save some time.

**Comment by joshuabaker** [comment]
@Haroenv Might be getting off topic for the issue, but duplicate requests might be a general issue when using a custom client with SSR.

In the sandbox linked below, I note that just passing the request along to the off-the-shelf search client results in a second, duplicate client-side request.

https://codesandbox.io/s/react-instantsearch-nextjs-duplicate-requests-te0fr5?file=/pages/index.js

**Comment by Haroenv** [comment]
Ah, I didn't see the customSearchClient was implemented like that. It indeed needs all of the keys, and only override the search method, like this: https://codesandbox.io/s/react-instantsearch-nextjs-duplicate-requests-forked-8xn8b6?file=/pages/index.js:247-630

Where in the documentation did you see the pattern of creating a new object? I'll see if that can be updated, maybe even a place it could warn in InstantSearch when not all methods of the search client are present?

**Comment by FabienMotte** [comment]
Hey!

We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately and is to be mostly solved, so we're going to close it.

Regarding the documentation update, I recently fixed the code snippets of the guide ["Conditional requests with React InstantSearch"](https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-requests/react/#implementing-a-proxy).
