### ISSUE TITLE
Server-rendered, Controlled, InstantSearch fails after re-render

### ISSUE THREAD

**Issue by bgschiller** [algolia/react-instantsearch#3482]
## 🐛 Bug description

We have set up a server-rendered instant search, including the `onStateChange` prop making it a controlled component. When the parent component re-renders, any state change will fail with the error:

> Error: The `start` method needs to be called before `setUiState`.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Clone down https://github.com/bgschiller/instantsearch-rerender-bug `git clone git@github.com:bgschiller/instantsearch-rerender-bug.git`
2. Set environment variables for `ALGOLIA_APP_ID` and `ALGOLIA_SEARCH_KEY`. I'm happy to provide mine if you need, as they're just for a demo environment for us.
3. `npm install` and `npm run dev`. Visit http://localhost:3000
4. In any order, click the "rerender" button and type something in the search box.
5. See error "Error: The `start` method needs to be called before `setUiState`."

**Live reproduction:**

https://codesandbox.io/s/gallant-banach-2zbyil

## 💭 Expected behavior

I expected this to work without error

## 🖥 Screenshots

![a traceback starting with "Error: The `start` method needs to be called before `setUiState`."](https://clip.brianschiller.com/efGbz0x-2022-05-26.png)

## Environment

- OS: verified on Windows, Ubuntu, and codesandbox
- Browser: Chrome
- Version: react-instantsearch-hooks-{web,server} 6.26.0

## Additional context

I came across this issue in the course of my work at DEPT, but I'll be leaving that job soon. I'm tagging @wintersieck to answer any follow-up questions.

**Comment by francoischalifour** [comment]
Thank you the bug report details and reproduction. I was able to reproduce this bug in an isolated test environment as well.

**Comment by chan-fullstack** [comment]
Same issue I'm encountering when closing a modal through `next/router` change. It seems like the InstantSearch instance becomes null after re-render.
![image](https://user-images.githubusercontent.com/61461187/171844955-c84cfdf8-55b1-44b2-8745-5ed80ca9bd5a.png)

**Comment by francoischalifour** [comment]
@bgschiller Migrating our internals with [`useSyncExternalStore()`](https://reactjs.org/docs/hooks-reference.html#usesyncexternalstore) in #3489 fixed your original issue (this is not released yet).

@zacharyliu @chan-fullstack Your issues might also be fixed with this PR. To make sure, could you please both provide bug reproductions? Here's a [Next.js sandbox with React InstantSearch Hooks](https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/hooks-next?file=/pages/index.tsx).
