### ISSUE TITLE
Wrong content-type header sent with requests

### ISSUE THREAD

**Issue by tremby** [algolia/react-instantsearch#3487]
## 🐛 Bug description

Requests are sent in JSON format, but with the header `content-type: application/x-www-form-urlencoded`.

The Algolia server doesn't seem to mind; nothing is broken except the dev tools' view of the request.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Set up `react-instantsearch-hooks-web`, add a `SearchBox`.
2. Type something in the box to cause a request
3. See the network tab in dev tools, inspect the request
4. See the outgoing headers and data

## 💭 Expected behavior

Correct header is sent (`content-type: application/json`)

## 🖥 Screenshots

Here you see the request header has the wrong content type.
![screenshot 1](https://user-images.githubusercontent.com/199635/170842745-97e24271-c866-47c7-a54d-c1e98302f8b0.png)

This is what Firefox renders in the request tab -- it's declared as URLencoded form data so it's been split at `&` symbols and key-value pairs split at `=` symbols.
![screenshot 2](https://user-images.githubusercontent.com/199635/170842749-bd95b9b9-2734-408e-840a-63b5746a3897.png)

If you flip to "raw" view you can see it's really JSON data.
![screenshot 3](https://user-images.githubusercontent.com/199635/170842750-cb274164-9c43-4200-a9d1-260d0454ff9e.png)

## Environment

- OS: n/a
- Browser: n/a (screenshots are firefox)
- Version: `algoliasearch 4.13.1`, `react-instantsearch-hooks-web 6.26.0`

**Comment by Haroenv** [comment]
This is actually on purpose to make sure we use something called a [Simple Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests) to avoid a network request for the CORS OPTIONS.

The payload is indeed not easy to read sometimes, but I've (personally) made a tool to easily read the parameters as an object again: https://haroen.me/algolia-tools/#request-explorer

**Comment by tremby** [comment]
Maybe `text/plain` would be better, then? It'd at least be readable without special addons.

**Comment by Haroenv** [comment]
I didn't know the engine changed to support text/plain as well, and that would be a better choice indeed. For now I'm not sure if eg. a special backend passed with "hosts" deals with that correctly, so changing it would be too risky to do in a non-major version. 

In a next major version we're planning we are already changing the request to not use `params` anymore, but pass all values directly in the body which is much more readable already, even with the wrong content-type. I'll bring this topic up and see if it makes sense to change it in that major version to text/plain as well.

For the time being if you want to pass the content type yourself, you can do that:

```js
algoliasearch('', '', { headers: { 'content-type': 'text/plain' }});
```

(in a sandbox: https://codesandbox.io/s/kind-goldwasser-z4335j?file=/src/App.tsx:308-463)
