### ISSUE TITLE
react-instantsearch-hooks useConfigure refine not updating other hooks

### ISSUE THREAD

**Issue by kanehara** [algolia/react-instantsearch#3490]
## 🐛 Bug description

When using the `refine` method from `useConfigure`, it does not update the state of refinement for other hooks - `useRefinementList`, `useCurrentRefinements`, etc.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Create a component that uses `useConfigure`
2. Create a nested component with `useRefinementList` or `useCurrentRefinements`
3. Add some facet filters with the `refine` method from the `useConfigure` hook
4. See that the refinement state is not updated from the results returned in `useRefinementList`, `useCurrentRefintments`

This does not happen when using `refine` from the `useRefinementList` hook

## 💭 Expected behavior

The state of refinement is updated everywhere when using `refine` from `useConfigure`

## Environment

- React InstantSearch version: 6.26.0
- React version: 17.0.2
- Browser: React Native 0.67.3
- OS: macOS

**Comment by Haroenv** [comment]
Could you explain your use case more clearly? Configure is meant for filters that aren't displayed, and doesn't have the extra logic indeed for updating the isRefined state of the other widgets, unless the right key is used (which will be overridden by refinementLists etc. if used). For a RefinementList, `configure.refine({ disjunctiveFacetsRefinements: { brand: ['Apple', 'Samsung']}})` will show up, hierarchical and menu use `hierarchicalFacetsRefinements`

**Comment by kanehara** [comment]
A different use case came up actually.  Say I wanted to apply a deep linked filter `category:shoes AND size:9` that could be passed into the URL and pass that into `filter` in `useConfigure`.  This won't update the state of the widgets which I'd expect it to.  Is there a reason the states could not be in sync b/w the two?

**Comment by Haroenv** [comment]
`filters` doesn't get parsed by the widgets. If you want to set a state across multiple widgets, I think the best option is via ui state:

```js
const { setIndexUiState } = useInstantSearch();

// ... in listener
setIndexUiState({
  refinementList: {
    category: ['shoes'],
    size: ['9'],
  },
})
```

Of course, depending on your ui, it could be different widgets, but this way you can set multiple refinements at the same time that are visible in the UI without worrying about getting the exact right search parameter it would send if refined
