### ISSUE TITLE
Unable to filter by attribute with multiple values

### ISSUE THREAD

**Issue by jsancho** [algolia/react-instantsearch#3510]
## 🐛 Bug description

Unable to filter items when providing multiple values for an attribute with Configure

## 🔍 Bug reproduction

I'm struggling to filter records in a similar way to what is being suggested on this article
https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/in-depth/filters-and-facetfilters/

```
index.search('', {
  filters: 'author:"Stephen King"'
});
```

I have an index full of vehicles and I want to retrieve a specific set of them when filtering by vin.

For example, given these 3 vehicles `VSSRJNLTMBH761617`, `VSSCHQDYC9S997972`, `KMFWBH7JP8U026425`..
I'd like to retrieve them all with a single query.
Typically, end-users will paste a list of VINs that they've obtained elsewhere, and we'd like to present those records directly.
(You can think of a VIN as an SKU)

If I search for a single VIN, the result is indeed found, so the data seems to be correctly indexed.
However, the issue is when I need to do a query to get those 3 items.

From reading the docs, I understand that I should be able to use syntax like the following
`"vin:VSSRJNLTMBH761617 OR vin:VSSCHQDYC9S997972 OR vin:KMFWBH7JP8U026425"` but that returns an empty result.

**Live reproduction:**
Please mind that I haven't created a sandbox, because it's a private index. 
I could create an additional free account and index some sample data, though.
Let me know if you'd like me to create a new index and I'll do so.

It looks like the `Configure` and `useConfigure` hook should be the way to go.

this returns an empty result set
`<Configure filters="vin:VSSRJNLTMBH761617 OR vin:VSSCHQDYC9S997972" />`

even when I filter by a single value I also get an empty `hits` array
`<Configure filters="vin:VSSRJNLTMBH761617" />`

## 💭 Expected behavior

To be able to provide multiple values for an attribute and to retrieve all the records that match exactly those values.

## 🖥 Screenshots
This is the query as captured by the network tools
<img width="323" alt="image" src="https://user-images.githubusercontent.com/1547884/173097048-5fdd9639-5d18-4136-9df6-faf619454fb0.png">

## Environment

- React InstantSearch Hooks version: 6.27.0
- React version: 18.1.0
- Browser: Chrome 102.0.5005.63
- OS: Windows

## Additional context

It could be that I'm approaching this in completely the wrong way, happy to take it all apart to get to the goal :)

**Comment by jsancho** [comment]
Wow, that's what it was.

I had not added it as a facetable attribute, because they are unique values and didn't make sense to group them.

But I've seen that there's an options to set it as facetable/filter only, which does make immediate sense and makes the filtering work!
<img width="550" alt="image" src="https://user-images.githubusercontent.com/1547884/173320123-85325a46-83dc-4a6c-89e2-a15e82b8d7df.png">

and because of this I've now found the docs where this is explained so clearly
https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/#how-to-filter-your-data

thanks @Haroenv

**Comment by Haroenv** [comment]
That's indeed exactly what the option is for! Have a great day
