### ISSUE TITLE
React Instantsearch Hooks: SSR not working on v6.27.0

### ISSUE THREAD

**Issue by francisconeves97** [algolia/react-instantsearch#3511]
## 🐛 Bug description

SSR with Next.js is not working on the latest version of `react-instantsearch-hooks-web` and `react-instantsearch-hooks-server` (6.27.0). Every element that is rendered inside the `<InstantSearch />` component is only rendered on the client side,  

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Clone the `hooks-ssr` example: https://github.com/algolia/react-instantsearch/tree/v6.22.0/examples/hooks-ssr
2. Change the `react-instantsearch-hooks`, `react-instantsearch-hooks-server` and `react-instantsearch-hooks-web` dependencies version from 6.22.0 to 6.27.0
3. Install the npm dependencies
4. Start the server
5. Verify that no search results were server side rendered by checking the html source

**Live reproduction:**

https://codesandbox.io/s/github/algolia/react-instantsearch/tree/v6.27.0/examples/hooks-next?file=/package.json

## 💭 Expected behavior

The widgets inside the `<InstantSearch />` should be server side rendered

## Environment

- React InstantSearch Hooks version: 6.27.0
- React version: 17.0.2

## Additional context

Tried to downgrade to version 6.26.0 and the search results are server side rendered, so the issue should have been introduced on the last release

**Comment by dominiksipowicz** [comment]
I can confirm and reproduce the SSR bug. It's working on the previous version `6.26.0`

It can be tested by simply disabling JavaScript in Google Chrome (Settings -> Prefrences  -> Debugger -> Disable JavaScript)

**Comment by Haroenv** [comment]
This is very surprising, as on a quick glance, the only relevant change happened in 6.25.0 with https://github.com/algolia/react-instantsearch/commit/0a13867f7dd5a8a18e0957b2072bbde3b02d6490, otherwise also InstantSearch.js was updated between 6.26.0 and 6.27.0

Thanks for reporting this, we are investigating further!

**Comment by dominiksipowicz** [comment]
thanks @francoischalifour, awesome!

**Comment by francisconeves97** [comment]
Amazing, thank you!
