### ISSUE TITLE
React InstantSearch Hooks Server: getServerState causes Next.js router to be null

### ISSUE THREAD

**Issue by francisconeves97** [algolia/react-instantsearch#3524]
## 🐛 Bug description

When using the `getServerState` function inside Next.js `getServerSideProps`, Next.js router can't be retrieved by using the `useRouter` hook.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to the React InstantSearch Next.js demo: https://codesandbox.io/s/github/algolia/react-instantsearch/tree/v6.28.0/examples/hooks-next
2. Inside the Homepage component use Next.js `useRouter` hook
3. `console.log` the return value of the `useRouter` hook and verify that the value is `null` instead of the Next.js router

**Live reproduction:**

https://codesandbox.io/s/great-brahmagupta-742dz9?file=/pages/index.tsx

- The `pages/index.tsx` uses the `getServerState` function and console.logs the router, which returns null
- The `pages/no-ssr.tsx` comments out the `getServerState` function and console.logs the router, which is defined 

## 💭 Expected behavior

Using `getServerState` shouldn't interfere with the `useRouter` hook. The `useRouter` hook should return the `router` object as it normally does

## Environment

- React InstantSearch Hooks version: 6.28.0
- React version: 18.1.0

## Additional context

I am not sure if this is a problem with the `getServerState` function or the way it is integrated with Next.js in the example. Probably when rendering the component we need to add some Next.js context so we can access context instances like the router

**Comment by francisconeves97** [comment]
Just verified that it is not related with this library itself, I will close this issue

**Comment by francoischalifour** [comment]
In `getServerSideProps()`, you could wrap the component you call in `getServerState()` with Next's `<RouterContext>`. 

```js
  const serverState = await getServerState(
    <RouterContext.Provider value={router}>
      <HomePage url={url} />
    </RouterContext.Provider>
  );
```

Next.js doesn't expose simple ways to create the `router` context though, so I suspect this needs some manual work.

**Comment by francisconeves97** [comment]
Thanks a lot for the help @francoischalifour! I ended up just adding null safe operators when using the router
