### ISSUE TITLE
NextJS static page with rewrite rule -> error on refine

### ISSUE THREAD

**Issue by matteorigotti** [algolia/react-instantsearch#3530]
## 🐛 Bug description

Refine in a nextJS static page throw this error if you defined a next.js rewrite rule:
`Error: Cannot refine the undeclared facet brand; it should be added to the helper options facets, disjunctiveFacets or hierarchicalFacets`

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Put a rewite rule in your `next.config.js`
2. Browse a static page including algolia search
3. Click on a refinement in the left sidebar

**Live reproduction:**

https://codesandbox.io/s/quizzical-night-mjlw22

## 💭 Expected behavior

The refinement should be applied correctly

## 🖥 Screenshots

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/97886602/174781965-50d416e0-9ad0-483f-a93d-89951a141184.png">

## Environment

- React InstantSearch Hooks version: 6.28.0
- React version: 18.1.0

## Additional context

I think that the problem is started with the migration to `useSyncExternalStore` in `useInstantSearchApi` because I noticed that in the case mentioned above `search.dispose()` function is called after the page load. Is it possible that migrating from `useEffect` to `useSyncExternalStore+useCallback` you forgot to remove the old cleanup function and actually it's invoked accidentally in some cases?

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/97886602/174783349-935c995e-99d0-4e09-91a8-dbd405043891.png">

**Comment by DB-Alex** [comment]
I have the same error with 1 index and when you use multiple indexes you can just not refine, no error also.

**Comment by DB-Alex** [comment]
An update about this bug.

When you remove the rewrites in the next.config.js and start using facets it works correctly.

As soon as you switch a page in Next with another index and start refining again the facets break with the exact same error:

<img width="945" alt="Screenshot 2022-06-22 at 11 42 04" src="https://user-images.githubusercontent.com/3672692/174998065-dc0793c9-5966-4f88-8599-d1ed4059c432.png">

**Comment by matteorigotti** [comment]
@Haroenv do you think it is correct that the `useCallback` returns a function that invoke the `search.dispose()`?
I tried to turn off the strictMode but the issue is still present.
Thanks for you work.

**Comment by DB-Alex** [comment]
Another issue which might be related is when you remove the server state from the ssr renderer the router does not get involved

**Comment by federicovezzoli** [comment]
Same exact issue appeared to me after upgrading hooks package from 6.24.0 to 6.29.0, I'm on next.js with server side rendering.

**Comment by DB-Alex** [comment]
@Haroenv is there something I can help with to speed up the current issues?

**Comment by francoischalifour** [comment]
@DB-Alex We were able to write a test that catches this issue. We're currently working on a fix for which you can expect a release in the next few days.

**Comment by francoischalifour** [comment]
@DB-Alex Yes, the fix hasn't landed yet. I'll keep you posted on this thread.

**Comment by DB-Alex** [comment]
@francoischalifour is it correct this is still not fixed in 60.3.1? Or am I doing something wrong?

Please let me know.

**Comment by francoischalifour** [comment]
@DB-Alex Nope, as said previously, I'll keep you posted here. The PR that fixes it is #3561. It'll likely land this week.

**Comment by DB-Alex** [comment]
Looks promising, first errors are gone!

**Comment by DB-Alex** [comment]
@francoischalifour When you refine using the useRefinementList hook the uiState object does not get updated. Neither does the router update function.

So urls are not in sync.

**Comment by francoischalifour** [comment]
@DB-Alex Can you please open another issue? This is likely unrelated. Thanks!

**Comment by federicovezzoli** [comment]
Fixed all the problems for me, thanks!
