### ISSUE TITLE
HierarchicalMenu rootPath is not working properly

### ISSUE THREAD

**Issue by jasarevicamar** [algolia/react-instantsearch#3540]
## 🐛 Bug description

When correct rootPath is provided to HierarchicalMenu no items (or some weird items) are displayed.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Open https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/hooks
2. Go to App.tsx
3. Add `rootPath="Audio"` to `HierarchicalMenu`
4. Check the site => Under HIERARCHY section there are no items
5. Remove rootPath prop
6. Click on `Audio` under HIERARCHY section
7. Check the site => There are items for `Audio` category

**Live reproduction:**

https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/hooks

## 💭 Expected behavior

When correct rootPath is provided and there are items for that facet, items should be displayed.

React InstantSearch Dom is working properly, and can be used as an example... Please try and do the same in the following Sandbox:
https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/e-commerce

## 🖥 Screenshots

No screenshots needed.

## Environment

The versions are provided in Sandbox.

## Additional context

Please ask if needed.

**Comment by Haroenv** [comment]
Hmm, I added rootPath and I indeed don't get the right results (only some) 

<img width="209" alt="Screenshot 2022-06-28 at 16 37 43" src="https://user-images.githubusercontent.com/6270048/176207035-b931c877-3f43-4f2f-a1da-c4f2414484c1.png">


https://codesandbox.io/s/frosty-darkness-vh17dn?file=/App.tsx is a demo with hooks / rootPath enabled

On which index have you checked this? I wonder if it could be related to renderingContent/facetOrdering

**Comment by jasarevicamar** [comment]
Hi @Haroenv, 

Thanks for your feedback.

Unfortunately, workaround will not work for my case... Could you please let me know is this going to be prioritized, and when can I expect the fix?
Just so I can decide wether I am going to wait or to implement a workaround.

**Comment by Haroenv** [comment]
We're investigating, but as no explanation has been found yet, if you can work around the issue, I'd do that first @jasarevicamar. If you find another workaround (eg using routing to enable the initial ui state alternatively), please let us know on the thread as well!
