### ISSUE TITLE
useMenu does not work properly when filtering for one level of an otherwise hierarchical facet

### ISSUE THREAD

**Issue by bartosz-urban-danfoss** [algolia/react-instantsearch#3543]
## 🐛 Bug description

When using `useMenu` to filter by a single level of an otherwise hierarchical attribute, no results are shown in the UI, despite being in the response. 

After using `transformItems` to achieve the desired result (as in the sandbox), `refine` does not work either. Sending refine seems to apply tags properly, but it does not update filters or results.

I have no issue with `useRefinementList` locally, but I want to achieve a single select component. However, when trying to replicate refinement list in the sandbox, it does not work, and behaves similarly to useMenu.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to `[this sandbox](https://codesandbox.io/s/youthful-tesla-99xsuz?file=/components/MenuUsingHierarchical.tsx)`
2. Results as expected when using a custom transformItems, that takes this data from _rawResults
3. Comment out transformItems
4. There will be no results 🐛
5. Notice that useEffect which happens on mount does not apply filtering at all, despite creating a tag 🐛
6. Replace `attribute` in `useMenu` with a simple attribute, such as "categories" and things will work as expected

**Live reproduction:**

https://codesandbox.io/s/youthful-tesla-99xsuz?file=/components/MenuUsingHierarchical.tsx

## 💭 Expected behavior

Using any single attribute in the form of `hierarchicalAttribute.level2` in `useMenu` behaves as any other attribute, no matter whether it's also a hierarchical facet or not.

## Environment

- React InstantSearch Hooks version: [e.g. 6.29.0]
- React version: [17.0.2]
- Browser: [Chrome]
- OS: [Windows / Ubuntu with WSL]

```json
"instantsearch.js": "4.43.0",
"algoliasearch": "4.13.1",
"react-instantsearch-hooks-web": "6.29.0",
"@algolia/client-search": "4.13.1",
"@algolia/autocomplete-core": "1.7.1",
"@algolia/autocomplete-plugin-query-suggestions": "1.7.1",
"@algolia/autocomplete-preset-algolia": "1.7.1",
"react": "17.0.2",
"react-dom": "17.0.2",
```

**Comment by Haroenv** [comment]
Could you explain further what you exactly want to achieve? Is there also a hierarchical menu in the UI, or is there only a hierarchical attribute used in the useMenu?

I don't fully understand yet what your use case is, but could you use `useHierarchicalMenu` to achieve it?

**Comment by joker-777** [comment]
I think I have the same problem.

**Comment by joker-777** [comment]
@Haroenv Cany idea when this bug gets priority? @bartosz-urban-danfoss Were you able to find a workaround?

**Comment by Haroenv** [comment]
@joker-777, I don't understand what experience exactly you're trying to achieve, do you have a code sample, diagram or something else?

**Comment by joker-777** [comment]
@bartosz-urban-danfoss Thanks a lot. I will try it out as well.

**Comment by FabienMotte** [comment]
We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately, so we're going to close it.

Having a `>` separator in the facet values is not currently supported with the `<Menu>` widget, instead you can use a `<RefinementList>` widget like so: https://codesandbox.io/s/trusting-kapitsa-ywxxrf?file=/src/App.tsx:1110-1168
