### ISSUE TITLE
In some cases there are multiple identical requests

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#355]
**Do you want to request a *feature* or report a *bug*?**

bug

**Bug: What is the current behavior?**

a single refinement (any of them) cases N requests with the exact same parameters

**Bug: What is the expected behavior?**

one request per exact same parameters

**What is the version you are using? Always use the latest one before opening a bug issue.**

4.0.10

This is visible in 

- [refining within hits guide](https://codesandbox.io/embed/oY1klpZYB)
- [yarn site (probably same origin partially)](https://yarnpkg.com)

As discussed with @vvo, we should deduplicate requests either at the React InstantSearch or Helper level, since this might be hard to solve otherwise.

**Comment by mthuret** [comment]
I think we can go for the deduplicate requests solutions only after understanding what is causing the bug (even though we find out that we don't have better solutions than deduplicating requests for now). 
cc @Haroenv @vvo

**Comment by vvo** [comment]
Finding the root cause is a priority, as for fixing like you said it can depend on our strategy (inside RIS, or inside the helper). Still the helper must be smarter on this part (pending request, same parameter, reuse request).

**Comment by callmephilip** [comment]
Seeing this issue as well and it's messing things up quite a bit for our analytics component. Do you guys have any plans to fix this in the near future?

**Comment by Haroenv** [comment]
@samouss is working on this right now, in the meantime any situations in which this occurs will help us pinpoint the issue. Can you make a reproduction on for example CodeSandbox @callmephilip ?

**Comment by callmephilip** [comment]
@Haroenv i don't think i can provide an easily reproducible example - the app is closed source. those multiple requests seem to fire when refinements are adjusted - we are using standard RefinemnentList components from RIS, nothing funky

**Comment by Haroenv** [comment]
A refinement list will always send two requests, one with `analytics: false` in it because one is to get the possible values, and the other for the number of results for that. Which analytics are you rolling out @callmephilip, the built-in Algolia ones? 

In any case, this issue is for cases when two duplicate requests are done on every change, not just on refinementList

**Comment by callmephilip** [comment]
I am seeing 2 requests with `analytics: false` when updating refinements 
re:analytics - we rolled a simple widget and a connector responsible to reporting search results being fetched to Google Tag manager. The connector looks smth like this:

```javascript
import { createConnector } from 'react-instantsearch';

export const connectAnalytics = createConnector({
  displayName: 'AlgoliaAnalytics',

  getProvidedProps(props, searchState, searchResults) {
    // inspect search results here and report to GTM
   return props;
  },
});
```

**Comment by callmephilip** [comment]
The requests sent seem identical:

```
{"requests":[{"indexName":"development_products","params":"query:
hitsPerPage:50
maxValuesPerFacet:10
page:0
highlightPreTag:<ais-highlight-0000000000>
highlightPostTag:</ais-highlight-0000000000>
facets:["make","model","type","year","price","color"]
tagFilters:
facetFilters:[["make:BMW"]]"},{"indexName":"development_products","params":"query=
hitsPerPage:1
maxValuesPerFacet:10
page:0
highlightPreTag:<ais-highlight-0000000000>
highlightPostTag:</ais-highlight-0000000000>
attributesToRetrieve:[]
attributesToHighlight:[]
attributesToSnippet:[]
tagFilters:
analytics:false
facets:make"}]}
```

And

```
{"requests":[{"indexName":"development_products","params":"query:
hitsPerPage:50
maxValuesPerFacet:10
page:0
highlightPreTag:<ais-highlight-0000000000>
highlightPostTag:</ais-highlight-0000000000>
facets:["make","model","type","year","price","color"]
tagFilters:
facetFilters:[["make:BMW"]]"},{"indexName":"development_products","params":"query=
hitsPerPage:1
maxValuesPerFacet:10
page:0
highlightPreTag:<ais-highlight-0000000000>
highlightPostTag:</ais-highlight-0000000000>
attributesToRetrieve:[]
attributesToHighlight:[]
attributesToSnippet:[]
tagFilters:
analytics:false
facets:make"}]}
```

**Comment by mthuret** [comment]
Hi @callmephilip 

I have some questions: are you using InstantSearch in controlled mode? If yes, are you directly modifying the `searchState` of InstantSearch (by changing refinements of the RL?). Or are you changing the RL props? 

A temporary workaround that can be used when dealing with multiple request until we find the underlying issue is to wrap the IS component and use the `shouldComponentUpdate` hook to remove the unwanted rendering.

**Comment by callmephilip** [comment]
@mthuret 

I have finally got a chance to start looking into this in more depth and I am definitely seeing some strange behaviors. Here are a few more points that might provide additional context:

- we are using IS in the controlled mode as per the explanations here (https://community.algolia.com/react-instantsearch/Getting_started_React_native.html#putting-our-filters-in-a-modal)
- falling back to the non controlled mode (effectively killing support for mobile filters) seems to fix the problem
- alongside duplicate requests there appear to be other random looking requests (e.g. hitting page 6 in the pagination would request some other page as well)

**Comment by callmephilip** [comment]
I've just upgraded to `5.0.1` and I am still seeing the issue

**Comment by samouss** [comment]
Thanks for those information, I understand that your app is a closed source. But having a small reproduction could help us to investigate more closely the issue. You can find a template [in CodeSandbox](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/React%20InstantSearch).

**Comment by callmephilip** [comment]
@samouss you can find a mini reproduction here: https://codesandbox.io/s/jj3990ry3

To my best understanding, whenever we were trying to use a wrapped component inside the `InstantSearch` component, this would trigger multiple searches. In the example above we have a simple search box extension to support random place holders. I am not 100% sure if it has something to do with the lib we are using (https://github.com/arunoda/react-komposer) - I have not tried this with any other compositions. Hopefully this is enough of a starting point to help us in the investigation

**Comment by samouss** [comment]
Thanks, it will help us a lot!

**Comment by samouss** [comment]
Hi @callmephilip, I looked at your example. 

The issue come from the `SearchBox` component and the random placeholder generation. With the current implementation of React InstantSearch when a connector receive new props it will perform a shallow comparison between the previous & the next props. When the props are different the component schedule a new request. It's known issue on our side here is the [issue](https://github.com/algolia/react-instantsearch/issues/1042). 

Back to your example, the `SearchBox` will receive a new random translation on every render. It means that every time the translation will change a new request will be schedule. [Here is](https://codesandbox.io/s/l2y1j8x4zq) an example that set always the same translation, you can notice that the request are not doubled.

**Comment by callmephilip** [comment]
Thanks for the clarifications, Samuel. Does this effectively prohibit the usage of any wrapped components inside IS?

**Comment by samouss** [comment]
No the usage of wrapper is not prohibit. What should be avoided (wrapper or not) is to pass a new reference of a prop on each render even when it doesn't change. But I hope we will get rid of this limitation in the upcoming versions.

**Comment by bobylito** [comment]
It seems that the latest version of react-instantsearch does not have the issue anymore. You can try this here: https://codesandbox.io/s/6opx1zk8n (based on a fork of @callmephilip example with the latest react-instantsearch version)

**Comment by samouss** [comment]
Actually no React InstantSearch still have the issue. It's patched in our API Client but not in the library itself. For example users that implement a custom search client (like the one implemented by @iam4x) will still have the issue.

**Comment by CodeMohan** [comment]
We are experiencing the same issue. Is there any work around for this?

**Comment by samouss** [comment]
@CodeMohan for the moment the workaround is inside [the Algolia client](https://github.com/algolia/algoliasearch-client-javascript). You can opt-in for an option that deduplicate pending requests. This behaviour is enabled by default with the version 5.2.0 of React InstantSearch. 

If for any reasons you can't upgrade to the v5 you can use the prop `algoliaClient` to provide a custom client to React InstantSearch. The provided client must be at least on the version [3.28.0](https://github.com/algolia/algoliasearch-client-javascript/blob/develop/CHANGELOG.md#3280). The client must be created with the option `_useRequestCache: true`. Here is [an example](https://codesandbox.io/s/2v7y5vv53n) that shows how to implement it.

**Comment by CodeMohan** [comment]
Thanks @samouss. We tried the second approach you suggested. It did remove the duplicate calls but experiencing other side effects. We are investigating those issues.

**Comment by cloakedninjas** [comment]
I've stumbled across this myself. Recently moved from purely client rendering to SSR and was seeing duplicate requests being sent out. With the above option going into `algoliaClient` this has removed the duplicate requests.

However - toggling refinements on/off/on/off results in new requests being made after each interaction, while our client-side only code was smart enough to not send identical requests out.

I've done text diffs on the requests with the same refinements and the payloads are identical.

Is there any update on this issue?

**Comment by samouss** [comment]
Would you mind create a reproducible example? That would help to understand the issue. We provide template to avoid you the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch).

**Comment by Haroenv** [comment]
note the prop is now called `searchClient`, but still works the same

**Comment by cloakedninjas** [comment]
> We provide a template to avoid you the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/react-instantsearch).

Do you have a `createInstantSearch` version of the boilerplate ?

**Comment by Haroenv** [comment]
Like this? http://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/server-side-rendering

**Comment by cloakedninjas** [comment]
I found the cause of my other issue, I was re-creating the `searchClient` each render, which explains  the cache being emptied and not preventing duplicate requests.

However `_useRequestCache: true` is still required (even with `5.7.0`)

**Comment by samouss** [comment]
Glad to see that you solved your issue. Yes, `_useRequestCache` is required to effectively deduplicate the request. Note that in the next version of the client this option will be enabled by default. At some point, we'll fix those issues inside React InstantSearch, but it's a tedious task that requires a lot of internal changes.

**Comment by Haroenv** [comment]
this has been fixed by using algoliasearch@4 or _useRequestCache in v3
