### ISSUE TITLE
Typing for "facets" missing in <DynamicWidgets> definition

### ISSUE THREAD

**Issue by jsancho** [algolia/react-instantsearch#3563]
## 🐛 Bug description

The [documentation](https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/facet-display/react/#preventing-extra-data-being-requested) describes a `facets` prop that can be used in `<DynamicWidgets>` to configure whether all facets are queried initially on mount.

The typescript linter shows an error as it seems that the typing is missing this prop.

The error can be disabled with a `{/* @ts-ignore */}` and the component seems to work as expected

Live reproduction here
https://codesandbox.io/s/algolia-react-hooks-vq820f?file=/src/App.tsx

- React InstantSearch Hooks version: 6.30.1
- React version: 18.0.0

**Comment by Haroenv** [comment]
Thanks, that indeed was incorrect. I've proposed a pull request to fix this in https://github.com/algolia/react-instantsearch/pull/3566

**Comment by jsancho** [comment]
brilliant! thanks very much :)
