### ISSUE TITLE
useWidget cleanup causes query to search on page navigation in next.js

### ISSUE THREAD

**Issue by carlreid** [algolia/react-instantsearch#3576]
## 🐛 Bug description

When navigating to another page in next.js, the `useWidget` cleanup is causing a stack trace that results in a re-fetch of data from the search index; even if that page has no use of this data.  
  
In my case, it is related to my custom refinement lists, that make use of `useRefinementList`.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/competent-wiles-47yvq6?file=/pages/index.tsx:1689-1726
2. Open up dev console to view network traffic
3. Click on the "page" link  
![image](https://user-images.githubusercontent.com/33623601/180415321-c8c23a1d-e5e1-4abb-a3fd-e806331445fc.png)
5. Observe 4 network calls being made:
![image](https://user-images.githubusercontent.com/33623601/180415255-404c815c-0bad-4564-85e5-c4142e3af85c.png)

**Live reproduction:**

https://codesandbox.io/s/competent-wiles-47yvq6?file=/pages/index.tsx:1689-1726

## 💭 Expected behavior

That no calls are being made when components unload.

## Environment

- React InstantSearch Hooks version: "react-instantsearch-hooks-web": "^6.30.2",
- React version: "react": "18.2.0",
- Browser: Firefox 103.0b9, Chrome 103.0.5060.134
- OS: Windows

## Additional context
Stack Trace:  
```
send/<
[algoliasearch-lite.umd.js:2:13083](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
send
[algoliasearch-lite.umd.js:2:12368](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
t
[algoliasearch-lite.umd.js:2:7674](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
w/<
[algoliasearch-lite.umd.js:2:8003](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
(Async: promise callback) w
[algoliasearch-lite.umd.js:2:7960](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
n
[algoliasearch-lite.umd.js:2:9618](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
read/</<
[algoliasearch-lite.umd.js:2:9950](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
get
[algoliasearch-lite.umd.js:2:4237](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
read/<
[algoliasearch-lite.umd.js:2:9909](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
get
[algoliasearch-lite.umd.js:2:4237](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
read
[algoliasearch-lite.umd.js:2:9867](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
J/<
[algoliasearch-lite.umd.js:2:11410](webpack://_N_E/node_modules/algoliasearch/dist/algoliasearch-lite.umd.js?1228)
AlgoliaSearchHelper.prototype._search
[algoliasearch.helper.js:1299](webpack://_N_E/node_modules/algoliasearch-helper/src/algoliasearch.helper.js?5e84)
AlgoliaSearchHelper.prototype.searchOnlyWithDerivedHelpers
[algoliasearch.helper.js:155](webpack://_N_E/node_modules/algoliasearch-helper/src/algoliasearch.helper.js?5e84)
start/mainHelper.search
[InstantSearch.js:388](webpack://_N_E/node_modules/instantsearch.js/es/lib/InstantSearch.js?40eb)
InstantSearch/<
[InstantSearch.js:107](webpack://_N_E/node_modules/instantsearch.js/es/lib/InstantSearch.js?40eb)
fn/progress<
[defer.js:24](webpack://_N_E/node_modules/instantsearch.js/es/lib/utils/defer.js?7d3a)
(Async: promise callback) fn
[defer.js:16](webpack://_N_E/node_modules/instantsearch.js/es/lib/utils/defer.js?7d3a)
removeWidgets
[index.js:271](webpack://_N_E/node_modules/instantsearch.js/es/widgets/index/index.js?2316)
cleanup
[useWidget.js:27](webpack://_N_E/node_modules/react-instantsearch-hooks/dist/es/lib/useWidget.js?707b)
(Async: setTimeout handler) useWidget/</<
[useWidget.js:60](webpack://_N_E/node_modules/react-instantsearch-hooks/dist/es/lib/useWidget.js?707b)
safelyCallDestroy
[react-dom.development.js:22831](webpack://_N_E/node_modules/react-dom/cjs/react-dom.development.js?ac89)
commitDeletionEffectsOnFiber
[react-dom.development.js:23998](webpack://_N_E/node_modules/react-dom/cjs/react-dom.development.js?ac89)
```

**Comment by JamesHemery** [comment]
This seems to have been introduced by version 6.30.2.

In my case, we have a lot of widgets, when the visitor clicks on a link and changes the page, this problem sends +15 requests...

Version 6.30.1 works correctly.

You can use this sandbox to test: https://codesandbox.io/s/prod-fire-rm18gm?file=/pages/index.tsx:0-2554

Just change the version from 6.30.1 to 6.30.2 to see the problem.

**Comment by dhayab** [comment]
Hi, this looks identical to https://github.com/algolia/react-instantsearch/issues/3586, which will be fixed by https://github.com/algolia/react-instantsearch/pull/3590 in the coming days.

**Comment by carlreid** [comment]
Well, I think it's the other way around that #3586 is identical to this (11 days older), but great there's a fix coming 😊

**Comment by FabienMotte** [comment]
Hey @carlreid! This issue should be fixed in the latest release of React InstantSearch Hooks [v6.31.1](https://github.com/algolia/react-instantsearch/releases/tag/v6.31.1).

Feel free to reopen if that's not the case, thank you!

**Comment by carlreid** [comment]
@FabienMotte Cheers for the ping. Look forward to trying out soon, and thanks for the fix ❤️
