### ISSUE TITLE
Multiple requests hit on component unmounts / route change in react

### ISSUE THREAD

**Issue by iamdhrooov** [algolia/react-instantsearch#3586]
## 🐛 Bug description

When changing routes in react or unmounting the components, the library hits the queries multiple times. (number of times specific refinements are added). This is happening on latest version v6.30.3 and not happening for v6.29.0

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to [Codepen link](https://codesandbox.io/s/strange-flower-13wnc5?file=/App.tsx)
2. Click on `Change route on top`
3. Check API query calls in the network tab.
4. Multiple queries hit on unmount.
5. Change version to v6.29.0 -> works fine

**Live reproduction:**

https://codesandbox.io/s/strange-flower-13wnc5?file=/App.tsx

## 💭 Expected behavior

It should not hit queries multiple times.

## Environment

- React InstantSearch Hooks version: [6.30.3]

**Comment by FabienMotte** [comment]
Hello @iamdhrooov,

Thanks for reporting this issue, I'm working on PR #3590 to fix it.
It should be released this week.

Thanks for your patience!

**Comment by FabienMotte** [comment]
Hey @iamdhrooov! This issue should be fixed in the latest release of React InstantSearch Hooks [v6.31.1](https://github.com/algolia/react-instantsearch/releases/tag/v6.31.1).

Feel free to reopen if that's not the case, thank you!

**Comment by iamdhrooov** [comment]
Thanks for the quick turnaround on this @FabienMotte Really appreciate it. :)

**Comment by ccchapman** [comment]
Would these excess network requests result in additional charges?

**Comment by Haroenv** [comment]
Yes, every request which happens will be charged. If this had an impact on your pricing fixed since 6.31.1, you can contact support@algolia.com
