### ISSUE TITLE
[Bug] useHierarchicalMenu - child item selection returns wrong menu items

### ISSUE THREAD

**Issue by jsdmc** [algolia/react-instantsearch#3587]
## 🐛 Bug description

When selecting last level items in hierarchical menu, hook returns also root level items that are not valid for selected filters.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://instantsearchjs.netlify.app/stories/?path=/story/refinements-hierarchicalmenu--default
2. Click on "Incipio" checkbox in BRANDS section
3. Go to hiearachical menu and select first level item "Computers & Tablets"
4. Select child level item "Computers & Tablets > iPad& Tablet Accessories"
5. See new root level categories appeared. (this is incorrect)
6. Click on any new category. "Audio" for example
7. You see "no results" now.

**Live reproduction:**

https://instantsearchjs.netlify.app/stories/?path=/story/refinements-hierarchicalmenu--default

## 💭 Expected behavior

After selection of child category - there should be no categories displayed if they don't contain items that satisfy applied filters (brand "Incipio")

## 🖥 Screenshots

![hierarchica-menu](https://user-images.githubusercontent.com/2140953/182611375-ba26a97a-5be3-42ac-86b1-e0e322031b6c.gif)

**Comment by dhayab** [comment]
Hi, thanks for reporting this. I've logged it internally so we can start working on a fix.

In the meantime, you can revert `algoliasearch-helper` to version `3.8.2`, which doesn't include the code that causes this issue.

**Comment by jsdmc** [comment]
@dhayab Which version of `react-instantsearch-hooks-web` should I use? I don't use `algoliasearch-helper` directly so not sure how all dependencies will be resolved even if I add version that you mentioned to `package.json` of my project

**Comment by jsdmc** [comment]
I guess it's gonna be 6.28.0
Please confirm @dhayab 
https://github.com/algolia/react-instantsearch/blob/v6.28.0/packages/react-instantsearch-hooks/package.json

**Comment by dhayab** [comment]
Reverting to an older react-instantsearch-hooks-web package won't work, since the range specifier for algoliasearch-helper will automatically get the latest minor version of the dependency.

If you're using Yarn, you can pin a transitive dependency by using the resolutions field of your package.json file:

```jsonc
{
  // ...
  "resolutions": {
    "algoliasearch-helper": "3.8.2"
  }
}
```

With npm, this is done with the overrides field:

```jsonc
{
  // ...
  "overrides": {
    "algoliasearch-helper": "3.8.2"
  }
}

**Comment by jsdmc** [comment]
Thanks @dhayab ! That works for now.

**Comment by dhayab** [comment]
Hi! We recently released a new version of the helper that fixes this issue internally (algoliasearch-helper@3.11.1).

You can remove the dependency pinning in your package.json file and reinstall your dependencies, it should automatically download the right version.
