### ISSUE TITLE
Server-Side Rendering with useRouter in Next.js

### ISSUE THREAD

**Issue by necheporenko** [algolia/react-instantsearch#3596]
## 🐛 Bug description
I tried to add SSR for my Next.js application using this [guide ](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/?client=index.js#with-nextjs), but got an error.

Doesn't work with `import { useRouter } from 'next/router'; console.log(router.asPath);` 

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to `https://codesandbox.io/s/crazy-curie-sdeqdi?file=/components/Panel.tsx`
2. See error `TypeError: Cannot read property 'asPath' of null`

**Live reproduction:**

https://codesandbox.io/s/crazy-curie-sdeqdi?file=/components/Panel.tsx

## 💭 Expected behavior

It should work without that:
```
-   const { asPath } = useRouter()
+  const router = useRouter()
+  const { asPath } = router || {}
```

**Comment by dhayab** [comment]
Hi, this is not an issue with InstantSearch. Next.js `useRouter` hook is not available in a server-side rendered component.
