### ISSUE TITLE
Documentation and examples for NextJs

### ISSUE THREAD

**Issue by Mar0cas** [algolia/react-instantsearch#3601]
## 🐛 Bug description

Your example on [CodeSandbox](https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/next?file=/components/app.js:1036-1046) in this [GitHub examples next doc](https://github.com/algolia/react-instantsearch/tree/master/examples/next), isn't working.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Go to https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/next?file=/components/app.js
2. Click in any filter or input search
3. See console errors

**Live reproduction:**

https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/next?file=/components/app.js

## 🖥 Screenshots

![image](https://user-images.githubusercontent.com/59584721/185966916-54829aa8-5cb9-4f3a-8bc0-4630f6241847.png)

## Environment

- React InstantSearch version: [e.g. 6.24.0]
- React version: [e.g. 18.1.0]
- Browser: [e.g. Chrome 102.0.5005.61, Safari 15.2]
- OS: [e.g. Windows / Linux / macOS / iOS / Android]

**Comment by dhayab** [comment]
Hi, thanks for your feedback! The sample works well locally, but it is currently broken in Codesandbox because it uses node 10 and some dependencies are not compatible.

I've added some specific settings for Codesandbox so it switches to the right node version.
