### ISSUE TITLE
React InstantSearch 

### ISSUE THREAD

**Issue by Vitor-Vilela** [algolia/react-instantsearch#3603]
## 🐛 Bug description

Hey Guys! I'm facing a problem with the implementation using react-instantsearch-hooks, basically what happens is:
I first receive from an algolia request a list of disjunctiveFacets to retrieve when using the InstantSearch component, then inside a Modal component I map the userData and the facets received from the results provided by the useInstantSearch() hook, since I have a lot of different attributes for the components using the useRefinementList() hook, I need to dynamic render them. When I update the results by applying a refine() inside one of those components, the old attributes are unmounted and I map the new list (received on the results from the hook) to only mount the ones applicable for the new parameters, and the problem is: When I do that the InstantSearch uiState updates itself to the initial state from when the modal was first mounted, causing the filters to be unapplied and the results from the useInstantSearch to rollback.
I also make use of VirtualizedFilters to keep the refinements applied when the modal is closed.
Attached I have a video to demonstrate the problem, you can see the search being reverted when the orange button number goes back to the initial state.
I don't know if you guys can help us with this kind of implementation, but I made sure to follow the documentation and to avoid re-renders on the filter components.

I can also share a test project in which the same behaviour is happening, it has the same hierarchy and follows the same routines for searching from our App

## 🔍 Bug reproduction

1. Search for comething
2. Open the filter modal
3. Try to apply a Refinement

https://github.com/Vitor-Vilela/filtertest

That's a private repositorie  since it has the search hierarchy and the access key from my App, I can provide access to any certified developer who can help

## 💭 Expected behavior

I expect the refinements to be applied without triggering the search rollback

## 🖥 Screenshots

https://user-images.githubusercontent.com/98328435/186752615-257dbdd3-5b47-45f1-b2c2-3e47a714c52c.mov

## Environment

- React InstantSearch Hooks version: 6.31.1
- React version: 17.0.2
- OS: iOs/Android

## Additional context

I have an open issue on your support platform the id is 510988

**Comment by dhayab** [comment]
Closing this as we're tracking the issue in #3604.
