### ISSUE TITLE
Cypress Testing: Uncaught TypeError: this.props.contextValue.store.getState is not a function

### ISSUE THREAD

**Issue by Wrishi** [algolia/react-instantsearch#3613]
I am getting this error while trying to test any component within `<InstantSearch/>`

![image](https://user-images.githubusercontent.com/17313248/188830318-88b80765-e1ef-4b60-81f7-b49d4537c69f.png)

Library versions:
```
    "algoliasearch": "^4.14.2",
    "react": "^18.2.0",
    "react-autosuggest": "^10.1.0",
    "react-dom": "^18.2.0",
    "react-instantsearch-dom": "^6.32.1",
    "react-instantsearch-hooks-web": "^6.32.1",
    "cypress": "^10.7.0",
```
I have tested this with React Tests as well, with the same error.

There are no errors, however, when I run the application.

**Comment by Haroenv** [comment]
What code is inside the cypress test which fails?

**Comment by Wrishi** [comment]
Here is the cypress code

```
import SearchBar from "../../src/components/searchbar/SearchBar"

describe('SearchBar.cy.js', () => {
  it('renders correctly', () => {
    cy.mount(<SearchBar/>)
  })
})
```

The simlipfied component structure is as follows:
```
<InstantSearch
        indexName={process.env.REACT_APP_SEARCH_INDEX}
        searchClient={searchClient}
        onSearchStateChange={(searchState) => console.log(searchState)}
>
        <Configure hitsPerPage={MAX_HITS}  filters="..."/>
        <div className="app">
              <SearchBar />
        </div>
</InstantSearch>
```

**Comment by Haroenv** [comment]
As you can see, you're mounting only the SearchBar, but it doesn't have the InstantSearch component surrounding it, and thus get this error
