### ISSUE TITLE
findResultsState with Nextjs useRouter makes router null when pre-rendering

### ISSUE THREAD

**Issue by foldess** [algolia/react-instantsearch#3620]
## 🐛 Bug description

When using ```findResultsState``` inside nextjs function ```getStaticProps``` the nextjs router object declared using ```const router = useRouter()``` is null instead of Server Router

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Clone repo [test Repository](https://github.com/foldess/instantsearch-nextjs-test)
2. run build
3. Look at logs

## 💭 Expected behavior

Router should not be undefined but server router instance

## 🖥 Screenshots

![image](https://user-images.githubusercontent.com/59058468/189853105-bbf63880-f927-47b7-9615-77854cbe7132.png)

## Environment

- React InstantSearch version: 6.32.1 on test repo, 6.22.0 on devlopment repo
- React version: 17.0.2
- Nextjs version: Latest on test repo, 12.2.5 on devlopment repo

**Comment by dhayab** [comment]
Hi, that's because `findResultsState()` renders the component with no knowledge of Next.js Router context, so you need to provide it explicitly. You can check https://github.com/algolia/react-instantsearch/issues/3524#issuecomment-1160078935 for more info.
