### ISSUE TITLE
Instant search not showing results in Next.js dev mode but works in prod mode. 

### ISSUE THREAD

**Issue by mjolnir91** [algolia/react-instantsearch#3629]
As stated in the title I get results back after making a next.js build and then doing next.js start. However, if I just run next.js dev I get no results back from algolia and I have no idea why I don't see any errors in the console.

**Comment by aymeric-giraudet** [comment]
Hi @mjolnir91 and @FilipMasar,

Thank you for raising the issue. However I need some more information so we can properly investigate it.

Which versions of `react-instantsearch` are you using ? 
Could you provide a link to a reproduction, either a GitHub repo or a codesandbox ?

**Comment by mjolnir91** [comment]
@FilipMasar I did exactly what you said and it fixed the issue.
@aymeric-giraudet 
    "react-instantsearch-dom": "^6.28.0",
    "@types/react-instantsearch-dom": "^6.12.3",
    "react": "latest",
    "next": "latest",
    
[package.txt](https://github.com/algolia/react-instantsearch/files/9609524/package.txt)

**Comment by mizozobu** [comment]
Downgrading `react` and `react-dom` to `17.0.2` solved the issue for me. Maybe it's not nextjs but react 18 that is causing this? Can anyone else confirm?

I'm using
```
"algoliasearch": "4.14.2",
"next": "12.3.1",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-instantsearch-dom": "6.33.0",
```

**Comment by aymeric-giraudet** [comment]
Makes sense @mizozobu as strict mode in React 18 mounts components twice in development environment.

We took that into account for `react-instantsearch-hooks-web` but we haven't for `react-instantsearch-dom`. Note that new projects should use `react-instantsearch-hooks-web` as it will eventually replace `react-instantsearch-dom`.

I will check with the team if we plan to add support to React 18 strict mode for `react-instantsearch-dom` and will get back to you all !

**Comment by aymeric-giraudet** [comment]
I was able to reproduce the bug but only when not using `getServerSideProps`, it works fine when following [this example](https://github.com/algolia/react-instantsearch/tree/master/examples/next). Were you using `findResultsState` in `getServerSideProps` ? If not I would recommend you to, it will be nicer for users and SEO.

I can also confirm that we do not plan to fix this as `react-instantsearch-hooks` is our main focus. 

If you want to check out how to use it with Next.js, [here's a guide](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/), you'll see that it's much more straightforward than with `react-instantsearch-dom` !
