### ISSUE TITLE
Algolia's searchBox is stuck and is not accepting new values

### ISSUE THREAD

**Issue by Arthur-Maskalenkas** [algolia/react-instantsearch#3634]
## 🐛 Bug description

I'm trying to type new values ​​after instantiating Algolia's SearchBox, but it doesn't change the input value at all. I've recreated the NextJs boilerplate and implemented it 5 times, but the value never changes. What could it be?

## 🔍 Bug reproduction

1 - Clone my repository https://github.com/Arthur-Maskalenkas/bug-report
2 - try typing input

**Live reproduction:**

https://codesandbox.io/p/github/Arthur-Maskalenkas/bug-report/csb-zf1foq/draft/happy-smoke?file=%2FREADME.md

## 💭 Expected behavior

I would like the input to update the value if anything is typed.

## 🖥 Screenshots

https://i.ibb.co/3rRc0tN/GIF-24-09-2022-17-47-21.gif

## Environment

- "algoliasearch": "^4.14.2"
- "react": "18.2.0"
- "react-instantsearch-dom": "^6.33.0"

## additional info
https://stackoverflow.com/questions/73840560/algolias-searchbox-is-stuck-and-is-not-accepting-new-values

**Comment by aymeric-giraudet** [comment]
Hi @Arthur-Maskalenkas,

This seems like a duplication of issue https://github.com/algolia/react-instantsearch/issues/3629.

- If your project is new, please use `react-instantsearch-hooks` as this is will eventually replace `react-instantsearch-dom`.
- If this is a project you already have in production and cannot upgrade from `react-instantsearch-dom` to `react-instantsearch-hooks`, I think it would be best to take advantage of Next.js SSR for better SEO and less latency for users (especially on mobile), following [this guide](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/)
- If the above applies and you really only want it to be ever rendered client-side, you can set `reactStrictMode: false` in `next.config.js`
