### ISSUE TITLE
`GoogleMapsLoader` instantly unmounts, not rendering Map

### ISSUE THREAD

**Issue by joepio** [algolia/react-instantsearch#3678]
Hi there! First off, thanks for maintaining this really nice library :)

I'm kind of stuck with `react-instantsearch-dom`, as you can read below, but maybe I should migrate to `react-instantsearch-hooks-web` anyway.

## 🐛 Bug description

I'm trying to render a map using `GoogleMapsLoader` and `GeoSearch`, but fail to render anything. I've set a `height` in the parent, so that's not it. 

There are no errors in the console, and the network responses look good - I can see that Google's API is responding with `200`s. 
And `window.google` is in fact a `google` object, so I suppose the googles js code is running just fine. 

I've [tried reproducing the bug in CodeSandbox](https://codesandbox.io/s/friendly-ganguly-jsmgsl?file=/src/index.js:681-697), but to no avail. It just works there.

The lambda in the children of `GeoSearch` is never called. If I put a `console.log` in, It never shows.
So for some reason something goes wrong in [`GoogleMapsLoader`](https://github.com/algolia/react-instantsearch/blob/d1f53ae815b75f13c18fd245e0403d57e7ae391c/packages/react-instantsearch-dom-maps/src/GoogleMapsLoader.js#L30).

This condition is always false, because `this.isUnmounting` seems to always be `true` in my case. 
```ts
// GoogleMapsLoader.js 
        if (!this.isUnmounting) {
          this.setState(() => ({
            google: window.google,
          }));
        }
```

So the google state is never set, and this always returns null:
```
      if (!this.state.google) {
        return null;
      }
```

`this.isUnmounting` is practically always set to true, because `componentWillUnmount` is called early on.

```
  componentWillUnmount() {
    this.isUnmounting = true;
  }
```

I thought this is supposed to be called only when a component will unmount? 

## Code

```ts
import React from "react";
import {
  GoogleMapsLoader,
  GeoSearch,
  Control,
  Marker,
} from "react-instantsearch-dom-maps";
import { mapsKey } from "./config";
import './Map.css';

export const Map = () => {
  return (
    <div className="Map">
      <GoogleMapsLoader apiKey={mapsKey}>
        {(google) => {
          console.log('google', google);

          return (
          <GeoSearch google={google}>
            {({ hits }) => (
              <div>
                <Control />
                {hits.map((hit) => (
                  <Marker key={hit.objectID} hit={hit} />
                ))}
              </div>
            )}
          </GeoSearch>
        )}}
      </GoogleMapsLoader>
    </div>
  );
};

```

## Environment

- React InstantSearch version: 6.38.0
- React version: 18.2
- Browser: Firefox and chrome
- OS: MacOS latest, m1

**Comment by Haroenv** [comment]
Does this reproduce in a clean-slate React InstantSearch implementation on your local machine or also not? I wonder if it could be related to strict mode / react 18 possibly? Have you tried if changing either of those made a difference?

**Comment by joepio** [comment]
Thanks for the quick reply, @Haroenv!

Indeed, removing `React.StrictMode` seemed to fix it! I also had to manually set some CSS properties (`height: 100%`).

Thanks!

**Comment by Haroenv** [comment]
This is thus indeed a bug in the maps package, which unmounts, but not correctly remounts. Strict mode calls the life cycle functions multiple times and this code wasn't written with that in mind.

As we haven't migrated the maps package to react hooks yet, I'd recommend staying with React InstantSearch dom for now.

Is avoiding strict mode an option for you in the mean time?

**Comment by joepio** [comment]
Avoiding strict mode is fine for me for now, thanks for helping out!

**Comment by nathan-schmidt-viget** [comment]
Had the same problem, removed `React.StrictMode` fixed it.

**Comment by FabienMotte** [comment]
We're doing a round of cleanup before migrating this repository to the new [InstantSearch monorepo](https://github.com/algolia/instantsearch.js). This issue seems not to have generated much activity lately and is to be mostly solved, so we're going to close it. Feel free to reopen it if needed.
