### ISSUE TITLE
Nextjs 13.0.5 SSR: Error: NextRouter was not mounted. 

### ISSUE THREAD

**Issue by abusada** [algolia/react-instantsearch#3691]
## 🐛 Bug description

After upgrading nextjs to version [13.0.5](https://github.com/vercel/next.js/releases/tag/v13.0.5) I started getting: `Error: NextRouter was not mounted.` when doing server side rendering.

## 🔍 Bug reproduction

1. Using the same code from [Server Side Rendering with Nextjs docs](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react-hooks/#with-nextjs)
2. Add `useRouter` to the page's main code

**Live reproduction:**
Look at `pages/index.tsx` https://replit.com/@FarisAbusada/NextAlgoliaSSR#pages/index.tsx

## 💭 Expected behavior

Expect page to render as it did with previous versions of nextjs.

## 🖥 Screenshots
![screenshot- 2022-11-30 at 10 45 50@2x](https://user-images.githubusercontent.com/2572320/204762736-a46e5650-703d-4ba1-a23f-e48a57301ccb.jpg)

## Environment

```
"dependencies": {
    "next": "^13.0.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "algoliasearch": "^4.14.2",
    "react-instantsearch-hooks-server": "^6.38.1",
    "react-instantsearch-hooks-web": "^6.38.1"
  },
```

**Comment by Haroenv** [comment]
You'll need to hoist useRouter to a level which isn't called inside getServerState, so that useRouter is only called by Next.js

**Comment by abusada** [comment]
@Haroenv, thanks for the quick response. I confirm that it works when I don't wrap the whole page with `getServerState` but only the component that is using `InstantSearchSSRProvider`.

**Comment by Haroenv** [comment]
Thanks for confirming this fixed your issue!
