### ISSUE TITLE
Highlight is not unicode safe

### ISSUE THREAD

**Issue by nickstanish** [algolia/react-instantsearch#37]
Highlighting turns unicode/emojis into question mark symbols.
JavaScript's String#split (and other similar functions) are not unicode-compliant, so would need a compliant library to handle the string operations. 

https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/src/core/highlight.js#L52

I believe using lodash for the string operation (which is included already) would allow this functionality to work out of the box.

https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L14565
![image](https://cloud.githubusercontent.com/assets/1869157/25027620/a65581ec-2073-11e7-859d-a0d13100adb3.png)

**Comment by nickstanish** [comment]
This isn't as simple as I originally thought it was. The `const highlightObject = get(hit[highlightProperty], attributeName);` is using the `_highlightResult` which already has the unicode messed up

**Comment by Haroenv** [comment]
This is a bug in the engine we know about unfortunately. We use UCS-2, and switching to UTF8/16 will take a lot of time. We noted that you notice this too
