### ISSUE TITLE
before search start function / after search finish function

### ISSUE THREAD

**Issue by frozenfung** [algolia/react-instantsearch#382]
**Do you want to request a *feature* or report a *bug*?**

feature

**Feature: What is your use case for such a feature?**

I am wondering is it possible for customization before/after per request is sent.

For example, I want to use tools like [bootstrap alert](https://www.w3schools.com/bootstrap/bootstrap_alerts.asp) so that when user change search state they will see simple alert like **Loading...** before request is send. In the other hand, I need to transform **Loading...** into **Finish** after the request is done. 

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

I would say that we can pass two more props into `<InstantSearch>` component like `beforeRequest` and `afterRequest` which we can define our own operation in these functions. If the signature is fine I can make a PR then.

**What is the version you are using? Always use the latest one before opening a bug issue.**

4.1.0-beta.4

Really appreciate you guys make such a awesome tools!

**Comment by mthuret** [comment]
Hi @frozenfung, thanks for the feedback :) 

For the `afterRequest`, you have the `onSearchStateChange` function that is called every time something is refined, I believed it can serve what you're looking for. 

Also we compute a `searching` field that you can access using this: https://community.algolia.com/react-instantsearch/guide/Conditional_display.html#displaying-content-when-loading
Warning: It's going to change very soon as a new api, `connectResultsState` is going to be release asap. 

Would that help already? What did I miss?

**Comment by frozenfung** [comment]
Thanks for fast reply! I think connectState is what I need.
