### ISSUE TITLE
connectorRange ignores min / max boundaries on first call

### ISSUE THREAD

**Issue by samouss** [algolia/react-instantsearch#384]
If you set boundaries on a widget related to `connectRange` (`RangeSlider`, `RangeInput`), there are ignored on the first call. In the given example the boundaries are set to `30` and `100`. The UI is align with the options but in the results we still have the products with prices out of bounds.

When you change the values of the slider, then reset it to the initial position the results is correct.

https://community.algolia.com/react-instantsearch/storybook/?selectedKind=RangeSlider&selectedStory=custom%20min%2Fmax%20bounds&full=0&down=1&left=1&panelRight=1&downPanel=storybooks%2Fstorybook-addon-knobs

**Comment by mthuret** [comment]
Thanks for spotting this @samouss! 

To precise it's the props `min` and `max` that are not taking into account for the first request. 
`defaultRefinement` is ok.
