### ISSUE TITLE
searchResults.loading is undefined

### ISSUE THREAD

**Issue by tiodan81** [algolia/react-instantsearch#39]
Using react-instantsearch 3.3.1, I tried to set up conditional rendering during loading per [the docs](https://community.algolia.com/react-instantsearch/guide/Conditional_display.html#displaying-content-when-loading), but `searchResults.loading` comes up undefined. Here's my code:

```
export default createConnector({
  displayName: 'SearchResults',
  getProvidedProps(props, searchState, searchResults) {
    const totalHits = searchResults.results ? searchResults.results.nbHits : 0
    console.log(searchResults);
    return {
      isLoading: searchResults.loading,
      totalHits
    }
  },
})(ConnectedHits)
```

When logging `searchResults` there, I get `{results: SearchResults, searching: true, error: null}` so I tried returning `{ isLoading: searchResults.searching, totalHits }`, which gives me real values. So it seems the docs for conditional display need to be updated.

**Comment by Haroenv** [comment]
Thanks for noticing this. We will investigate where the issue lies, or if you're sure where the fix is, feel free to update the document
