### ISSUE TITLE
clear button doesn't close the searchbox (website)

### ISSUE THREAD

**Issue by Shipow** [algolia/react-instantsearch#40]
**Do you want to request a *feature* or report a *bug*?**

bug

**Bug: What is the current behavior?**

docsearch clear button only dismisses the popup

**Bug: What is the expected behavior?**

clear button clears the search and dismisses the popup

**Bug: What browsers are impacted? Which versions?**

All?

**What is the version you are using? Always use the latest one before opening a bug issue.**

https://community.algolia.com/react-instantsearch/

**Comment by Haroenv** [comment]
Did you make this issue by accident? Feel free to reopen when you updated the description.

**Comment by Haroenv** [comment]
This will be gone when we move to the community header though, cc @jonasba

**Comment by Shipow** [comment]
Can we plan the migration in that case? I really don't like bugs powered by algolia :p

**Comment by JonasBa** [comment]
@Shipow on it ;)
