### ISSUE TITLE
Can't catch network error on refine()

### ISSUE THREAD

**Issue by noclat** [algolia/react-instantsearch#414]
I generate API keys that expire quiet quickly, and when the user keeps the tab open on background and comes back after the token has expired, the `refine()` function called inside a custom search box using `connectSearchBox` throws a network error I cannot catch. I'd like to be able to handle the error and refresh the page when Algolia returns that error, but could not find any way to do that.

![errors](https://user-images.githubusercontent.com/1834312/31085493-94479eda-a797-11e7-924f-5d9b46a7ea40.png)

1. First log thrown by connected search box when `refine()` is called, not catchable. Query body reads `{message: ""validUntil" parameter expired (less than current date)", status: 400}`.
2. Second log thrown by native API client `.search()` method, catchable.

**Comment by Haroenv** [comment]
Did you try `componentDidCatch` in react 16? I think it might be related

**Comment by mthuret** [comment]
@noclat Also `connectResultsState` should let you access the error => probably just the error message though, I'll need to check.

**Comment by noclat** [comment]
Works like charm 👍
