### ISSUE TITLE
Add editorconfig

### ISSUE THREAD

**Issue by vvo** [algolia/react-instantsearch#415]
This ease collaboration and enforces things like:
- indentation style
- strip white space
- always add an empty line

Example:

```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

WDYT?

**Comment by Haroenv** [comment]
indent_style and indent_size are redundant with prettier and eslint, but WFM

**Comment by vvo** [comment]
> indent_style and indent_size are redundant with prettier and eslint, but WFM

As discussed in IS.js repo, this also allows us to ensure every files are going through those rules, not just JavaScript files.

So that when saving a markdown file you do not endup with weird diff because some spaces are extraneous.

**Comment by vvo** [comment]
> indent_style and indent_size are redundant with prettier

Quick note: seems like prettier has no parameters around this, weird

**Comment by vvo** [comment]
Done in IS.js https://github.com/algolia/instantsearch.js/pull/2435

**Comment by mthuret** [comment]
@vvo works for me
