### ISSUE TITLE
connectStateResults should give access to props

### ISSUE THREAD

**Issue by denkristoffer** [algolia/react-instantsearch#417]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

I am using `createConnector` to access props, searchState and searchResults and do some calculations in the `getProvidedProps` function. After version 4.1.2 I get the warning that I should use the new `connectStateResults` instead. However that doesn't let me access props the way `createConnector` does.

**Bug: What is the expected behavior?**

Either `connectStateResults` should give access to props, or the warning shouldn't be thrown when `createConnector` is used to access props.

**Comment by mthuret** [comment]
Hi @denkristoffer,

Thanks for your feedback, I actually wondered myself if `props` was something useful to access in this context. I'm curious to know what's your use case with them :)

**Comment by denkristoffer** [comment]
I'm only using it to get the `attributeName`. The idea was to make my connector generic enough that it could be used for different attributes in the future.

```js
const rawData = searchResults.results.disjunctiveFacets.filter(
        facet => facet.name === props.attributeName,
      )
```

**Comment by mthuret** [comment]
I see, I'll add it back soon :)
