### ISSUE TITLE
Make SearchBox even better

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#43]
- [ ] contrast issue
    - contrast of icon is too low
- [x] add aria-label or title on input search
- [x] add aria-hidden=‘true’ on decorative svg
- [x] move focus back to search box when clear is pressed

Also to be thought together with adding a way to focus hits by default, then we can move the focus to the first hit on `submit`

**Comment by goetsu** [comment]
also : 
- move focus back to input when user activate clear button
- change border color / outline the whole search box when focus is in input

**Comment by Haroenv** [comment]
I just tested adding a `title` (in this case `test`), and what I found was that it simply duplicated the placeholder in VoiceOver. I don't think that's useful.

![screen shot 2017-04-20 at 09 21 58](https://cloud.githubusercontent.com/assets/6270048/25218729/247933ce-25ac-11e7-8d14-78b46ada18ca.png)

Also the `role=img` on the svgs already makes VoiceOver speak about a button with the title given, so that seems not needed as well to me.

**Comment by goetsu** [comment]
placeholder isn't par of accessible name calculation so even if VoiceOver read it some other screenreader may not.

**Comment by Haroenv** [comment]
Not according to the specs, but it is according to real-life browsers: http://www.html5accessibility.com/tests/placeholder-labelling.html

**Comment by goetsu** [comment]
@Haroenv yes for now but specs is clear now and bugs have been filled for every browsers to remove that form accessibility tree so look more safe to duplicate with aria-label or title.

**Comment by mthuret** [comment]
I'm closing this as I assume the work @ronanlevesque is doing covers this.
