### ISSUE TITLE
PropTypes from the main React package gives warning

### ISSUE THREAD

**Issue by lezoudali** [algolia/react-instantsearch#44]
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

`React.PropTypes` is deprecated. We should now use the `prop-types` package.

**Comment by Haroenv** [comment]
yes. We have PR #41 open for that, and issue #20 as well. Will be solved soon!
