### ISSUE TITLE
[doc] Suggestion regarding Community pages with very few content

### ISSUE THREAD

**Issue by aseure** [algolia/react-instantsearch#445]
After @mthuret 's release of React InstantSearch 4.1.3 today, I've checked the documentation page. I've landed on https://community.algolia.com/react-instantsearch/widgets/ which is quite empty at first sight. It's expected as it's the "entry" page for this part of the documentation but I still find it lacks something.

I just wanted to share with you what the Rust documentation is doing in that regard which I find quite nice: they are adding big arrow buttons on the sides like here https://doc.rust-lang.org/book/second-edition/ch04-00-understanding-ownership.html. From that, you immediatly understand that you're starting/in the middle of something, even if the page is empty i.e. you are not in a dead end.

**Comment by Haroenv** [comment]
I think the front page of a section could have a link to all of its widgets?

**Comment by vvo** [comment]
Yes that would work, a wall of square with widget names could be a nice way to easily go to them

**Comment by vvo** [comment]
As for the rust website, I am completely lost on the webpage you sent, I don't get which big arrow you meant

**Comment by mthuret** [comment]
It's the arrow on the left/right, a bit like the navigation we propose on the guide page. 

@Haroenv @vvo As the link to the widget are already on the left, like a sidebar, your proposal is to remove them and put them in the center?

**Comment by vvo** [comment]
> your proposal is to remove them and put them in the center?

Keep both, but make the widgets homepage a wall of widgets names. But that might look weird, no precise idea here

**Comment by mthuret** [comment]
Keeping both is a bit weird IMHO. 

Maybe having no sidebar, but the list of widgets directly after the two lines of text could to the trick.

**Comment by Haroenv** [comment]
I think the duplication makes more sense, because there won’t be a different sidebar depending on which page you’re on. A nice grid under the explanation text seems good

**Comment by vvo** [comment]
> Maybe having no sidebar, but the list of widgets directly after the two lines of text could to the trick.

Yes but then you can't change widget when you are on another webpage

**Comment by samouss** [comment]
We don't have those pages inside [the new documentation website](https://www.algolia.com/doc/).
