### ISSUE TITLE
Bug after updating from v3 to v4

### ISSUE THREAD

**Issue by THook** [algolia/react-instantsearch#46]
Hello all,

I tried to update from v3 to v4 in order to use multi-indexing.
Now, all it does is returning an error on line 145 of createInstantSearchManager.js because Object.values is not function.

Any insight on this would be greatly appreciated!

**Bug: What is the current behavior?**

Updating to 4.0.0-beta.0 and up breaks basic working examples.
See: https://jsfiddle.net/8r928c4y/ where I just updated the dependency to 4.0.0-beta.2

**Bug: What is the expected behavior?**

Seamless update from v3 to v4!

**Bug: What browsers are impacted? Which versions?**

I'm working on Chrome but any browser I believe.

Thank you for your time,
Hugo

**Comment by mthuret** [comment]
Hi @THook,

Thank you very much for reporting this. I believe it's because of the usage of Object.values which is not widely supported by every browsers.

I'll make a change and release a new beta :)

**Comment by THook** [comment]
Thanks @mthuret ! I actually read that error so much times that I was totally misreading it. I have an old version on Chrome that may not support Object.values indeed...

I am looking forward for the change,
thanks again

**Comment by mthuret** [comment]
Hey @THook, I just published a beta.3. Can you retry? :)

**Comment by THook** [comment]
Perfect! Works like a charm. I'll add multi-indexing to a working example to test it all out :)

**Comment by mthuret** [comment]
That's great to hear! Happy coding :)

And don't hesitate to share your feedback if any on the new multi-index feature.
