### ISSUE TITLE
/es/ folder doesn't contain es2015 code, but commonjs

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#499]
**Do you want to request a *feature* or report a *bug*?**

bug I guess

**Bug: What is the current behavior?**

the es folder contains the same as the main folder

see https://unpkg.com/react-instantsearch@4.1.3/es/

**Bug: What is the expected behavior?**

the es folder to contain es2015 modules

**What is the version you are using? Always use the latest one before opening a bug issue.**

4.1.3

**Comment by Haroenv** [comment]
This might be because the `env` is broken in babel https://github.com/babel/babel/issues/5276, we can move to `.babelrc.js` and have a way simpler config

**Comment by mthuret** [comment]
Could you handle this @Haroenv?

**Comment by Haroenv** [comment]
Very weird that #547 didn't fix this, but it's still the case: https://unpkg.com/react-instantsearch@4.2.0/es/connectors.js

**Comment by Haroenv** [comment]
oops, this wasn't in 4.2.0 yet 😄
