### ISSUE TITLE
Searchbox: limit to 512 characters

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#510]
**Do you want to request a *feature* or report a *bug*?**

bit of both

**Bug: What is the current behavior?**

Search interface accepts input over 512 character, but the engine does not

**Bug: What is the expected behavior?**

The interface to limit the search query

The workaround for now is to use the connectSearchBox and manually trimming the input or not allowing longer input

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

no option to add, just limit the input box

**What is the version you are using? Always use the latest one before opening a bug issue.**

4.1.3

**Comment by vvo** [comment]
Can we dig also the usecase behing this request? While having a maximum on the input is good (and must be done for all the libs), I wonder how it can happen that someone got this and why it caused trouble on the UI (maybe the error was uncatched or smg?)

**Comment by Haroenv** [comment]
Originally reported in person by @67ideas, what was the usecase Jack?

**Comment by 67ideas** [comment]
Unfortunately, they don't have the original query available -- but it would have been an address search (likely copy and pasted from somewhere on the web). It only happened once.
