### ISSUE TITLE
Consider using `>=` in `engines` field of package.json

### ISSUE THREAD

**Issue by Hypnosphi** [algolia/react-instantsearch#512]
I get the following error when using `node@8.7.0` and `yarn@1.2.1`:
```
$ yarn
yarn install v1.2.1
[1/5] 🔍  Validating package.json...
error @4.1.3: The engine "node" is incompatible with this module. Expected version "8.6.0".
error @4.1.3: The engine "yarn" is incompatible with this module. Expected version "1.2.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by mthuret** [comment]
Hi @Hypnosphi, Is this happening when using `react-instantsearch`as a deps or when using the `react-instantsearch` repo? 

@marielaures, @vvo: I remember that you got an issue with yarn 1.2.1, what was it?

**Comment by Hypnosphi** [comment]
No, it happens when i clone the repo and run `yarn install`

**Comment by vvo** [comment]
@Hypnosphi Indeed for Yarn this is not so good to lock it down to 1.2.0 but 1.2.1 was buggy recently. Try with 1.2.1, do a PR changing it to ~1.2.1 (patches only, do check .travis.yml too) and let us know. Yarn is still pretty recent and we had bad experience lately.

For nodejs, nvm install and nvm use are very easy to run, allowing us to ensure that the dev env you get and the one travis runs on is the same as ours. So let's keep it strict.
