### ISSUE TITLE
Widgets: Update DOM and rename names

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#519]
Breadcrumb
- [x] Update DOM 

ClearAll
- [x] Update DOM 
- [x] Rename to ClearRefinements

CurrentRefinements
- [x] Update DOM 

HierarchicalMenu
- [x] Update DOM 
- [x] Rename `limitMin` to `limit`
- [x] Rename `limitMax` to `showMoreLimit`

Highlight
- [x] have a `ais-Highlight` class
- [x] Rename `attributeName` to `attribute`

Hits
- [x] Update DOM 
- [x] ~~Rename to Results~~

HitsPerPage
- [x] Update DOM 
- [x] ~~Rename to ResultsPerPage~~

InfiniteHits
- [x] Update DOM 
- [x] ~~Rename to InfiniteResults~~

Menu
- [x] Update DOM 
- [x] Rename `attributeName` to `attribute`
- [x] Rename `limitMin` to `limit`
- [x] Rename `limitMax` to `showMoreLimit`
- [x] Rename `withSearchBox` to `searchable`

MultiRange
- [x] Update DOM 
- [x] Rename to NumericMenu
- [x] Rename `attributeName` to `attribute`

Pagination
- [x] Update DOM 
- [x] Rename `maxPages` to `totalPages`
- [x] Rename `pagesPadding` to `padding`

RangeInput
- [x] Update DOM 
- [x] Rename `attributeName` to `attribute`

RangeSlider
- [x] If makes sense update guide (we don't package this widget) 

RefinementList
- [x] Update DOM 
- [x] Rename `attributeName` to `attribute`
- [x] Rename `limitMin` to `limit`
- [x] Rename `limitMax` to `showMoreLimit`
- [x] Rename `withSearchBox` to `searchable`

SearchBox
- [x] Update DOM 

SortBy
- [x] Update DOM 

StarRating
- [x] Update DOM 
- [x] Rename to RatingMenu
- [x] Rename `attributeName` to `attribute`

Snippet
- [x] Rename `attributeName` to `attribute`

Toggle
- [x] Update DOM 
- [x] Rename to ToggleRefinement
- [x] Rename `attributeName` to `attribute`

**Comment by samouss** [comment]
Done, will be ship with the v5.
