### ISSUE TITLE
Invalid value for "insidePolygon" parameter, expected float

### ISSUE THREAD

**Issue by alexandregiordanelli** [algolia/react-instantsearch#529]
"Invalid value for "insidePolygon" parameter, expected float"
when I do

`<Configure insidePolygon={[47.3165,4.9665,47.3424,5.0201,47.32,4.98]} />`

params on debug
`query=&page=0&highlightPreTag=%3Cais-highlight-0000000000%3E&highlightPostTag=%3C%2Fais-highlight-0000000000%3E&insidePolygon=%5B47.3165%2C4.9665%2C47.3424%2C5.0201%2C47.32%2C4.98%5D&facets=%5B%5D&tagFilters=`

**Comment by alexandregiordanelli** [comment]
@mthuret Do have an idea about why it occurs?

**Comment by Haroenv** [comment]
Hey! Thanks for this issue, could you explain what fixed your issue?
