### ISSUE TITLE
Default filtering connectInfinitHits connector in React Native

### ISSUE THREAD

**Issue by romafederico** [algolia/react-instantsearch#539]
Hi there!

I've successfuly created an infinit hit list using the connectInfinitHits connector in React Native, but I need bring only results a specific criteria. After going through the documentation, I believe this could be achieved by using a <Configure /> widget. Please see below my implementation:

```jsx
export default class App extends React.Component {

  render() {
    return (
      <View style={styles.main}>
        <InstantSearch
          appId="xxxxx"
          apiKey="xxxxxx"
          indexName="xxxxx"
        >
          <Configure search={{searchParameters: {filters: 'status: "pending"'}}}/>
          <View style={{ flexDirection: 'row' }}>
            <SearchBox/>
          </View>
          <SearchResults/>
        </InstantSearch>
      </View>
    );
  }
}
```

Consider that <SearchBox /> is a custom component using the connectSearchBox connector, and not the default widget provided by Algolia. 

What am I doing wrong?

**Comment by mthuret** [comment]
Hi @romafederico,

If I understsand correctly, you trying to filter you results to only get those with a status pending? 

If that's correct could you try this syntax instead? 

```
         
<Configure filters='status:pending'/>
```

You could also use `connectToggle` like that: 

```
const Toggle = connectToggle(() => null)
<Toggle
        attributeName="status"
        label=""
        value='pending'
        defaultRefinement={true}
/>
```

**Comment by romafederico** [comment]
Thanks @mthuret ! I can't believe how such a simple thing took so much of my time.
