### ISSUE TITLE
Multi-Index Autocomplete not working

### ISSUE THREAD

**Issue by gl0gl0** [algolia/react-instantsearch#54]
The autocomplete example that uses multiple indexes: https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/examples/autocomplete/src/App-Multi-Index.js

Is not working for me. There is an error showing up:
https://screencast.com/t/saLZ5A1k6

Any help would be very much appreciated.
Thanks!

**Comment by mthuret** [comment]
Hi @gl0gl0 

We refactored this example to simplify it a bit, it was merged yesterday: see https://github.com/algolia/react-instantsearch/pull/45

I didn't release a new beta yet, I will do today :)

**Comment by mthuret** [comment]
Should be fix with 4.0.0-beta.4

**Comment by duhaime** [comment]
@mthuret @Haroenv is this example available anywhere now? The previous link 404's.
