### ISSUE TITLE
`refine(undefined)` disables `defaultRefinement`

### ISSUE THREAD

**Issue by catamphetamine** [algolia/react-instantsearch#560]
When `refine({})` is called for a range widget it resets to `undefined` and after that `defaultRefinement` is not taking any effect.

And also `defaultRefinement={{ min: 1 }}` throws:

```js
Warning: Failed prop type: The prop `defaultRefinement.max` is marked as required in `AlgoliaRange(InstantSearchDate)`, but its value is `undefined`.
```

**Comment by samouss** [comment]
Hi @catamphetamine,

> When refine({}) is called for a range widget it resets to undefined and after that defaultRefinement is not taking any effect.

The `defaultRefinement` is used as initial value. When you call `refine` with `undefined` or an empty object it will reset the refinement to the min / max values of the range. The behaviour is the same on other widgets, when you refine without value the `defaultRefinement` is not reapply.

> And also `defaultRefinement={{ min: 1 }}` throws

You are right, we should be able to pass only one of the two property as a `defaultRefinement`.

**Comment by catamphetamine** [comment]
>  When you call refine with undefined or an empty object it will reset the refinement to the min / max values of the range. 

Is this behaviour customisable via modifying some piece of source code?
The only mention of `defaultRefinement` seems to be this:

https://github.com/algolia/react-instantsearch/blob/c85a7bf98d7d0f549e69efa637c2dc2aae49821e/packages/react-instantsearch/src/core/indexUtils.js#L181-L183

Since `defaultRefinement` isn't being reset in any way seems that after `refine()`ing to `undefined` the execution doesn't get to that `if` condition returning somewhere above.

**Comment by samouss** [comment]
You don't have to modify some piece of code. What you can do instead is to implement a custom widget with [the connector API](https://community.algolia.com/react-instantsearch/guide/Connectors.html).

You will need to the  [`connectRange`](https://community.algolia.com/react-instantsearch/connectors/connectRange.html) for this. Then in your component when the `refine` function is called with without a value you can pass the `defaultRefinement` instead.

Seems ok to you?

**Comment by catamphetamine** [comment]
Seems that I already tried that: then it would write `defaultRefinement.min` to `min` and that's not what's intended.
The intended behaviour is `min` staying `undefined` while also picking up `defaultRefinement.min` while it's `undefined`.
My disagreement with the default behaviour is that why does "Clear All" also clear `defaultRefinement`s.
I mean, I can stop it from doing so using `transformItems` but that only fixes the "Clear All" button.
It doesn't fix manually setting the range `min` value to `undefined` because after that it's stuck with `undefined` and not picking up `defaultRefinement.min`. 
Anyway, don't bother too much.
My point was just that if a user manually clears a field having `defaultRefinement` then it should not be stuck at `undefined` and should instead keep inheriting from `defaultRefinement`.

**Comment by catamphetamine** [comment]
Yeah, I guess, resetting to `undefined` is OK after all.
Ignore the comment above then.
It's just our team trying to implement advanced widgets hacking around your code.

**Comment by samouss** [comment]
Ok, fine! 😉

I'll close this issue and track the bug of the `PropTypes` in #564.

Feel free to reopen it if needed.
