### ISSUE TITLE
Bug - findResultsState return unfiltered data

### ISSUE THREAD

**Issue by kievechua** [algolia/react-instantsearch#561]
**Bug: What is the current behavior?**
The code base is mostly refering [next.js](https://github.com/zeit/next.js/tree/canary/examples/with-algolia-react-instantsearch)
~~~javascript
const searchState = { 
    hierarchicalMenu: { 
        parentA: 'childA', 
        parentB: 'childB' 
    },
    page: '1' 
}
const resultsState = await findResultsState(App, { searchState })
~~~
Return unfiltered data of 10 items in the list

**Bug: What is the expected behavior?**
Return filtered data of 4 items in the list

**Bug: What browsers are impacted? Which versions?**
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
react-instantsearch 4.1.x, 4.2.x

**Comment by kievechua** [comment]
Maybe I try to elaborate on my project will make that clearer.
What I'm building is a document upload service for internal usage.
So 1 document can consist multiple type. Example claim receipt can fall under hr & finance.
So the document object will look like this.
~~~javascript
{ // uploaded, approved, deleted, and etc
  hrDoc: 'approved',
  finDoc: 'uploaded'
}
~~~
End of day user can filter either type or both.
There're multiple Hierarchical Menu
~~~javascript
const DocFilter = connectHierarchicalMenu(({ items, refine, currentRefinement, createURL, attributes, ...rest }) => {
  return <ul>
    <li>
      {labels[attributes[0]]}
      <ul>
      {items.map((item, index) =>
        <li onTouchTap={() => { refine(item.value) }}>
          {labels[item.label]}
        </li>
      </ul>
    <li />
  </ul>
})

{[
  ['hrDoc', 'sub_category'],
  ['finDoc', 'sub_category'],
].map((attributes, index) =>
  <DocFilter key={index} attributes={attributes} />
)}
~~~
Then listen changes via `<InstantSearch onSearchStateChange={this.onSearchStateChange}>`
~~~javascript
onSearchStateChange (searchState) {
  // searchState = {
  //   hierarchicalMenu: {
  //     hrDoc: "approved",
  //     finDoc: "uploaded",
  //     devDoc: ""
  //   },
  //   page: 1
  // }
  
  const href = searchStateToUrl(searchState)
  // http://localhost:3000/?
  //    hierarchicalMenu%5BdevDoc%5D=
  //    &hierarchicalMenu%5BhrDoc%5D=approved
  //    &hierarchicalMenu%5BfinDoc%5D=uploaded
  //    &page=1
  Router.push(href, href, { shallow: true })
}
~~~
Then on SSR
~~~javascript
static async getInitialProps (params) {
  const props = {
    ...(WrappedComponent.getInitialProps ? await WrappedComponent.getInitialProps(params) : {})
  }
  
  const searchState = qs.parse(
    params.asPath.substring(params.asPath.indexOf('?') + 1)
  )
  // { 
  //   '/': '',
  //   hierarchicalMenu: { 
  //     hrDoc: 'approved', 
  //     finDoc: 'uploaded' 
  //   },
  //   page: '1' 
  // }
  
  const resultsState = await findResultsState(App, { searchState })
  // resultsState.content.hits.length === 10
}
~~~
On page 1st load it will show list of 10 items via connectHits
After client side rendering kick in, it will be replace with list of 4 items, which is the expected result.

Please let me know if I do it wrongly

**Comment by samouss** [comment]
Sorry for the misunderstanding @kievechua! Can you provide a working example of your issue? I fail to reproduce your problem.

Thanks 😉

**Comment by kievechua** [comment]
Found the issue, it's due to order of HOC.
```compose(
  baseHOC,
  ...
  algoliaHOC,
 otherHOC
)```

`const resultsState = await findResultsState(App, { searchState })`
Since the App relied on otherHOC so it break on SSR, but work fine on CSR.
