### ISSUE TITLE
Documentation for algoliaClient field

### ISSUE THREAD

**Issue by sheerun** [algolia/react-instantsearch#572]
Could you provide documentation for [algoliaClient](https://community.algolia.com/react-instantsearch/widgets/InstantSearch.html#default-props-entry-InstantSearch-algoliaClient) parameter? What methods/fields should it expose? What are shapes of parameters and responses?

**Do you want to request a *feature* or report a *bug*?**
documentation

**Feature: What is your use case for such a feature?**
Providing custom algoliaClient so I can make it return results make from combined Algolia Places results (https://community.algolia.com/places/rest.html ) and my custom dataset.

**Comment by Haroenv** [comment]
You should be able to do that without providing a separate client, by having a places index in your appID; then you can use the multi-index feature: https://community.algolia.com/react-instantsearch/guide/Multi_index.html

Regardless of that, the custom algoliaClient should have: 

* `addAlgoliaAgent`
* `search` (with an array of requests)

Implemented as like the https://github.com/algolia/algoliasearch-client-javascript

search will be called every time something changes in the state of RIS. 

Does that make sense? Feel free to ask more information!

**Comment by sheerun** [comment]
thanks for writing this :) could you document these two methods on the documentation page?

**Comment by Haroenv** [comment]
did it work for what you were planning to use it for @sheerun ?

**Comment by sheerun** [comment]
I didn't have to do it yet. Is it relevant to this issue? It's about documentation, not fixing my problem :)

**Comment by samouss** [comment]
The `algoliaClient` prop is now deprecated in favor of [`searchClient`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/#widget-param-searchclient). To know more about the signature of the prop you can take a look at [the guide dedicated to back-end search](https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/in-depth/backend-instantsearch/react/). The guide is about proxying Algolia though a backend but the same concept apply for a custom frontend only client.
