### ISSUE TITLE
Stories for Multi-index aren't wrapped in their container

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#58]
**Do you want to request a *feature* or report a *bug*?**

bug

**Bug: What is the current behavior?**

![screen shot 2017-04-25 at 15 33 04](https://cloud.githubusercontent.com/assets/6270048/25387868/818b735a-29cc-11e7-8554-ae5a0876a56a.png)

**Bug: What is the expected behavior?**

![screen shot 2017-04-25 at 15 33 04](https://cloud.githubusercontent.com/assets/6270048/25387911/9df88456-29cc-11e7-80d1-0e49dfa3907f.png)

**Bug: What browsers are impacted? Which versions?**

**Comment by mthuret** [comment]
I believe that what we want here is:

- Multi Index that have a real business use case (find the right indices)
- Style the autocomplete better 
- Maybe a new container to display the link to github (they are already mentioned in the multi index guide though).
