### ISSUE TITLE
Configure has conflict with RefinementList's defaultRefinement

### ISSUE THREAD

**Issue by springuper** [algolia/react-instantsearch#583]
**Bug: What is the current behavior?**

I use `Configure` widget and `RefinementList` together:

1. we use `RefinementList` to filter results
2. `Configure` is passed by a dynamically resolved `facetFilters` prop, so that we can search results from specific id, along with the normal filter supported by `RefinementList`
3. we have one `RefinementList`, its name is `active`, and has two values: `ture` and `false`, we make the `defaultRefinement` as `true`
4. when we want to search by specific ids, we change `Configure`'s `facetFilters` prop to `[['objectID:01234', 'objectID:56789']]`
5. nothing happens

here is a demo: https://jsfiddle.net/springuper/ob9mwvfa/11/. but it's broken by some other errors before our code.

**Bug: What is the expected behavior?**

the `Configure`'s `facetFilters` prop should take effect and retrieve correct results from server.

**Bug: What browsers are impacted? Which versions?**

Chrome: Version 61.0.3163.100 (Official Build) (64-bit) 
react-instantsearch: 4.2.0

**What is your use case for such a feature?**

we want to use normal filters and sometimes need to search specific ids:

![image](https://user-images.githubusercontent.com/687412/32493564-eec3fbb2-c383-11e7-83f0-b6a170a4251e.png)

**Comment by mthuret** [comment]
Can you try using `filters` instead of `facetFilters`? 

I believe that right now we don't merge configure given `facetFilters` with the one that are set by every widgets. 

See: https://codesandbox.io/s/6o8wzo59w

**Comment by springuper** [comment]
it works, thanks.
