### ISSUE TITLE
Server-side rendering doc improvement 

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#584]
We should indicate that: 

* findResultsState() function returns a Promise 
* InstantSearch server resultsState props expects the resolved promise from `findResultsState`.

**Comment by davidfurlong** [comment]
I think this can be closed https://community.algolia.com/react-instantsearch/server-side-renderings/findResultsState.html

**Comment by Haroenv** [comment]
Thanks! seems like this is clear enough indeed
