### ISSUE TITLE
Unused import are no more reported

### ISSUE THREAD

**Issue by mthuret** [algolia/react-instantsearch#59]
When an unused import is present, the build is not failing anymore. 

This might be related to the addition of prettier.

**Comment by Haroenv** [comment]
Probably a removal too much in algolia/eslint-confit-algolia indeed

**Comment by vvo** [comment]
Fixed, please upgrade eslint-config-algolia:

```
yarn add eslint-config-algolia # no --dev for react-instantsearch root folder
```
