### ISSUE TITLE
Different id for Search and Autocomplete connectors

### ISSUE THREAD

**Issue by skydevht** [algolia/react-instantsearch#595]
Hello, I'm on the version 4.2.0 of the library and It is been working great.
The only trouble so far is that I'm trying to do a searchbox where you can add tag (A little like facebook on the web) and then search for all documents with those tag. I'm using the connectSearchbox and connectAutocomplete HOC but as soon as I'm typing the search results are updated as well as the suggestions.
A little dive on the source show me this behaviour may be due to the two HOC sharing the same id (both are query). The react extension for chrome show that the currentRefinement props for both are updated at the same time.
So I wonder if it is possible to change one of the ID as I guess this use case is pretty common (showing suggestion then when clicked will update the search result).

**Comment by Skyd1400** [comment]
For now I will try to rewrite the autocomplete connector as I'm on a tight deadline

**Comment by Skyd1400** [comment]
Updating the id didn't work. I will add a second InstantSearch and turn it into a controlled Component

**Comment by Haroenv** [comment]
Can you show the behaviour that failed in a codeSandbox? If you’re using connectAutoComplete, I don’t see why you still need a connectSearchBox in there

**Comment by Skyd1400** [comment]
It didn't failed. It just that I want to autocomplete with an index then clicking on the suggestion will search in another index. The autocomplete connector refinement is updated with every key press and so is the search box connector. But I want the latter's refinement to be updated only when I press enter.

**Comment by Skyd1400** [comment]
It works but you have to create a custom component using searchbox connector (I didn't want the ui) and put it inside the second instant search

**Comment by samouss** [comment]
Hi, if this is still an issue please open another issue with a reproducible example. Cheers!
