### ISSUE TITLE
Algolia AutoComplete Connector missing ObjectId

### ISSUE THREAD

**Issue by anonrig** [algolia/react-instantsearch#614]
**Do you want to request a *feature* or report a *bug*?**
bug

**Bug: What is the current behavior?**
AutoComplete connector doesn't return the current refinement's object id.

**Bug: What is the expected behavior?**
It should return the object id of the refinement so that it will be used as a foreign key.

**Bug: What browsers are impacted? Which versions?**
Latest version.

**Feature: What is your use case for such a feature?**
We store postgresql id as an ObjectId in the Algolia and want to use built-in search with Semantic-ui react and want to gather objectId to store it on our side.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
Proposed API entry is: refinement should be an object that has a key: objectid as well as the text.

**What is the version you are using? Always use the latest one before opening a bug issue.**
Latest

**Comment by Haroenv** [comment]
Hey there, what exactly do you mean with a refinement that needs an objectID? The hits in autocomplete already return it normally. Could you write the diff in API you want?

**Comment by Haroenv** [comment]
please reopen this issue with more information if you still have this issue. Thanks!
