### ISSUE TITLE
With multiple indices, Configure prevents InfiniteHits to load more results on secondary indices

### ISSUE THREAD

**Issue by bgelineau** [algolia/react-instantsearch#637]
**Do you want to request a *feature* or report a *bug*?**

a bug

**Bug: What is the current behavior?**

With multiple indices, Configure prevents InfiniteHits to load more results on secondary indices. On the given fiddle, you can load more results for the main index but not for the one in an ``Index`` component :
 https://jsfiddle.net/4w04hrud/1/

The bug exists only since version 4.1.1, 4.1.0 works fine.

**Bug: What is the expected behavior?**

Be able to load more results on all indices.

**Bug: What browsers are impacted? Which versions?**

all

**What is the version you are using? Always use the latest one before opening a bug issue.**

npm@latest : 4.2.0

**Comment by Haroenv** [comment]
might be related to https://github.com/algolia/react-instantsearch/compare/v4.1.0...v4.1.1#diff-abfd06bcd49105496f748fc1cd82af3d

**Comment by samouss** [comment]
Hi @bgelineau,

We found where the issue come from, but not a proper fix yet! As a workaround you can scope the `Configure` components inside your `Index` component. You end up with something like:

```jsx
<InstantSearch indexName="bestbuy">
  <SearchBox />

  <Index indexName="bestbuy">
    <Configure hitsPerPage={5} />
    <InfiniteHits />
  </Index>

  <Index indexName="products">
    <Configure hitsPerPage={5} />
    <InfiniteHits />
  </Index>
</InstantSearch>
```
