### ISSUE TITLE
Server side rendering with provided results from Algolia response

### ISSUE THREAD

**Issue by tlenclos** [algolia/react-instantsearch#649]
**Feature: What is your use case for such a feature?**
We would like to render server side but with provided props data (ie: with React on Rails it's only possible to register components and so we can't make the initial request on the server). We also use it in a symfony app with the official Algolia PHP client.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
I tried to pass the results of the algolia response directly to the component and render this server side but without success (if I only render client side a request is still made and on the server it's trying to access the browser specific API even though we followed this setup https://community.algolia.com/react-instantsearch/guide/Server-side_rendering.html#appjs

```jsx
<InstantSearch
  resultsState={
     new SearchResults(
       new SearchParameters(),
       props.algoliaResults
     )
  }
...
```

**What is the version you are using? Always use the latest one before opening a bug issue.**
4.2.0

**Comment by Haroenv** [comment]
Can you make a project which fails? Our examples and test pass, so I'm wondering if it might be something wrong with module resolution path

**Comment by tlenclos** [comment]
Do you have an example that render the `<InstantSearch>` component server side with a custom resultsState props ? 

The problem with React on rails is that we can't render by fetching the results like you are doing in the examples with `await findResultsState` so I'm trying to render it but by passing the response I already got from the app.

**Comment by samouss** [comment]
Hi @tlenclos,

I'm not sure that I have fully understand your use case. Let me recap, you try to render your React application on the server side from the Rails backend (with [React on Rails](https://github.com/shakacode/react_on_rails)?). For that you probably need to perform the request to Algolia from the Rails backend too. Then you want to pass the results to your application. That's where `props.algoliaResults` come from.

Is it correct? As @Haroenv said if you can provide a working example it will be a lot easier to understand what is your problem and find possible solutions.

**Comment by tlenclos** [comment]
Sorry I'll try to put together an example asap

> I'm not sure that I have fully understand your use case. Let me recap, you try to render your React application on the server side from the Rails backend (with React on Rails?). For that you probably need to perform the request to Algolia from the Rails backend too. Then you want to pass the results to your application. That's where props.algoliaResults come from.

Yes, I first tried to follow the documentation with `await findResultsState` but with our current server rendering solution (react on rails) it's not possible (https://github.com/shakacode/react_on_rails/issues/948).

So the main issue is that I can't figure out the structure expected for the `resultsState` props, passing the raw algolia response is not working (crashing on various places trying to get properties that are not available).

**Comment by samouss** [comment]
Actually you can recreate the `resultsState` props but in some cases it may not work. In each InstantSearch libraries we are using the [helper](https://github.com/algolia/algoliasearch-helper-js). It's responsible for managing the state of the query and performing the requests through the [client](https://github.com/algolia/algoliasearch-client-javascript). In some widgets (ex: `RefinementList`) the helper will perform multiple queries to actually retrieve the correct number of facets count for example. So if you perform only one request on Algolia, but the App actually require two request or more the first rendering will display wrong results. When the client will be mount it will trigger the correct number of requests and the DOM will be updated with the correct results. At the end you will have a kind of flash of invisible content.

I have made a [repository](https://github.com/samouss/react-instantsearch-ssr-custom-props) for explaining the problem (see [server](https://github.com/samouss/react-instantsearch-ssr-custom-props/blob/master/src/server.js)). The example is built with Node but you can apply the same concept with any kind of backend. On the `master` branch you will find a working example with a simple query. You can switch on the `with-false-ssr`  branch you will have an example that reproduce the problem explain above. The first rendering displays the page with wrong results and when the client is mount the DOM is updated.

At the end it's not impossible to do the SSR with an other backend than Node but you will have to reproduce the same behaviour than the helper for making the requests. It's not an easy task and it will be very error prone.

**Comment by samouss** [comment]
I'm closing this one since it's inactive, feel free to re-open an issue.
