### ISSUE TITLE
Spread the hit props on HitComponent

### ISSUE THREAD

**Issue by samouss** [algolia/react-instantsearch#658]
In the `Hits` component we actually pass the `hit` as props to the `HitComponent`. We use it like this:

```jsx
const HitComponent = ({ hit }) => <div>{hit.name}</div>;
```

Would be easier to spread the props on the `HitComponent`. We remove the unnecessary nested `hit` property on the props. Then we could use the component like this:

```jsx
const HitComponent = ({ name }) => <div>{name}</div>;
```

> see https://github.com/algolia/react-instantsearch/pull/654#discussion_r153152236

**Comment by Haroenv** [comment]
This should also break `<Highlight />` and `<Snippet />`, but I think it would make sense to pass the `_highlightResult`, `_snippetResult` instead of `hit` to those. What do you think, maybe those can be renamed?

**Comment by samouss** [comment]
Agree!  Instead of passing the `hit` + `highlightProperty`, you could directly pass the result of the computation `hit[highlightProperty]` as props.

**Comment by Haroenv** [comment]
yep, good idea to pass `_highlightResult[attribute]`, since that's simple to understand, rather than arbitrarily passing the complete hit. I suspect it might even be slightly more efficient since not every change needs to be tracked, but not sure

**Comment by Haroenv** [comment]
closing makes sense for now, we likely won't change it, and it's not necessarily worth the transition in a breaking change
