### ISSUE TITLE
Remove lodash

### ISSUE THREAD

**Issue by jaredpalmer** [algolia/react-instantsearch#663]
There are a handful (like 4) lodash methods in the repo that could just be replaced and save on bundle size.

**Comment by Haroenv** [comment]
There are a lot more used in the internal helper (almost all of them). This is a huge chore unfortunately, combined with the fact that we often use them there to iterate over objects. I totally agree with you, but it’s a titan’s job

**Comment by samouss** [comment]
Agree, but we can still remove it from React InstantSearch. It will be ready when the helper will do its own migration.

**Comment by Haroenv** [comment]
This has been fixed in v6 actually
