### ISSUE TITLE
ais-RefinementList__itemBox is listed twice

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#700]
The classes `ais-RefinementList__itemBox` and `ais-RefinementList__itemLabel` are applied twice in the DOM of a RefinementList

**Comment by vvo** [comment]
Can you detail this issue a bit more? Not sure we have the required context to know what to fix. If you know what to fix, where please go ahead or show us

**Comment by Haroenv** [comment]
Not sure what to fix, just saw that the class name was twice in my dom

**Comment by vvo** [comment]
Maybe provide a reproducible example or some DOM output copy/paste

**Comment by samouss** [comment]
It will be fix with IntantSearch.css I guess. Maybe we can wait for the release?

**Comment by Haroenv** [comment]
This happens with every refinementList, an example is this one: https://codesandbox.io/s/oY1klpZYB

<img width="693" alt="screen shot 2017-12-18 at 11 26 30" src="https://user-images.githubusercontent.com/6270048/34101559-6057f88c-e3e6-11e7-8178-d36d00724d69.png">
<img width="247" alt="screen shot 2017-12-18 at 11 26 35" src="https://user-images.githubusercontent.com/6270048/34101560-606f3ef2-e3e6-11e7-90f3-eafa3220374f.png">

**Comment by vvo** [comment]
Thanks, much clearer!

**Comment by samouss** [comment]
I'll close this issue, since in the next version we drop the support for the theme. We are now rely on a new library called [InstantSearch.css](https://yarnpkg.com/en/package/instantsearch.css) and the CSS naming has changed, so this issue will be fixed.
