### ISSUE TITLE
Question for connectSearchBox!

### ISSUE THREAD

**Issue by romafederico** [algolia/react-instantsearch#709]
Is there a way in which I can pass extra refinements? Let's say I have a select element populated with tyre sizes... can I take the selected option and pass it as a string to be searched in one of the properties of the result in connectHits?

**Comment by Haroenv** [comment]
I'm not sure what you mean, do you mean something like [withSearchBox](https://community.algolia.com/react-instantsearch/widgets/RefinementList.html#default-props-entry-RefinementList-withSearchBox) on RefinementList? Could you make a small sketch of the wanted behaviour?

**Comment by romafederico** [comment]
Hi! ... sorry for the delay in responding. Here goes a more detailed explanation of what I need. Have in mind that we're selling car tyres on our site. I've got the following

- A connectedSearchBox and connectedHits
- A MenuSelect Widget that takes all the clients names and builds a filter

          <div className="order-container">
            <div class="row">
              <div class="col-md-11">
                <ConnectedSearchBox/>
                <label>Clients: <MenuSelect attributeName="client_user.client.title" /></label>
              </div>
              <div class="col-sm-1 clear">
                <ClearAll/>
              </div>
            </div>
            <CurrentRefinements/>

            <table class="received-line-items table table-hover table-outline mb-0 hidden-sm-down">
              <thead class="thead-default">
              <tr>
                <div class="table-head" style="width:8%">Created</div>
                <div class="table-head" style="width:12%">Order Number</div>
                <div class="table-head" style="width:4%">Status</div>
                <div class="table-head" style="width:12%">Client</div>
                <div class="table-head" style="width:12%">Client User</div>
                <div class="table-head" style="width:12%">Billing Profile</div>
                <div class="table-head" style="width:12%">Shipping Profile</div>
                <div class="table-head" style="width:12%">Customer Notes</div>
                <div class="table-head" style="width:12%"></div>
              </tr>
              </thead>
              <CustomHits hitComponent={CustomHits}/>
            </table>
            <Pagination/>
          </div>

I wanted to create two more MenuSelect Widgets that would take tyre sizes to filter by size ... and by order date. Since the amount of tyre sizes and dates is too big, the widget simply doesn't render.

So I was wondering if I could create a custom select element, convert the option selected into a string, and pass that string SOMEHOW into refinements so I can filter the connectedHits.

Kind of like the same beahavior than a search box but using a select element and looking into specific attributes of my results object.

**Comment by samouss** [comment]
Hi @romafederico, first of all sorry about the delay. I messed up with my notifications and I forgot the issue. Did you solve your issue at the end?

**Comment by samouss** [comment]
I'm closing this one since it's inactive, feel free to re-open an issue.
