### ISSUE TITLE
Building @mentions with createConnector

### ISSUE THREAD

**Issue by THook** [algolia/react-instantsearch#71]
Hi all,

I'm trying to build an @mention into a textarea, using antd Mention component. But it seems that new props aren't communicated properly to the connected component.

I created a small Fiddle to show the issue : https://jsfiddle.net/8r928c4y/16/

If it is a misuse rather than a bug, feel free to close the ticket of course ;)

**Bug: What is the current behavior?**
I believe new props are not communicated to child component. If the Fiddle, you can see that `getProvidedProps` is called on state change and returns hits as it should.

**Bug: What is the expected behavior?**
To retrieve matching hits from the Mention component

**Bug: What browsers are impacted? Which versions?**
Chrome v 49 at least

Thanks!

**Comment by Haroenv** [comment]
Hey, this seems like a great use case!

However, the jsfiddle you shared doesn't use react-instantsearch as far as I can see. Can you show what you've tried? A `createConnector` should be able to help here, where you connect to both the query and the hits. 

Thanks for trying this!

**Comment by THook** [comment]
Ahah, it seems like I forgot to save it.. Meh. Will rewrite something when I'm at work, sorry for the inconvenience!

**Comment by THook** [comment]
There you go! I just forgot to save the draft! ;)

So, as you can see : `getProvidedProps` gets new hits from the `onSearchChange` Mention callback, and returns hits. But new props aren't communicated, at least the way I thought they would!

**Comment by THook** [comment]
Oh ok, I changed the call on line 49 and it's all working fine now. Just had to explicitly bind props.hits to the hit formatting. React behavior misunderstanding I guess?

I'm updating and cleaning the Fiddle, feel free to share if it's needed, it's the least I can do ;)

**Comment by Haroenv** [comment]
That's amazing, we will definitely make a guide for this. If you want and are as ⚡️ fast as you are on this issue, feel free to make a PR. Either in /examples or as a guide!

**Comment by THook** [comment]
Sure! I'll push something in the evening

**Comment by mthuret** [comment]
@THook if you need to access hits, query and refine depending of an entry, then you can try the `connectAutoComplete` connector. It's available with the v4.0.0-beta.

**Comment by THook** [comment]
Quick heads up : I came back to the fiddle in order to make a PR but it doesn't work as expected anymore. It seems like the query state is never updated. See logs of https://jsfiddle.net/8r928c4y/17/ . It happens both in my app and in the Fiddle

**Comment by mthuret** [comment]
Hi @THook, can you give me a heads up about what you're expecting when typing something in the mention textarea? I'm a bit lost with your functional use case.

**Comment by THook** [comment]
Hello @mthuret , I am expecting the dropdown values to match my query, exactly like Github mentions work. Typing "@a" and "@z" doesn't update anymore the dropdown suggestions accordingly. When you log the connector state, you can see that the query doesn't get updated on search change, at least on my chrome version

Hope it helps!

**Comment by Haroenv** [comment]
I made it work with `connectAutocomplete` (after #75 is merged) @THook. 

![2017-04-30 18_00_27](https://cloud.githubusercontent.com/assets/6270048/25565809/f212f7fa-2dce-11e7-8e97-ff50a5631fba.gif)


Here’s the code for an app with the Mention component, to be made in a guide when #75 is merged.

```js
import React from 'react';
import { Mention } from 'antd';
import 'antd/dist/antd.css';
import { InstantSearch } from 'react-instantsearch/dom';
import { connectAutoComplete } from 'react-instantsearch/connectors';

const _formatHitsForAutoSuggest = hits => hits.map((value, key) => value.name);

const AsyncMention = ({ hits, refine, currentRefinement }) => (
  <Mention
    style={{ width: 500, height: 100 }}
    prefix="#"
    notFoundContent={'No suggestion'}
    placeholder="tag something here"
    suggestions={_formatHitsForAutoSuggest(hits)}
    onSearchChange={value => refine(value)}
  />
);

const ConnectedAsyncMention = connectAutoComplete(AsyncMention);

const App = () => (
  <InstantSearch
    appId="latency"
    apiKey="3d9875e51fbd20c7754e65422f7ce5e1"
    indexName="bestbuy"
  >
    <ConnectedAsyncMention />
  </InstantSearch>
);

export default App;
```

**Comment by mthuret** [comment]
Hey @THook, we just released a new beta with the `connectAutoComplete` fix. Here's a jsfiddle https://jsfiddle.net/q3t2mLvb/ to illustrate how it works.

**Comment by mthuret** [comment]
We added this example as a possible usage of the `connectAutoComplete` connector (see: https://github.com/algolia/react-instantsearch/pull/76).

**Comment by bwanlin** [comment]
How would you add multi-index search in this mention component? thanks !

**Comment by mthuret** [comment]
@bwanlin: what is the desired output? 

The `hits` forwarded props of the `connectAutoComplete` has the following form `[{index1: hits, index2: hits, ...}]` when used with `Index`. See [this example](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/examples/autocomplete/src/App-Multi-Index.js) to have an idea.
