### ISSUE TITLE
Different Configure across multi-index (beta)

### ISSUE THREAD

**Issue by davidfurlong** [algolia/react-instantsearch#73]
**Do you want to request a *feature* or report a *bug*?**

Feature (question): I would like to disable Geo-search filtering for records which don't have coordinates. This seems to be currently impossible in the settings, so it seems I could do this by splitting the non-coordinate records into a separate index & then using multi-index. However I am wondering whether this will work using the multi-index feature in react-instantsearch@beta. 

Essentially I would put `<Configure aroundRadius="5000" minimumAroundRadius="2500" aroundLatLng={aroundLatLng} />` inside the `<Index>` component and would it only apply to that index? (Its not clear from docs that this will work)

Its also not clear whether I can use multiple `<Index/>` HOC's with the same indexName (because of the way my component tree is structured

**Comment by mthuret** [comment]
Yes, when using an <Index> component under an <InstantSearch> root component you can declare widgets that will target a precise index.
Using Configure, It's what we do for our stories with <Index/>, see: https://github.com/algolia/react-instantsearch/blob/master/stories/MultiIndex.stories.js

Also, I'm not sure to see why you would use several <Index> with the same indexName, but this should work. Every widgets under an <Index indexName="indexA"/> will be applied for this index only. Let me know how it goes.

**Comment by davidfurlong** [comment]
I can't Configure aroundLatLng to be null (which the docs https://www.algolia.com/doc/api-client/javascript/parameters/aroundLatLng/ says it has as a default value) after setting it somewhere else. 

```
{"message":"Invalid value for \"aroundLatLng\" parameter, expected two integers like \"aroundLatLng=47.316669,5.016670\"","status":400}
```
Form Data:

aroundLatLng:null

**Comment by Haroenv** [comment]
I think the `null` referenced there is when it’s not set at all. Can you try setting `Configure` without the prop at all vs setting it to `null`

If that’s the case, then #10 is the same.

**Comment by davidfurlong** [comment]
I think not setting the prop as a means of removing it would be a terrible design decision.

**Comment by Haroenv** [comment]
There’s no need to be rude here. I am trying to help figure out what the cause of the bug is, so that it can be fixed.

**Comment by davidfurlong** [comment]
What I'm saying is I'm not going to test doing that because I think its really unlikely

**Comment by davidfurlong** [comment]
and I'm not being rude

**Comment by mthuret** [comment]
Okay I'll write your example done here @davidfurlong as it more related to this issue than the other one. (the other one is about not having Configure removing explicit `null` value from their own props). 

```js
<InstantSearch>
  <Configure someThing={3} aroundLatLng="1,2" />
  <Index indexName="a">
     <Configure someThingElse={5} />
  </Index>
  <Index indexName="b">
</InstantSearch>
````
If you write something like that, it means that `arountLatLng` will be applied for a and b. Same for `someThing`. `someThingElse` on the other hand will only be applied for a. 

If I understand correctly, you said that the absence of `arountLatLng` under a and b, override its behaviour? If that's the case, this is an issue.

**Comment by davidfurlong** [comment]
Thanks @mthuret yes that example belongs here instead.

I said that I was trying to remove the aroundLatLng option in `indexName` `a` by doing `aroundLatLng={null}` (as the docs state that this is the default value for the `aroundLatLng` search state. However my requests are then failed because null is not an acceptable value. Thus it was suggested by @Haroenv that I should remove the setting of `aroundLatLng` from inside the nested Configure, and that that would perhaps remove the `aroundLatLng` configuration from that index. I didn't try that because I can't imagine you designing it like that. 

I have shifted my `aroundLatLng` from the outer `Configure` to the inner one, but it still remains that there seems to be no way to unset the value of `aroundLatLng` once configured for a particular index.

**Comment by mthuret** [comment]
Apparently, `aroundLatLng` doesn't accept null as a value (even though, it's mentioned that its default value is null. I'll check this point with the API team on tuesday, to clarify).

Then right now, to me the usage of this search parameters behave like: either you use it with values and it's applied, or you don't pass anything if you don't want this to apply. But this is more an API question than a Configure one per se. The `Configure` widget is just a way to apply `search parameters` to your request, so it will accept any values that the API can accept. If the way to not apply a search parameter is to not pass any values, then it means that this property should be removed from the `Configure` props. 

If you want to only apply `aroundLatLng` to the index a for instance, then you should declare it under `<Index indexName="a"/>`: 

```js
<InstantSearch>
  <Configure someThing={3} />
  <Index indexName="a">
     <Configure someThingElse={5}  aroundLatLng="1,2" />
  </Index>
  <Index indexName="b">
</InstantSearch>
```

And if at some point you now that this parameter isn't needed anymore for index "a", then you should write something like that:

```js
<InstantSearch>
  <Configure someThing={3} />
  <Index indexName="a">
     <Configure someThingElse={5} />
  </Index>
  <Index indexName="b">
</InstantSearch>
```

Is this what you try and that didn't work?

**Comment by davidfurlong** [comment]
yep so this seems to be more of an API issue with setting `aroundLatLng` to be `null`.
I can do as you suggested & have done and its no longer responding with an error about aroundLatLng being null.

**Comment by davidfurlong** [comment]
I suspect having looked at the internal searchState in context that setting `aroundLatLng={undefined}` will have the desired effect (although this is not a great practice)

**Comment by Haroenv** [comment]
Setting undefined is [equivalent](http://stackoverflow.com/a/32233058/3185307) to not setting a prop in React, so this makes sense. Null and false will propagate down, while undefined acts as if it doesn’t exist.

I think this question has been solved now? 

Have a nice day!
