### ISSUE TITLE
SearchBox reset clears input value, but doesn't reset Algolia query or trigger search

### ISSUE THREAD

**Issue by kblizeck** [algolia/react-instantsearch#799]
Video of what's happening :: http://recordit.co/VMNlEnkZsr

**Bug: What is the current behavior?**
Using the `SearchBox` widget, the reset button just clears the SearchBox input value, it doesn't trigger a search/clear the search.

I entered the term "Morgan" and click the submit button, one result shows in the sidebar. I hit the clear/reset button, the value is cleared but the one result remains in the sidebar - the previous list of all results doesn't appear.

**Bug: What is the expected behavior?**
Clicking the reset button will clear the current Algolia results.

**Comment by samouss** [comment]
Hi @kblizeck,

Thanks for reporting this, could you confirm that your have disabled the `searchAsYouType` prop? 

The problem seems to come from there.

**Comment by kblizeck** [comment]
Hi @samouss - correct, I do have `searchAsYouType={false}`

**Comment by kblizeck** [comment]
Hi @samouss! I did a `yarn upgrade --latest react-instantsearch` and I still am not seeing your change from #802. Is there something else I need to do to get this fix?

**Comment by Haroenv** [comment]
We didn't release it yet, if you want to have it before we release it, you'll have to download the repository and `yarn link` it @kblizeck

**Comment by kblizeck** [comment]
Oh duh @Haroenv - when is the release planned for?

**Comment by samouss** [comment]
@kblizeck I will release the patch version tomorrow.
