### ISSUE TITLE
Make 4.0.0 available via npm

### ISSUE THREAD

**Issue by flouc001** [algolia/react-instantsearch#80]
**Bug: What is the current behavior?**
Currently npm installs version 3.3.1 which doesn't include some vital bug fixes such as the critical bug addressed in commit a31fb4b7b

**Bug: What is the expected behavior?**
npm should install v4.0.0-beta5 and if users require v3.3.1 they should specify that in their package.json file.

**Bug: What browsers are impacted? Which versions?**
All applications using non-specific versions will be affected however those using non-specific versioning are usually able to adapt quickly and require the latest bug fixes.

I could really use the latest beta on npm. If not it means I have to bring react-instantsearch outside of the npm versioning system which I am very reluctant to do.

Thanks for your work so far, so much time has been saved with the react implementation 👍

**Comment by mthuret** [comment]
You can use the tag "beta" if you want to use right away our v4.0.0 betas :)

The release version of the v4 should be available soon (beginning of next week at the latest). 

Also, I might release a 3.3.2 containing only this fix.

**Comment by flouc001** [comment]
I completely forgot about tags! Thanks I'll use the beta tag for now and then hope back into production builds when 4.0.0 goes live. I do think a31fb4b would benefit everyone using this repo.

**Comment by mthuret** [comment]
3.3.2 has this fix now.

**Comment by flouc001** [comment]
Thank you :+1:
