### ISSUE TITLE
onSearchStateChange resolves in infinite loop

### ISSUE THREAD

**Issue by chrisdrohr** [algolia/react-instantsearch#860]
I've been stuck on this issue for about 6 hours. Is there something not in the docs that i'm missing??
```

   onSearchStateChange = searchState => {
            clearTimeout(this.debouncedSetState);
            this.debouncedSetState = setTimeout(() => {
                window.history.pushState(
                    searchState,
                    null,
                    searchStateToUrl(searchState)
                );
            }, 1000);
            this.setState({ searchState });
        };
```

**Comment by Haroenv** [comment]
Can you make this into a complete fiddle or code sandbox please?

**Comment by chrisdrohr** [comment]
After working on a sandbox demo for awhile i realize there's a lot i'll have to add and change to get it working.
I have based my code off of the Material UI Demo from Algolia: 
[https://github.com/algolia/react-instantsearch/blob/master/docgen/src/examples/material-ui/App.js](url)

Should this example still be working with the updated React Router? just wanted to check that first so i can be sure im on the right track. Thanks
