### ISSUE TITLE
NumericMenu items ignore the value "0" in their bounds

### ISSUE THREAD

**Issue by bgelineau** [algolia/react-instantsearch#867]
**Do you want to request a *feature* or report a *bug*?**

a bug

**Bug: What is the current behavior?**

MultiRange items ignore the value 0 in their bounds. In the following fiddle, we would expect the "Free" option to return nothing and not every item: https://jsfiddle.net/ar80rgpc/33/ This also impacts ranges with negative values as start:0 will return items with negative values.

**Bug: What is the expected behavior?**

To handle the 0 value differently than a missing value.

**Bug: What browsers are impacted? Which versions?**

all

**What is the version you are using? Always use the latest one before opening a bug issue.**

react-instantsearch@4.4.1

**Comment by levic92** [comment]
I am experiencing a similar issue in my connected range slider component. When I have a min value of 0 and try to refine the max value it won't actually filter correctly, but if min is set to anything but 0 it will work. This even occurs when setting a default refinement, if the min is 0 it won't actually work (but if min is set to 1 it filters correctly).

**Comment by Haroenv** [comment]
This is still reproducible with NumericMenu; the replacement of MultiRanges: https://codesandbox.io/s/9oxqnnrkno

**Comment by jhalborg** [comment]
Ran into this bug recently, and would very much appreciate a fix!

**Comment by jhalborg** [comment]
Ran into this bug recently, and would very much appreciate a fix! 

(PS: Was encouraged to comment here [overhere](https://discourse.algolia.com/t/numericmenu-start-0-end-0-doesnt-work-for-me/9095/12?u=jm1) )
