### ISSUE TITLE
IE 11 doesn't support String.startsWith()

### ISSUE THREAD

**Issue by denkristoffer** [algolia/react-instantsearch#869]
`react-instantsearch` 4.4.1 breaks in IE 11 because of the use of [`startsWith()` in `createConnector`](https://github.com/algolia/react-instantsearch/blob/9c5106de70fb08de851e3aaca0ab7ce20d5eac04/packages/react-instantsearch/src/core/createConnector.js#L97) — I'm unsure if this is on purpose or not, since I can't find a list of supported browsers. Are users expected to polyfill this themselves or should it be a part of the library?

**Comment by Haroenv** [comment]
This wasn't done on purpose (sorry for that). The library should support IE11 normally, although maybe not explicitly. You can either load the (pretty small) polyfill, or open a PR to use

```js
connectorDesc.displayName.substr(0, 7) !== 'Algolia'
```

instead

**Comment by denkristoffer** [comment]
Cool, no worries, I just wanted to make sure before opening a PR 👍  Done!
