### ISSUE TITLE
React-native Range Slider widget disables other widgets when in use

### ISSUE THREAD

**Issue by rtman** [algolia/react-instantsearch#879]
Hi,

I'm working on a Range Slider widget for use with defining price ranges, it's not done yet but when I put it into my overall search screen it seems to disable all my other widgets, like: hits, refinementList, hierarchicalMenu. They work properly when this new component is removed but when it's in they don't show any information anymore when brought up, except for the refinementList for 'price', that still shows properly. Any thoughts on why?

Here is my Range Slider widget so far:

```
export const DrawerRangeMultiSlider = connectRange(({refine, createURL, currentRefinement, min, max}) => {
  return(
    <RangeMultiSlider refine={refine} currentRefinement={currentRefinement} min={min} max={max}/>
  )
})

export class RangeMultiSlider extends React.Component{
  constructor(props){
    super(props);
  }

  onChangeValues = (sliderState) => {
    //console.log('sliderState', sliderState);
    if (this.props.currentRefinement.min !== sliderState[0] || this.props.currentRefinement.max !== sliderState[1]) {
      this.props.refine({min: sliderState[0], max: sliderState[1]});
    }
  };  

  render(){
    return(
      <View style={{alignItems: 'center', justifyContent: 'center'}}>
        <MultiSlider
          sliderLength={150}
          onValuesChange={(sliderState) => this.onChangeValues(sliderState)}
          min={this.props.min}
          max={this.props.max}
          values={[this.props.currentRefinement.min, this.props.currentRefinement.max]}
          step={1}/>
      </View>
    )
  }
}
```

And I'm calling it like this:

```
                            <DrawerRangeMultiSlider
                                min={1}
                                max={200}
                                attributeName={'price'}
                                precision={2}/>
```

**Comment by samouss** [comment]
For the `connectRange` connector [there is one requirement](https://community.algolia.com/react-instantsearch/connectors/connectRange.html#requirements): the value in your records for the `attributeName` that you passed must be holding numerical values. So in your case, be sure that the `price` attribute contains numeric values.

**Comment by rtman** [comment]
I'm noticing that my prices are input as strings, they're still numbers however. Is this a problem?

**Comment by samouss** [comment]
Yes in order to make the widget working, the attribute must be a `number' not `string`.

**Comment by rtman** [comment]
Thanks, just confirmed that!
