### ISSUE TITLE
Deploy examples live

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#88]
**Do you want to request a *feature* or report a *bug*?**

Feature 

**Feature: What is your use case for such a feature?**

You can see easily how an example looks

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

Adding either a deploy.now.sh button, deploying them in CI or making sure netlify deploys this too

**What is the version you are using? Always use the latest one before opening a bug issue.**

4.0.0-beta.6

**Comment by Haroenv** [comment]
It would be nice if they were deployed just like the “big” examples are.

**Comment by vvo** [comment]
I think you meant recipes?

**Comment by Haroenv** [comment]
Yep, see also https://github.com/zpnk/deploy.now/issues/17#issuecomment-306295664

**Comment by vvo** [comment]
I am unsure we want to use zeit/now, only because we already have GitHub pages, netlify so adding a third deploy provider: unsure.

What we could do is deploy those recipes just as how examples are deployed: by adding them to our webpack/flow.

**Comment by Haroenv** [comment]
You can run each example in code sandbox, e.g. https://github.com/algolia/react-instantsearch/tree/master/examples/react-router becomes https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/react-router
