### ISSUE TITLE
Can't have two Toggles on same attribute with different refinement values

### ISSUE THREAD

**Issue by vvo** [algolia/react-instantsearch#885]
**Do you want to request a *feature* or report a *bug*?**

A bug, here's the test case: https://codesandbox.io/s/8k163npw42 and the linked community ticket: https://discourse.algolia.com/t/yes-no-filter-using-react-widgets/4164/4

![2018-01-22 15 01 52](https://user-images.githubusercontent.com/123822/35224428-429edcf6-ff85-11e7-91a6-c7fcf7229cc9.gif)

**Bug: What is the current behavior?**

When using a Toggle like this:

```jsx
      <div className="filter">
        <Toggle attributeName="smoker" label="Yes" value={1} />
        <Toggle attributeName="smoker" label="No" value={0} />
      </div>
```

It will send both refinement values when clicking any Toggle:

![image](https://user-images.githubusercontent.com/123822/35217834-eb39a2a6-ff6c-11e7-9f5d-98f59c5c7bb7.png)

**Bug: What is the expected behavior?**

Only one refinement value must be sent.

**Bug: What browsers are impacted? Which versions?**

All

**What is the version you are using? Always use the latest one before opening a bug issue.**

4.4.1

This is also very linked to our recent discussions about adding the offValue feasibility to Toggle. Then with a connectToggle we could solve this issue. But even that, this usage is valid and should work I believe?

**Comment by Haroenv** [comment]
🤔 both are toggled on though, what would you expect here?

**Comment by vvo** [comment]
They are toggled on by the library itself, when you click a single checkbox, it toggles both, here's a GIF that does a better job at explaining what's happening:

![2018-01-22 15 01 52](https://user-images.githubusercontent.com/123822/35224406-3501ceb4-ff85-11e7-9d9e-504760a3a303.gif)

**Comment by samouss** [comment]
With the current implementation it's the attended behaviour. Since we only store the attribute name with the current refinement (`true|false`) inside the `searchState`, both checkbox will always be in sync.

```js
// searchState of the above app
const searchState = {
  toggle: {
    smoker: true // when it's checked, false otherwise
  }
}
```

**Comment by ivark16** [comment]
I'm currently having the same issues with toggleRefinement. Feel like it makes sense to be able to toggle the same attribute with different values. @vvo where you able to solve this problem?

**Comment by Haroenv** [comment]
In most case this would work best as a single refinement list. You can either use facet ordering to force the order of the values to be only 0 and 1, or use transformItems like this: https://codesandbox.io/s/react-instantsearch-codesandbox-simple-highlighting-forked-htlve?file=/index.js @ivark16

**Comment by ivark16** [comment]
Thanks for the reply @Haroenv, yes ended up with a similar solution but with Menu since that was better suited for our requirements.

**Comment by Haroenv** [comment]
Thanks for confirming. I'll close this issue as a refinement on a single attribute with multiple values is better solved using a menu/refinementList than multiple toggles.
