### ISSUE TITLE
Access all items properties from transformItems

### ISSUE THREAD

**Issue by adrien-gueret** [algolia/react-instantsearch#89]
**Do you want to request a *feature* or report a *bug*?**
Submit a feature.

**Feature: What is your use case for such a feature?**
I use the `<Menu />` component in order to filter my items according to some tags. Tags have this format:

```json
{
      "id": 3,
      "name": "Développement",
      "position": 1
}
```

And the component is used like this:

```jsx
<Menu
    attributeName="tags.name"
    transformItems={ transformItems }
/>
```

The `<Menu />` component has a prop `transformItems` : I use it in order to sort the menu items according to tag name:

```js
function transformItems(items) {
    return items.sort((a, b) => a.label.localeCompare(b.label));
}
```

The `items` parameter received by this function is NOT an array containing my tags, but an array filled with another shape of objects (that's why I need to compare the `label` property and not the `name` one).

It's fine if I want to order by tags names, but what if I want to order by the `position` property?
The goal is to highlight some menu items, but not according to number of results, just arbitrarily (that's why we have a `position` property in our tags).

The issue here is that the `transformItems` function doesn't receive the original tag. I'm quite sure it's by design, but it could be great if we could access other properties, instead just the one sent via `attributeName`.

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**
It would be awesome if we can access the whole object properties from the `transformItems` function. Maybe as second parameters ? Or inside a subproperty ?

Or maybe I've missed something and I don't use the right options to do what I need to achieve: if it's the case, sorry for that!

**What is the version you are using? Always use the latest one before opening a bug issue.**
I use the version 3.3.2.

Thanks in advance!

**Comment by mthuret** [comment]
I'm closing this as for now having facet metadata is not supported by the API. 

Currently the way to solve this is either to have a static list elsewhere, or to concatenate all the metadata with the label and split those inside `transformItems`. 

I'll reopen this later if any change.
