### ISSUE TITLE
I have enabled urlSync to true, but still I am not able to do refinement List based on query string

### ISSUE THREAD

**Issue by ankitachetu** [algolia/react-instantsearch#895]
I have **enabled urlSync to true**, but the refine list that I am passing in the _query string is not able to refine the selected options_.
Below I am forwarding an example : **shop/desk-sets?refinementList%5Bcolor%5D%5B0%5D=black**
the link is not selecting the color back in my refinement list.
We are using _react-instantsearch library_ for the same, please guide us to select on basis of URL or **can we reverse the process so as to get the URL based on the selection of color in URL bar** so that we can get to know what URL is formed based on selection of the refinement list.

Your quick response will be highly appreciated. Thanks!

**Comment by Haroenv** [comment]
Hey @ankitachetu, did you mean to open this issue for InstantSearch.js (and not React InstantSearch)? React InstantSearch doesn't have a `urlSync` option.

**Comment by ankitachetu** [comment]
Hey @Haroenv we are using React-InstantSearch package, can you help us the same to perform in this package..? Thanks

**Comment by Haroenv** [comment]
Can you make a [Sandbox using this template](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/React%20InstantSearch) please? 

All documentation regarding synchronising should be available here: 

* https://community.algolia.com/react-instantsearch/guide/Routing.html

See also a possible API to simplify this (not yet implemented): #271

**Comment by samouss** [comment]
Hi @ankitachetu, does it solve your issue?

**Comment by samouss** [comment]
I'm closing this issue since it's inactive since a couple of time. Feel free to open another issue if you still have a problem.
