### ISSUE TITLE
Allow using of the Places dataset

### ISSUE THREAD

**Issue by Haroenv** [algolia/react-instantsearch#90]
**Do you want to request a *feature* or report a *bug*?**

feature

**Feature: What is your use case for such a feature?**

You can easily use the Places index

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

adding a `placesApiKey` prop  to `<InstantSearch />` will allow you to use an `<Index>` with the places index.

In is.js places is handled as a separate widget, but then it has the dropdown etc. too, I think that's a different issue.

cc @raphi

**Comment by raphi** [comment]
👍

**Comment by mthuret** [comment]
@Haroenv @raphi I'm not sure we want to allow the browsing inside the Places dataset directly from RIS but rather propose a widget for RIS inside places. 

Indeed it was an issue that already existed there: https://github.com/algolia/instantsearch.js/issues/1773. I didn't recreated it as it was not a high priority (=> we would rather have first a solid geo loc example using google). Of course this can be discuss :)

**Comment by oyeanuj** [comment]
@Haroenv @mthuret What is the best way to use 'Places` with react-instantsearch? I already have a search experience set up with this library - can I reuse it in any way for Places?

**Comment by Haroenv** [comment]
@oyeanuj, what are you going to use the dataset for (to figure out what will be the best method for now)? 

I think the best fallback might be to use the `algoliasearch` client library for the places things manually, since it uses different methods than the regular search methods

**Comment by Haroenv** [comment]
see also https://github.com/kontrollanten/algolia-places-react

**Comment by mthuret** [comment]
Hi @oyeanuj, eventually we want to integrate a places autocomplete widget directly on our InstantSearch library but for now, you'll need to follow the strategies @Haroenv mentioned :)

**Comment by oyeanuj** [comment]
@Haroenv @mthuret Thank you for the links. My use-case is for users to add their cities, so using an autocomplete just for that.

I think I might stick with `react-geosuggest` for now but it would be cool if eventually `Places` could be used with `InstantSearch` with all of the customizability and reuse that it offers!
