### ISSUE TITLE
Clear the SearchBox trigger two queries

### ISSUE THREAD

**Issue by samouss** [algolia/react-instantsearch#926]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Bug: What is the current behavior?**

When the SearchBox has a `defaultRefinement` if you click on the clear button it triggers two queries instead of one. You can reproduce it in [Storybook](https://community.algolia.com/react-instantsearch/storybook/?selectedKind=SearchBox&selectedStory=with%20a%20default%20query&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs).

**Bug: What is the expected behavior?**

Trigger only one query

**Bug: What browsers are impacted? Which versions?**

All

**What is the version you are using? Always use the latest one before opening a bug issue.**

4.4.2

**Comment by Haroenv** [comment]
Yep, I confirm that this is happening. We should really memoise a bit harder at some level
