### ISSUE TITLE
connectHierarchicalMenu is giving an item with all keys undefined instead of the expected refined item which also has sub items.

### ISSUE THREAD

**Issue by davidfurlong** [algolia/react-instantsearch#938]
**Do you want to request a *feature* or report a *bug*?**

**Bug**

**Bug: What is the current behavior?**

The currently refined item has all keys being undefined

**Bug: What is the expected behavior?**

It should have normal keys and then an array of items

**Bug: What browsers are impacted? Which versions?**

All

**What is the version you are using? Always use the latest one before opening a bug issue.**

4.4.2

Attached is a log of the store state results relevant parts (I think) ~ Left is working, right is broken. The left version is also using an earlier version of react-instantsearch (4.2 vs 4.4.2). 
![screen shot 2018-02-02 at 12 52 11](https://user-images.githubusercontent.com/614768/35732018-24760114-0818-11e8-94df-6c91fb048b72.png)

Props of HierarchicalMenu after connected
![screen shot 2018-02-02 at 11 46 51](https://user-images.githubusercontent.com/614768/35732062-5b0c6600-0818-11e8-9f85-da1750ab70b0.png)

I have tried using the same index and the issue persists.
Network requests are sending the same activities.lvl0 values.

Using the same index we get:

![screen shot 2018-02-02 at 13 19 03](https://user-images.githubusercontent.com/614768/35732942-bd609576-081b-11e8-84c6-7248abfb00e4.png)

If you need a demo, you can see our currently broken live site: www.deedmob.com/discover (Activity dropdown)

----

Deeper into the rabbit hole:

![screen shot 2018-02-02 at 13 35 49](https://user-images.githubusercontent.com/614768/35733519-0b86d9a2-081e-11e8-9b6b-c9fb7e189428.png)

**Comment by samouss** [comment]
Hi @davidfurlong, thanks for the screenshots but I have some struggle to reproduce the error that you describe. Could you please make an example with the issue, we provide template to avoid you the boilerplate part. You can find it on [CodeSandbox](https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/React%20InstantSearch).

**Comment by samouss** [comment]
I'm closing this one since it's inactive, feel free to re-open an issue.
