### ISSUE TITLE
Would like to have features that can provide different filters to each index

### ISSUE THREAD

**Issue by intelcoder** [algolia/react-instantsearch#955]
I am currently using this library with react-autosuggest and trying to search on the multiple indexes.
However, it seems each indexes cannot have different filters unlike javascript version. At least could not find any docs or information. 
Can we have feature that we can pass different filters to the each individual index ? 
```
<InstantSearch>
      <Index key={indexName1} indexName={indexName1} filters={"(candy_type:123123)"}} />)
      <Index key={indexName2} indexName={indexName2} filters={"(animal_type:123123)"}} />)
</InstantSearch>
```

**Comment by Haroenv** [comment]
You can use the Configure component for that, or virtual widgets (has a guide, but I’m on mobile now)

**Comment by intelcoder** [comment]
Thanks for the answer! I was able to pass different config with Configure component as you mentioned.
```
  <Index key={indexName} indexName={indexName}>
        <Configure filters='your filter'} hitsPerPage={5} />
  </Index>
```
