### ISSUE TITLE
Possible to set paginationLimitedTo to a different value?

### ISSUE THREAD

**Issue by aaronbushnell** [algolia/react-instantsearch#997]
Is it possible to set `paginationLimitedTo` to something other than the default of `1000`? I tried applying it to:

```jsx
<Configure paginationLimitedTo={5000} />
```
and
```jsx
<InstantSearch
  appId="APP_ID"
  apiKey="APP_KEY"
  indexName="INDEX"
  paginationLimitedTo={5000}
>
```
but neither worked. Is there a way to do this?

**Comment by samouss** [comment]
No, it's not possible to set the [`paginationLimitedTo`](https://www.algolia.com/doc/api-reference/api-parameters/paginationLimitedTo) from InstantSearch. This option is only available at settings time and not query time. You can find more information about the different scopes [in the documentation](https://www.algolia.com/doc/api-client/settings/?language=javascript#the-scope-of-settings-and-parameters).
